#!/usr/bin/env sage -python
"""Certify the resolved, reduced H92 source-q8 E8 pushforward lattice.

This fixes the remaining distinction between:

  * the singular integral ideal I=(u^2,X,Y), and
  * the complete resolved II* neighbourhood, including the affine component.

We work in the REDUCED q8 normalization: the global -11F twist is kept
separate.  Thus locally at E8 the divisor is

    9*O + 9*(-P1) + (exceptional E8 correction),

with no affine-fibre coefficient.

Integral coordinates:
    u = 1/t,
    X = u^4*x,
    Y = u^6*y,
    Q = u^2*m = (Y-Y_P)/(X-X_P).

Step A: prove the 18-element horizontal frame

    C = 1,Q,...,Q^9, X,XQ,...,XQ^7

is saturated on the affine II* component.

At u=0 the reduced Weierstrass cubic is Y^2=X^3.  Normalize it by
    X=r^2, Y=r^3.
If s0=Y_P(0)/X_P(0), then P1 corresponds to r=s0 and

    Q0 = (r^3-s0^3)/(r^2-s0^2).

The 18 reductions of C are checked to be QQ-linearly independent as rational
functions of r.  Therefore no nonzero (1/u)-multiple of a C-combination can
be regular on the affine component.  This proves affine u-saturation of C.

Step B: impose the exact exceptional correction.

The repository already certifies that the resolved E8 valuation cycle selects
the complete singular ideal
    I=(u^2,X,Y),
with quotient basis 1,u and colength 2.

Put
    s(u)=Y_P/X_P.
Since X_P is a unit at u=0,

    Q-s = (X_P*Y-Y_P*X)/(X_P*(X-X_P)) in (X,Y).

Hence the full preimage of I inside C is generated by

    u^2,
    Q^b-s^b  (1<=b<=9),
    X*Q^b    (0<=b<=7).

Its determinant in C is u^2, so it has colength two; because C -> R/I is
surjective through the constant generator 1, this contained submodule is the
entire preimage.

Combining Step A and Step B proves the displayed rank-18 lattice is already
saturated on the COMPLETE resolved II* fibre.

The global -11F twist is deliberately NOT applied here.
"""

import argparse
import hashlib
import json
from pathlib import Path

from sage.all import PolynomialRing, QQ, matrix

ROOT = Path.cwd()
P1 = ROOT / "artifacts/generated-results/elkies-k3-h92-p1-lift.json"
TARGET = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-e8-local-target.json"
MODULE = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-e8-complete-module.json"
RESOLUTION = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-e8-resolution.json"
DEFAULT_OUTPUT = ROOT / "artifacts/local/elkies-k3/q8-e8-resolved-reduced-lattice.json"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def polynomial(ring, values):
    return ring([QQ(v) for v in values])


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()

for path in (P1, TARGET, MODULE, RESOLUTION):
    if not path.exists():
        raise SystemExit("missing {}".format(path))

p1 = json.loads(P1.read_text())
target = json.loads(TARGET.read_text())
module = json.loads(MODULE.read_text())
resolution = json.loads(RESOLUTION.read_text())

assert p1["status"] == "PASS_EXACT_H92_P1"
assert target["status"] == "PASS_EXACT_Q8_E8_SOURCE_TARGET"
assert module["status"] == "PASS_EXACT_Q8_E8_COMPLETE_MODULE"
assert resolution["status"] == "PASS_EXACT_E8_BLOWUP_CHARTS"

assert tuple(target["q8"]["chart_exceptional_cycle"]) == (
    "-2","-4","-6","-10","-4","-7","-5","-8"
)
assert module["complete_ideal"]["generators"] == ["Y","X","u^2"]
assert module["complete_ideal"]["quotient_basis"] == ["1","u"]
assert int(module["complete_ideal"]["colength"]) == 2

R = PolynomialRing(QQ, "u")
u = R.gen()
K = R.fraction_field()

x_p = K(polynomial(R, p1["x_entrance_base"]["numerator_coefficients"]))
x_p /= K(polynomial(R, p1["x_entrance_base"]["denominator_coefficients"]))
y_p = K(polynomial(R, p1["y_entrance_base"]["numerator_coefficients"]))
y_p /= K(polynomial(R, p1["y_entrance_base"]["denominator_coefficients"]))

X_p = u**4*x_p
Y_p = u**6*y_p
assert X_p.valuation(u) == 0
assert Y_p.valuation(u) == 0
assert X_p.denominator()(0)
assert Y_p.denominator()(0)

X0 = QQ(X_p(0))
Y0 = QQ(Y_p(0))
assert X0 and Y0 and Y0**2 == X0**3
s0 = QQ(Y0/X0)
assert s0 and s0**2 == X0 and s0**3 == Y0

s = K(Y_p/X_p)
assert s.valuation(u) == 0
assert s.denominator()(0)
assert QQ(s(0)) == s0

# -------------------------------------------------------------------------
# A. Affine-component saturation.
# -------------------------------------------------------------------------
S = PolynomialRing(QQ, "r")
r = S.gen()
SF = S.fraction_field()

Q0_raw = SF((r**3-Y0)/(r**2-X0))
Q0 = SF((r**2+s0*r+s0**2)/(r+s0))
assert Q0_raw == Q0

affine_functions = [Q0**b for b in range(10)]
affine_functions += [SF(r**2)*Q0**b for b in range(8)]
assert len(affine_functions) == 18

# One common denominator (r+s0)^9 clears all 18 functions.
common = (r+s0)**9
cleared = []
for f in affine_functions:
    value = SF(common)*f
    assert value.denominator().degree() == 0
    cleared.append(S(value.numerator() / value.denominator()[0]))

max_degree = max(poly.degree() for poly in cleared)
coeff_matrix = matrix(
    QQ,
    [[poly[d] for d in range(max_degree+1)] for poly in cleared],
)
affine_rank = int(coeff_matrix.rank())
assert affine_rank == 18

# -------------------------------------------------------------------------
# B. Full preimage of I=(u^2,X,Y) inside C.
# -------------------------------------------------------------------------
# Q-s is explicitly in (X,Y):
#
# Q-s = (X_P*Y-Y_P*X)/(X_P*(X-X_P)).
#
# Both denominator factors are units at the E8 singular point.
assert X0
assert (-X0)

preimage_basis = [{
    "name": "u^2",
    "C_coordinates": {"1": "u^2"},
}]
for b in range(1, 10):
    preimage_basis.append({
        "name": "Q^{}-s^{}".format(b,b),
        "C_coordinates": {
            "Q^{}".format(b): "1",
            "1": "-s^{}".format(b),
        },
    })
for b in range(8):
    preimage_basis.append({
        "name": "X*Q^{}".format(b),
        "C_coordinates": {"X*Q^{}".format(b): "1"},
    })
assert len(preimage_basis) == 18

# Transformation is triangular after ordering C as
# 1,Q,...,Q^9,X,...,XQ^7; determinant is u^2.
preimage_colength = 2

# C relative to the old generic frame
# B=(1,m,...,m^9,x,xm,...,xm^7):
#
# Q^b=u^(2b)m^b,  XQ^b=u^(4+2b)x*m^b.
C_over_B_det = 2*sum(range(10)) + sum(4+2*b for b in range(8))
assert C_over_B_det == 178
resolved_reduced_det = C_over_B_det + preimage_colength
assert resolved_reduced_det == 180

basis_in_B = [{
    "name": "u^2",
    "expression": "u^2",
}]
for b in range(1,10):
    basis_in_B.append({
        "name": "Q^{}-s^{}".format(b,b),
        "expression": "u^{}*m^{} - s(u)^{}".format(2*b,b,b),
    })
for b in range(8):
    basis_in_B.append({
        "name": "X*Q^{}".format(b),
        "expression": "u^{}*x*m^{}".format(4+2*b,b),
    })

payload = {
    "schema": "elkies-k3.h92-q8-e8-resolved-reduced-lattice.v1",
    "status": "PASS_EXACT_Q8_E8_RESOLVED_REDUCED_LATTICE",
    "normalization": {
        "global_fibre_twist_removed": "-11F is not applied locally here",
        "local_divisor": "9O+9(-P1)+E8 exceptional correction",
    },
    "inputs": {
        "p1": {"path": str(P1.relative_to(ROOT)), "sha256": digest(P1)},
        "e8_target": {"path": str(TARGET.relative_to(ROOT)), "sha256": digest(TARGET)},
        "e8_complete_ideal": {"path": str(MODULE.relative_to(ROOT)), "sha256": digest(MODULE)},
        "e8_resolution": {"path": str(RESOLUTION.relative_to(ROOT)), "sha256": digest(RESOLUTION)},
    },
    "integral_coordinates": {
        "u": "1/t",
        "X": "u^4*x",
        "Y": "u^6*y",
        "Q": "u^2*m=(Y-Y(P1))/(X-X(P1))",
        "s": "Y(P1)/X(P1)",
    },
    "affine_component": {
        "special_fibre": "Y^2=X^3",
        "normalization": "X=r^2,Y=r^3",
        "P1_parameter": str(s0),
        "Q_reduction": str(Q0),
        "horizontal_frame_rank": affine_rank,
        "horizontal_frame_dimension": 18,
        "conclusion": (
            "C=(1,Q,...,Q^9,X,...,XQ^7) is u-saturated on the affine "
            "II* component: no nonzero C-combination may be divided by u "
            "and remain regular there."
        ),
    },
    "exceptional_correction": {
        "cycle": target["q8"]["chart_exceptional_cycle"],
        "complete_ideal": "(u^2,X,Y)",
        "quotient_basis": ["1","u"],
        "colength": 2,
        "Q_minus_s_identity": (
            "(X_P*Y-Y_P*X)/(X_P*(X-X_P))"
        ),
        "preimage_basis_in_C": preimage_basis,
        "preimage_is_complete": True,
    },
    "resolved_reduced_lattice": {
        "rank": 18,
        "basis_in_original_generic_frame": basis_in_B,
        "det_C_over_B": C_over_B_det,
        "det_exceptional_preimage": preimage_colength,
        "det_valuation_relative_B": resolved_reduced_det,
        "saturated": True,
        "saturation_argument": (
            "Any hypothetical one-u enlargement regular on the full resolved "
            "fibre is first forced back into C by affine saturation; the exact "
            "exceptional ideal then forces it back into the displayed preimage."
        ),
    },
    "boundary": (
        "This resolves the reduced E8 local lattice only. The global -11F "
        "base twist and intersection with reduced E7 and h-adic collision "
        "lattices remain separate."
    ),
}

args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

print(
    "Q8E8RESOLVED|affine_rank=18|exceptional_colength=2|"
    "C_over_B_det=178|reduced_E8_det=180|saturated=1|"
    "status=PASS_EXACT_Q8_E8_RESOLVED_REDUCED_LATTICE",
    flush=True,
)
