#!/usr/bin/env python3
"""Smoke verification for the shared HC4/DC2 canonical-search primitives."""

from __future__ import annotations

import sympy as sp

from canonical_transform_search import (
    canonical_poisson_matrix,
    compose_maps,
    exact_invariant_shear,
    mixed_line_hamiltonians,
    poisson_bracket,
    verify_symplectic_map,
)


def verify_pair_count(pair_count: int, q_p_bracket: int) -> None:
    q = sp.symbols(f"q0:{pair_count}")
    p = sp.symbols(f"p0:{pair_count}")
    variables = q + p
    poisson = canonical_poisson_matrix(
        pair_count,
        q_p_bracket=q_p_bracket,
    )

    for index in range(pair_count):
        assert poisson_bracket(
            q[index], p[index], variables, poisson
        ) == q_p_bracket

    # A polynomial in one mixed linear form has an exact finite time-one
    # Hamiltonian flow.  Its inverse is the shear generated by -H.
    alphabet = mixed_line_hamiltonians(
        q,
        p,
        degrees=(2, 3),
        coefficients=(-1, 1),
    )
    assert len(alphabet) == 8 * pair_count**2
    hamiltonian = next(
        letter.hamiltonian
        for letter in alphabet
        if letter.source_index == 0
        and letter.dual_index == pair_count - 1
        and letter.epsilon == 1
        and letter.degree == 3
        and letter.coefficient == 1
    )
    shear = exact_invariant_shear(hamiltonian, variables, poisson)
    inverse = exact_invariant_shear(-hamiltonian, variables, poisson)
    verify_symplectic_map(shear, variables, poisson)
    verify_symplectic_map(inverse, variables, poisson)
    assert compose_maps(inverse, shear, variables) == variables
    assert compose_maps(shear, inverse, variables) == variables


verify_pair_count(2, -1)  # DC2 convention: {p_i,q_j}=delta_ij.
verify_pair_count(3, 1)   # HC4 mixed-pivot convention.

print("PASS: shared exact canonical-search primitives in ranks two and three")
