#!/usr/bin/env python3
"""Exact good-prime certificates for the symmetric cubic GMC(2) support.

On the first of the four nonvanishing charts of the support
``{-3,-1,1,3}``, normalize

    P = W^3 + W + a*Z*W^2 + c*Z + d*Z^2*W + e*Z^3,   c*e != 0.

The other chart representatives select the radial coefficient in weight
``+1``, or the radial coefficients in both weights ``-1,+1``.  Swapping
``Z,W`` supplies the fourth chart.  On every representative, the second
moment eliminates ``e``.  Singular computes the reduced standard basis over
QQ for the localized ideal generated by moments 4, 6, and 8.  At a fixed
prime, the verifier checks that reducing this rational basis gives the same
leading monomials as an independently computed modular standard basis and
that every reduced rational generator lies in the modular ideal.  This is a
good-reduction certificate: the 84 standard monomials are a basis in
characteristic zero and at the selected prime.

For each representative the verifier forms the 84 by 84 matrix of
multiplication by the tenth moment in the modular quotient.  Full rank
modulo the certified good prime implies that its characteristic-zero
determinant is nonzero.  Thus the tenth moment is a unit in every chart's
order-eight quotient, excluding the entire symmetric support.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import sympy as sp

from verify_two_real_gmc_frontier import W, Z, expectation


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "artifacts"
    / "generated-results"
    / "two_real_gmc_symmetric_chart.json"
)
PRIME = 1_000_003


def primitive_numerator(expression: sp.Expr, variables: tuple[sp.Symbol, ...]) -> sp.Expr:
    """Return a sign-normalized primitive integral numerator."""

    numerator = sp.together(expression).as_numer_denom()[0]
    _, primitive = sp.Poly(numerator, *variables, domain=sp.QQ).primitive()
    result = primitive.as_expr()
    if sp.Poly(result, *variables).LC() < 0:
        result = -result
    return sp.expand(result)


def singular_expression(expression: sp.Expr) -> str:
    """Serialize an integral SymPy expression for Singular."""

    polynomial = sp.Poly(expression)
    assert polynomial.domain == sp.ZZ
    return sp.sstr(sp.expand(expression)).replace("**", "^")


def moment_systems() -> list[dict[str, object]]:
    """Construct the three sign-reflection representative systems."""

    a, b, c, d, e, rho = sp.symbols("a b c d e rho")
    polynomial = (
        W**3 + b * W + a * Z * W**2 + c * Z + d * Z**2 * W + e * Z**3
    )
    moments: dict[int, sp.Expr] = {}
    power = sp.Integer(1)
    for order in range(1, 11):
        power = sp.expand(power * polynomial)
        moments[order] = sp.factor(expectation(power))

    assert all(moments[order] == 0 for order in (1, 3, 5, 7, 9))
    chart_specs = (
        {
            "key": "constant_constant",
            "label": "constant coefficient selected in weights -1 and +1",
            "normalization": {b: 1},
            "selected_positive_coefficient": c,
            "normalized_polynomial": (
                "W^3 + W + a*Z*W^2 + c*Z + d*Z^2*W + e*Z^3"
            ),
            "nonvanishing_condition": "c*e != 0",
            "charts_covered": ("constant_constant",),
        },
        {
            "key": "constant_radial",
            "label": "constant coefficient in weight -1 and radial coefficient in weight +1",
            "normalization": {b: 1},
            "selected_positive_coefficient": d,
            "normalized_polynomial": (
                "W^3 + W + a*Z*W^2 + c*Z + d*Z^2*W + e*Z^3"
            ),
            "nonvanishing_condition": "d*e != 0",
            "charts_covered": ("constant_radial", "radial_constant"),
        },
        {
            "key": "radial_radial",
            "label": "radial coefficient selected in weights -1 and +1",
            "normalization": {a: 1},
            "selected_positive_coefficient": d,
            "normalized_polynomial": (
                "W^3 + b*W + Z*W^2 + c*Z + d*Z^2*W + e*Z^3"
            ),
            "nonvanishing_condition": "d*e != 0",
            "charts_covered": ("radial_radial",),
        },
    )

    systems: list[dict[str, object]] = []
    for spec in chart_specs:
        normalization = spec["normalization"]
        assert isinstance(normalization, dict)
        normalized_second_moment = sp.expand(moments[2].subs(normalization))
        assert sp.degree(normalized_second_moment, e) == 1
        e_solution = sp.solve(normalized_second_moment, e)[0]
        assert sp.expand(normalized_second_moment.subs(e, e_solution)) == 0
        variables = tuple(
            variable for variable in (a, b, c, d) if variable not in normalization
        )
        eliminated = {
            order: primitive_numerator(
                moments[order].subs(normalization).subs(e, e_solution),
                variables,
            )
            for order in (4, 6, 8, 10)
        }
        selected = spec["selected_positive_coefficient"]
        assert isinstance(selected, sp.Symbol)
        localization_factor = primitive_numerator(
            selected.subs(normalization) * e_solution,
            variables,
        )
        assert localization_factor != 0
        systems.append(
            {
                **spec,
                "variables": variables + (rho,),
                "e_solution": e_solution,
                "localization_factor": localization_factor,
                "ideal_generators": (
                    eliminated[4],
                    eliminated[6],
                    eliminated[8],
                    sp.expand(rho * localization_factor - 1),
                ),
                "tenth_moment": eliminated[10],
                "moment_term_counts": {
                    str(order): len(sp.Poly(eliminated[order], *variables).terms())
                    for order in (4, 6, 8, 10)
                },
            }
        )
    return systems


def singular_program(system: dict[str, object]) -> str:
    """Emit the rational/modular standard-basis and multiplication audit."""

    ideal_generators = system["ideal_generators"]
    tenth_moment = system["tenth_moment"]
    variables = system["variables"]
    assert isinstance(ideal_generators, tuple)
    assert isinstance(tenth_moment, sp.Expr)
    assert isinstance(variables, tuple)
    generators = ",\n".join(
        singular_expression(generator) for generator in ideal_generators
    )
    h_expression = singular_expression(tenth_moment)
    variable_names = ",".join(str(variable) for variable in variables)
    coefficient_variables = "*".join(str(variable) for variable in variables)
    return f"""
ring rational_ring=0,({variable_names}),dp;
option(redSB);
ideal I={generators};
poly h={h_expression};
ideal G=slimgb(I);
print("Q_BASIS_SIZE "+string(size(G)));
print("Q_DIMENSION "+string(dim(G)));
print("Q_VECTOR_DIMENSION "+string(vdim(G)));

ring prime_ring={PRIME},({variable_names}),dp;
option(redSB);
ideal Ip=imap(rational_ring,I);
ideal Gqp=imap(rational_ring,G);
poly hp=imap(rational_ring,h);
ideal Gp=slimgb(Ip);

int same_leading_monomials=1;
int i;
int j;
int found;
for (i=1;i<=size(Gqp);i++)
{{
  found=0;
  for (j=1;j<=size(Gp);j++)
  {{
    if (leadmonom(Gqp[i])==leadmonom(Gp[j])) {{ found=1; }}
  }}
  if (found==0) {{ same_leading_monomials=0; }}
}}
for (i=1;i<=size(Gp);i++)
{{
  found=0;
  for (j=1;j<=size(Gqp);j++)
  {{
    if (leadmonom(Gp[i])==leadmonom(Gqp[j])) {{ found=1; }}
  }}
  if (found==0) {{ same_leading_monomials=0; }}
}}
int rational_generators_mod_prime_remainders=size(reduce(Gqp,Gp));
print("P_BASIS_SIZE "+string(size(Gp)));
print("P_VECTOR_DIMENSION "+string(vdim(Gp)));
print("SAME_LEADING_MONOMIALS "+string(same_leading_monomials));
print(
  "RATIONAL_GENERATORS_MOD_PRIME_REMAINDERS "
  +string(rational_generators_mod_prime_remainders)
);

ideal Bp=kbase(Gp);
int quotient_dimension=size(Bp);
matrix multiplication[quotient_dimension][quotient_dimension];
poly remainder;
matrix coefficients;
int column;
int term;
for (column=1;column<=quotient_dimension;column++)
{{
  remainder=reduce(hp*Bp[column],Gp);
  coefficients=coef(remainder,{coefficient_variables});
  for (term=1;term<=ncols(coefficients);term++)
  {{
    found=0;
    for (i=1;i<=quotient_dimension;i++)
    {{
      if (coefficients[1,term]==Bp[i])
      {{
        multiplication[i,column]=coefficients[2,term];
        found=1;
      }}
    }}
    if (found==0) {{ print("UNMATCHED_STANDARD_MONOMIAL"); }}
  }}
}}
print("MULTIPLICATION_SIZE "+string(quotient_dimension));
print("MULTIPLICATION_RANK "+string(rank(multiplication)));
"""


def parse_markers(output: str) -> dict[str, int]:
    """Parse the integer certificate markers printed by Singular."""

    names = (
        "Q_BASIS_SIZE",
        "Q_DIMENSION",
        "Q_VECTOR_DIMENSION",
        "P_BASIS_SIZE",
        "P_VECTOR_DIMENSION",
        "SAME_LEADING_MONOMIALS",
        "RATIONAL_GENERATORS_MOD_PRIME_REMAINDERS",
        "MULTIPLICATION_SIZE",
        "MULTIPLICATION_RANK",
    )
    result: dict[str, int] = {}
    for name in names:
        match = re.search(rf"(?m)^{name}\s+(-?\d+)\s*$", output)
        if match is None:
            raise RuntimeError(f"Singular did not report {name}:\n{output[-4000:]}")
        result[name] = int(match.group(1))
    return result


def run_certificate(
    singular: str,
    system: dict[str, object],
) -> tuple[dict[str, object], dict[str, int]]:
    """Run and validate one representative's exact Singular certificate."""

    completed = subprocess.run(
        (singular, "-q"),
        input=singular_program(system),
        text=True,
        capture_output=True,
        check=True,
        timeout=1800,
    )
    if (
        "?" in completed.stderr
        or "?" in completed.stdout
        or "UNMATCHED_STANDARD_MONOMIAL" in completed.stdout
    ):
        raise RuntimeError(
            "Singular certificate emitted an error:\n"
            + completed.stderr
            + "\n"
            + completed.stdout[-4000:]
        )
    markers = parse_markers(completed.stdout)

    assert markers["Q_DIMENSION"] == 0
    assert markers["Q_BASIS_SIZE"] == 53
    assert markers["Q_VECTOR_DIMENSION"] == 84
    assert markers["P_BASIS_SIZE"] == markers["Q_BASIS_SIZE"]
    assert markers["P_VECTOR_DIMENSION"] == markers["Q_VECTOR_DIMENSION"]
    assert markers["SAME_LEADING_MONOMIALS"] == 1
    assert markers["RATIONAL_GENERATORS_MOD_PRIME_REMAINDERS"] == 0
    assert markers["MULTIPLICATION_SIZE"] == markers["Q_VECTOR_DIMENSION"]
    assert markers["MULTIPLICATION_RANK"] == markers["MULTIPLICATION_SIZE"]
    return system, markers


def certificate_record(
    system: dict[str, object],
    markers: dict[str, int],
) -> dict[str, object]:
    """Build one representative's machine-readable proof record."""

    return {
        "representative": system["key"],
        "chart": system["label"],
        "charts_covered": list(system["charts_covered"]),
        "normalized_polynomial": system["normalized_polynomial"],
        "nonvanishing_condition": system["nonvanishing_condition"],
        "second_moment_elimination": f"e = {system['e_solution']}",
        "localization_factor_after_elimination": str(
            system["localization_factor"]
        ),
        "moment_term_counts_after_elimination": system["moment_term_counts"],
        "order_eight_quotient": {
            "rational_reduced_basis_size": markers["Q_BASIS_SIZE"],
            "dimension": markers["Q_DIMENSION"],
            "vector_space_dimension": markers["Q_VECTOR_DIMENSION"],
        },
        "good_prime_certificate": {
            "prime": PRIME,
            "modular_reduced_basis_size": markers["P_BASIS_SIZE"],
            "modular_vector_space_dimension": markers["P_VECTOR_DIMENSION"],
            "same_leading_monomials": True,
            "reduced_rational_generators_have_zero_modular_remainder": True,
        },
        "tenth_moment_multiplication": {
            "matrix_size": markers["MULTIPLICATION_SIZE"],
            "rank_mod_prime": markers["MULTIPLICATION_RANK"],
            "determinant_mod_prime": "nonzero (certified by full matrix rank)",
        },
        "conclusion": (
            "the tenth moment is a unit in the characteristic-zero localized "
            "order-eight quotient; this nonvanishing chart is empty through "
            "moment order ten"
        ),
    }


def main() -> None:
    singular = shutil.which("Singular")
    assert singular is not None, "the symmetric GMC chart certificate requires Singular"
    systems = moment_systems()
    with ThreadPoolExecutor(max_workers=len(systems)) as executor:
        results = list(
            executor.map(
                lambda system: run_certificate(singular, system),
                systems,
            )
        )
    records = [
        certificate_record(system, markers) for system, markers in results
    ]
    assert sum(len(record["charts_covered"]) for record in records) == 4
    first = records[0]
    payload = {
        "format": "two-real-gmc-symmetric-support-v2",
        "support": [-3, -1, 1, 3],
        "sign_reflection": (
            "swapping Z and W identifies the constant_radial and "
            "radial_constant charts"
        ),
        "representative_certificates": records,
        "charts_in_support": 4,
        "charts_excluded": 4,
        "exceptional_four_weight_charts_before": 24,
        "exceptional_four_weight_charts_remaining": 20,
        # Retain the first-chart fields for consumers of the v1 artifact.
        "order_eight_quotient": first["order_eight_quotient"],
        "tenth_moment_multiplication": first["tenth_moment_multiplication"],
        "conclusion": (
            "all four nonvanishing charts of the symmetric support are empty "
            "through moment order ten"
        ),
        "scope": (
            "one of four exceptional four-weight supports is excluded; this "
            "is not a proof of GMC in two real variables"
        ),
    }
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n")
    for record in records:
        print(
            "PASS symmetric GMC chart:",
            record["representative"],
            "covers",
            len(record["charts_covered"]),
            "chart(s); good-prime rank 84 of 84",
        )
    print(
        "PASS symmetric GMC support: excluded all 4 charts; wrote",
        OUTPUT.relative_to(ROOT),
    )


if __name__ == "__main__":
    main()
