#!/usr/bin/env python3
"""Verify the E8 degree-six theorem and exhaustive A5 coset atlas."""

from __future__ import annotations

from itertools import permutations


Permutation = tuple[int, ...]
DEGREE = 6
IDENTITY = tuple(range(DEGREE))


def compose(left: Permutation, right: Permutation) -> Permutation:
    """Compose tuple permutations as ``left`` after ``right``."""

    return tuple(left[right[index]] for index in range(len(left)))


def inverse(permutation: Permutation) -> Permutation:
    """Return the inverse tuple permutation."""

    result = [0] * len(permutation)
    for index, image in enumerate(permutation):
        result[image] = index
    return tuple(result)


def power(permutation: Permutation, exponent: int) -> Permutation:
    """Raise a permutation to a nonnegative power."""

    result = tuple(range(len(permutation)))
    factor = permutation
    while exponent:
        if exponent & 1:
            result = compose(result, factor)
        factor = compose(factor, factor)
        exponent //= 2
    return result


def cycle_type(permutation: Permutation) -> tuple[int, ...]:
    """Return the decreasing cycle partition, including fixed points."""

    seen: set[int] = set()
    lengths: list[int] = []
    for start in range(len(permutation)):
        if start in seen:
            continue
        point = start
        length = 0
        while point not in seen:
            seen.add(point)
            length += 1
            point = permutation[point]
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


def orbit(generators: tuple[Permutation, ...], start: int = 0) -> set[int]:
    """Return the orbit of one sheet under the generated group."""

    degree = len(generators[0])
    reached = {start}
    frontier = [start]
    moves = generators + tuple(inverse(generator) for generator in generators)
    while frontier:
        point = frontier.pop()
        for move in moves:
            image = move[point]
            if image not in reached:
                reached.add(image)
                frontier.append(image)
    assert reached <= set(range(degree))
    return reached


def all_orbits(generators: tuple[Permutation, ...]) -> set[frozenset[int]]:
    """Return all sheet orbits under the supplied generators."""

    remaining = set(range(len(generators[0])))
    result: set[frozenset[int]] = set()
    while remaining:
        component = frozenset(orbit(generators, min(remaining)))
        result.add(component)
        remaining.difference_update(component)
    return result


def generated_group(generators: tuple[Permutation, ...]) -> set[Permutation]:
    """Enumerate the subgroup generated by the supplied permutations."""

    identity = tuple(range(len(generators[0])))
    group = {identity}
    frontier = [identity]
    moves = generators + tuple(inverse(generator) for generator in generators)
    while frontier:
        element = frontier.pop()
        for move in moves:
            product = compose(element, move)
            if product not in group:
                group.add(product)
                frontier.append(product)
    return group


def conjugate(permutation: Permutation, relabeling: Permutation) -> Permutation:
    """Conjugate by a simultaneous relabeling of the six sheets."""

    return compose(compose(relabeling, permutation), inverse(relabeling))


def all_subgroups(group: set[Permutation]) -> set[frozenset[Permutation]]:
    """Enumerate every subgroup by adjoining generators breadth first."""

    identity = tuple(range(len(next(iter(group)))))
    known = {frozenset((identity,))}
    frontier = [frozenset((identity,))]
    while frontier:
        subgroup = frontier.pop()
        for generator in group.difference(subgroup):
            enlarged = frozenset(generated_group(tuple(subgroup) + (generator,)))
            if enlarged not in known:
                known.add(enlarged)
                frontier.append(enlarged)
    return known


def coset_action(
    group: set[Permutation], subgroup: frozenset[Permutation], element: Permutation
) -> Permutation:
    """Return left multiplication by ``element`` on the cosets of a subgroup."""

    unseen = set(group)
    cosets: list[frozenset[Permutation]] = []
    while unseen:
        representative = min(unseen)
        coset = frozenset(compose(representative, member) for member in subgroup)
        cosets.append(coset)
        unseen.difference_update(coset)
    coset_index = {coset: index for index, coset in enumerate(cosets)}
    action = []
    for coset in cosets:
        representative = next(iter(coset))
        image = frozenset(
            compose(compose(element, representative), member)
            for member in subgroup
        )
        action.append(coset_index[image])
    return tuple(action)


def audit_icosahedral_coset_atlas() -> None:
    """Classify all transitive coset actions of the A5 quotient."""

    degree_five_group = {
        permutation
        for permutation in permutations(range(5))
        if sum(
            permutation[left] > permutation[right]
            for left in range(5)
            for right in range(left + 1, 5)
        )
        % 2
        == 0
    }
    identity = tuple(range(5))
    meridian = (1, 0, 3, 2, 4)  # (1 2)(3 4)
    a_image = (0, 2, 4, 3, 1)  # (2 3 5)
    b_image = (4, 3, 1, 0, 2)  # (1 5 3 2 4)
    assert generated_group((a_image, b_image)) == degree_five_group
    assert power(a_image, 3) == power(b_image, 5) == identity
    assert compose(inverse(a_image), power(b_image, 2)) == meridian

    subgroups = all_subgroups(degree_five_group)
    assert len(subgroups) == 59

    # Simultaneous conjugacy in A5 gives exactly the classical subgroup
    # classes 1,C2,C3,V4,C5,S3,D5,A4,A5.
    conjugacy_classes: set[frozenset[frozenset[Permutation]]] = set()
    for subgroup in subgroups:
        conjugacy_classes.add(
            frozenset(
                frozenset(conjugate(member, element) for member in subgroup)
                for element in degree_five_group
            )
        )
    assert len(conjugacy_classes) == 9

    representatives = [
        next(iter(conjugacy_class)) for conjugacy_class in conjugacy_classes
    ]
    expected = {
        1: ((1,), (1,), (1,), 1, 0),
        5: ((3, 1, 1), (5,), (2, 2, 1), 1, 2),
        6: ((3, 3), (5, 1), (2, 2, 1, 1), 2, 2),
        10: ((3, 3, 3, 1), (5, 5), (2, 2, 2, 2, 1, 1), 2, 4),
        12: ((3, 3, 3, 3), (5, 5, 1, 1), (2, 2, 2, 2, 2, 2), 0, 6),
        15: (
            (3, 3, 3, 3, 3),
            (5, 5, 5),
            (2, 2, 2, 2, 2, 2, 1, 1, 1),
            3,
            6,
        ),
        20: (
            (3, 3, 3, 3, 3, 3, 1, 1),
            (5, 5, 5, 5),
            (2, 2, 2, 2, 2, 2, 2, 2, 2, 2),
            0,
            10,
        ),
        30: (
            (3, 3, 3, 3, 3, 3, 3, 3, 3, 3),
            (5, 5, 5, 5, 5, 5),
            (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1),
            2,
            14,
        ),
        60: (
            (3,) * 20,
            (5,) * 12,
            (2,) * 30,
            0,
            30,
        ),
    }
    actual = {}
    for subgroup in representatives:
        degree = len(degree_five_group) // len(subgroup)
        a_coset = coset_action(degree_five_group, subgroup, a_image)
        b_coset = coset_action(degree_five_group, subgroup, b_image)
        meridian_coset = coset_action(degree_five_group, subgroup, meridian)
        expected_image_order = 1 if degree == 1 else len(degree_five_group)
        assert len(generated_group((a_coset, b_coset))) == expected_image_order
        fixed_sheets = cycle_type(meridian_coset).count(1)
        ramified_rows = cycle_type(meridian_coset).count(2)
        actual[degree] = (
            cycle_type(a_coset),
            cycle_type(b_coset),
            cycle_type(meridian_coset),
            fixed_sheets,
            ramified_rows,
        )
        # The central image and preferred longitude are trivial and the
        # meridian, respectively.  Hence every ramified peripheral orbit is
        # one two-cycle and has residue degree one.
        central_coset = power(a_coset, 3)
        longitude_coset = compose(
            central_coset, power(inverse(meridian_coset), 15)
        )
        assert central_coset == tuple(range(degree))
        assert longitude_coset == meridian_coset
        assert all(
            len(component) in (1, 2)
            for component in all_orbits((meridian_coset, longitude_coset))
        )
    assert actual == expected
    assert {
        degree for degree, data in actual.items() if data[3] > 0 and degree >= 6
    } == {6, 10, 15, 30}

    # With r separate (2,1) rows, common carrier contact b, total negativity
    # N, and s_X additional smooth blowups, the doubled root-subtracted
    # finite-length lower ledger is
    #   7d-62+4N-4r(b-6)-s_X  (squarefree),
    # or the same expression with 67 in the double-row case.
    minimal_maximal_squarefree = {
        degree: 7 * degree - 62 - 4 * actual[degree][4]
        for degree in (6, 10, 15, 30)
    }
    assert minimal_maximal_squarefree == {6: -28, 10: -8, 15: 19, 30: 92}
    minimal_maximal_double = {
        degree: 7 * degree - 67 - 4 * actual[degree][4]
        for degree in (15, 30)
    }
    assert minimal_maximal_double == {15: 14, 30: 87}


def main() -> None:
    symmetric_group = tuple(permutations(range(DEGREE)))

    # The weighted-homogeneous E8 curve P^5-Q^3=0 has torus-knot group
    # <a,b | a^3=b^5>.  Since [a]=5 and [b]=3 in its abelianization, the
    # word m=a^(-1)b^2 is a positively oriented geometric meridian.
    by_cube: dict[Permutation, list[Permutation]] = {}
    by_fifth: dict[Permutation, list[Permutation]] = {}
    for permutation in symmetric_group:
        by_cube.setdefault(power(permutation, 3), []).append(permutation)
        by_fifth.setdefault(power(permutation, 5), []).append(permutation)

    solutions: set[tuple[Permutation, Permutation]] = set()
    solution_types: set[
        tuple[tuple[int, ...], tuple[int, ...], tuple[int, ...]]
    ] = set()
    for central_image, cube_roots in by_cube.items():
        for a_image in cube_roots:
            a_inverse = inverse(a_image)
            for b_image in by_fifth.get(central_image, ()):
                meridian = compose(a_inverse, power(b_image, 2))
                if cycle_type(meridian) != (2, 2, 1, 1):
                    continue
                if orbit((a_image, b_image)) != set(range(DEGREE)):
                    continue
                solutions.add((a_image, b_image))
                solution_types.add(
                    (
                        cycle_type(a_image),
                        cycle_type(b_image),
                        cycle_type(central_image),
                    )
                )

    assert len(solutions) == 720
    assert solution_types == {((3, 3), (5, 1), (1, 1, 1, 1, 1, 1))}

    # A representative, in one-based cycle notation, is
    # a=(1 2 3)(4 5 6), b=(2 4 5 3 6), m=(1 3)(2 4).
    a_image = (1, 2, 0, 4, 5, 3)
    b_image = (0, 3, 5, 4, 2, 1)
    meridian = compose(inverse(a_image), power(b_image, 2))
    assert meridian == (2, 3, 0, 1, 4, 5)
    assert power(a_image, 3) == power(b_image, 5) == IDENTITY
    assert cycle_type(meridian) == (2, 2, 1, 1)
    assert orbit((a_image, b_image)) == set(range(DEGREE))

    # Every solution is a simultaneous conjugate of the representative.
    conjugacy_orbit = {
        (conjugate(a_image, relabeling), conjugate(b_image, relabeling))
        for relabeling in symmetric_group
    }
    assert len(conjugacy_orbit) == 720
    assert conjugacy_orbit == solutions

    # The meridian and a generate the (2,3,5) triangle group image:
    # m^2=a^3=(ma)^5=1.  Its exact closure has order 60, hence it is the
    # icosahedral A5 group in its exceptional transitive six-point action.
    assert power(meridian, 2) == IDENTITY
    assert power(compose(meridian, a_image), 5) == IDENTITY
    image = generated_group((meridian, a_image))
    assert image == generated_group((a_image, b_image))
    assert len(image) == 60

    # For the (3,5) torus knot, the preferred longitude is z*m^(-15),
    # where z=a^3=b^5.  Here z is trivial and m has order two, so the
    # longitude has the same image as m.  The peripheral orbits therefore
    # keep the two ramified transposition cycles separate.  Each has
    # transverse index e=2 and residue degree f=1; a single (2,2) divisor
    # would require the longitude to exchange the two cycles.
    central_image = power(a_image, 3)
    longitude = compose(central_image, power(inverse(meridian), 15))
    assert central_image == IDENTITY
    assert longitude == meridian
    peripheral_orbits = all_orbits((meridian, longitude))
    assert peripheral_orbits == {
        frozenset((0, 2)),
        frozenset((1, 3)),
        frozenset((4,)),
        frozenset((5,)),
    }
    audit_icosahedral_coset_atlas()

    print(
        "PASS: the E8 torus-knot group has exactly 720 labeled transitive "
        "degree-six actions whose meridian has type 2+2+1+1; they form one "
        "conjugacy class with image A5 of order 60, and the peripheral "
        "action forces two distinct (e,f)=(2,1) boundary rows; the exhaustive "
        "A5 coset atlas has fixed-sheet F2 degrees 6,10,15,30, with every "
        "ramified peripheral row again of type (2,1)"
    )


if __name__ == "__main__":
    main()
