#!/usr/bin/env python3
"""Exact degree-five relation for the centered d=2 seventh moment.

Let nu_m=mu_m/(2m+1)! and center the binomial moment sequence by

    x_m=sum_(p=0)^m binom(m,p)(-nu_1)^(m-p)nu_p.

The full d=2 moment field is generated over Q(mu_1,...,mu_6) by x_7 and
has degree five there.  Homogeneity therefore gives a unique relation

    x_7^5 + sum_(k=1)^5 A_k(x_2,...,x_6)x_7^(5-k) = 0,

where A_k has weighted degree 7k for weights 2,...,6.

This checker reconstructs the 418 rational ansatz coefficients from five
good primes.  It then verifies the relation exactly at 418 fixed integral
coefficient matrices.  The corresponding ansatz evaluation matrix has
full rank modulo 1000003, so the exact evaluations identify the unique
universal relation without expanding a degree-35 polynomial in nine
variables.  Finally, modular rank jumps certify that each of
x_8,...,x_12 lies outside the polynomial algebra generated by the
preceding centered moments.  A transverse six-parameter operator slice
then gives exact symbolic identities expressing x_13,...,x_18 in the
algebra generated by x_2,...,x_12.
"""

from __future__ import annotations

import json
import random
from fractions import Fraction
from math import comb, factorial, gcd, isqrt
from pathlib import Path

from flint import fmpq, fmpq_mpoly_ctx, nmod_mat


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "artifacts"
    / "generated-results"
    / "two_pair_d2_moment_field_relation.json"
)
INTERPOLATION_PRIMES = (
    1_000_000_007,
    1_000_000_009,
    1_000_000_033,
    1_000_000_087,
    1_000_000_093,
)
RANK_PRIME = 1_000_003
WEIGHTS = (2, 3, 4, 5, 6)
RELATION_DEGREE = 5
POST_CUTOFF_ORDERS = tuple(range(13, 19))
POST_CUTOFF_WEIGHTS = tuple(range(2, 13))
POST_CUTOFF_INTERPOLATION_PRIMES = INTERPOLATION_PRIMES + (
    1_000_000_097,
    1_000_000_103,
)


def weighted_exponents(total: int) -> list[tuple[int, ...]]:
    result: list[tuple[int, ...]] = []

    def recurse(
        index: int,
        remainder: int,
        prefix: tuple[int, ...],
    ) -> None:
        if index == len(WEIGHTS):
            if remainder == 0:
                result.append(prefix)
            return
        weight = WEIGHTS[index]
        for exponent in range(remainder // weight + 1):
            recurse(
                index + 1,
                remainder - exponent * weight,
                prefix + (exponent,),
            )

    recurse(0, total, ())
    return result


def weighted_exponents_for(
    weights: tuple[int, ...],
    total: int,
) -> list[tuple[int, ...]]:
    result: list[tuple[int, ...]] = []

    def recurse(
        index: int,
        remainder: int,
        prefix: tuple[int, ...],
    ) -> None:
        if index == len(weights):
            if remainder == 0:
                result.append(prefix)
            return
        weight = weights[index]
        for exponent in range(remainder // weight + 1):
            recurse(
                index + 1,
                remainder - exponent * weight,
                prefix + (exponent,),
            )

    recurse(0, total, ())
    return result


EXPONENT_BLOCKS = tuple(
    weighted_exponents(7 * coefficient_index)
    for coefficient_index in range(1, RELATION_DEGREE + 1)
)
ANSATZ_SIZE = sum(len(block) for block in EXPONENT_BLOCKS)


def modular_centered_moments(
    point: list[list[int]],
    prime: int,
    max_order: int = 7,
) -> list[int]:
    factorials = [1]
    for value in range(1, 2 * max_order + 2):
        factorials.append(factorials[-1] * value % prime)

    power = [[1]]
    moments = [1]
    for order in range(1, max_order + 1):
        size = 2 * order + 1
        current = [[0] * size for _ in range(size)]
        for left, previous_row in enumerate(power):
            for right, value in enumerate(previous_row):
                if not value:
                    continue
                for row in range(3):
                    for column in range(3):
                        current[left + row][right + column] = (
                            current[left + row][right + column]
                            + value * point[row][column]
                        ) % prime
        power = current
        moments.append(
            sum(
                factorials[index]
                * factorials[2 * order - index]
                * power[index][index]
                for index in range(size)
            )
            % prime
        )

    normalized = [
        moments[order]
        * pow(factorials[2 * order + 1], prime - 2, prime)
        % prime
        for order in range(max_order + 1)
    ]
    shift = normalized[1]
    return [
        sum(
            comb(order, index)
            * pow(-shift, order - index, prime)
            * normalized[index]
            for index in range(order + 1)
        )
        % prime
        for order in range(max_order + 1)
    ]


def exact_centered_moments(
    point: list[list[int]],
) -> list[Fraction]:
    power = [[1]]
    moments = [1]
    for order in range(1, 8):
        size = 2 * order + 1
        current = [[0] * size for _ in range(size)]
        for left, previous_row in enumerate(power):
            for right, value in enumerate(previous_row):
                if not value:
                    continue
                for row in range(3):
                    for column in range(3):
                        current[left + row][right + column] += (
                            value * point[row][column]
                        )
        power = current
        moments.append(
            sum(
                factorial(index)
                * factorial(2 * order - index)
                * power[index][index]
                for index in range(size)
            )
        )

    normalized = [
        Fraction(moments[order], factorial(2 * order + 1))
        for order in range(8)
    ]
    shift = normalized[1]
    return [
        sum(
            (
                Fraction(comb(order, index))
                * (-shift) ** (order - index)
                * normalized[index]
                for index in range(order + 1)
            ),
            Fraction(0),
        )
        for order in range(8)
    ]


def monomial_value(
    values: list[int] | list[Fraction],
    exponents: tuple[int, ...],
    modulus: int | None = None,
) -> int | Fraction:
    result: int | Fraction = 1
    for value, exponent in zip(values, exponents):
        result *= value**exponent
        if modulus is not None:
            result %= modulus
    return result


def ansatz_row(
    centered: list[int],
    prime: int,
) -> list[int]:
    variables = centered[2:7]
    seventh = centered[7]
    result = []
    for coefficient_index, block in enumerate(EXPONENT_BLOCKS, 1):
        seventh_power = pow(
            seventh, RELATION_DEGREE - coefficient_index, prime
        )
        result.extend(
            int(monomial_value(variables, exponents, prime))
            * seventh_power
            % prime
            for exponents in block
        )
    return result


def interpolation_point(sample: int, prime: int) -> list[list[int]]:
    generator = random.Random(9137 + sample)
    return [
        [generator.randrange(prime) for _column in range(3)]
        for _row in range(3)
    ]


def verification_point(sample: int) -> list[list[int]]:
    generator = random.Random(50000 + sample)
    return [
        [generator.randrange(-9, 10) for _column in range(3)]
        for _row in range(3)
    ]


def solve_mod_prime(prime: int) -> list[int]:
    rows = []
    right_hand_side = []
    for sample in range(ANSATZ_SIZE):
        centered = modular_centered_moments(
            interpolation_point(sample, prime), prime
        )
        rows.append(ansatz_row(centered, prime))
        right_hand_side.append(
            [-pow(centered[7], RELATION_DEGREE, prime) % prime]
        )
    matrix = nmod_mat(rows, prime)
    assert matrix.rank() == ANSATZ_SIZE
    solution = matrix.solve(nmod_mat(right_hand_side, prime))
    return [int(solution[index, 0]) for index in range(ANSATZ_SIZE)]


def rational_reconstruction(
    residue: int,
    modulus: int,
) -> Fraction | None:
    residue %= modulus
    bound = isqrt(modulus // 2)
    old_remainder, remainder = modulus, residue
    old_coefficient, coefficient = 0, 1
    while abs(remainder) >= bound:
        quotient = old_remainder // remainder
        old_remainder, remainder = (
            remainder,
            old_remainder - quotient * remainder,
        )
        old_coefficient, coefficient = (
            coefficient,
            old_coefficient - quotient * coefficient,
        )
    if (
        coefficient == 0
        or abs(coefficient) >= bound
        or gcd(remainder, coefficient) != 1
    ):
        return None
    if coefficient < 0:
        remainder = -remainder
        coefficient = -coefficient
    if (residue * coefficient - remainder) % modulus:
        return None
    return Fraction(remainder, coefficient)


def reconstruct_relation() -> list[Fraction]:
    residues: list[int] | None = None
    modulus = 1
    for prime in INTERPOLATION_PRIMES:
        prime_solution = solve_mod_prime(prime)
        if residues is None:
            residues = prime_solution
            modulus = prime
            continue
        inverse = pow(modulus, -1, prime)
        for index, value in enumerate(prime_solution):
            residues[index] += modulus * (
                (value - residues[index]) * inverse % prime
            )
        modulus *= prime
    assert residues is not None
    reconstructed = [
        rational_reconstruction(value, modulus) for value in residues
    ]
    assert all(value is not None for value in reconstructed)
    return [value for value in reconstructed if value is not None]


def independent_columns(
    rows: list[list[int]],
    prime: int,
) -> list[int]:
    chosen: list[int] = []
    rank = 0
    for column in range(len(rows[0])):
        candidate = chosen + [column]
        candidate_rank = nmod_mat(
            [[row[index] for index in candidate] for row in rows],
            prime,
        ).rank()
        if candidate_rank > rank:
            chosen = candidate
            rank = candidate_rank
    return chosen


def independent_rows(
    rows: list[list[int]],
    columns: list[int],
    prime: int,
) -> list[int]:
    chosen: list[int] = []
    rank = 0
    for row_index in range(len(rows)):
        candidate = chosen + [row_index]
        candidate_rank = nmod_mat(
            [
                [rows[index][column] for column in columns]
                for index in candidate
            ],
            prime,
        ).rank()
        if candidate_rank > rank:
            chosen = candidate
            rank = candidate_rank
        if rank == len(columns):
            break
    assert rank == len(columns)
    return chosen


def post_cutoff_evaluation_rows(
    order: int,
    exponents: list[tuple[int, ...]],
    prime: int,
) -> tuple[list[list[int]], list[int]]:
    sample_count = len(exponents) + 15
    rows = []
    targets = []
    for sample in range(sample_count):
        centered = modular_centered_moments(
            interpolation_point(order * 1000 + sample, prime),
            prime,
            order,
        )
        rows.append(
            [
                int(
                    monomial_value(
                        centered[2:13],
                        exponent,
                        prime,
                    )
                )
                for exponent in exponents
            ]
        )
        targets.append(centered[order])
    return rows, targets


def reconstruct_post_cutoff_expression(
    order: int,
) -> tuple[list[tuple[int, ...]], list[int], list[Fraction]]:
    exponents = weighted_exponents_for(POST_CUTOFF_WEIGHTS, order)
    first_rows, _ = post_cutoff_evaluation_rows(
        order,
        exponents,
        POST_CUTOFF_INTERPOLATION_PRIMES[0],
    )
    columns = independent_columns(
        first_rows,
        POST_CUTOFF_INTERPOLATION_PRIMES[0],
    )

    residues: list[int] | None = None
    modulus = 1
    for prime in POST_CUTOFF_INTERPOLATION_PRIMES:
        rows, targets = post_cutoff_evaluation_rows(
            order,
            exponents,
            prime,
        )
        row_indices = independent_rows(rows, columns, prime)
        matrix = nmod_mat(
            [
                [rows[row][column] for column in columns]
                for row in row_indices
            ],
            prime,
        )
        right_hand_side = nmod_mat(
            [[targets[row]] for row in row_indices],
            prime,
        )
        solution = matrix.solve(right_hand_side)
        prime_solution = [
            int(solution[index, 0]) for index in range(len(columns))
        ]
        for row, target in zip(rows, targets):
            assert (
                sum(
                    row[column] * prime_solution[index]
                    for index, column in enumerate(columns)
                )
                - target
            ) % prime == 0

        if residues is None:
            residues = prime_solution
            modulus = prime
            continue
        inverse = pow(modulus, -1, prime)
        for index, value in enumerate(prime_solution):
            residues[index] += modulus * (
                (value - residues[index]) * inverse % prime
            )
        modulus *= prime

    assert residues is not None
    reconstructed = [
        rational_reconstruction(value, modulus) for value in residues
    ]
    assert all(value is not None for value in reconstructed)
    return (
        exponents,
        columns,
        [value for value in reconstructed if value is not None],
    )


def dense_slice_centered_moments(max_order: int):
    # In operator coordinates A=C^T diag(2,1,2), take the affine slice
    #
    #       [0 1 0]
    #   A = [a b c].
    #       [d e f]
    #
    # At A_0=[[0,1,0],[0,0,1],[1,0,0]], the first-row coordinates of
    # [X,A_0] for the standard sl2 generators form the matrix below.
    # Its determinant is 4, so SL2 times this slice dominates End(Sym^2).
    raising = [
        [0, 0, 0],
        [2, 0, 0],
        [0, 1, 0],
    ]
    lowering = [
        [0, 1, 0],
        [0, 0, 2],
        [0, 0, 0],
    ]
    cartan = [
        [-2, 0, 0],
        [0, 0, 0],
        [0, 0, 2],
    ]
    base_operator = [
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
    ]

    def matrix_product(
        left: list[list[int]],
        right: list[list[int]],
    ) -> list[list[int]]:
        return [
            [
                sum(
                    left[row][index] * right[index][column]
                    for index in range(3)
                )
                for column in range(3)
            ]
            for row in range(3)
        ]

    orbit_vectors = []
    for generator in (raising, lowering, cartan):
        left_product = matrix_product(generator, base_operator)
        right_product = matrix_product(base_operator, generator)
        orbit_vectors.append(
            [
                left_product[row][column] - right_product[row][column]
                for row in range(3)
                for column in range(3)
            ]
        )
    orbit_minor = [
        [orbit_vectors[column][row] for column in range(3)]
        for row in range(3)
    ]
    assert orbit_minor == [
        [-2, 0, 0],
        [0, 0, -2],
        [0, -1, 0],
    ]
    determinant = (
        orbit_minor[0][0]
        * (
            orbit_minor[1][1] * orbit_minor[2][2]
            - orbit_minor[1][2] * orbit_minor[2][1]
        )
        - orbit_minor[0][1]
        * (
            orbit_minor[1][0] * orbit_minor[2][2]
            - orbit_minor[1][2] * orbit_minor[2][0]
        )
        + orbit_minor[0][2]
        * (
            orbit_minor[1][0] * orbit_minor[2][1]
            - orbit_minor[1][1] * orbit_minor[2][0]
        )
    )
    assert determinant == 4

    context = fmpq_mpoly_ctx.get(("a", "b", "c", "d", "e", "f"))
    a, b, c, d, e, f = context.gens()
    zero = context.constant(0)
    coefficient_matrix = [
        [zero, a / 2, d / 2],
        [context.constant(1), b, e],
        [zero, c / 2, f / 2],
    ]
    power = [[context.constant(1)]]
    moments = [context.constant(1)]
    for order in range(1, max_order + 1):
        size = 2 * order + 1
        current = [[zero for _ in range(size)] for _ in range(size)]
        for left, previous_row in enumerate(power):
            for right, value in enumerate(previous_row):
                if not value:
                    continue
                for row in range(3):
                    for column in range(3):
                        current[left + row][right + column] += (
                            value * coefficient_matrix[row][column]
                        )
        power = current
        moments.append(
            sum(
                (
                    factorial(index)
                    * factorial(2 * order - index)
                    * power[index][index]
                    for index in range(size)
                ),
                zero,
            )
        )
    normalized = [
        moments[order] / factorial(2 * order + 1)
        for order in range(max_order + 1)
    ]
    shift = normalized[1]
    centered = [
        sum(
            (
                comb(order, index)
                * (-shift) ** (order - index)
                * normalized[index]
                for index in range(order + 1)
            ),
            zero,
        )
        for order in range(max_order + 1)
    ]
    return context, centered, determinant


def polynomial_term_count(polynomial) -> int:
    return sum(1 for _ in polynomial.terms())


def exact_relation_value(
    centered: list[Fraction],
    coefficients: list[Fraction],
) -> Fraction:
    variables = centered[2:7]
    seventh = centered[7]
    result = seventh**RELATION_DEGREE
    offset = 0
    for coefficient_index, block in enumerate(EXPONENT_BLOCKS, 1):
        seventh_power = seventh ** (
            RELATION_DEGREE - coefficient_index
        )
        for exponents in block:
            coefficient = coefficients[offset]
            offset += 1
            if coefficient:
                result += (
                    coefficient
                    * monomial_value(variables, exponents)
                    * seventh_power
                )
    assert offset == len(coefficients)
    return result


def main() -> None:
    assert [len(block) for block in EXPONENT_BLOCKS] == [
        3,
        19,
        49,
        120,
        227,
    ]
    assert ANSATZ_SIZE == 418

    coefficients = reconstruct_relation()
    nonzero_count = sum(bool(value) for value in coefficients)
    assert nonzero_count == 241

    rank_rows = []
    for sample in range(ANSATZ_SIZE):
        point = verification_point(sample)
        centered_mod = modular_centered_moments(point, RANK_PRIME)
        rank_rows.append(ansatz_row(centered_mod, RANK_PRIME))
        centered_exact = exact_centered_moments(point)
        assert exact_relation_value(centered_exact, coefficients) == 0
    assert nmod_mat(rank_rows, RANK_PRIME).rank() == ANSATZ_SIZE

    # Field generation stops at x_7, but polynomial generation does not.
    # In centered coordinates, translation-invariant polynomials in the
    # earlier moments are exactly polynomials in the earlier x_m.
    generator_certificates = []
    centered_samples = [
        modular_centered_moments(
            verification_point(sample), RANK_PRIME, 12
        )
        for sample in range(30)
    ]
    for order in range(8, 13):
        earlier_weights = tuple(range(2, order))
        monomials = []

        def collect_monomials(
            index: int,
            remainder: int,
            prefix: tuple[int, ...],
        ) -> None:
            if index == len(earlier_weights):
                if remainder == 0:
                    monomials.append(prefix)
                return
            weight = earlier_weights[index]
            for exponent in range(remainder // weight + 1):
                collect_monomials(
                    index + 1,
                    remainder - exponent * weight,
                    prefix + (exponent,),
                )

        collect_monomials(0, order, ())
        old_rows = [
            [
                int(
                    monomial_value(
                        [centered[weight] for weight in earlier_weights],
                        exponents,
                        RANK_PRIME,
                    )
                )
                for exponents in monomials
            ]
            for centered in centered_samples
        ]
        old_rank = nmod_mat(old_rows, RANK_PRIME).rank()
        extended_rows = [
            row + [centered[order]]
            for row, centered in zip(old_rows, centered_samples)
        ]
        extended_rank = nmod_mat(extended_rows, RANK_PRIME).rank()
        assert old_rank == len(monomials)
        assert extended_rank == old_rank + 1
        generator_certificates.append(
            {
                "centered_moment": order,
                "earlier_weighted_monomial_count": len(monomials),
                "earlier_span_rank": old_rank,
                "rank_after_adjoining_moment": extended_rank,
                "prime": RANK_PRIME,
            }
        )

    post_cutoff_data = []
    dense_context, dense_centered, orbit_minor_determinant = (
        dense_slice_centered_moments(max(POST_CUTOFF_ORDERS))
    )
    for order in POST_CUTOFF_ORDERS:
        exponents, columns, expression_coefficients = (
            reconstruct_post_cutoff_expression(order)
        )
        expression = dense_context.constant(0)
        terms = []
        for coefficient, column in zip(expression_coefficients, columns):
            exponent = exponents[column]
            term = dense_context.constant(
                fmpq(coefficient.numerator, coefficient.denominator)
            )
            for value, power in zip(dense_centered[2:13], exponent):
                term *= value**power
            expression += term
            if coefficient:
                terms.append(
                    {
                        "exponents_x2_through_x12": list(exponent),
                        "coefficient": str(coefficient),
                    }
                )
        assert dense_centered[order] - expression == 0
        post_cutoff_data.append(
            {
                "centered_moment": order,
                "weighted_monomial_count": len(exponents),
                "independent_expression_monomial_count": len(columns),
                "nonzero_expression_term_count": len(terms),
                "dense_slice_target_term_count": polynomial_term_count(
                    dense_centered[order]
                ),
                "terms": terms,
            }
        )
    assert [
        item["independent_expression_monomial_count"]
        for item in post_cutoff_data
    ] == [23, 33, 38, 50, 57, 75]

    sparse_blocks = []
    offset = 0
    for coefficient_index, block in enumerate(EXPONENT_BLOCKS, 1):
        terms = []
        for exponents in block:
            coefficient = coefficients[offset]
            offset += 1
            if coefficient:
                terms.append(
                    {
                        "exponents_x2_through_x6": list(exponents),
                        "coefficient": str(coefficient),
                    }
                )
        sparse_blocks.append(
            {
                "coefficient_index": coefficient_index,
                "weighted_degree": 7 * coefficient_index,
                "x7_power": RELATION_DEGREE - coefficient_index,
                "terms": terms,
            }
        )

    payload = {
        "normalization": (
            "nu_m=mu_m/(2m+1)!, "
            "x_m=sum_p binom(m,p)(-nu_1)^(m-p)nu_p"
        ),
        "relation": (
            "x7^5+sum_(k=1)^5 A_k(x2,x3,x4,x5,x6)*x7^(5-k)=0"
        ),
        "weights_x2_through_x7": [2, 3, 4, 5, 6, 7],
        "relation_degree_in_x7": RELATION_DEGREE,
        "ansatz_block_sizes": [len(block) for block in EXPONENT_BLOCKS],
        "ansatz_size": ANSATZ_SIZE,
        "nonzero_coefficient_count": nonzero_count,
        "interpolation_primes": list(INTERPOLATION_PRIMES),
        "exact_verification_point_count": ANSATZ_SIZE,
        "verification_ansatz_rank": ANSATZ_SIZE,
        "verification_rank_prime": RANK_PRIME,
        "coefficient_blocks": sparse_blocks,
        "necessary_additional_algebra_generators": generator_certificates,
        "post_cutoff_interpolation_primes": list(
            POST_CUTOFF_INTERPOLATION_PRIMES
        ),
        "dense_operator_slice": {
            "operator": "[[0,1,0],[a,b,c],[d,e,f]]",
            "orbit_coordinate_minor_determinant": orbit_minor_determinant,
            "dominance_conclusion": (
                "SL2 times the affine slice is dense in End(Sym^2)"
            ),
        },
        "post_cutoff_generation": post_cutoff_data,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n")

    print(
        "PASS d=2 moment relation: reconstructed 241 nonzero "
        "coefficients in a 418-term ansatz"
    )
    print(
        "PASS d=2 moment relation: exact verification at 418 integral "
        "points with full-rank ansatz evaluation"
    )
    print(
        "PASS d=2 moment relation: x_7 has the certified monic "
        "degree-five equation over Q[x_2,...,x_6]"
    )
    print(
        "PASS d=2 moment algebra: x_8,...,x_12 are necessary "
        "additional polynomial generators"
    )
    print(
        "PASS d=2 moment algebra: dense-slice polynomial identities "
        "express x_13,...,x_18 in Q[x_2,...,x_12]"
    )


if __name__ == "__main__":
    main()
