#!/usr/bin/env sage -python
"""Export the recovered hidden generic sections to portable Python source.

The exploratory reconstruction lives in a Sage ``.sobj`` file.  This script
turns the eleven exact rational functions into plain numerator/denominator
coefficient tuples over Q, so later searches do not depend on an opaque or
machine-local Sage serialization.

Typical use from the repository root::

    sage -python elliptic-curves/cas/newfamily/export_hidden_sections.py \
      --input /tmp/newfamily_hidden_sections_complete.sobj \
      --out elliptic-curves/cas/newfamily/hidden_sections_data.py

The generated file is deterministic and should be committed after replay.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from sage.all import QQ, PolynomialRing, load


def qtext(value) -> str:
    value = QQ(value)
    if value.denominator() == 1:
        return str(value.numerator())
    return f"({value.numerator()},{value.denominator()})"


def coefficient_tuple(poly) -> str:
    degree = poly.degree()
    values = [poly[i] if i <= degree else QQ(0) for i in range(degree + 1)]
    return "(" + ", ".join(qtext(value) for value in values) + ",)"


def as_num_den(function, ring):
    numerator = ring(function.numerator())
    denominator = ring(function.denominator())
    gcd = numerator.gcd(denominator)
    if gcd not in (0, 1, -1):
        numerator //= gcd
        denominator //= gcd
    lc = denominator.leading_coefficient()
    numerator /= lc
    denominator /= lc
    return numerator, denominator


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    recovered = load(args.input)
    sections = recovered["sections"]
    if set(sections) != set(range(11)):
        raise SystemExit(f"expected sections 0..10, found {sorted(sections)}")

    ring = PolynomialRing(QQ, "T")

    rows = []
    for index in range(11):
        x_function, y_function = sections[index]
        xn, xd = as_num_den(x_function, ring)
        yn, yd = as_num_den(y_function, ring)
        rows.append((index, xn, xd, yn, yd))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        '"""Generated exact hidden generic sections for the newfamily rank-11 K3.\n',
        "\n",
        "Generated by ``export_hidden_sections.py`` from the exact recovered Sage object.\n",
        "Each rational function stores polynomial coefficients in ascending order.\n",
        '"""\n',
        "\n",
        "# Rational numbers are encoded either as integers or as (numerator, denominator).\n",
        "SECTIONS = (\n",
    ]

    for index, xn, xd, yn, yd in rows:
        lines.extend(
            [
                "    {\n",
                f'        "index": {index},\n',
                f'        "x_num": {coefficient_tuple(xn)},\n',
                f'        "x_den": {coefficient_tuple(xd)},\n',
                f'        "y_num": {coefficient_tuple(yn)},\n',
                f'        "y_den": {coefficient_tuple(yd)},\n',
                "    },\n",
            ]
        )
    lines.append(")\n")
    out.write_text("".join(lines))

    print(f"sections={len(rows)}")
    for index, xn, xd, yn, yd in rows:
        print(
            "U%d x=(%d,%d) y=(%d,%d)" %
            (index, xn.degree(), xd.degree(), yn.degree(), yd.degree())
        )
    print(f"saved={out}")
    print("DONE")


if __name__ == "__main__":
    main()
