#!/usr/bin/env python3
"""Exact checks for finite etale algebras as Keller fibers.

The checker has six independent layers:

1. direct Jacobian and inverse-polynomial checks for translated seeds;
2. Jacobian-one normalization and effective coordinate-degree checks;
3. quotient-ring reconstruction, using an explicit Bezout inverse of E';
4. an exact target-scaling audit of the displayed Berend--Bilu map.
5. diagonal/off-diagonal CRT decompositions of the finite-fiber collision
   algebras;
6. exact cubic S3 normal-closure certificates for two connected fibers.
"""
from __future__ import annotations

from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from jcsearch.keller_fiber import (
    jacobian_one_normalization,
    quadratic_gauge_map as shared_quadratic_gauge_map,
    total_coordinate_degrees as shared_total_coordinate_degrees,
)

x, y, z, S, ell = sp.symbols("x y z S ell")
r, u, w = sp.symbols("r u w")


def quadratic_gauge_map(G: sp.Expr) -> tuple[sp.Expr, sp.Expr, sp.Expr]:
    """Compatibility wrapper for the shared quadratic-gauge compiler."""
    return shared_quadratic_gauge_map(G, S, (x, y, z))


def total_coordinate_degrees(
    mapping: tuple[sp.Expr, sp.Expr, sp.Expr],
) -> tuple[int, int, int]:
    return shared_total_coordinate_degrees(mapping, (x, y, z))


def quotient_reduce(expression: sp.Expr, modulus: sp.Expr) -> sp.Expr:
    """Reduce a rational expression in QQ(S) modulo a squarefree modulus."""
    expression = sp.cancel(expression)
    numerator, denominator = expression.as_numer_denom()
    modulus_poly = sp.Poly(modulus, S, domain=sp.QQ)
    numerator_poly = sp.Poly(sp.expand(numerator), S, domain=sp.QQ).rem(modulus_poly)
    denominator_poly = sp.Poly(sp.expand(denominator), S, domain=sp.QQ).rem(modulus_poly)
    denominator_inverse = sp.invert(denominator_poly, modulus_poly)
    return sp.Poly(
        numerator_poly * denominator_inverse,
        S,
        domain=sp.QQ,
    ).rem(modulus_poly).as_expr()


def ideal_contains(groebner_basis: sp.GroebnerBasis, expression: sp.Expr) -> bool:
    """Test exact ideal membership by normal-form reduction."""
    return sp.expand(groebner_basis.reduce(sp.expand(expression))[1]) == 0


def check_collision_decomposition(P: sp.Expr) -> None:
    """Verify the diagonal/off-diagonal CRT for A=QQ[T]/(P).

    In QQ[r,u], the collision, diagonal, and off-diagonal ideals are

      (P(r),P(u)),  (P(r),u-r),  (P(r),(P(u)-P(r))/(u-r)).

    Separability makes the latter two comaximal.  The Bezout inverse of
    P'(r) produces the diagonal idempotent explicitly.
    """
    p_s = sp.Poly(P, S, domain=sp.QQ)
    assert sp.gcd(p_s, p_s.diff()).degree() == 0
    degree = p_s.degree()
    p_r = sp.expand(P.subs(S, r))
    p_u = sp.expand(P.subs(S, u))
    divided_difference = sp.cancel((p_u - p_r) / (u - r))
    assert sp.expand((u - r) * divided_difference - (p_u - p_r)) == 0

    collision = sp.groebner([p_r, p_u], u, r, order="lex", domain=sp.QQ)
    diagonal = sp.groebner([p_r, u - r], u, r, order="lex", domain=sp.QQ)
    off_diagonal = sp.groebner(
        [p_r, divided_difference],
        u,
        r,
        order="lex",
        domain=sp.QQ,
    )

    derivative_inverse = sp.invert(
        sp.Poly(sp.diff(p_r, r), r, domain=sp.QQ),
        sp.Poly(p_r, r, domain=sp.QQ),
    ).as_expr()
    diagonal_idempotent = sp.expand(derivative_inverse * divided_difference)
    off_diagonal_idempotent = sp.expand(1 - diagonal_idempotent)

    assert ideal_contains(collision, diagonal_idempotent**2 - diagonal_idempotent)
    assert ideal_contains(diagonal, diagonal_idempotent - 1)
    assert ideal_contains(off_diagonal, diagonal_idempotent)
    assert ideal_contains(diagonal, off_diagonal_idempotent)
    assert ideal_contains(off_diagonal, off_diagonal_idempotent - 1)
    assert ideal_contains(collision, diagonal_idempotent * (u - r))

    # The obstruction kernel is the principal idempotent ideal generated by
    # 1-e_Delta and also the ideal generated by u-r in the collision ring.
    assert ideal_contains(collision, off_diagonal_idempotent * (u - r) - (u - r))

    # Comaximality and the product/intersection identity give the exact CRT.
    sum_ideal = sp.groebner(
        [p_r, u - r, divided_difference],
        u,
        r,
        order="lex",
        domain=sp.QQ,
    )
    assert ideal_contains(sum_ideal, 1)
    product_generators = [
        left * right
        for left in (p_r, u - r)
        for right in (p_r, divided_difference)
    ]
    product_ideal = sp.groebner(
        product_generators,
        u,
        r,
        order="lex",
        domain=sp.QQ,
    )
    assert all(ideal_contains(collision, generator) for generator in product_generators)
    assert ideal_contains(product_ideal, p_r)
    assert ideal_contains(product_ideal, p_u)

    # Standard monomial counts are N^2, N, and N(N-1), respectively.
    collision_leads = {poly.LM(order="lex").exponents for poly in collision.polys}
    diagonal_leads = {poly.LM(order="lex").exponents for poly in diagonal.polys}
    off_diagonal_leads = {
        poly.LM(order="lex").exponents for poly in off_diagonal.polys
    }
    assert collision_leads == {(degree, 0), (0, degree)}
    assert diagonal_leads == {(1, 0), (0, degree)}
    assert off_diagonal_leads == {(degree - 1, 0), (0, degree)}


def rational_is_square(value: sp.Rational) -> bool:
    """Return whether a rational number is a square in QQ."""
    value = sp.Rational(value)
    if value < 0:
        return False
    numerator_root = sp.integer_nthroot(int(value.p), 2)
    denominator_root = sp.integer_nthroot(int(value.q), 2)
    return numerator_root[1] and denominator_root[1]


def check_cubic_s3_off_diagonal(P: sp.Expr) -> None:
    """Identify the cubic off-diagonal collision algebra with its S3 closure."""
    p_s = sp.Poly(P, S, domain=sp.QQ)
    assert p_s.degree() == 3
    assert p_s.is_irreducible
    discriminant = sp.Rational(sp.discriminant(p_s))
    assert discriminant != 0 and not rational_is_square(discriminant)

    group, _ = sp.polys.numberfields.galois_group(p_s)
    assert group.order() == 6 and not group.is_abelian

    p_r = sp.expand(P.subs(S, r))
    p_u = sp.expand(P.subs(S, u))
    divided_difference = sp.cancel((p_u - p_r) / (u - r))
    off_diagonal = sp.groebner(
        [p_r, divided_difference],
        u,
        r,
        order="lex",
        domain=sp.QQ,
    )

    # The third root is already present on the ordered-distinct-root sheet.
    third_root = sp.expand(-r - u - p_s.all_coeffs()[1] / p_s.all_coeffs()[0])
    assert ideal_contains(off_diagonal, P.subs(S, third_root))

    # w=r+2u is primitive in both examples.  Elimination gives an irreducible
    # sextic and explicit expressions for r and u in QQ[w], so the
    # off-diagonal quotient is the six-dimensional splitting field.
    primitive = sp.groebner(
        [p_r, divided_difference, w - r - 2 * u],
        r,
        u,
        w,
        order="lex",
        domain=sp.QQ,
    )
    leading_monomials = {
        poly.LM(order="lex").exponents for poly in primitive.polys
    }
    assert leading_monomials == {(1, 0, 0), (0, 1, 0), (0, 0, 6)}
    eliminants = [
        poly.as_expr()
        for poly in primitive.polys
        if not poly.as_expr().has(r, u)
    ]
    assert len(eliminants) == 1
    primitive_polynomial = sp.Poly(eliminants[0], w, domain=sp.QQ)
    assert primitive_polynomial.degree() == 6
    assert primitive_polynomial.is_irreducible


def check_hasse_collision_blocks() -> None:
    """Verify A5⊗A5 = A5 × (N6^3 × L2) for the optimal Hasse fiber."""
    cubic_r = r**3 - 19
    quadratic_u = u**2 + u + 1
    cross = sp.groebner(
        [cubic_r, quadratic_u],
        r,
        u,
        order="lex",
        domain=sp.QQ,
    )

    # The cross block contains all roots r, r*u, r*u^2 of T^3-19.
    assert ideal_contains(cross, u**3 - 1)
    for root in (r, r * u, r * u**2):
        assert ideal_contains(cross, root**3 - 19)

    # A primitive element gives a degree-six field, hence this cross block is
    # the S3 normal closure. The opposite cross block is canonically isomorphic.
    primitive = sp.groebner(
        [cubic_r, quadratic_u, w - r - u],
        r,
        u,
        w,
        order="lex",
        domain=sp.QQ,
    )
    eliminants = [
        poly.as_expr()
        for poly in primitive.polys
        if not poly.as_expr().has(r, u)
    ]
    assert len(eliminants) == 1
    cross_primitive = sp.Poly(eliminants[0], w, domain=sp.QQ)
    assert cross_primitive.degree() == 6 and cross_primitive.is_irreducible

    # Cubic internal off-diagonal, two cross blocks, and the quadratic
    # internal off-diagonal have ranks 6+6+6+2=20.
    block_ranks = (6, 6, 6, 2)
    assert sum(block_ranks) == 5 * 4
    assert 5 + sum(block_ranks) == 5**2


def check_scheme_reconstruction(P: sp.Expr, a: sp.Expr) -> None:
    """Check both sides of the reconstruction in QQ[S]/(P(a+S))."""
    translated = sp.expand(P.subs(S, S + a))
    G = sp.expand(translated - P.subs(S, a))
    poly = sp.Poly(G, S, domain=sp.QQ)
    degree = poly.degree()
    coeff = {k: poly.coeff_monomial(S**k) for k in range(1, degree + 1)}
    g1 = coeff[1]
    g3 = coeff[3]
    assert g1 != 0 and g3 != 0 and coeff[degree] != 0

    pi = sp.Integer(1)
    b_target = sp.Integer(0)
    c_target = sp.cancel(-2 * P.subs(S, a) / g1)
    E = sp.expand(G - g1 * (b_target * S**2 + c_target) / 2)
    assert sp.expand(E - translated) == 0

    E_poly = sp.Poly(E, S, domain=sp.QQ)
    derivative_poly = E_poly.diff()
    assert sp.gcd(E_poly, derivative_poly).degree() == 0

    # Bezout supplies the unit used by the scheme-theoretic reconstruction.
    derivative_inverse = sp.invert(derivative_poly, E_poly).as_expr()
    assert quotient_reduce(sp.diff(E, S) * derivative_inverse - 1, E) == 0

    beta = sp.cancel((sp.diff(G, S) / g1 - 1 - pi * S**2) / S)
    d = quotient_reduce(sp.diff(E, S) / g1, E)
    d_inverse = quotient_reduce(1 / d, E)
    Q = quotient_reduce(b_target - beta, E)
    t_bar = d_inverse
    x_bar = quotient_reduce(S * d_inverse, E)
    y_bar = quotient_reduce(Q - pi * S, E)
    q_bar = quotient_reduce(pi * d, E)
    z_bar = quotient_reduce(
        (q_bar - (g1 / g3) * y_bar**2 * (1 + 3 * t_bar)) / t_bar**2,
        E,
    )

    # Reconstruct the rational chart globally in the quotient algebra.
    assert quotient_reduce(1 + x_bar * y_bar - t_bar, E) == 0
    assert quotient_reduce(
        t_bar**2 * z_bar
        + (g1 / g3) * y_bar**2 * (1 + 3 * t_bar)
        - q_bar,
        E,
    ) == 0
    assert quotient_reduce(x_bar / t_bar - S, E) == 0
    assert quotient_reduce(y_bar + x_bar * q_bar - Q, E) == 0

    # Substitution into all three map coordinates returns the target in R.
    mapping = quadratic_gauge_map(G)
    outputs = [
        quotient_reduce(
            component.subs({x: x_bar, y: y_bar, z: z_bar}),
            E,
        )
        for component in mapping
    ]
    assert quotient_reduce(outputs[0] - pi, E) == 0
    assert quotient_reduce(outputs[1] - b_target, E) == 0
    assert quotient_reduce(outputs[2] - c_target, E) == 0

    # The determinant-one target scaling must preserve this distinguished
    # fiber as a scheme, not merely fix the numeral zero in isolation.
    normalized_outputs = [
        quotient_reduce(
            component.subs({x: x_bar, y: y_bar, z: z_bar}),
            E,
        )
        for component in jacobian_one_normalization(mapping)
    ]
    assert quotient_reduce(normalized_outputs[0] - pi, E) == 0
    assert quotient_reduce(normalized_outputs[1], E) == 0
    assert quotient_reduce(normalized_outputs[2] - c_target, E) == 0


def check_polynomial_to_fiber_transfer() -> None:
    examples = [
        S**3 - S - 1,
        2 * S**4 - S**3 - S**2 + S + 1,
        (S**3 - 19) * (S**2 + S + 1),
    ]
    for P in examples:
        p_poly = sp.Poly(P, S, domain=sp.QQ)
        degree = p_poly.degree()
        assert sp.gcd(p_poly, p_poly.diff()).degree() == 0
        a = next(
            sp.Integer(k)
            for k in range(-10, 11)
            if sp.diff(P, S).subs(S, k) != 0
            and sp.diff(P, S, 3).subs(S, k) != 0
        )
        G = sp.expand(P.subs(S, S + a) - P.subs(S, a))
        g_poly = sp.Poly(G, S, domain=sp.QQ)
        g1 = g_poly.coeff_monomial(S)
        assert g1 != 0
        assert g_poly.coeff_monomial(S**3) != 0
        assert g_poly.degree() == degree

        mapping = quadratic_gauge_map(G)
        assert sp.factor(sp.Matrix(mapping).jacobian((x, y, z)).det()) == -2

        jacobian_one = jacobian_one_normalization(mapping)
        assert sp.factor(sp.Matrix(jacobian_one).jacobian((x, y, z)).det()) == 1
        degrees = total_coordinate_degrees(jacobian_one)
        assert degrees[0] <= 7
        assert degrees[1] <= 6 * degree + 2
        assert degrees[2] <= 6 * degree
        assert max(degrees) <= 6 * degree + 2

        target_c = sp.cancel(-2 * P.subs(S, a) / g1)
        inverse = sp.expand(G - g1 * target_c / 2)
        assert sp.expand(inverse - P.subs(S, S + a)) == 0
        check_scheme_reconstruction(P, a)
        check_collision_decomposition(P)


def check_minimal_hasse_map() -> None:
    P5 = sp.expand((S**3 - 19) * (S**2 + S + 1))
    G = sp.expand(P5 - P5.subs(S, 0))
    assert P5 == S**5 + S**4 + S**3 - 19 * S**2 - 19 * S - 19
    assert G == S**5 + S**4 + S**3 - 19 * S**2 - 19 * S

    normalized = quadratic_gauge_map(G)
    assert sp.factor(sp.Matrix(normalized).jacobian((x, y, z)).det()) == -2
    normalized_one = jacobian_one_normalization(normalized)
    assert sp.factor(sp.Matrix(normalized_one).jacobian((x, y, z)).det()) == 1

    t = 1 + x * y
    q = t**2 * z - 19 * y**2 * (1 + 3 * t)
    displayed = (
        t * q,
        19 * y
        - 3 * x * q
        + 38 * t * q
        - 4 * t**2 * x**2 * q**4
        - 5 * t**2 * x**3 * q**5,
        19 * x * (5 - 3 * t)
        + x**3 * z
        + 2 * (x * q) ** 4
        + 3 * (x * q) ** 5,
    )

    # The integral map is exactly diag(1,19,19) after the normalized gauge.
    assert sp.expand(displayed[0] - normalized[0]) == 0
    assert sp.expand(displayed[1] - 19 * normalized[1]) == 0
    assert sp.expand(displayed[2] - 19 * normalized[2]) == 0
    assert sp.factor(sp.Matrix(displayed).jacobian((x, y, z)).det()) == -722
    assert -722 == 19**2 * (-2)

    # The normalized target (1,0,-2) becomes the displayed target (1,0,-38).
    normalized_target = (sp.Integer(1), sp.Integer(0), sp.Integer(-2))
    displayed_target = (
        normalized_target[0],
        19 * normalized_target[1],
        19 * normalized_target[2],
    )
    assert displayed_target == (1, 0, -38)

    g1 = sp.Poly(G, S).coeff_monomial(S)
    normalized_inverse = sp.expand(
        G - g1 * (normalized_target[1] * S**2 + normalized_target[2]) / 2
    )
    assert normalized_inverse == P5
    assert sp.gcd(sp.Poly(P5, S), sp.Poly(sp.diff(P5, S), S)).degree() == 0
    check_scheme_reconstruction(P5, sp.Integer(0))


def check_infinite_family() -> None:
    G = (
        S**5
        - sp.Rational(3, 2) * S**4
        + sp.Rational(3, 2) * S**3
        - sp.Rational(5, 4) * S**2
        + sp.Rational(9, 16) * S
    )
    mapping = quadratic_gauge_map(G)
    assert sp.factor(sp.Matrix(mapping).jacobian((x, y, z)).det()) == -2
    assert sp.factor(
        sp.Matrix(jacobian_one_normalization(mapping)).jacobian((x, y, z)).det()
    ) == 1

    B = sp.Rational(32, 9) * ell
    C = (8 * ell + 1) / 3
    inverse = sp.expand(G - sp.Rational(9, 32) * (B * S**2 + C))
    expected = sp.expand(
        ((S - sp.Rational(1, 2)) ** 3 - ell)
        * (S**2 + sp.Rational(3, 4))
    )
    assert sp.expand(inverse - expected) == 0


if __name__ == "__main__":
    check_polynomial_to_fiber_transfer()
    check_minimal_hasse_map()
    check_infinite_family()
    check_cubic_s3_off_diagonal(S**3 - S - 1)
    check_cubic_s3_off_diagonal(S**3 - 2)
    check_cubic_s3_off_diagonal(S**3 - 19)
    check_hasse_collision_blocks()
    print("PASS: squarefree polynomials in degrees 3, 4, and 5 transfer")
    print("PASS: target-preserving output scaling gives determinant-one maps")
    print("PASS: coordinate degrees satisfy the effective 6N+2 bound")
    print("PASS: quotient-ring reconstruction composes in both directions")
    print("PASS: collision fibers split exactly into diagonal and off-diagonal factors")
    print("PASS: collision, diagonal, and off-diagonal ranks are N^2, N, N(N-1)")
    print("PASS: cubic off-diagonal factors are the exact S3 normal closures")
    print("PASS: the Hasse collision algebra is A5 times N6^3 times L2")
    print("PASS: the explicit Hasse map is diag(1,19,19) of the normalized gauge")
    print("PASS: determinant -722, target -38, and inverse P5 agree exactly")
    print("PASS: one fixed quadratic-gauge map carries the infinite family")
