#!/usr/bin/env sage -python
"""
status: HISTORICAL_DIAGNOSTIC
claim: q24 p-adic SRR exactification was attempted and did not verify.
superseded-by: fixed q24 Theta/resolved-RR construction route.

Exactify the H92 q24 section from an EXISTING high-precision p-adic checkpoint
using simultaneous rational reconstruction (SRR), not more Hensel lifting.

Input:
    q24-direct-hensel-p512.json   (or another q24 direct Hensel checkpoint)

The Newton solve is already nonsingular and converged p-adically.  The previous
driver failed only because it rational-reconstructed each of 156 coefficients
independently.

Here we exploit shared arithmetic structure.  For a block of p-adic residues

    r_i mod M,  M=p^N,

a rational vector a_i/d satisfies

    a_i - d*r_i == 0 mod M.

Thus [d,a_1,...,a_n] is a short vector in the lattice generated by

    [1, r_1, ..., r_n]
    [0, M,   ..., 0  ]
    ...
    [0, 0,   ..., M  ].

LLL recovers the common-denominator rational vector when it is sufficiently
short.  We try natural whole-polynomial blocks first, then progressively
smaller contiguous chunks.  NO new p-adic Newton iteration is performed.

A strategy is accepted only if:
  * all reconstructed coefficients reproduce the p-adic residues modulo p^N;
  * Z is monic degree 24, X degree 52, Y degree 78;
  * the exact cleared D13 equation vanishes in QQ[U];
  * reduction modulo 100003 equals the independently certified degree-46
    modular q24 section.

Success writes q8-q24-horizontal-section-qq.json directly.
"""

import argparse
import json
import math
import time
from pathlib import Path

from sage.all import GF, QQ, ZZ, PolynomialRing, gcd, matrix


def locate_repo(explicit=None):
    candidates=[]
    if explicit:
        candidates.append(Path(explicit).expanduser())
    cwd=Path.cwd().resolve()
    candidates += [cwd,*cwd.parents]
    h=Path.home()
    candidates += [
        h/"Documents"/"jacobian-research",
        h/"jacobian-research",
        h/"src"/"jacobian-research",
        h/"git"/"jacobian-research",
        h/"projects"/"jacobian-research",
    ]
    seen=set()
    for c in candidates:
        try:
            c=c.resolve()
        except Exception:
            continue
        if c in seen:
            continue
        seen.add(c)
        if (c/"elkies-k3/scripts").is_dir() and (c/"artifacts/generated-results").is_dir():
            return c
    raise SystemExit("Could not locate jacobian-research")


parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument("--repo",type=Path)
parser.add_argument("--input",type=Path)
parser.add_argument("--output",type=Path)
parser.add_argument("--exact-output",type=Path)
args=parser.parse_args()

ROOT=locate_repo(args.repo)
LOCAL=ROOT/"artifacts/local/elkies-k3"
GEN=ROOT/"artifacts/generated-results"

INPUT=(
    args.input.resolve()
    if args.input
    else LOCAL/"q24-direct-hensel-p512.json"
)
MODSEED=LOCAL/"q24-degree46-direct-global-mod-100003.json"

q8_candidates=[
    LOCAL/"q8-corrected2cover-qq-child.json",
    GEN/"elkies-k3-h92-q6-child-q8-corrected2cover-qq-child.json",
]
CHILD=next((
    p for p in q8_candidates
    if p.exists()
    and "child" in json.loads(p.read_text())
    and "minimal_A_coefficients_low_to_high"
        in json.loads(p.read_text()).get("child",{})
),None)

for p in (INPUT,MODSEED):
    if not p.exists():
        raise SystemExit(f"Missing prerequisite: {p}")
if CHILD is None:
    raise SystemExit("No complete corrected q8 child artifact")

hen=json.loads(INPUT.read_text())
mod=json.loads(MODSEED.read_text())
child=json.loads(CHILD.read_text())

assert hen["schema"]=="elkies-k3.h92-q24-direct-hensel-lift.v1"
assert hen["status"]=="PASS_Q24_DIRECT_HENSEL"
assert hen["jacobian_rank"]==156
assert hen["final_residual_valuation"]>=hen["precision"]
assert len(hen["residues"])==156
assert mod["status"]=="PASS_MODULAR_Q24_FROM_DIRECT_DEGREE46_BRIDGE"
assert child["status"]=="PASS_EXACT_CORRECTED_Q8_D13_CHILD"

p=ZZ(hen["prime"])
N=int(hen["precision"])
M=p**N
residues=[ZZ(x)%M for x in hen["residues"]]
assert len(residues)==156

print(
    "Q24SRR_SETUP|"
    f"prime={p}|precision={N}|modulus_bits={M.nbits()}|"
    "newton=REUSED_NO_MORE_HENSEL|status=PASS",
    flush=True,
)

A_QQ=[QQ(v) for v in child["child"]["minimal_A_coefficients_low_to_high"]]
B_QQ=[QQ(v) for v in child["child"]["minimal_B_coefficients_low_to_high"]]

# Unknown layout from the Hensel solver:
#   Z lower 24, X 53, Y 79.
blocks_layout={
    "Z":(0,24),
    "X":(24,77),
    "Y":(77,156),
}


def centered(r):
    r=ZZ(r)%M
    return r-M if r>M//2 else r


def candidate_from_row(row, original):
    d=ZZ(row[0])
    if not d or d%p==0:
        return None
    nums=[ZZ(x) for x in row[1:]]
    if d<0:
        d=-d
        nums=[-x for x in nums]

    # Do NOT divide by a gcd unless the reduced vector still satisfies the
    # original modulus congruence.  LLL may return a scalar multiple.
    g=abs(gcd([d]+nums))
    variants=[(d,nums)]
    if g>1:
        dd=d//g
        aa=[a//g for a in nums]
        variants.insert(0,(dd,aa))

    for dd,aa in variants:
        if dd%p==0:
            continue
        if all((aa[i]-dd*original[i])%M==0 for i in range(len(aa))):
            q=[QQ(aa[i])/QQ(dd) for i in range(len(aa))]
            return {
                "den":dd,
                "nums":aa,
                "q":q,
                "max_bits":max(
                    [abs(dd).nbits()]
                    + [abs(a).nbits() for a in aa]
                ),
                "den_bits":abs(dd).nbits(),
            }
    return None


def srr_chunk(values,label):
    n=len(values)
    sym=[centered(v) for v in values]

    B=matrix(ZZ,n+1,n+1)
    B[0,0]=1
    for j,r in enumerate(sym):
        B[0,j+1]=r
    for i in range(n):
        B[i+1,i+1]=M

    started=time.monotonic()
    L=B.LLL(delta=0.99)
    elapsed=time.monotonic()-started

    candidates=[]
    seen=set()
    for row in L.rows():
        c=candidate_from_row(row,values)
        if c is None:
            continue
        key=tuple(c["q"])
        if key in seen:
            continue
        seen.add(key)
        candidates.append(c)

    candidates.sort(key=lambda c:(c["max_bits"],c["den_bits"]))
    if candidates:
        c=candidates[0]
        print(
            "Q24SRR_CHUNK|"
            f"label={label}|n={n}|candidates={len(candidates)}|"
            f"max_bits={c['max_bits']}|den_bits={c['den_bits']}|"
            f"seconds={elapsed:.3f}|status=CANDIDATE",
            flush=True,
        )
        return c["q"]

    print(
        "Q24SRR_CHUNK|"
        f"label={label}|n={n}|candidates=0|"
        f"seconds={elapsed:.3f}|status=NO_VECTOR",
        flush=True,
    )
    return None


def reconstruct_with_chunks(chunk_size):
    out=[None]*156
    chunks=[]
    for block,(lo,hi) in blocks_layout.items():
        start=lo
        while start<hi:
            end=min(start+chunk_size,hi)
            chunks.append((block,start,end))
            start=end

    for block,start,end in chunks:
        q=srr_chunk(
            residues[start:end],
            f"{block}[{start-blocks_layout[block][0]}:{end-blocks_layout[block][0]}]",
        )
        if q is None:
            return None
        out[start:end]=q

    assert all(v is not None for v in out)
    return out


def reconstruct_whole_blocks():
    out=[None]*156
    for block,(lo,hi) in blocks_layout.items():
        q=srr_chunk(residues[lo:hi],block)
        if q is None:
            return None
        out[lo:hi]=q
    assert all(v is not None for v in out)
    return out


def verify_candidate(coeffs,strategy):
    Zq=list(coeffs[:24])+[QQ(1)]
    Xq=list(coeffs[24:77])
    Yq=list(coeffs[77:])

    # Exact p^N congruence.
    for i,q in enumerate(coeffs):
        den=ZZ(q.denominator())
        num=ZZ(q.numerator())
        if den%p==0 or (num-den*residues[i])%M:
            return None

    RQ=PolynomialRing(QQ,"U")
    Z=RQ(Zq)
    X=RQ(Xq)
    Y=RQ(Yq)
    A=RQ(A_QQ)
    B=RQ(B_QQ)

    if not (
        Z.degree()==24 and Z.leading_coefficient()==1
        and X.degree()==52 and Y.degree()==78
    ):
        print(
            f"Q24SRR_VERIFY|strategy={strategy}|"
            f"degrees={Z.degree()},{X.degree()},{Y.degree()}|"
            "status=WRONG_DEGREES",
            flush=True,
        )
        return None

    identity=Y**2-X**3-A*X*Z**4-B*Z**6
    if identity:
        print(
            f"Q24SRR_VERIFY|strategy={strategy}|"
            f"identity_degree={identity.degree()}|status=NOT_EXACT",
            flush=True,
        )
        return None

    # Literal reduction to the degree-46 modular section.
    finite=GF(p)
    RF=PolynomialRing(finite,"U")

    def red(poly):
        return RF([
            finite(ZZ(v.numerator()))/finite(ZZ(v.denominator()))
            for v in poly.list()
        ])

    sec=mod["section_mod_p"]
    Zm=RF([finite(int(v)) for v in sec["Z_coefficients_low_to_high"]])
    Xm=RF([finite(int(v)) for v in sec["X_coefficients_low_to_high"]])
    Ym=RF([finite(int(v)) for v in sec["Y_coefficients_low_to_high"]])

    if red(Z)!=Zm or red(X)!=Xm or red(Y)!=Ym:
        print(
            f"Q24SRR_VERIFY|strategy={strategy}|"
            "modp_match=0|status=REJECT",
            flush=True,
        )
        return None

    max_num_bits=max(
        abs(ZZ(v.numerator())).nbits()
        for v in list(Z)+list(X)+list(Y)
    )
    max_den_bits=max(
        abs(ZZ(v.denominator())).nbits()
        for v in list(Z)+list(X)+list(Y)
    )

    print(
        "Q24SRR_VERIFY|"
        f"strategy={strategy}|identity=PASS|modp=PASS|"
        f"max_num_bits={max_num_bits}|max_den_bits={max_den_bits}|"
        "status=PASS_EXACT_Q24",
        flush=True,
    )

    return Z,X,Y,max_num_bits,max_den_bits


# Whole polynomial blocks first, then smaller chunks.
strategies=[
    ("whole_blocks",None),
    ("chunks_24",24),
    ("chunks_16",16),
    ("chunks_12",12),
    ("chunks_8",8),
    ("chunks_6",6),
    ("chunks_4",4),
]

winner=None
diagnostics=[]

for name,size in strategies:
    print(f"Q24SRR_STRATEGY|name={name}|status=START",flush=True)
    coeffs=(
        reconstruct_whole_blocks()
        if size is None
        else reconstruct_with_chunks(size)
    )
    if coeffs is None:
        diagnostics.append({"strategy":name,"reconstructed":False})
        print(f"Q24SRR_STRATEGY|name={name}|status=NO_RECONSTRUCTION",flush=True)
        continue

    verified=verify_candidate(coeffs,name)
    diagnostics.append({
        "strategy":name,
        "reconstructed":True,
        "exact":bool(verified),
    })
    if verified:
        winner=(name,verified)
        break

if winner is None:
    diag_out=(
        args.output.resolve()
        if args.output
        else LOCAL/"q24-srr-diagnostics.json"
    )
    diag_out.write_text(json.dumps({
        "schema":"elkies-k3.h92-q24-srr-diagnostics.v1",
        "status":"NEEDS_DIFFERENT_EXACTIFICATION",
        "prime":int(p),
        "precision":N,
        "modulus_bits":int(M.nbits()),
        "strategies":diagnostics,
        "next":(
            "Do not increase Hensel precision automatically. "
            "Use exact direct degree-46 trace over QQ(U), or structured "
            "multi-prime/simultaneous reconstruction."
        ),
    },indent=2,sort_keys=True)+"\n")
    print(f"OUTPUT|{diag_out}",flush=True)
    print(
        "Q24SRR_RESULT|status=NO_EXACT_VECTOR_FROM_CURRENT_SRR|"
        "action=STOP_HENSEL",
        flush=True,
    )
    raise SystemExit(2)

strategy,(Z,X,Y,max_num_bits,max_den_bits)=winner

exact_payload={
    "schema":"elkies-k3.h92-q8-q24-horizontal-section-qq.v3",
    "status":"PASS_EXACT_Q24_HORIZONTAL_SECTION",
    "zero":"II*_E8_1_branch_anchor",
    "formula":"Q24 = AJ(Qmap-S3) + 2*G1",
    "bridge":{
        "formula":"Qmap-S3",
        "q8_degree":46,
    },
    "profile":{
        "P_dot_O":24,
        "height":"52",
        "D13_local_correction":"0",
        "Z_degree":24,
        "X_degree":52,
        "Y_degree":78,
        "x_degrees":[52,48],
        "y_degrees":[78,72],
    },
    "section":{
        "Z_coefficients_low_to_high":[str(v) for v in Z.list()],
        "X_coefficients_low_to_high":[str(v) for v in X.list()],
        "Y_coefficients_low_to_high":[str(v) for v in Y.list()],
        "x_numerator_coefficients_low_to_high":[str(v) for v in X.list()],
        "x_denominator_coefficients_low_to_high":[str(v) for v in (Z**2).list()],
        "y_numerator_coefficients_low_to_high":[str(v) for v in Y.list()],
        "y_denominator_coefficients_low_to_high":[str(v) for v in (Z**3).list()],
        "x":"X/Z^2",
        "y":"Y/Z^3",
    },
    "verification":{
        "exact_weierstrass_identity":True,
        "p512_congruence":True,
        "reduction_matches_degree46_modular_section":True,
    },
    "exactification":{
        "method":"simultaneous rational reconstruction by LLL",
        "strategy":strategy,
        "source_hensel_checkpoint":str(INPUT.relative_to(ROOT)),
        "hensel_precision_reused":N,
        "modulus_bits":int(M.nbits()),
        "max_numerator_bits":int(max_num_bits),
        "max_denominator_bits":int(max_den_bits),
        "additional_hensel_iterations":0,
    },
    "source_modular_seed":str(MODSEED.relative_to(ROOT)),
    "child_model":str(CHILD.relative_to(ROOT)),
    "next":(
        "Build the exact q24 isotropic divisor / resolved RR pencil on D13 "
        "and derive the D12/MW5 child."
    ),
}

exact_out=(
    args.exact_output.resolve()
    if args.exact_output
    else LOCAL/"q8-q24-horizontal-section-qq.json"
)

if exact_out.exists():
    old=json.loads(exact_out.read_text())
    if old.get("status")=="PASS_EXACT_Q24_HORIZONTAL_SECTION":
        # Refuse to overwrite a contradictory exact section.
        RQ=Z.parent()
        sec=old.get("section",{})
        if "x_numerator_coefficients_low_to_high" in sec:
            ox=RQ([QQ(v) for v in sec["x_numerator_coefficients_low_to_high"]])
            od=RQ([QQ(v) for v in sec["x_denominator_coefficients_low_to_high"]])
            assert X*od==ox*(Z**2)

exact_out.parent.mkdir(parents=True,exist_ok=True)
exact_out.write_text(json.dumps(exact_payload,indent=2,sort_keys=True)+"\n")

if args.output:
    diag=args.output.resolve()
    diag.write_text(json.dumps({
        "schema":"elkies-k3.h92-q24-srr-diagnostics.v1",
        "status":"PASS_EXACT_Q24_BY_SRR",
        "strategy":strategy,
        "prime":int(p),
        "precision":N,
        "modulus_bits":int(M.nbits()),
        "max_numerator_bits":int(max_num_bits),
        "max_denominator_bits":int(max_den_bits),
        "strategies":diagnostics,
    },indent=2,sort_keys=True)+"\n")
    print(f"OUTPUT|{diag}",flush=True)

print(f"EXACT_OUTPUT|{exact_out}",flush=True)
print(
    "Q24SRR_RESULT|"
    f"strategy={strategy}|"
    f"max_num_bits={max_num_bits}|max_den_bits={max_den_bits}|"
    "status=PASS_EXACT_Q24_BY_SIMULTANEOUS_RECONSTRUCTION",
    flush=True,
)
