from sage.all import *
from pathlib import Path

FRAME=Path("elkies-k3/data/fibrations/q90_mw7_frame.txt")
F=matrix(ZZ,[[ZZ(x) for x in ln.split()] for ln in FRAME.read_text().splitlines() if ln.strip()])
assert F.nrows()==17 and F.ncols()==17 and F.is_symmetric()
print(f"Q90NODE|stage=input|rank={F.rank()}|det={F.det()}|positive={F.is_positive_definite()}",flush=True)

def qform_from_hessian(H):
    co=[]
    for i in range(H.nrows()):
        for j in range(i,H.ncols()):
            co.append(H[i,i]//2 if i==j else H[i,j])
    return QuadraticForm(ZZ,H.nrows(),co)

Q=qform_from_hessian(F)
arr=Q.short_vector_list_up_to_length(2,True)
roots_half=[vector(ZZ,r) for r in (arr[1] if len(arr)>1 else [])]
roots=roots_half+[-r for r in roots_half]
Rmat=matrix(ZZ,[list(r) for r in roots_half])
rrank=Rmat.rank() if roots_half else 0
print(f"Q90NODE|stage=roots|half={len(roots_half)}|signed={len(roots)}|rank={rrank}",flush=True)

# Exact root lattice generated by all roots.
Lroot=matrix(ZZ,[list(r) for r in roots]).row_module()
B=Lroot.basis_matrix()
Groot=B*F*B.transpose()
print(f"Q90NODE|stage=root_lattice|rank={B.rank()}|det={abs(Groot.det())}|gram={Groot}",flush=True)

# Build root graph: connect signed roots by inner product -1 after choosing a simple system.
# We find a positive chamber by choosing a random generic vector and selecting positive roots,
# then greedily extract indecomposable positive roots as simple roots.
def classify_ade(rank,nroots,det):
    # Search ADE partitions by invariant triple.
    comps=[]
    def inv(t,n):
        if t=="A": return (n,n*(n+1),n+1)
        if t=="D":
            if n<4: return None
            return (n,2*n*(n-1),4)
        if t=="E":
            return {6:(6,72,3),7:(7,126,2),8:(8,240,1)}.get(n)
    atoms=[]
    for n in range(1,18): atoms.append((f"A{n}",)+inv("A",n))
    for n in range(4,18): atoms.append((f"D{n}",)+inv("D",n))
    for n in (6,7,8): atoms.append((f"E{n}",)+inv("E",n))
    sols=[]
    def rec(start,rleft,nleft,dleft,chosen):
        if rleft==0:
            if nleft==0 and dleft==1: sols.append(tuple(chosen))
            return
        for i in range(start,len(atoms)):
            name,r,nr,d=atoms[i]
            if r>rleft or nr>nleft or dleft%d: continue
            rec(i,rleft-r,nleft-nr,dleft//d,chosen+[name])
    rec(0,rank,nroots,det,[])
    return sols

sols=classify_ade(rrank,len(roots),abs(Groot.det()))
print(f"Q90NODE|stage=ADE|solutions={sols}",flush=True)

# Full NS presentation at this node.
U=matrix(ZZ,[[0,1],[1,0]])
NS=block_diagonal_matrix(U,-F)
assert abs(NS.det())==948
print(f"Q90NODE|stage=NS|rank={NS.rank()}|det={NS.det()}",flush=True)

# Trivial lattice determinant from U + root lattice.
triv_det=abs(Groot.det())
mw_rank=17-rrank
reg_tors1=QQ(abs(NS.det()))/QQ(triv_det)
print(f"Q90NODE|stage=shioda|root_rank={rrank}|MW_rank={mw_rank}|root_det={triv_det}|regulator_if_torsion1={reg_tors1}",flush=True)

out=Path("artifacts/local/elkies-k3/q90-node-analysis.txt")
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text(
    f"det_frame={F.det()}\n"
    f"root_rank={rrank}\nroot_count={len(roots)}\nroot_det={abs(Groot.det())}\n"
    f"ADE={sols}\nMW_rank={mw_rank}\nregulator_if_torsion1={reg_tors1}\n"
    f"root_basis=\n{B}\nroot_gram=\n{Groot}\n"
)
print(f"Q90NODE|stage=done|out={out}",flush=True)
