#!/usr/bin/env sage
"""Rejected saturated-module diagnostic for an intermediate CM-43 class.

The O/E7-reduced class is ``D=Q79+4*O-43*F``.  It is not movable in the full
CM-43 chamber: fixed sections ``4*(P1-P2)`` and ``P3-P2`` reduce it to the old
fiber ``F``.  This script preserves the earlier module-saturation experiment
and is not a live q=60 construction.

On a smooth old fiber the
relative space is generated by ``1,x,y,x^2,z_Q``, but neither ``z_Q`` nor
``h*z_Q`` is a globally saturated generator.  Put

    D0 = h^2*x-Nx,   Nq = h^3*y+Ny,

and choose the unique polynomial ``k`` of degree < deg(h) satisfying
``k = Ny/Nx (mod h)``.  Since ``h*z_Q=Nq/D0`` and its reduction modulo h is
``-Ny/Nx``, the compensated function

    w = (h*z_Q+k)/h
      = ((Ny-k*Nx)/h + k*h*x + h^2*y) / D0

is integral at every zero of h and has infinity weight two.  Therefore
``{1,x,y,x^2,w}`` is the required saturated relative module.

For a coefficient of w of degree M, the four regular coefficient bounds are
M+2, M-2, M-4, M-6.  Clearing D0 (weight 120), this script imposes infinity
weight <=120 and divisibility by T^43 for the rejected intermediate class.
Any kernel or full-rank result is diagnostic only.
"""

import argparse
from pathlib import Path

from sage.all import *


parser = argparse.ArgumentParser()
parser.add_argument("--p", type=int, default=101)
parser.add_argument("--min-degree", type=int, default=40)
parser.add_argument("--max-degree", type=int, default=48)
parser.add_argument(
    "--fiber-at-infinity", action="store_true",
    help="represent -43F at infinity (weight <=77) instead of T=0",
)
args = parser.parse_args()

load(str(Path(__file__).resolve().parent / "verify_cm43_humbert8_anchor.sage"))

p = ZZ(args.p)
assert p.is_prime()
field = GF(p)
RTp = PolynomialRing(field, "T")
Tp = RTp.gen()

Q79 = 4*point1-5*point2+point3
Nxq = RT(Q79[0].numerator())
Nyq = RT(Q79[1].numerator())
hq = RT(Q79[0].denominator().sqrt())
assert Q79[0].denominator() == hq**2
assert Q79[1].denominator() == hq**3
assert (Nxq.degree(), Nyq.degree(), hq.degree()) == (120, 180, 58)


def reduce_polynomial(poly):
    assert all(QQ(value).denominator() % p for value in poly)
    return RTp([
        field(QQ(value).numerator())/field(QQ(value).denominator())
        for value in poly
    ])


Nx, Ny, h = map(reduce_polynomial, (Nxq, Nyq, hq))
assert gcd(Nx, h) == 1
k = RTp((Ny*inverse_mod(Nx, h)) % h)
scalar_quotient, scalar_remainder = (Ny-k*Nx).quo_rem(h)
assert scalar_remainder == 0 and k.degree() < h.degree()

# Numerator of the saturated generator w over D0=h^2*x-Nx.
w_terms = (
    ("one", scalar_quotient),
    ("x", k*h),
    ("y", h**2),
)
assert max(
    polynomial.degree()+{"one": 0, "x": 4, "y": 6}[kind]
    for kind, polynomial in w_terms
) == 122

cleared_weights = {
    "one": 0, "x": 4, "x2": 8, "x3": 12, "y": 6, "yx": 10,
}


def analyze(max_degree):
    columns = []
    names = []

    def add(name, terms):
        column = {}
        for kind, polynomial, shift in terms:
            for degree, value in enumerate(polynomial):
                if value:
                    key = (kind, degree+shift)
                    column[key] = column.get(key, field(0))+value
        columns.append(column)
        names.append(name)

    for degree in range(max_degree+1):
        add(
            f"c[{degree}]",
            tuple((kind, polynomial, degree) for kind, polynomial in w_terms),
        )

    regular_data = (
        ("a0", "one", max_degree+2),
        ("a1", "x", max_degree-2),
        ("a2", "x2", max_degree-6),
        ("b0", "y", max_degree-4),
    )
    h2 = h**2
    for prefix, kind, upper in regular_data:
        for degree in range(max(-1, upper)+1):
            if kind == "one":
                terms = (("x", h2, degree), ("one", -Nx, degree))
            elif kind == "x":
                terms = (("x2", h2, degree), ("x", -Nx, degree))
            elif kind == "x2":
                terms = (("x3", h2, degree), ("x2", -Nx, degree))
            else:
                terms = (("yx", h2, degree), ("y", -Nx, degree))
            add(f"{prefix}[{degree}]", terms)

    row_keys = set()
    for column in columns:
        for kind, degree in column:
            if args.fiber_at_infinity:
                constrained = degree+cleared_weights[kind] > 77
            else:
                constrained = (
                    degree+cleared_weights[kind] > 120 or degree < 43
                )
            if constrained:
                row_keys.add((kind, degree))
    row_keys = sorted(row_keys)
    row_index = {key: index for index, key in enumerate(row_keys)}
    entries = {}
    for column_index, column in enumerate(columns):
        for key, value in column.items():
            if key in row_index and value:
                entries[(row_index[key], column_index)] = value
    system = matrix(field, len(row_keys), len(columns), entries, sparse=True)
    rank = system.rank()
    nullity = system.ncols()-rank
    c_rank = None
    if nullity:
        kernel = system.right_kernel_matrix()
        c_rank = kernel[:, :max_degree+1].rank()
    print(
        f"CM43Q60SATRR|p={p}|M={max_degree}|rows={system.nrows()}"
        f"|columns={system.ncols()}|rank={rank}|nullity={nullity}"
        f"|kernel_c_rank={c_rank}|deg_k={k.degree()}",
        flush=True,
    )


assert 0 <= args.min_degree <= args.max_degree
for degree in range(args.min_degree, args.max_degree+1):
    analyze(degree)

print("CM43Q60SATRR|status=RANK_ANALYSIS_COMPLETE", flush=True)
