from sage.all import *
from pathlib import Path

OUT=Path("artifacts/local/elkies-k3")
OUT.mkdir(parents=True,exist_ok=True)

U=matrix(ZZ,[[0,1],[1,0]])
E8=matrix(ZZ,[
[2,-1,0,0,0,0,0,0],
[-1,2,-1,0,0,0,0,0],
[0,-1,2,-1,0,0,0,-1],
[0,0,-1,2,-1,0,0,0],
[0,0,0,-1,2,-1,0,0],
[0,0,0,0,-1,2,-1,0],
[0,0,0,0,0,-1,2,0],
[0,0,-1,0,0,0,0,2],
])
A2=matrix(ZZ,[[2,-1],[-1,2]])
NS=block_diagonal_matrix(U,-E8,-E8,-A2)

ve8=vector(ZZ,[9,-2,-10,-7,-4,4,3,-7])
w=vector(ZZ,[0]*20)
for i,x in enumerate(ve8): w[2+i]=x
assert w*NS*w==-316

# Generic NS S=w^perp.
K=matrix(ZZ,1,20,list(w*NS)).right_kernel_matrix()
S=K*NS*K.transpose()
assert S.rank()==19 and abs(S.det())==948

# Enumerate the roots in the broken first E8 orthogonal to ve8.
def qform_from_hessian(H):
    co=[]
    n=H.nrows()
    for i in range(n):
        for j in range(i,n):
            co.append(H[i,i]//2 if i==j else H[i,j])
    return QuadraticForm(ZZ,n,co)

Q8=qform_from_hessian(E8)
# Sage returns one representative from each +/- pair here.
roots_half=[vector(ZZ,r) for r in Q8.short_vector_list_up_to_length(2,True)[1]]
roots=[r for r in roots_half if r*E8*ve8==0]
signed=roots+[-r for r in roots]
print(f"R3FIB|stage=broken_E8|half_roots={len(roots)}|signed_roots={len(signed)}|rank={matrix(ZZ,roots).rank()}",flush=True)

# Classify simply from rank/root count, then verify decomposition by connected components.
rank=matrix(ZZ,roots).rank()
root_count=len(signed)
known={
    (1,2):"A1",
    (2,6):"A2",
    (3,12):"A3",
    (4,20):"A4",
    (4,24):"D4",
}
# For reducible rank 4, 12 roots uniquely gives A2+A2 among ADE root systems.
if (rank,root_count)==(4,12):
    dtype="A2+A2"
else:
    dtype=known.get((rank,root_count),"unknown")
print(f"R3FIB|stage=root_type|type={dtype}|rank={rank}|roots={root_count}",flush=True)

# Find a small independent basis of the root lattice and compute its saturated determinant.
basis=[]
for r in sorted(signed,key=lambda v:tuple(abs(int(x)) for x in v)):
    if not basis or matrix(QQ,basis+[r]).rank()>len(basis):
        basis.append(r)
        if len(basis)==rank: break
B=matrix(ZZ,basis)
Gbroken=B*E8*B.transpose()
print(f"R3FIB|broken_basis={basis}|gram={Gbroken}|det_basis_gram={Gbroken.det()}",flush=True)

# The chosen independent roots may span a sublattice. Compute the lattice generated by ALL roots.
L=matrix(ZZ,signed).row_module()
Lb=L.basis_matrix()
Groot=Lb*E8*Lb.transpose()
print(f"R3FIB|broken_root_lattice_basis={Lb}|gram={Groot}|det={Groot.det()}",flush=True)
assert Groot.det()==9  # A2^2

# Full inherited reducible root system is E8 + A2(original) + A2^2.
root_det=ZZ(1*3*9)
root_rank=ZZ(8+2+4)
mw_rank=ZZ(19-2-root_rank)
print(f"R3FIB|stage=trivial|ADE=E8+A2+A2+A2|root_rank={root_rank}|root_det={root_det}|MW_rank={mw_rank}",flush=True)
assert root_det==27 and mw_rank==3

# Assuming no torsion, Shioda discriminant formula gives the MW regulator.
# |disc(NS)| = disc(root)*Reg(MW)/|tors|^2.
reg_no_tors = QQ(abs(S.det())) / QQ(root_det)
print(f"R3FIB|stage=shioda|discNS={abs(S.det())}|regulator_if_torsion1={reg_no_tors}",flush=True)

# Build the full trivial lattice directly in CM NS coordinates:
# U + broken roots + untouched second E8 + untouched final A2.
gens=[]
# U basis.
for i in range(2):
    e=vector(ZZ,[0]*20); e[i]=1; gens.append(e)
# broken root lattice basis.
for r in Lb.rows():
    e=vector(ZZ,[0]*20)
    for j,x in enumerate(r): e[2+j]=x
    gens.append(e)
# second E8.
for i in range(8):
    e=vector(ZZ,[0]*20); e[10+i]=1; gens.append(e)
# final A2.
for i in range(2):
    e=vector(ZZ,[0]*20); e[18+i]=1; gens.append(e)

Triv=matrix(ZZ,gens)
assert Triv.nrows()==16
Gtriv=Triv*NS*Triv.transpose()
print(f"R3FIB|stage=trivial_exact|rank={Gtriv.rank()}|det={Gtriv.det()}",flush=True)
assert abs(Gtriv.det())==27

# Orthogonal complement of the trivial lattice in the CM NS has rank 4:
# it contains w plus the 3-dimensional generic MW direction.
pair=Triv*NS
C=pair.right_kernel_matrix()
GC=C*NS*C.transpose()
print(f"R3FIB|stage=essential_CM|rank={GC.rank()}|det={GC.det()}|gram={GC}",flush=True)

# Intersect with w^perp to get the generic rank-3 essential lattice.
constraints=matrix(ZZ,list(pair.rows())+[list(w*NS)])
C3=constraints.right_kernel_matrix()
G3=C3*NS*C3.transpose()
print(f"R3FIB|stage=essential_generic|rank={G3.rank()}|det={G3.det()}|gram={G3}",flush=True)
assert G3.rank()==3

# Positive version for easier comparison with MW heights.
P3=-G3
print(f"R3FIB|positive_essential_gram={P3}|det={P3.det()}",flush=True)

(OUT/"inherited-rank3-fibration.txt").write_text(
    f"broken_type={dtype}\n"
    f"broken_root_gram={Groot}\n"
    f"ADE=E8+A2+A2+A2\n"
    f"root_det={root_det}\n"
    f"mw_rank={mw_rank}\n"
    f"regulator_if_torsion1={reg_no_tors}\n"
    f"essential_generic={G3}\n"
    f"positive_essential={P3}\n"
)
print("R3FIB|stage=done|status=OK",flush=True)
