#!/usr/bin/env sage-python
"""Certify zero-orbit Weil compression for terminal rank-transfer cores.

The reverse masks use only the A_W-coordinate zero in the forced splitting
A_K = A_W orthogonal_sum (-A_C).  Averaging a vector-valued modular form over
O(q_W) commutes with the Weil representation and leaves those coefficients
unchanged.  This checker computes the exact orbit quotient for the four
terminal finite quadratic modules and certifies, by good-prime reduction, that
the cyclic Weil submodule generated by e_0 is the whole orbit quotient.
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path

from sage.all import (
    GF,
    Genus,
    ComplexBallField,
    Permutation,
    PermutationGroup,
    QQ,
    ZZ,
    block_diagonal_matrix,
    diagonal_matrix,
    identity_matrix,
    lcm,
    matrix,
    next_prime,
    vector,
)


ROOT = Path(__file__).resolve().parents[2]
GENERATED = ROOT / "artifacts/generated-results"
BRIDGES = GENERATED / "elkies-k3-integral-rank-transfer-bridge-reglue-v1.json"
MASKS = GENERATED / "elkies-k3-integral-rank-transfer-reverse-theta-masks-v1.json"
OUTPUT = GENERATED / "elkies-k3-integral-rank-transfer-weil-compression-v1.json"


def relative(path):
    return str(Path(path).resolve().relative_to(ROOT))


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def fractional_part(value):
    value = QQ(value)
    return value - value.floor()


def glued_frame(core, bridge, glue_vector):
    """Reconstruct W from the certified maximal graph presentation."""

    split = block_diagonal_matrix(core, bridge)
    denominator = lcm(value.denominator() for value in glue_vector)
    generators = (
        denominator * identity_matrix(QQ, split.nrows())
    ).stack(matrix(QQ, [denominator * glue_vector])).change_ring(ZZ)
    basis = generators.row_module(ZZ).basis_matrix().change_ring(QQ) / denominator
    candidate = basis * split * basis.transpose()
    assert all(value in ZZ for value in candidate.list())
    return candidate.change_ring(ZZ)


def orbit_partition(module):
    """Return O(q)-orbits as lists of indices, with the zero orbit first."""

    elements = list(module)
    index = {element: position for position, element in enumerate(elements)}
    orthogonal_group = module.orthogonal_group()
    permutations = [
        Permutation([index[automorphism(element)] + 1 for element in elements])
        for automorphism in orthogonal_group.gens()
    ]
    permutation_group = PermutationGroup(permutations)
    orbits = [[position - 1 for position in orbit] for orbit in permutation_group.orbits()]
    zero_index = index[module.zero()]
    zero_orbit_index = next(
        position for position, orbit in enumerate(orbits) if zero_index in orbit
    )
    orbits[0], orbits[zero_orbit_index] = orbits[zero_orbit_index], orbits[0]
    assert orbits[0] == [zero_index]
    assert sum(map(len, orbits)) == len(elements)
    assert sorted(position for orbit in orbits for position in orbit) == list(
        range(len(elements))
    )
    return elements, orthogonal_group, orbits


def first_good_split_prime(level):
    """Choose deterministically a prime with an N-th root of unity."""

    prime = next_prime(2 * level + 1)
    while (prime - 1) % level:
        prime = next_prime(prime)
    return ZZ(prime)


def cyclic_orbit_quotient_certificate(module, orbits):
    """Compute the S,T-closure of e_0 on orbit functions modulo a good prime.

    Omitting the common nonzero scalar in the Weil S-matrix does not change an
    invariant subspace.  Full rank after specialization proves full rank over
    the cyclotomic field: a nonzero minor modulo the selected prime cannot
    have been the zero cyclotomic integer.
    """

    elements = list(module)
    representatives = [orbit[0] for orbit in orbits]
    quadratic_gram = module.gram_matrix_quadratic()
    coordinates = [vector(ZZ, module.gens_vector(element)) for element in elements]

    def bilinear(left, right):
        return fractional_part(
            coordinates[left] * quadratic_gram * coordinates[right]
        )

    def half_quadratic(position):
        coordinates_value = coordinates[position]
        return fractional_part(
            (coordinates_value * quadratic_gram * coordinates_value) / 2
        )

    phases = [half_quadratic(position) for position in representatives]
    for right in representatives:
        phases.extend(bilinear(left, right) for left in range(len(elements)))
    level = ZZ(lcm(value.denominator() for value in phases))
    prime = first_good_split_prime(level)
    field = GF(prime)
    primitive_root = field.multiplicative_generator() ** ((prime - 1) // level)
    roots = [primitive_root**power for power in range(level)]

    def root_of_unity(exponent):
        return roots[int(fractional_part(exponent) * level)]

    s_matrix = matrix(
        field,
        [
            [
                sum(
                    (
                        root_of_unity(-bilinear(left, right))
                        for left in orbit
                    ),
                    field.zero(),
                )
                for orbit in orbits
            ]
            for right in representatives
        ],
    )
    t_matrix = diagonal_matrix(
        field,
        [root_of_unity(half_quadratic(position)) for position in representatives],
    )

    dimension = len(orbits)
    subspace = matrix(field, 1, dimension, [1] + [0] * (dimension - 1)).row_space()
    growth = [subspace.dimension()]
    while True:
        basis = list(subspace.basis())
        enlarged = matrix(
            field,
            basis
            + [s_matrix * value for value in basis]
            + [t_matrix * value for value in basis],
        ).row_space()
        growth.append(enlarged.dimension())
        if enlarged.dimension() == subspace.dimension():
            break
        subspace = enlarged
    assert subspace.dimension() == dimension
    assert primitive_root.multiplicative_order() == level
    return {
        "weil_phase_level": int(level),
        "split_prime": int(prime),
        "primitive_root_order": int(primitive_root.multiplicative_order()),
        "cyclic_closure_dimensions": list(map(int, growth)),
        "cyclic_submodule_dimension": int(subspace.dimension()),
        "equals_full_orthogonal_invariant_space": True,
    }


def smith_module_data(module):
    """Coordinate data for fast exact finite-module phase evaluation."""

    elements = list(module)
    coordinates = [vector(ZZ, list(element)) for element in elements]
    generators = module.smith_form_gens()
    bilinear_gram = matrix(
        QQ,
        [
            [QQ(left.inner_product(right)) for right in generators]
            for left in generators
        ],
    )
    return elements, coordinates, bilinear_gram


def exponential_sum(phase_counts, precision=192):
    """Evaluate a cyclotomic integer with certified ball arithmetic."""

    field = ComplexBallField(precision)
    imaginary_unit = field.gen(0)
    return sum(
        field(multiplicity)
        * (2 * field.pi() * imaginary_unit * field(phase)).exp()
        for phase, multiplicity in phase_counts.items()
    )


def fixed_trace_sums(coordinates, bilinear_gram, automorphisms, sign):
    """Twisted Gauss sums entering the invariant Riemann--Roch formula."""

    s_counts = Counter()
    st_counts = Counter()
    for automorphism in automorphisms:
        for value in coordinates:
            bilinear = sign * (value * automorphism) * bilinear_gram * value
            quadratic = sign * (value * bilinear_gram * value) / 2
            s_counts[fractional_part(bilinear)] += 1
            st_counts[fractional_part(bilinear - quadratic)] += 1
    return exponential_sum(s_counts), exponential_sum(st_counts)


def unique_integer_in_ball(value):
    """Certify that a real ball contains exactly one integer."""

    lower = value.lower().ceil()
    upper = value.upper().floor()
    assert lower == upper
    return ZZ(lower)


def invariant_modular_dimensions(frame_module, bridge_module, orbits):
    """Riemann--Roch dimensions after O(q_W) averaging and theta parity.

    The theta series uses the dual discriminant form
    -q_K=(-q_W) orthogonal_sum q_C.  Since -1 belongs to O(q_W), the
    total theta involution reduces the bridge factor independently modulo
    b ~ -b.  This is the invariant_forms_dimension trace formula evaluated
    on the product group O(q_W) x {+1,-1}.
    """

    frame_elements, frame_coordinates, frame_gram = smith_module_data(
        frame_module
    )
    bridge_elements, bridge_coordinates, bridge_gram = smith_module_data(
        bridge_module
    )
    frame_group = frame_module.orthogonal_group()
    frame_automorphisms = [value.matrix() for value in frame_group]
    bridge_rank = len(bridge_module.invariants())
    bridge_automorphisms = [
        identity_matrix(ZZ, bridge_rank),
        -identity_matrix(ZZ, bridge_rank),
    ]

    frame_s, frame_st = fixed_trace_sums(
        frame_coordinates, frame_gram, frame_automorphisms, -1
    )
    bridge_s, bridge_st = fixed_trace_sums(
        bridge_coordinates, bridge_gram, bridge_automorphisms, 1
    )

    frame_representatives = [frame_coordinates[orbit[0]] for orbit in orbits]
    bridge_representatives = []
    seen = set()
    for element, coordinates in zip(bridge_elements, bridge_coordinates):
        if element in seen:
            continue
        bridge_representatives.append(coordinates)
        seen.add(element)
        seen.add(-element)

    t_exponents = [
        fractional_part(
            (frame_value * frame_gram * frame_value) / 2
            - (bridge_value * bridge_gram * bridge_value) / 2
        )
        for frame_value in frame_representatives
        for bridge_value in bridge_representatives
    ]
    coefficient_dimension = len(t_exponents)
    alpha_t = sum(t_exponents)
    isotropic_orbits = sum(value == 0 for value in t_exponents)
    discriminant_order = len(frame_elements) * len(bridge_elements)
    group_order = len(frame_automorphisms) * len(bridge_automorphisms)

    field = frame_s.parent()
    imaginary_unit = field.gen(0)
    weight = QQ(15) / 2
    signature = 1  # signature of -q_K for a positive rank-15 core
    zeta_s = (
        2
        * field.pi()
        * imaginary_unit
        * field((2 * weight + signature) / 8)
    ).exp()
    zeta_st = (
        2
        * field.pi()
        * imaginary_unit
        * field((4 * weight + 3 * signature - 10) / 24)
    ).exp()
    dimension_ball = (
        field(coefficient_dimension * (weight + 5) / 12 - alpha_t)
        + zeta_s
        * frame_s
        * bridge_s
        / (4 * group_order * field(discriminant_order).sqrt())
        - (
            zeta_st
            * frame_st
            * bridge_st
            / (group_order * field(discriminant_order).sqrt())
        ).real()
        * field(2)
        / (3 * field(3).sqrt())
    )
    assert 0 in dimension_ball.imag()
    modular_dimension = unique_integer_in_ball(dimension_ball.real())
    cusp_dimension = modular_dimension - isotropic_orbits
    assert cusp_dimension >= 0
    return {
        "weight": "15/2",
        "riemann_roch_ball_precision_bits": 192,
        "dimension_integer_uniqueness_certified": True,
        "orthogonal_theta_symmetric_coefficient_dimension": coefficient_dimension,
        "modular_forms_dimension": int(modular_dimension),
        "isotropic_orbit_count": int(isotropic_orbits),
        "cusp_forms_dimension": int(cusp_dimension),
    }


def terminal_record(edge, mask_record):
    core = matrix(ZZ, edge["core"]["gram"])
    presentation = edge["new_frame"]
    bridge = matrix(ZZ, presentation["bridge_gram"])
    glue = vector(
        QQ,
        [
            QQ(value)
            for value in presentation["glue_generators"][0][
                "K_plus_C_dual_coordinates"
            ]
        ],
    )
    frame = glued_frame(core, bridge, glue)
    module = Genus(frame).discriminant_form().normal_form()
    bridge_module = Genus(bridge).discriminant_form().normal_form()
    elements, orthogonal_group, orbits = orbit_partition(module)

    # The canonical involution belongs to O(q_W), so every x and -x occur in
    # the same W-orbit.  Theta parity therefore reduces the bridge coordinate
    # independently modulo b ~ -b.
    orbit_index = {
        element_index: orbit_number
        for orbit_number, orbit in enumerate(orbits)
        for element_index in orbit
    }
    element_index = {element: position for position, element in enumerate(elements)}
    assert all(
        orbit_index[position] == orbit_index[element_index[-element]]
        for position, element in enumerate(elements)
    )

    bridge_invariants = list(map(int, presentation["bridge_discriminant_group_invariants"]))
    assert len(bridge_invariants) == 1
    bridge_order = bridge_invariants[0]
    assert bridge_order % 2 == 1
    frame_order = abs(int(frame.det()))
    core_order = abs(int(core.det()))
    assert core_order == frame_order * bridge_order
    assert int(mask_record["cyclic_order"]) == bridge_order

    orbit_dimension = len(orbits)
    full_dimension = core_order
    invariant_dimension = orbit_dimension * bridge_order
    theta_symmetric_dimension = orbit_dimension * ((bridge_order + 1) // 2)
    certificate = cyclic_orbit_quotient_certificate(module, orbits)
    assert certificate["cyclic_submodule_dimension"] == orbit_dimension
    modular_dimensions = invariant_modular_dimensions(
        module, bridge_module, orbits
    )
    assert (
        modular_dimensions["orthogonal_theta_symmetric_coefficient_dimension"]
        == theta_symmetric_dimension
    )
    mask_classes = []
    for bridge_class in mask_record["classes"]:
        sizes = {
            int(graph["sign_symmetry_reduced_mask_cell_count"])
            for graph in bridge_class["graphs"]
        }
        accepts = {
            bool(graph["zero_mask_accepts"])
            for graph in bridge_class["graphs"]
        }
        assert len(sizes) == len(accepts) == 1
        mask_size = sizes.pop()
        cusp_kernel_lower_bound = (
            modular_dimensions["cusp_forms_dimension"] - mask_size
        )
        assert cusp_kernel_lower_bound > 0
        mask_classes.append(
            {
                "bridge_class_index": int(bridge_class["bridge_class_index"]),
                "sign_reduced_mask_cells": mask_size,
                "observed_core_accepts": accepts.pop(),
                "cusp_zero_mask_kernel_dimension_lower_bound": (
                    cusp_kernel_lower_bound
                ),
            }
        )
    return {
        "corridor": edge["corridor"],
        "frame_discriminant_order": frame_order,
        "bridge_discriminant_order": bridge_order,
        "core_discriminant_order": core_order,
        "frame_discriminant_group_invariants": list(map(int, module.invariants())),
        "frame_discriminant_quadratic_gram": [
            [str(value) for value in row]
            for row in module.gram_matrix_quadratic().rows()
        ],
        "orthogonal_group_order": int(orthogonal_group.order()),
        "orthogonal_orbit_count": orbit_dimension,
        "orthogonal_orbit_size_distribution": {
            str(size): sum(len(orbit) == size for orbit in orbits)
            for size in sorted(set(map(len, orbits)))
        },
        "zero_orbit_size": len(orbits[0]),
        "full_weil_coefficient_dimension": full_dimension,
        "orthogonal_invariant_coefficient_dimension": invariant_dimension,
        "theta_symmetric_coefficient_dimension": theta_symmetric_dimension,
        "full_to_invariant_reduction": str(QQ(full_dimension) / invariant_dimension),
        "full_to_theta_symmetric_reduction": str(
            QQ(full_dimension) / theta_symmetric_dimension
        ),
        "reverse_mask_coordinates_preserved": int(
            mask_record["unoriented_sign_reduced_mask_count"]
        ),
        "modular_dimension_sieve": {
            **modular_dimensions,
            "mask_classes": mask_classes,
            "smallest_cusp_zero_mask_kernel_dimension_lower_bound": min(
                row["cusp_zero_mask_kernel_dimension_lower_bound"]
                for row in mask_classes
            ),
        },
        **certificate,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    arguments = parser.parse_args()

    bridges = json.loads(BRIDGES.read_text())
    masks = json.loads(MASKS.read_text())
    assert bridges["status"] == "PASS_EXACT_BRIDGE_REGLUE_CERTIFICATES"
    assert masks["status"] == "PASS_EXACT_REVERSE_THETA_ZERO_MASKS"
    terminal_edges = {
        row["corridor"]: row
        for row in bridges["edges"]
        if int(row["target_root_rank"]) == 0
    }
    mask_records = {row["corridor"]: row for row in masks["corridors"]}
    assert set(terminal_edges) == set(mask_records)
    records = [
        terminal_record(terminal_edges[name], mask_records[name])
        for name in sorted(terminal_edges)
    ]
    assert len(records) == 4
    assert all(row["zero_orbit_size"] == 1 for row in records)
    assert all(row["equals_full_orthogonal_invariant_space"] for row in records)

    payload = {
        "schema": "elkies-k3.integral-rank-transfer-weil-compression.v1",
        "status": "PASS_EXACT_ZERO_ORBIT_WEIL_COMPRESSION",
        "inputs": {
            relative(BRIDGES): digest(BRIDGES),
            relative(MASKS): digest(MASKS),
        },
        "theorem": {
            "factorization": (
                "The forced finite form is q_K=q_W orthogonal_sum (-q_C), "
                "and every reverse-mask coordinate has A_W-coordinate zero."
            ),
            "projection": (
                "Averaging over O(q_W) commutes with the Weil representation. "
                "Because {0} is a singleton orbit, it preserves every masked "
                "Fourier coefficient exactly."
            ),
            "dimension": (
                "Modular feasibility may therefore be computed in "
                "C[A_W]^{O(q_W)} tensor C[A_C], followed by theta symmetry, "
                "instead of the full C[A_K]."
            ),
            "cyclic_refinement": (
                "The still smaller candidate is the cyclic Weil submodule "
                "generated by e_0. For each of the four observed q_W it equals "
                "C[A_W]^{O(q_W)}; full rank is certified after reduction at a "
                "prime splitting the recorded cyclotomic phase field."
            ),
            "modular_dimension_audit": (
                "The invariant Riemann--Roch trace formula computes the exact "
                "weight-15/2 modular and cusp dimensions. Any m-cell zero "
                "mask has cusp-kernel codimension at most m; every observed "
                "mask leaves a positive kernel of the certified recorded "
                "dimension."
            ),
        },
        "corridors": records,
        "aggregate": {
            "corridor_count": len(records),
            "minimum_full_to_theta_symmetric_reduction": str(
                min(
                    QQ(row["full_weil_coefficient_dimension"])
                    / row["theta_symmetric_coefficient_dimension"]
                    for row in records
                )
            ),
            "maximum_full_to_theta_symmetric_reduction": str(
                max(
                    QQ(row["full_weil_coefficient_dimension"])
                    / row["theta_symmetric_coefficient_dimension"]
                    for row in records
                )
            ),
            "minimum_cusp_zero_mask_kernel_dimension_lower_bound": min(
                row["modular_dimension_sieve"][
                    "smallest_cusp_zero_mask_kernel_dimension_lower_bound"
                ]
                for row in records
            ),
            "all_masks_leave_nonzero_cusp_kernel": True,
            "rank17_children_constructed": 0,
        },
        "proof_boundary": {
            "proved": (
                "Exact preservation of all reverse-mask coordinates under "
                "orthogonal averaging, and exact orbit/cyclic dimensions for "
                "the four terminal finite quadratic modules."
            ),
            "not_proved": (
                "The dimension calculation does not decide whether the affine "
                "normalization theta_K(0,0)=1 is compatible with each rejected "
                "mask. No integral nonnegative modular signature has yet been "
                "enumerated, no allowed signature has been realized by a new "
                "lattice, and no end-to-end core-generation or complexity "
                "theorem is claimed."
            ),
        },
        "reproduce": (
            "sage -python elkies-k3/scripts/"
            "certify_integral_rank_transfer_weil_compression.sage --check"
        ),
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    output = arguments.output if arguments.output.is_absolute() else ROOT / arguments.output
    if arguments.check:
        if not output.exists():
            raise SystemExit(f"missing artifact: {output}")
        if output.read_text() != encoded:
            raise SystemExit(f"stale artifact: {output}")
        print("PASS zero-orbit Weil compression")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(encoded)
    print(relative(output))


if __name__ == "__main__":
    main()
