#!/usr/bin/env sage-python
"""Classify determinant-78 frames by a complete Niemeier-first census.

The positive rank-seven Nishiyama auxiliary has root system A3+A2+A1.
We first enumerate A3 root-subsystem orbits in every rooted Niemeier lattice,
then add A2 and A1 in the successive orthogonal root systems.  For every
primitive root anchor, the last norm-four auxiliary generator is enumerated
exactly modulo the residual Weyl group by dominant Dynkin labels and an exact
fixed-space ellipsoid.  Saturated orthogonal complements are classified by
their roots and deduplicated by PARI integral isometry.

This is a J2/frame classification.  It does not quotient by automorphisms of
the K3 surface and it does not construct equations or neighbour corridors.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
from collections import Counter, deque
from pathlib import Path

from sage.all import (
    CartanMatrix,
    Genus,
    Graph,
    QQ,
    ZZ,
    block_diagonal_matrix,
    ceil,
    diagonal_matrix,
    floor,
    identity_matrix,
    matrix,
    pari,
    vector,
)


ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "artifacts/generated-results/elkies-k3-rooted-niemeier-catalog.json"
SOURCE_FRAME = ROOT / "elkies-k3/data/lattice/e6_rank4_det78_frame.txt"
OUTPUT = ROOT / "artifacts/generated-results/elkies-k3-e6-rank4-det78-niemeier-frames-v1.json"

A3 = CartanMatrix(["A", 3])
A2 = CartanMatrix(["A", 2])
A1 = CartanMatrix(["A", 1])
ROOT_GRAM = block_diagonal_matrix(A3, A2, A1)
# In this standard chain basis the final generator has square 4 and pairs only
# with one endpoint of A3.  The Schur-complement norm is 4-3/4=13/4.
LAST_PAIRINGS = vector(ZZ, [-1, 0, 0, 0, 0, 0])
LAST_NORM = QQ(4)
RESIDUAL_BUDGET = QQ(13) / 4

TYPE_FROM_INVARIANT = {
    **{(rank, rank * (rank + 1)): f"A{rank}" for rank in range(1, 25)},
    **{(rank, 2 * rank * (rank - 1)): f"D{rank}" for rank in range(4, 25)},
    (6, 72): "E6",
    (7, 126): "E7",
    (8, 240): "E8",
}


def rows(value):
    return [list(map(int, row)) for row in matrix(ZZ, value).rows()]


def load_matrix(path):
    return matrix(
        ZZ,
        [
            [ZZ(entry) for entry in line.split()]
            for line in Path(path).read_text().splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ],
    )


def gram_sha256(value):
    text = "\n".join(" ".join(map(str, row)) for row in value.rows()) + "\n"
    return hashlib.sha256(text.encode()).hexdigest()


def primitive_rows(value):
    value = matrix(ZZ, value)
    smith = value.smith_form()[0]
    return tuple(abs(int(smith[i, i])) for i in range(value.nrows())) == (
        1,
    ) * value.nrows()


def signed_roots(gram):
    data = pari(gram).qfminim(2)
    half = [vector(ZZ, column) for column in matrix(ZZ, data[2].sage()).columns()]
    result = half + [-root for root in half]
    assert len(result) == int(data[0])
    return result


def root_components(gram, roots):
    unseen = set(range(len(roots)))
    result = []
    while unseen:
        component = {min(unseen)}
        pending = list(component)
        unseen.difference_update(component)
        while pending:
            current = pending.pop()
            adjacent = {
                index
                for index in unseen
                if roots[current] * gram * roots[index] != 0
            }
            component.update(adjacent)
            unseen.difference_update(adjacent)
            pending.extend(sorted(adjacent))
        result.append([roots[index] for index in sorted(component)])
    return result


def simple_roots(gram, roots):
    # Lexicographic sign is a regular infinitesimal linear functional and
    # avoids bounded trial searches for a chamber vector.
    positive = [root for root in roots if next(entry for entry in root if entry) > 0]
    positive_set = {tuple(map(int, root)) for root in positive}
    result = matrix(
        ZZ,
        [
            root
            for root in positive
            if not any(tuple(map(int, root - other)) in positive_set for other in positive)
        ],
    )
    assert result.rank() == result.nrows()
    return result


def hnf_key(value):
    return tuple(tuple(map(int, row)) for row in matrix(ZZ, value).hermite_form().rows())


def a3_orbit_representatives(gram, component_roots):
    """One A3 root-sublattice representative per Weyl orbit.

    Every A3 root can be moved to the fixed root and every root of A3 can be
    used as the first endpoint.  The stabilizer of that root is generated by
    reflections in its orthogonal roots, so the following finite orbit
    quotient is complete.
    """
    fixed = component_roots[0]
    subsystems = {}
    for middle in component_roots:
        if fixed * gram * middle != -1:
            continue
        for endpoint in component_roots:
            if fixed * gram * endpoint != 0 or middle * gram * endpoint != -1:
                continue
            basis = matrix(ZZ, [fixed, middle, endpoint])
            if basis * gram * basis.transpose() != A3:
                continue
            subsystems.setdefault(hnf_key(basis), basis)

    identity = identity_matrix(ZZ, gram.nrows())
    reflections = [
        identity - gram * root.column() * root.row()
        for root in component_roots
        if root * gram * fixed == 0
    ]
    unseen = set(subsystems)
    representatives = []
    while unseen:
        initial = min(unseen)
        orbit = {initial}
        pending = deque([initial])
        while pending:
            key = pending.popleft()
            basis = matrix(ZZ, key)
            for reflection in reflections:
                image = hnf_key(basis * reflection)
                if image not in subsystems:
                    raise AssertionError("A3 stabilizer left the enumerated subsystem set")
                if image not in orbit:
                    orbit.add(image)
                    pending.append(image)
        unseen.difference_update(orbit)
        representatives.append(subsystems[initial])
    return representatives, len(subsystems)


def first_a2_basis(gram, roots):
    first = roots[0]
    second = next(root for root in roots if first * gram * root == -1)
    result = matrix(ZZ, [first, second])
    assert result * gram * result.transpose() == A2
    return result


def dominant_labels_up_to(cartan_inverse, bound):
    rank = cartan_inverse.nrows()
    current = [ZZ(0)] * rank
    result = []

    def extend(index, norm):
        if index == rank:
            result.append((tuple(map(int, current)), norm))
            return
        cross = sum(
            current[previous] * cartan_inverse[previous, index]
            for previous in range(index)
        )
        coefficient = 0
        while True:
            new_norm = (
                norm
                + 2 * coefficient * cross
                + coefficient * coefficient * cartan_inverse[index, index]
            )
            if new_norm > bound:
                break
            current[index] = coefficient
            extend(index + 1, new_norm)
            coefficient += 1
        current[index] = 0

    extend(0, QQ(0))
    return result


def rational_ldl(value):
    size = value.nrows()
    lower = matrix(QQ, size, size)
    diagonal = [QQ(0)] * size
    for row in range(size):
        lower[row, row] = 1
        diagonal[row] = value[row, row] - sum(
            lower[row, index] ** 2 * diagonal[index] for index in range(row)
        )
        assert diagonal[row] > 0
        for later in range(row + 1, size):
            lower[later, row] = (
                value[later, row]
                - sum(
                    lower[later, index]
                    * diagonal[index]
                    * lower[row, index]
                    for index in range(row)
                )
            ) / diagonal[row]
    assert lower * diagonal_matrix(diagonal) * lower.transpose() == value
    return lower, diagonal


def exact_ceil_sqrt(value):
    numerator = int(value.numerator())
    denominator = int(value.denominator())
    result = math.isqrt(numerator // denominator)
    while result * result * denominator < numerator:
        result += 1
    return result


def shifted_ellipsoid_shell(quadratic, centre, norm):
    dimension = quadratic.nrows()
    if dimension == 0:
        return [tuple()] if norm == 0 else []
    lower, diagonal = rational_ldl(quadratic)
    current = [ZZ(0)] * dimension
    shifted = [QQ(0)] * dimension
    result = []

    def extend(index, remaining):
        if index < 0:
            if remaining == 0:
                result.append(tuple(map(int, current)))
            return
        tail = sum(
            lower[later, index] * shifted[later]
            for later in range(index + 1, dimension)
        )
        local_centre = centre[index] - tail
        radius = exact_ceil_sqrt(remaining / diagonal[index])
        first = int(floor(local_centre)) - radius - 1
        last = int(ceil(local_centre)) + radius + 1
        for coordinate in range(first, last + 1):
            local_shift = QQ(coordinate) - local_centre
            term = diagonal[index] * local_shift**2
            if term > remaining:
                continue
            current[index] = coordinate
            shifted[index] = QQ(coordinate) - centre[index]
            extend(index - 1, remaining - term)

    extend(dimension - 1, norm)
    return result


def ade_type(gram):
    roots = signed_roots(gram)
    if not roots:
        return "0", 0, 0
    pieces = []
    rank = 0
    for component in root_components(gram, roots):
        component_rank = matrix(ZZ, component).rank()
        invariant = (int(component_rank), len(component))
        pieces.append(TYPE_FROM_INVARIANT[invariant])
        rank += component_rank
    pieces.sort(key=lambda value: (value[0], int(value[1:])))
    counts = Counter(pieces)
    label = "+".join(
        (f"{count}{piece}" if count > 1 else piece)
        for piece, count in sorted(counts.items(), key=lambda item: (item[0][0], int(item[0][1:])))
    )
    return label, int(rank), len(roots)


def root_span_data(gram):
    roots = signed_roots(gram)
    if not roots:
        return [], 1, True
    basis = matrix(ZZ, roots).row_module().basis_matrix()
    root_gram = basis * gram * basis.transpose()
    smith = basis.smith_form()[0]
    invariants = [abs(int(smith[i, i])) for i in range(basis.nrows())]
    return invariants, abs(int(root_gram.det())), invariants == [1] * basis.nrows()


def matrix_key(value):
    return tuple(tuple(map(int, row)) for row in matrix(ZZ, value).rows())


def matrix_group(generators, degree, expected_order):
    identity = identity_matrix(ZZ, degree)
    seen = {matrix_key(identity): identity}
    pending = deque([identity])
    while pending:
        current = pending.popleft()
        for generator in generators:
            image = current * generator
            key = matrix_key(image)
            if key not in seen:
                seen[key] = image
                pending.append(image)
    if len(seen) != expected_order:
        raise AssertionError("small orthogonal-group closure has wrong order")
    return list(seen.values())


def root_glue_data(value):
    """Root basis, integral orthogonal quotient and finite outer data."""
    value = matrix(ZZ, value)
    roots = signed_roots(value)
    if not roots:
        return {"rank": 0, "gram": value}
    parts = root_components(value, roots)
    simple_parts = [simple_roots(value, part) for part in parts]
    simple = matrix(ZZ, [row for part in simple_parts for row in part.rows()])
    cartan = simple * value * simple.transpose()
    graph = Graph()
    graph.add_vertices(range(simple.nrows()))
    graph.add_edges(
        (row, column)
        for row in range(simple.nrows())
        for column in range(row)
        if cartan[row, column] == -1
    )
    orthogonal = (simple * value).right_kernel_matrix()
    quotient = orthogonal * value * orthogonal.transpose()
    completion = simple.stack(orthogonal)
    types = []
    for part in parts:
        invariant = (matrix(ZZ, part).rank(), len(part))
        types.append(TYPE_FROM_INVARIANT[invariant])
    return {
        "rank": simple.nrows(),
        "simple": simple,
        "cartan": cartan,
        "graph": graph,
        "orthogonal": orthogonal,
        "quotient": quotient,
        "completion": completion,
        "component_types": types,
    }


def quotient_automorphisms(quotient):
    degree = quotient.nrows()
    if degree == 0:
        return [matrix(ZZ, 0, 0)]
    data = pari(quotient).qfauto()
    order = int(data[0])
    generators = [matrix(ZZ, item.sage()).transpose() for item in data[1]]
    return matrix_group(generators, degree, order)


def quotient_isometries(left, right):
    if left.nrows() != right.nrows() or left.det() != right.det():
        return []
    if left.nrows() == 0:
        return [matrix(ZZ, 0, 0)]
    # PARI returns M with M^t * right * M = left for qfisom(left,right).
    column_isometry = pari(left).qfisom(pari(right))
    if column_isometry == 0:
        return []
    initial = matrix(ZZ, column_isometry.sage()).transpose()
    assert initial * right * initial.transpose() == left
    return [initial * automorphism for automorphism in quotient_automorphisms(right)]


def graph_isometry_matrices(left, right):
    isomorphic, initial = left.is_isomorphic(right, certificate=True)
    if not isomorphic:
        return []
    result = []
    for automorphism in right.automorphism_group():
        images = [automorphism(initial[index]) for index in range(left.num_verts())]
        permutation = matrix(ZZ, len(images), len(images))
        for source, target in enumerate(images):
            permutation[source, target] = 1
        result.append(permutation)
    return result


def integral_glue_extensions(
    left, right, left_data, right_data, root_maps, quotient_maps
):
    """Return the number of integral extensions of the block isometries.

    In the completion bases, roots and their integral orthogonal quotients are
    orthogonal.  Thus every supplied block map is already a rational isometry;
    it extends to the full lattice exactly when

        C_left^-1 * diag(root_map, quotient_map) * C_right

    is integral.  Equal determinants then force the integral map to be
    unimodular.  Clearing the one common denominator avoids constructing
    millions of dense rational block matrices during the all-Niemeier pass.
    """
    rank = left_data["rank"]
    left_inverse = left_data["completion"].inverse()
    denominator = ZZ(left_inverse.denominator())
    scaled_inverse = matrix(ZZ, denominator * left_inverse)
    right_completion = right_data["completion"]
    root_left = scaled_inverse[:, :rank]
    quotient_left = scaled_inverse[:, rank:]
    root_right = right_completion[:rank, :]
    quotient_right = right_completion[rank:, :]
    root_parts = [root_left * item * root_right for item in root_maps]
    quotient_parts = [
        quotient_left * item * quotient_right for item in quotient_maps
    ]
    count = 0
    for root_part in root_parts:
        for quotient_part in quotient_parts:
            numerator = root_part + quotient_part
            if not all(entry % denominator == 0 for entry in numerator.list()):
                continue
            trial = matrix(ZZ, numerator / denominator)
            assert abs(trial.det()) == 1
            assert trial * right * trial.transpose() == left
            count += 1
    return count


def root_glue_isometric(left, right, left_data=None, right_data=None):
    """Exact isometry using the root span and low-rank orthogonal quotient."""
    left = matrix(ZZ, left)
    right = matrix(ZZ, right)
    left_data = left_data or root_glue_data(left)
    right_data = right_data or root_glue_data(right)
    if left_data["rank"] != right_data["rank"]:
        return False
    if left_data["rank"] == 0:
        return pari(left).qfisom(pari(right)) != 0
    root_maps = graph_isometry_matrices(left_data["graph"], right_data["graph"])
    quotient_maps = quotient_isometries(left_data["quotient"], right_data["quotient"])
    if not root_maps or not quotient_maps:
        return False
    return bool(
        integral_glue_extensions(
            left, right, left_data, right_data, root_maps, quotient_maps
        )
    )


def weyl_order(component_types):
    exceptional = {"E6": 51840, "E7": 2903040, "E8": 696729600}
    result = ZZ(1)
    for component in component_types:
        family = component[0]
        rank = int(component[1:])
        if family == "A":
            result *= math.factorial(rank + 1)
        elif family == "D":
            result *= 2 ** (rank - 1) * math.factorial(rank)
        else:
            result *= exceptional[component]
    return result


def root_glue_automorphism_order(value, data=None):
    value = matrix(ZZ, value)
    data = data or root_glue_data(value)
    if data["rank"] == 0:
        return int(pari(value).qfauto()[0])
    root_maps = graph_isometry_matrices(data["graph"], data["graph"])
    quotient_maps = quotient_automorphisms(data["quotient"])
    outer_count = integral_glue_extensions(
        value, value, data, data, root_maps, quotient_maps
    )
    return int(weyl_order(data["component_types"]) * outer_count)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--output", type=Path, default=OUTPUT)
parser.add_argument("--check", action="store_true")
parser.add_argument("--ambient", action="append", default=[])
arguments = parser.parse_args()

# Rootful rank-17 isometry tests can use substantially more than PARI's
# one-gigabyte default stack even after root-type bucketing.
pari.allocatemem(8 * 1024**3)

catalog = json.loads(CATALOG.read_text())
source_frame = load_matrix(SOURCE_FRAME)
target_genus = Genus(source_frame)
assert source_frame.nrows() == 17 and source_frame.det() == 78

auxiliary = matrix(ZZ, 7, 7)
auxiliary[:6, :6] = ROOT_GRAM
auxiliary[6, 6] = 4
auxiliary[6, :6] = LAST_PAIRINGS
auxiliary[:6, 6] = LAST_PAIRINGS.column()
assert auxiliary.det() == 78
assert int(pari(auxiliary).qfminim(2)[0]) == 20

selected = set(arguments.ambient)
ambient_rows = []
classes = []
total_a3_subsystems = 0
total_root_anchors = 0
total_label_tuples = 0
total_ellipsoid = 0
total_integral = 0
total_primitive = 0

for ambient_entry in catalog["rooted_niemeier_lattices"]:
    label = ambient_entry["label"]
    if selected and label not in selected:
        continue
    gram = matrix(ZZ, ambient_entry["gram"])
    ambient_roots = signed_roots(gram)
    components = root_components(gram, ambient_roots)
    counts = Counter()
    anchors = []

    for component_index, component in enumerate(components):
        if matrix(ZZ, component).rank() < 3:
            continue
        a3_representatives, subsystem_count = a3_orbit_representatives(gram, component)
        total_a3_subsystems += subsystem_count
        counts["A3_fixed_root_subsystems"] += subsystem_count
        counts["A3_weyl_orbits"] += len(a3_representatives)
        for a3_index, a3_basis in enumerate(a3_representatives, start=1):
            after_a3 = [
                root
                for root in ambient_roots
                if root * gram * a3_basis.transpose() == 0
            ]
            for a2_component_index, a2_component in enumerate(root_components(gram, after_a3)):
                if matrix(ZZ, a2_component).rank() < 2:
                    continue
                a2_basis = first_a2_basis(gram, a2_component)
                first_five = a3_basis.stack(a2_basis)
                after_a2 = [
                    root
                    for root in after_a3
                    if root * gram * a2_basis.transpose() == 0
                ]
                for a1_component_index, a1_component in enumerate(root_components(gram, after_a2)):
                    a1_basis = matrix(ZZ, [a1_component[0]])
                    root_basis = first_five.stack(a1_basis)
                    if root_basis * gram * root_basis.transpose() != ROOT_GRAM:
                        raise AssertionError("root anchor Gram changed")
                    if not primitive_rows(root_basis):
                        counts["nonprimitive_root_anchors"] += 1
                        continue
                    anchors.append(
                        {
                            "root_basis": root_basis,
                            "origin": [
                                component_index,
                                a3_index,
                                a2_component_index,
                                a1_component_index,
                            ],
                        }
                    )

    # Exact duplicate root anchors can arise because equivalent residual
    # components were deliberately retained.  Removing literal row-lattice
    # duplicates is safe and keeps a complete cover.
    unique_anchors = {}
    for anchor in anchors:
        unique_anchors.setdefault(hnf_key(anchor["root_basis"]), anchor)
    anchors = list(unique_anchors.values())
    total_root_anchors += len(anchors)
    counts["primitive_root_anchor_cover"] = len(anchors)

    for anchor_index, anchor in enumerate(anchors, start=1):
        root_basis = anchor["root_basis"]
        residual_roots = [
            root
            for root in ambient_roots
            if root * gram * root_basis.transpose() == 0
        ]
        residual_components = root_components(gram, residual_roots)
        simple_components = [simple_roots(gram, part) for part in residual_components]
        residual_simple = matrix(
            ZZ,
            [row for part in simple_components for row in part.rows()],
        ) if simple_components else matrix(ZZ, 0, 24)
        component_choices = [
            dominant_labels_up_to(
                (part * gram * part.transpose()).inverse(), RESIDUAL_BUDGET
            )
            for part in simple_components
        ]
        choices = itertools.product(*component_choices) if component_choices else [((),)]
        label_records = []
        for choice in choices:
            projected = sum((entry[1] for entry in choice), QQ(0))
            if projected <= RESIDUAL_BUDGET:
                labels = tuple(
                    value for component_choice, unused_norm in choice for value in component_choice
                )
                label_records.append((labels, projected))
        total_label_tuples += len(label_records)
        counts["dominant_label_tuples"] += len(label_records)

        constraint = (gram * root_basis.transpose()).augment(
            gram * residual_simple.transpose()
        )
        extra_coordinates = []
        for coordinate in range(24):
            if constraint.ncols() == 24:
                break
            unit = matrix(ZZ, 24, 1, [int(index == coordinate) for index in range(24)])
            trial = constraint.augment(unit)
            if trial.rank() > constraint.rank():
                constraint = trial
                extra_coordinates.append(coordinate)
        assert constraint.nrows() == constraint.ncols() == 24
        inverse = constraint.inverse()
        coordinate_norm = inverse * gram * inverse.transpose()
        prefix_size = 6 + residual_simple.nrows()
        fixed_quadratic = coordinate_norm[prefix_size:, prefix_size:]
        fixed_inverse = fixed_quadratic.inverse() if fixed_quadratic.nrows() else matrix(QQ, 0, 0)

        for labels, projected in label_records:
            prefix = vector(QQ, list(LAST_PAIRINGS) + list(labels))
            prefix_norm = prefix * coordinate_norm[:prefix_size, :prefix_size] * prefix
            if fixed_quadratic.nrows():
                linear = prefix * coordinate_norm[:prefix_size, prefix_size:]
                centre = -linear * fixed_inverse
                minimum = prefix_norm - linear * fixed_inverse * linear
            else:
                centre = vector(QQ, [])
                minimum = prefix_norm
            assert minimum == QQ(3) / 4 + projected
            remaining = LAST_NORM - minimum
            fixed_solutions = shifted_ellipsoid_shell(fixed_quadratic, centre, remaining)
            total_ellipsoid += len(fixed_solutions)
            counts["fixed_ellipsoid_solutions"] += len(fixed_solutions)
            for fixed in fixed_solutions:
                coordinates = vector(QQ, list(LAST_PAIRINGS) + list(labels) + list(fixed))
                last_rational = coordinates * inverse
                if not all(entry.denominator() == 1 for entry in last_rational):
                    counts["nonintegral_last_vectors"] += 1
                    continue
                total_integral += 1
                counts["integral_last_vectors"] += 1
                last = vector(ZZ, last_rational)
                auxiliary_basis = root_basis.stack(matrix(ZZ, [last]))
                if auxiliary_basis * gram * auxiliary_basis.transpose() != auxiliary:
                    raise AssertionError("auxiliary embedding Gram changed")
                if not primitive_rows(auxiliary_basis):
                    counts["nonprimitive_auxiliary_embeddings"] += 1
                    continue
                total_primitive += 1
                counts["primitive_auxiliary_embeddings"] += 1
                complement_basis = (auxiliary_basis * gram).right_kernel_matrix()
                complement = complement_basis * gram * complement_basis.transpose()
                assert complement.nrows() == 17 and complement.det() == 78
                assert Genus(complement) == target_genus
                lll_change = complement.LLL_gram().transpose()
                assert abs(lll_change.det()) == 1
                complement = lll_change * complement * lll_change.transpose()
                complement_basis = lll_change * complement_basis
                root_type, root_rank, signed_root_count = ade_type(complement)
                root_smith, root_determinant, root_primitive = root_span_data(complement)
                glue_data = root_glue_data(complement)
                record = {
                    "niemeier": label,
                    "anchor_index": anchor_index,
                    "anchor_origin": anchor["origin"],
                    "residual_root_rank": residual_simple.nrows(),
                    "dominant_labels": list(map(int, labels)),
                    "root_basis_in_ambient": rows(root_basis),
                    "last_vector_in_ambient": list(map(int, last)),
                    "auxiliary_basis_in_ambient": rows(auxiliary_basis),
                    "complement_basis_in_ambient": rows(complement_basis),
                    "complement_gram": complement,
                    "root_type": root_type,
                    "root_rank": root_rank,
                    "signed_root_count": signed_root_count,
                    "root_smith_invariants": root_smith,
                    "root_determinant": root_determinant,
                    "root_lattice_primitive": root_primitive,
                }
                matched = None
                for class_row in classes:
                    if class_row["root_type"] != root_type:
                        continue
                    isometric = root_glue_isometric(
                        class_row["gram"],
                        complement,
                        class_row["glue_data"],
                        glue_data,
                    )
                    if isometric:
                        matched = class_row
                        break
                if matched is None:
                    matched = {
                        "gram": complement,
                        "glue_data": glue_data,
                        "root_type": root_type,
                        "root_rank": root_rank,
                        "signed_root_count": signed_root_count,
                        "root_smith_invariants": root_smith,
                        "root_determinant": root_determinant,
                        "root_lattice_primitive": root_primitive,
                        "embedding_count_in_cover": 0,
                        "niemeier_counts": Counter(),
                        "representative": record,
                    }
                    classes.append(matched)
                matched["embedding_count_in_cover"] += 1
                matched["niemeier_counts"][label] += 1

    ambient_rows.append({"niemeier": label, **{key: int(value) for key, value in sorted(counts.items())}})
    print(
        "DET78NIEMEIER|ambient={}|anchors={}|labels={}|primitive={}|classes_so_far={}".format(
            label,
            counts["primitive_root_anchor_cover"],
            counts["dominant_label_tuples"],
            counts["primitive_auxiliary_embeddings"],
            len(classes),
        ),
        flush=True,
    )

class_rows = []
weighted_mass = QQ(0)
for index, class_row in enumerate(classes, start=1):
    representative = class_row["representative"]
    automorphism_order = root_glue_automorphism_order(
        class_row["gram"], class_row["glue_data"]
    )
    weighted_mass += QQ(1) / automorphism_order
    class_rows.append(
        {
            "class_index": index,
            "gram": rows(class_row["gram"]),
            "gram_sha256": gram_sha256(class_row["gram"]),
            "determinant": 78,
            "root_type": class_row["root_type"],
            "root_rank": class_row["root_rank"],
            "mw_rank_for_rho_19": 17 - class_row["root_rank"],
            "signed_root_count": class_row["signed_root_count"],
            "root_smith_invariants": class_row["root_smith_invariants"],
            "root_determinant": class_row["root_determinant"],
            "root_lattice_primitive": class_row["root_lattice_primitive"],
            "automorphism_group_order": automorphism_order,
            "embedding_count_in_enumerated_cover": class_row["embedding_count_in_cover"],
            "niemeier_provenance_counts": dict(sorted(class_row["niemeier_counts"].items())),
            "matches_explicit_MW4_source_frame": bool(
                root_glue_isometric(source_frame, class_row["gram"])
            ),
            "representative_embedding": {
                key: value
                for key, value in representative.items()
                if key not in ("complement_gram",)
            },
        }
    )

root_rank_distribution = Counter(row["root_rank"] for row in class_rows)
rootless = [row for row in class_rows if row["root_rank"] == 0]
target_mass = target_genus.mass()
complete_run = not selected
if complete_run and weighted_mass != target_mass:
    raise ArithmeticError(
        f"genus mass did not close: classes give {weighted_mass}, target is {target_mass}"
    )
result = {
    "schema": "elkies-k3.e6-rank4-det78-niemeier-frames.v1",
    "status": "PASS_COMPLETE_DET78_J2_FRAME_CLASSIFICATION",
    "classification_scope": {
        "proved": (
            "Every primitive embedding of the pinned rank-seven auxiliary is covered "
            "through all 23 rooted Niemeier lattices. The Leech lattice is excluded "
            "because the auxiliary contains roots. Successive A3, A2 and A1 residual-"
            "Weyl reductions cover every root anchor; every dominant last-vector label "
            "and exact fixed-space ellipsoid point is enumerated. Saturated complements "
            "are deduplicated by exact integral isometry."
        ),
        "boundary": (
            "Embedding counts retain duplicates under full anchor stabilizers and are "
            "cover counts, not full-automorphism orbit counts. Frame classes are J2 "
            "classes, not J1 surface-automorphism orbits."
        ),
    },
    "inputs": {
        "catalog": str(CATALOG.relative_to(ROOT)),
        "catalog_sha256": hashlib.sha256(CATALOG.read_bytes()).hexdigest(),
        "source_frame": str(SOURCE_FRAME.relative_to(ROOT)),
        "source_frame_sha256": hashlib.sha256(SOURCE_FRAME.read_bytes()).hexdigest(),
    },
    "auxiliary": {
        "gram": rows(auxiliary),
        "gram_sha256": gram_sha256(auxiliary),
        "determinant": 78,
        "root_type": "A3+A2+A1",
        "root_rank": 6,
        "last_pairings": list(map(int, LAST_PAIRINGS)),
        "last_norm": 4,
        "last_schur_norm": "13/4",
    },
    "accounting": {
        "rooted_niemeier_classes_processed": len(ambient_rows),
        "leech_excluded_by_auxiliary_roots": 1,
        "fixed_root_A3_subsystems_before_weyl_quotient": total_a3_subsystems,
        "primitive_root_anchor_cover": total_root_anchors,
        "dominant_last_vector_label_tuples": total_label_tuples,
        "exact_fixed_ellipsoid_solutions": total_ellipsoid,
        "integral_last_vectors": total_integral,
        "primitive_auxiliary_embeddings_in_cover": total_primitive,
        "frame_isometry_classes": len(class_rows),
        "root_rank_distribution": {
            str(key): value for key, value in sorted(root_rank_distribution.items())
        },
        "rootless_frame_classes": len(rootless),
        "explicit_source_matches": sum(
            row["matches_explicit_MW4_source_frame"] for row in class_rows
        ),
        "target_genus_mass": str(target_mass),
        "deduplicated_weighted_mass": str(weighted_mass),
        "genus_mass_closed": bool(complete_run and weighted_mass == target_mass),
    },
    "ambient_accounting": ambient_rows,
    "frames": class_rows,
}

payload = json.dumps(result, indent=2, sort_keys=True) + "\n"
if arguments.check:
    if arguments.output.read_text() != payload:
        raise SystemExit("determinant-78 Niemeier artifact is stale")
else:
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(payload)

print(
    "DET78NIEMEIER|embeddings={}|classes={}|rootless={}|source_matches={}|status=PASS".format(
        total_primitive,
        len(class_rows),
        len(rootless),
        result["accounting"]["explicit_source_matches"],
    ),
    flush=True,
)
