#!/usr/bin/env sage -python
"""Compile the resolved third-q12 pencil at u=-2 over GF(19^2).

The input horizontal is the exact Frobenius-orbit representative certified by
``certify_q80_po0_rur_third_q12_modp.sage``.  Its denominator is ``h^2,h^3``.
This verifier Smith-saturates the relative module generated by ``{1,x,h*z}``,
uses shifted weak Popov reduction at infinity, and takes the seven sections of
``L(H+2O+2F)`` before the reducible-fibre corrections.

At infinity the I3* singularity has the resolved D7 complete ideal

    (Y, U^2, Z*U, Z^3),

with quotient basis ``1,Z,Z^2,U``.  The finite I1* correction is one complete
D5 fibre, so its residual quotient is evaluation at the singular point.  The
four D7 rows plus this D5 row have rank five and leave the required
two-dimensional pencil.  Eliminating the old y-coordinate removes the fixed
horizontal factor and leaves a quadratic-in-new-base, cubic-in-x moving
equation.

This is an exact modular connected-pencil certificate.  It does not yet
convert the generic member to a minimal Weierstrass Jacobian or prove the
A5+A3+3A1 child fibre configuration.
"""

import argparse
import hashlib
import json
from pathlib import Path

from sage.all import (
    GF,
    Matrix,
    PolynomialRing,
    QQ,
    vector,
)


ROOT = Path(__file__).resolve().parents[2]
SURFACE = ROOT / (
    "artifacts/generated-results/"
    "q80-fixed-u-minus2-p19-height-shell-with-po1.json"
)
HORIZONTAL = ROOT / (
    "artifacts/generated-results/"
    "q80-fixed-u-minus2-p19-po0-rur-third-q12-modp.json"
)
LATTICE = ROOT / "artifacts/generated-results/q80-d7d5-mw5-height-lattice.json"
DEFAULT_OUTPUT = ROOT / (
    "artifacts/generated-results/"
    "q80-third-q12-um2-p19-resolved-pencil.json"
)

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


surface_payload = json.loads(SURFACE.read_text())
horizontal_payload = json.loads(HORIZONTAL.read_text())
lattice_payload = json.loads(LATTICE.read_text())
if horizontal_payload["schema"] != "elkies-k3.q80-po0-rur-third-q12-modp.v1":
    raise ValueError("unexpected horizontal schema")
if horizontal_payload["status"] != (
    "PASS_EXACT_MODP2_THIRD_Q12_HORIZONTAL_FROBENIUS_ORBIT"
):
    raise ValueError("the modular horizontal is not certified")
if lattice_payload["third_q12_horizontal"]["canonical_height"] != "8":
    raise ValueError("unexpected lattice target")

prime = 19
base_finite = GF(prime)
modulus_ring = PolynomialRing(base_finite, "r_modulus")
r_modulus = modulus_ring.gen()
finite = GF(prime**2, "r", modulus=r_modulus**2 + 12 * r_modulus + 3)
r = finite.gen()
base_ring = PolynomialRing(finite, "W")
W = base_ring.gen()


def reduce_rational(value):
    value = QQ(value)
    return finite(value.numerator()) / finite(value.denominator())


def field_element(value):
    return finite(str(value))


def field_coordinates(value):
    values = list(finite(value).list())
    values += [base_finite.zero()] * (2 - len(values))
    return [int(values[0]), int(values[1])]


equation = surface_payload["parameters"][0]["exact_equations"]["second_q4"]
A = base_ring(
    [reduce_rational(value) for value in equation["A_coefficients_low_to_high"]]
)
B = base_ring(
    [reduce_rational(value) for value in equation["B_coefficients_low_to_high"]]
)

horizontal = horizontal_payload["third_q12"]["candidates_up_to_sign"][0]


def horizontal_polynomial(coordinate, part):
    return base_ring(
        [field_element(value) for value in horizontal[coordinate][part]]
    )


Nx = horizontal_polynomial("x", "numerator_coefficients_low_to_high")
x_denominator = horizontal_polynomial(
    "x", "denominator_coefficients_low_to_high"
)
Ny = horizontal_polynomial("y", "numerator_coefficients_low_to_high")
y_denominator = horizontal_polynomial(
    "y", "denominator_coefficients_low_to_high"
)
h_factors = tuple(x_denominator.factor())
if len(h_factors) != 1 or int(h_factors[0][1]) != 2:
    raise ArithmeticError("horizontal x denominator is not one square")
h = h_factors[0][0].monic()
if x_denominator != h**2 or y_denominator != h**3:
    raise ArithmeticError("horizontal denominators do not share h")
if Ny**2 != Nx**3 + A * Nx * h**4 + B * h**6:
    raise ArithmeticError("horizontal section does not satisfy the parent equation")

# Use the common denominator D0=h^2*x-Nx and numerator monomials
# [1,x,x^2,x^3,y,xy].  Smith saturation adds every finite-prime generator
# missing from the raw columns {1,x,h*z_H}.
module_matrix = Matrix(
    base_ring,
    (
        (-Nx, 0, Ny),
        (h**2, -Nx, 0),
        (0, h**2, 0),
        (0, 0, 0),
        (0, 0, h**3),
        (0, 0, 0),
    ),
)
smith, smith_left, smith_right = module_matrix.smith_form()
if smith != smith_left * module_matrix * smith_right:
    raise ArithmeticError("Smith identity failed")
if not smith_left.is_invertible() or not smith_right.is_invertible():
    raise ArithmeticError("Smith transformations are not unimodular")
smith_degrees = tuple(smith[index, index].degree() for index in range(3))
if smith_degrees != (0, 0, 6):
    raise ArithmeticError("unexpected Smith invariant degrees")
saturated_module = smith_left.inverse()[:, :3]

row_weights = (0, 4, 8, 12, 6, 10)


def column_pivot(column):
    candidates = tuple(
        (entry.degree() + row_weights[row], row)
        for row, entry in enumerate(column)
        if entry
    )
    if not candidates:
        raise ArithmeticError("zero module column")
    return max(candidates)


def shifted_weak_popov(basis):
    basis = Matrix(base_ring, basis)
    while True:
        pivots = tuple(
            column_pivot(basis.column(index)) for index in range(basis.ncols())
        )
        collision = next(
            (
                (left, right)
                for left in range(len(pivots))
                for right in range(left + 1, len(pivots))
                if pivots[left][1] == pivots[right][1]
            ),
            None,
        )
        if collision is None:
            return basis
        first, second = collision
        if pivots[first][0] > pivots[second][0]:
            first, second = second, first
        pivot_row = column_pivot(basis.column(first))[1]
        reducer = basis[pivot_row, first]
        target = basis[pivot_row, second]
        degree_delta = target.degree() - reducer.degree()
        factor = target.leading_coefficient() / reducer.leading_coefficient()
        basis.set_column(
            second,
            basis.column(second)
            - factor * W**degree_delta * basis.column(first),
        )


popov_module = shifted_weak_popov(saturated_module)
popov_pivots = tuple(
    column_pivot(popov_module.column(index))
    for index in range(popov_module.ncols())
)
generator_weights = tuple(degree - 8 for degree, unused in popov_pivots)
if generator_weights != (0, 2, 0):
    raise ArithmeticError("unexpected shifted Popov weights")

global_columns = []
global_column_labels = []
for generator, weight in enumerate(generator_weights):
    degree_bound = 2 - weight
    for degree in range(degree_bound + 1):
        global_columns.append(
            W**degree * popov_module.column(generator)
        )
        global_column_labels.append((generator, degree))
if len(global_columns) != 7:
    raise ArithmeticError("unexpected global ambient dimension")

# Resolve the D7 point at infinity.  With t=1/W, xbar=t^4*x,
# ybar=t^6*y, and u=xbar-3t, the first nonzero pieces are
# ybar^2-u^3-9t*u^2 and there is no degree-four term.  Consequently the
# canonical quotient coordinates used by the complete ideal are exact to the
# required length: t=-(Z+U)/9, xbar=(2U-Z)/3.
local_ring = PolynomialRing(finite, names=("t", "u", "ybar"))
t, u, ybar = local_ring.gens()
local_A = sum(finite(A[index]) * t**(8 - index) for index in range(len(A.list())))
local_B = sum(finite(B[index]) * t**(12 - index) for index in range(len(B.list())))
local_equation = ybar**2 - (u + 3 * t) ** 3 - local_A * (u + 3 * t) - local_B
homogeneous = local_equation.homogeneous_components()
if homogeneous[2] != ybar**2 or homogeneous[3] != -u**3 - 9 * t * u**2:
    raise ArithmeticError("unexpected D7 tangent equation")
if homogeneous.get(4, local_ring.zero()):
    raise ArithmeticError("D7 coordinate change has an unexpected degree-four term")

local_fraction = local_ring.fraction_field()
xbar = local_fraction(u + 3 * t)


def at_inverse_base(polynomial):
    return sum(
        finite(coefficient) * local_fraction(t) ** (-index)
        for index, coefficient in enumerate(polynomial.list())
    )


hbar = local_fraction(t**2) * at_inverse_base(h)
nxbar = local_fraction(t**8) * at_inverse_base(Nx)
denominator_bar = hbar**2 * xbar - nxbar
local_monomials_without_y = (
    local_fraction.one(),
    xbar / t**4,
    (xbar / t**4) ** 2,
    (xbar / t**4) ** 3,
    local_fraction.zero(),
    local_fraction.zero(),
)

residue_ring = PolynomialRing(finite, names=("Z", "U"))
Z, U = residue_ring.gens()


def reduce_residue(polynomial):
    answer = [finite.zero()] * 4
    positions = {(0, 0): 0, (1, 0): 1, (2, 0): 2, (0, 1): 3}
    for exponent, coefficient in residue_ring(polynomial).dict().items():
        z_degree, u_degree = map(int, exponent)
        if u_degree >= 2 or (u_degree and z_degree) or z_degree >= 3:
            continue
        answer[positions[(z_degree, u_degree)]] += coefficient
    return vector(finite, answer)


def multiply_residues(left, right):
    return vector(
        finite,
        (
            left[0] * right[0],
            left[0] * right[1] + left[1] * right[0],
            left[0] * right[2] + left[2] * right[0] + left[1] * right[1],
            left[0] * right[3] + left[3] * right[0],
        ),
    )


def rational_residue(value):
    value = local_fraction(value)
    numerator = local_ring(value.numerator())
    denominator = local_ring(value.denominator())
    substitution = {t: -(Z + U) / finite(9), u: U}
    numerator_residue = reduce_residue(
        residue_ring(numerator.subs(substitution))
    )
    denominator_residue = reduce_residue(
        residue_ring(denominator.subs(substitution))
    )
    constant = denominator_residue[0]
    if not constant:
        raise ArithmeticError("D7 local denominator is not a unit")
    nilpotent = vector(
        finite,
        (0, denominator_residue[1], denominator_residue[2], denominator_residue[3]),
    )
    one = vector(finite, (1, 0, 0, 0))
    inverse = (
        one / constant
        - nilpotent / constant**2
        + multiply_residues(nilpotent, nilpotent) / constant**3
    )
    if multiply_residues(denominator_residue, inverse) != one:
        raise ArithmeticError("D7 quotient inverse failed")
    return multiply_residues(numerator_residue, inverse)


d7_column_residues = []
for column in global_columns:
    numerator = sum(
        at_inverse_base(entry) * monomial
        for entry, monomial in zip(column, local_monomials_without_y)
    )
    # D0=t^-8*Dbar.  Multiplication by t^2 is the F=2
    # trivialization, hence the total factor t^10.
    d7_column_residues.append(
        rational_residue(t**10 * numerator / denominator_bar)
    )
d7_rows = Matrix(finite, d7_column_residues).transpose()
if d7_rows.rank() != 4 or d7_rows.right_kernel().dimension() != 3:
    raise ArithmeticError("resolved D7 quotient has the wrong rank")

# The finite I1* correction is one complete D5 fibre.  Its length-one
# residual quotient is evaluation at the singular point of the reduced cubic.
delta = 4 * A**3 + 27 * B**2
star_factor = next(factor for factor, exponent in delta.factor() if exponent == 7)
star_root = -star_factor[0] / star_factor[1]
node_ring = PolynomialRing(finite, "x_node")
x_node = node_ring.gen()
node_cubic = x_node**3 + A(star_root) * x_node + B(star_root)
singular_roots = node_cubic.gcd(node_cubic.derivative()).roots(
    multiplicities=False
)
if len(singular_roots) != 1:
    raise ArithmeticError("finite I1* cubic has no unique singular x")
singular_x = singular_roots[0]
finite_denominator = h(star_root) ** 2 * singular_x - Nx(star_root)
if not finite_denominator:
    raise ArithmeticError("horizontal meets the finite D5 singular point")
finite_monomials = (
    finite.one(),
    singular_x,
    singular_x**2,
    singular_x**3,
    finite.zero(),
    finite.zero(),
)
d5_row = vector(
    finite,
    [
        sum(
            entry(star_root) * monomial
            for entry, monomial in zip(column, finite_monomials)
        )
        / finite_denominator
        for column in global_columns
    ],
)

gate_matrix = d7_rows.stack(Matrix(finite, [d5_row]))
if gate_matrix.rank() != 5 or gate_matrix.right_kernel().dimension() != 2:
    raise ArithmeticError("resolved q12 gate does not leave a pencil")
kernel = gate_matrix.right_kernel().basis_matrix()

zero_column = vector(base_ring, [0] * 6)
kernel_numerators = [
    sum(
        (coefficient * column for coefficient, column in zip(row, global_columns)),
        zero_column,
    )
    for row in kernel.rows()
]

# Eliminate y from N1-T*N0 and the old Weierstrass equation.  Since the
# numerator basis is [1,x,x^2,x^3,y,xy], the relation is linear in y.
plane_ring = PolynomialRing(finite, names=("W0", "x0"))
W0, x0 = plane_ring.gens()
parameter_polynomials = PolynomialRing(plane_ring, "Tnew")
Tnew = parameter_polynomials.gen()


def split_numerator(column):
    even = sum(
        plane_ring(column[index](W0)) * x0**index for index in range(4)
    )
    odd = plane_ring(column[4](W0) + column[5](W0) * x0)
    return even, odd


even_zero, odd_zero = split_numerator(kernel_numerators[0])
even_one, odd_one = split_numerator(kernel_numerators[1])
even_relation = even_one - Tnew * even_zero
odd_relation = odd_one - Tnew * odd_zero
old_cubic = x0**3 + plane_ring(A(W0)) * x0 + plane_ring(B(W0))
eliminated = even_relation**2 - odd_relation**2 * old_cubic
nonzero_coefficients = tuple(value for value in eliminated.list() if value)
fixed_factor = nonzero_coefficients[0]
for coefficient in nonzero_coefficients[1:]:
    fixed_factor = fixed_factor.gcd(coefficient)
expected_fixed = plane_ring(h(W0) ** 2 * x0 - Nx(W0))
if fixed_factor * expected_fixed.leading_coefficient() != (
    expected_fixed * fixed_factor.leading_coefficient()
):
    raise ArithmeticError("elimination fixed factor is not h^2*x-Nx")
moving = parameter_polynomials(
    [coefficient // fixed_factor for coefficient in eliminated.list()]
)
moving_degrees = (
    int(moving.degree()),
    int(max(coefficient.degree(W0) for coefficient in moving.list())),
    int(max(coefficient.degree(x0) for coefficient in moving.list())),
)
if moving_degrees != (2, 9, 3):
    raise ArithmeticError("resolved moving equation has unexpected degrees")


def vector_record(value):
    return [field_coordinates(entry) for entry in value]


moving_terms = []
for parameter_degree, coefficient in enumerate(moving.list()):
    for exponent, scalar in coefficient.dict().items():
        moving_terms.append(
            [
                int(parameter_degree),
                int(exponent[0]),
                int(exponent[1]),
                field_coordinates(scalar),
            ]
        )

output = {
    "schema": "elkies-k3.q80-third-q12-resolved-pencil-modp2.v1",
    "status": "PASS_EXACT_RESOLVED_THIRD_Q12_PENCIL_MOD19_QUADRATIC",
    "specialization": {
        "u": "-2",
        "prime": prime,
        "extension_modulus": "r^2+12*r+3",
    },
    "horizontal": {
        "h_coefficients_low_to_high": vector_record(h.list()),
        "x_numerator_coefficients_low_to_high": vector_record(Nx.list()),
        "y_numerator_coefficients_low_to_high": vector_record(Ny.list()),
    },
    "saturated_ambient": {
        "common_denominator": "h^2*x-Nx",
        "numerator_basis": ["1", "x", "x^2", "x^3", "y", "x*y"],
        "smith_degrees": list(map(int, smith_degrees)),
        "popov_pivots": [list(map(int, value)) for value in popov_pivots],
        "generator_weights": list(map(int, generator_weights)),
        "F_bound": 2,
        "dimension": len(global_columns),
        "column_labels_generator_degree": [list(value) for value in global_column_labels],
    },
    "resolved_gates": {
        "D7": {
            "complete_ideal": "(Y,U^2,ZU,Z^3)",
            "quotient_basis": ["1", "Z", "Z^2", "U"],
            "rows": [vector_record(row) for row in d7_rows.rows()],
            "rank": int(d7_rows.rank()),
        },
        "D5": {
            "root": field_coordinates(star_root),
            "singular_x": field_coordinates(singular_x),
            "row": vector_record(d5_row),
        },
        "combined_rank": int(gate_matrix.rank()),
        "kernel_dimension": int(gate_matrix.right_kernel().dimension()),
        "kernel": [vector_record(row) for row in kernel.rows()],
    },
    "moving_equation": {
        "variables": ["Tnew", "W0", "x0"],
        "terms_T_W_x_coefficient_1_r": sorted(moving_terms),
        "degrees_T_W_x": list(moving_degrees),
        "fixed_factor": "h^2*x-Nx up to a nonzero scalar",
    },
    "inputs": {
        "surface": {"path": str(SURFACE.relative_to(ROOT)), "sha256": sha256(SURFACE)},
        "horizontal": {
            "path": str(HORIZONTAL.relative_to(ROOT)),
            "sha256": sha256(HORIZONTAL),
        },
        "lattice": {"path": str(LATTICE.relative_to(ROOT)), "sha256": sha256(LATTICE)},
        "worker": {
            "path": str(Path(__file__).resolve().relative_to(ROOT)),
            "sha256": sha256(Path(__file__).resolve()),
        },
    },
    "claim_boundary": {
        "proved": [
            "complete finite-prime Smith saturation of {1,x,h*z_H}",
            "seven-dimensional shifted-Popov ambient for H+2O+2F",
            "resolved D7 complete-ideal quotient and finite D5 singular-point gate",
            "rank-five gate matrix with a two-dimensional q12 kernel",
            "fixed-factor removal and exact moving equation of degrees (2,9,3)",
        ],
        "not_proved": [
            "normalization genus one of the moving equation",
            "a minimal Weierstrass Jacobian for the child",
            "the A5+A3+3A1 fibre configuration or MW rank six",
            "alignment at another prime or characteristic-zero lifting",
        ],
    },
    "reproduce": (
        "sage -python "
        "elkies-k3/scripts/compile_q80_third_q12_um2_p19_resolved_pencil.sage"
    ),
}
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(output, indent=2, sort_keys=True) + "\n")
print(
    "Q80THIRDQ12P19|smith=0,0,6|weights=0,2,0|ambient=7|"
    "D7_rank=4|D5_rows=1|gate_rank=5|kernel=2|"
    "moving_degrees=2,9,3|"
    "status=PASS_EXACT_RESOLVED_THIRD_Q12_PENCIL_MOD19_QUADRATIC",
    flush=True,
)
