from sage.all import *
from pathlib import Path
import argparse
from itertools import product

ap=argparse.ArgumentParser(description="Construct exact Eichler order for (D,N)=(6,79), its Gross lattice, and enumerate primitive CM vectors.")
ap.add_argument("--bound",type=int,default=80)
ap.add_argument("--targets",default="3,24")
ap.add_argument("--out",default="artifacts/local/elkies-k3/exact-gross-lattice.txt")
a=ap.parse_args()

D=ZZ(6); N=ZZ(79); TOTAL=D*N
targets=[ZZ(x) for x in a.targets.split(",") if x.strip()]

A=QuaternionAlgebra(D)
print(f"EXACTGROSS|stage=algebra|A={A}",flush=True)

try:
    ram=tuple(map(int,A.ramified_primes()))
except Exception:
    ram=()
print(f"EXACTGROSS|ramified_primes={ram}",flush=True)
if ram and set(ram)!={2,3}:
    raise RuntimeError(f"unexpected ramification {ram}")

# Sage 10.9 order_with_level() only supports algebras ramified at one
# finite prime.  Our algebra has discriminant 6 = 2*3, so construct an
# Eichler order of level 79 as the intersection of two maximal orders.
#
# If alpha in M has reduced norm 79, then generically
#
#     M intersect alpha^(-1) M alpha
#
# has local distance 1 at 79, hence Eichler level 79.
M = A.maximal_order()
mb = list(M.basis())

def qnorm(x):
    try:
        return ZZ(x.reduced_norm())
    except Exception:
        return ZZ(x.norm())

alpha = None
alpha_coeffs = None

for B in (2,3,4,5,6,8,10,12,16,20):
    print(f"EXACTGROSS|stage=search_alpha|bound={B}", flush=True)

    for c0 in range(-B,B+1):
      for c1 in range(-B,B+1):
       for c2 in range(-B,B+1):
        for c3 in range(-B,B+1):
            if c0 == c1 == c2 == c3 == 0:
                continue

            # primitive M-coordinate vector
            if gcd([abs(c0),abs(c1),abs(c2),abs(c3)]) != 1:
                continue

            x = c0*mb[0] + c1*mb[1] + c2*mb[2] + c3*mb[3]

            if abs(qnorm(x)) == N:
                alpha = x
                alpha_coeffs = (c0,c1,c2,c3)
                break
        if alpha is not None: break
       if alpha is not None: break
      if alpha is not None: break
    if alpha is not None: break

if alpha is None:
    raise RuntimeError("could not find primitive maximal-order element of norm 79")

print(
    f"EXACTGROSS|stage=alpha"
    f"|coeffs={alpha_coeffs}"
    f"|norm={qnorm(alpha)}"
    f"|alpha={alpha}",
    flush=True
)

ainv = alpha.inverse()

# Conjugation preserves maximality.
conj_basis = [ainv*b*alpha for b in mb]
M2 = A.quaternion_order(conj_basis)

assert M2.is_maximal()

O = M.intersection(M2)

idx = O.free_module().index_in(M.free_module())
print(f"EXACTGROSS|stage=order|total_level={TOTAL}|index_in_maximal={idx}|expected_index={N}",flush=True)
print(f"EXACTGROSS|order={O}",flush=True)
print(f"EXACTGROSS|maximal={M}",flush=True)
if idx != N:
    raise RuntimeError(f"Eichler index mismatch {idx} != {N}")

ob=list(O.basis())
print("EXACTGROSS|order_basis="+" ; ".join(map(str,ob)),flush=True)

# Standard quaternion-coordinate row vectors.
def qcoords(x):
    # Quaternion element coefficient_tuple is the most stable API; fallback list.
    try:
        c=x.coefficient_tuple()
    except Exception:
        try:
            c=x.list()
        except Exception:
            c=tuple(x)
    return vector(QQ,c)

def tr(x):
    try: return QQ(x.reduced_trace())
    except Exception:
        try: return QQ(x.trace())
        except Exception: return QQ(2*qcoords(x)[0])

def nr(x):
    try: return QQ(x.reduced_norm())
    except Exception:
        try: return QQ(x.norm())
        except Exception:
            return QQ(x*x.conjugate())

# Gross generators tau(b)=2b-Tr(b). They span rank 3 but four images have one relation.
tau=[2*b-tr(b)*A.one() for b in ob]
tc=[qcoords(x) for x in tau]
print("EXACTGROSS|tau_generators="+" ; ".join(map(str,tau)),flush=True)

# Express trace-zero elements by their i,j,k coordinates; scalar coordinate must vanish.
V=[]
for c in tc:
    if c[0] != 0:
        raise RuntimeError(f"tau image not trace zero: {c}")
    V.append(vector(QQ,c[1:]))

# Lattice generated by rational rows V. Clear denominators, HNF, then rescale back.
den=lcm([QQ(x).denominator() for v in V for x in v])
Z=matrix(ZZ,[[ZZ(den*x) for x in v] for v in V])
LZ=Z.row_module()
Bz=LZ.basis_matrix()
if Bz.nrows()!=3:
    raise RuntimeError(f"Gross lattice rank {Bz.nrows()} != 3")
B=(Bz.change_ring(QQ))/den
print(f"EXACTGROSS|coordinate_den={den}",flush=True)
print("EXACTGROSS|gross_basis_rows="+" ; ".join(" ".join(map(str,r)) for r in B.rows()),flush=True)

# Convert trace-zero coordinate vector (i,j,k coeffs) back to quaternion.
gens=A.gens()
# Depending on Sage, gens() can be i,j,k.
i,j,k=gens[0],gens[1],gens[2]
def from3(v):
    return QQ(v[0])*i + QQ(v[1])*j + QQ(v[2])*k

gb=[from3(B.row(r)) for r in range(3)]

# Norm quadratic Gram G with q(z)=z^T G z, i.e. G_ii=N(bi), 2G_ij=N(bi+bj)-...
G=matrix(QQ,3,3)
for r in range(3):
    G[r,r]=nr(gb[r])
for r in range(3):
    for s in range(r+1,3):
        gij=(nr(gb[r]+gb[s])-nr(gb[r])-nr(gb[s]))/2
        G[r,s]=G[s,r]=gij

print(f"EXACTGROSS|norm_gram_det={G.det()}|gram={G}",flush=True)
if not all(QQ(x).denominator()==1 for x in G.list()):
    print("EXACTGROSS|WARNING=Gross norm Gram is not integral in computed basis",flush=True)

def gcd3(v):
    return gcd([abs(ZZ(x)) for x in v])

def qval(v):
    vv=vector(ZZ,v)
    return QQ(vv*G*vv)

# Enumerate primitive representations; preserve all up to cap per target plus total counts.
hits={n:[] for n in targets}
counts={n:0 for n in targets}
BND=a.bound
for x in range(-BND,BND+1):
  for y in range(-BND,BND+1):
    for z in range(-BND,BND+1):
      if x==y==z==0: continue
      if gcd3((x,y,z))!=1: continue
      q=qval((x,y,z))
      if q in hits:
          counts[q]+=1
          if len(hits[q])<100:
              beta=x*gb[0]+y*gb[1]+z*gb[2]
              hits[q].append(((x,y,z),beta))

for n in targets:
    print(f"EXACTGROSS|target={n}|primitive_count_box={counts[n]}|shown={len(hits[n])}",flush=True)
    for idx,(v,beta) in enumerate(hits[n][:20]):
        print(f"GROSSHIT|target={n}|id={idx}|v={v}|norm={nr(beta)}|beta={beta}",flush=True)

# Reconstruct O from Gross lattice as a sanity check:
# O = 1/2 { x in Z + O^T : Nr(x) in 4Z }.
# At minimum every original tau(b) should be integral combination of gb.
Binv=B.inverse()
for n,v in enumerate(V):
    coeff=v*Binv
    if not all(QQ(c).denominator()==1 for c in coeff):
        raise RuntimeError(f"tau generator {n} not integral in Gross basis: {coeff}")
print("EXACTGROSS|stage=basis_check|status=OK",flush=True)

lines=[
    f"D={D}",
    f"N={N}",
    f"total_level={TOTAL}",
    f"index={idx}",
    f"ramified={ram}",
    "order_basis="+repr([str(x) for x in ob]),
    "gross_basis="+repr([str(x) for x in gb]),
    "norm_gram="+repr([[str(x) for x in row] for row in G.rows()]),
]
for n in targets:
    lines.append(f"target_{n}_count_box={counts[n]}")
    lines.append(f"target_{n}_vectors="+repr([v for v,_ in hits[n]]))
Path(a.out).parent.mkdir(parents=True,exist_ok=True)
Path(a.out).write_text("\n".join(lines)+"\n")
print(f"EXACTGROSS|stage=done|out={a.out}",flush=True)
