#!/usr/bin/env sage -python
"""Compile exact generic-component q=8 E7 valuation conditions on H92.

For the source q=8 class, the actual resolved E7 comparison is

    g*f in (q6_F0_module)^9,

where ``g`` is the Cartier factor for the integral q=8 twist.  At the generic
point of an E7 component the q6_F0 module is generated by ``t``.  If

    f = u^i/h(u)^k * x^a*m^b,       u=1/t,

then its exact residual order at component j is

    w_j + (4*k-i-9)*v_j(t) + a*v_j(x) + b*v_j(m).

All entries are read from the actual H92 resolution.  The output groups every
negative-order source term by component and residual order.  A singleton group
is an immediate exact linear condition on that coefficient; non-singleton
groups are retained for a later chart-function-field evaluator, since their
leading residues may cancel.
"""

import argparse
import hashlib
import json
from pathlib import Path

from sage.all import ZZ


ROOT = Path(__file__).resolve().parents[2]
AMBIENT = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-endpoint-rr-ambient.json"
ALL_EDGE = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-actual-e7-all-edge-module.json"
GLUING = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-actual-e7-gluing.json"
POWER = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-actual-e7-power-module.json"
DEFAULT_OUTPUT = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-all-component-generic-conditions.json"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical_digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def basis_signature(basis):
    return [
        [entry["kind"], int(entry["x_power"]), int(entry["m_power"]),
         int(entry["u_power"]), int(entry["h_power"])]
        for entry in basis
    ]


def path_label(path):
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--ambient", type=Path, default=AMBIENT)
parser.add_argument("--all-edge", type=Path, default=ALL_EDGE)
parser.add_argument("--gluing", type=Path, default=GLUING)
parser.add_argument("--power-module", type=Path, default=POWER)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()

ambient = json.loads(args.ambient.read_text())
all_edge = json.loads(args.all_edge.read_text())
gluing = json.loads(args.gluing.read_text())
power = json.loads(args.power_module.read_text())
assert ambient["status"] in {
    "PASS_EXACT_Q8_ENDPOINT_RR_AMBIENT",
    "PASS_EXACT_Q8_ENLARGED_ENDPOINT_RR_AMBIENT",
}
assert all_edge["status"] == "PASS_EXACT_Q6_ACTUAL_E7_ALL_EDGE_MODULE"
assert gluing["status"] == "PASS_EXACT_Q8_ACTUAL_E7_GLUING"
assert power["status"] == "PASS_EXACT_Q8_E7_CLEARED_POWER_MODULE"
assert power["q6_marked_module"]["fractional_form"] == "t*J_P1/(x-xP1)"

orders = all_edge["exceptional_orders"]
components = tuple(all_edge["actual_component_order"])
v_t = tuple(ZZ(value) for value in orders["t"])
v_x = tuple(ZZ(value) for value in orders["x"])
v_m = tuple(ZZ(value) for value in orders["m_exact"])
assert components == tuple("E7_{}".format(index) for index in range(1, 8))
assert v_t == (2, 2, 4, 3, 1, 2, 3)
assert v_x == (2, 4, 6, 4, 2, 3, 5)
assert v_m == (1, 1, 3, 2, 0, 2, 2)

twist = [None] * 7
for edge in gluing["actual_edge_chart_gluing"]:
    for component in edge["components"]:
        index = int(component["name"].split("_")[1])-1
        value = ZZ(component["w_coefficient"])
        if twist[index] is None:
            twist[index] = value
        else:
            assert twist[index] == value
assert tuple(twist) == (2, 5, 6, 4, 6, 3, 5)


def residual(entry, index):
    a = ZZ(entry["x_power"])
    b = ZZ(entry["m_power"])
    i = ZZ(entry["u_power"])
    k = ZZ(entry["h_power"])
    return twist[index] + (4*k-i-9)*v_t[index] + a*v_x[index] + b*v_m[index]


component_conditions = []
for component_index, component in enumerate(components):
    grouped = {}
    for basis_index, entry in enumerate(ambient["ambient_basis"]):
        value = int(residual(entry, component_index))
        if value < 0:
            grouped.setdefault(value, []).append(basis_index)
    records = [
        {
            "residual_order": order,
            "basis_indices": labels,
            "basis_labels": [ambient["ambient_basis"][label] for label in labels],
            "singleton_exact_linear_condition": len(labels) == 1,
        }
        for order, labels in sorted(grouped.items())
    ]
    component_conditions.append({
        "component": component,
        "orders": {
            "t": int(v_t[component_index]),
            "x": int(v_x[component_index]),
            "m": int(v_m[component_index]),
            "q8_twist": int(twist[component_index]),
            "q6_ninth_generator": int(9*v_t[component_index]),
        },
        "residual_formula": "w+(4*k-i-9)*ord(t)+a*ord(x)+b*ord(m)",
        "negative_order_groups": records,
        "singleton_condition_count": sum(row["singleton_exact_linear_condition"] for row in records),
    })

singleton_indices = tuple(sorted({
    row["basis_indices"][0]
    for condition in component_conditions
    for row in condition["negative_order_groups"]
    if row["singleton_exact_linear_condition"]
}))
singleton_rows = [
    [1 if column == index else 0 for column in range(ambient["ambient_dimension"])]
    for index in singleton_indices
]
assert len(singleton_indices) == len(singleton_rows)

payload = {
    "schema": "elkies-k3.h92-q8-all-component-generic-conditions.v1",
    "status": "PASS_EXACT_Q8_ALL_COMPONENT_GENERIC_CONDITION_TEMPLATE",
    "inputs": {
        "endpoint_ambient": {"path": path_label(args.ambient), "sha256": digest(args.ambient)},
        "q6_actual_all_edge_module": {"path": path_label(args.all_edge), "sha256": digest(args.all_edge)},
        "q8_actual_gluing": {"path": path_label(args.gluing), "sha256": digest(args.gluing)},
        "q8_power_module": {"path": path_label(args.power_module), "sha256": digest(args.power_module)},
    },
    "component_order": list(components),
    "ambient_basis_sha256": canonical_digest(basis_signature(ambient["ambient_basis"])),
    "q8_twist": [int(value) for value in twist],
    "coefficient_convention": "u^i/h(u)^k*x^a*m^b with u=1/t and h(1/t)*t^4 a unit at t=0",
    "component_conditions": component_conditions,
    "singleton_coordinate_block": {
        "basis_indices": list(singleton_indices),
        "matrix": singleton_rows,
        "rank": len(singleton_rows),
        "interpretation": "Each selected coefficient has a unique negative generic-component leading order and must vanish.",
    },
    "compiler_instruction": (
        "Set every singleton negative-order coefficient to zero. For each "
        "non-singleton group, evaluate the leading residues in the indicated "
        "actual edge-chart function field and impose their exact linear relation. "
        "Then add the node and marked-branch chart conditions before declaring "
        "the E7 cover complete."
    ),
    "boundary": (
        "This is the complete generic-component valuation layer only. It does "
        "not yet evaluate non-singleton residue cancellation, edge nodes, marked "
        "branch jets, overlaps, a global q8 kernel, or a pencil."
    ),
}
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(payload, indent=2, sort_keys=True)+"\n")
singletons = sum(item["singleton_condition_count"] for item in component_conditions)
negative_groups = sum(len(item["negative_order_groups"]) for item in component_conditions)
print(
    "H92Q8ALLCOMPONENTS|ambient={}|negative_groups={}|singleton_groups={}|singleton_rank={}|"
    "status=PASS_EXACT_Q8_ALL_COMPONENT_GENERIC_CONDITION_TEMPLATE".format(
        ambient["ambient_dimension"], negative_groups, singletons, len(singleton_rows)
    ),
    flush=True,
)
