#!/usr/bin/env sage -python
"""Package the cleared ninth-power q=6 E7 module for the q=8 compiler.

The source q=6 E7 module is the fractional marked module

    t * J_P1 / (x-x_P1),       J_P1=(x-x_P1,y-y_P1).

It is essential not to replace its ninth tensor power by a scalar complete
ideal: the marked branch has pole order nine and the following q=8 correction
is non-anti-nef.  On an actual resolved edge chart with Cartier correction
``g``, the q=8 membership condition can instead be cleared exactly as

    (x-x_P1)^9 g f in t^9 J_P1^9.

The right hand side has the ten displayed binomial generators.  This script
records that finite generator family, the actual six chart pullbacks, and the
cleared form of every source q=8 generic-frame monomial.  It deliberately
does *not* decide membership: a later evaluator must work in each resolved
chart (including its surface relation and transitions).
"""

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PULLBACKS = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-actual-e7-chart-pullbacks.json"
GLUING = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-actual-e7-gluing.json"
TARGET = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-e7-local-target.json"
GENERIC = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-generic-rr-ambient.json"
DEFAULT_OUTPUT = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-actual-e7-power-module.json"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--pullbacks", type=Path, default=PULLBACKS)
parser.add_argument("--gluing", type=Path, default=GLUING)
parser.add_argument("--target", type=Path, default=TARGET)
parser.add_argument("--generic", type=Path, default=GENERIC)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()

pullbacks = json.loads(args.pullbacks.read_text())
gluing = json.loads(args.gluing.read_text())
target = json.loads(args.target.read_text())
generic = json.loads(args.generic.read_text())
assert pullbacks["status"] == "PASS_EXACT_H92_E7_CHART_PULLBACKS"
assert gluing["status"] == "PASS_EXACT_Q8_ACTUAL_E7_GLUING"
assert target["status"] == "PASS_EXACT_Q8_E7_LOCAL_TARGET"
assert generic["status"] == "PASS_EXACT_Q8_GENERIC_RR_AMBIENT"
assert target["tensor_comparison"]["identity"] == "c8=9*c6+(2,5,6,4,6,3,5)"

charts = {entry["name"]: entry for entry in pullbacks["charts"]}
gluing_charts = {entry["name"]: entry for entry in gluing["actual_edge_chart_gluing"]}
assert set(charts) == set(gluing_charts)
assert len(charts) == 6

# Clear the unique fractional denominator of the q6 marked module.  Writing
# Lx=x-x(P1), Ly=y-y(P1), its ninth power is generated by
# t^9 Lx^(9-j) Ly^j / Lx^9 for 0<=j<=9.  This is an identity of fractional
# modules, not an assertion that the ideal t^9 J^9 is complete downstairs.
power_generators = [
    {
        "index": j,
        "unscaled_generator": "t^9*(x-xP1)^({})*(y-yP1)^{}".format(9-j, j),
        "cleared_membership_generator": "(x-xP1)^({})*(y-yP1)^{}".format(9-j, j),
    }
    for j in range(10)
]
assert [entry["index"] for entry in power_generators] == list(range(10))

# A source-q8 basis monomial is u^i x^a m^b/h^k.  Multiplying by Lx^9
# removes the chord denominator m=Ly/Lx and gives the exact generator index
# b times a chart-dependent coefficient.  The generic frame has b<=9, so no
# negative exponent is introduced.
generic_terms = []
for entry in generic["basis"]:
    a = int(entry["x_power"])
    b = int(entry["m_power"])
    assert a in (0, 1) and 0 <= b <= 9
    generic_terms.append({
        "basis": {"kind": entry["kind"], "x_power": a, "m_power": b},
        "source_monomial": "u^i*x^{}*m^{}/h^k".format(a, b),
        "cleared_factor": "g*u^i*x^{} / h^k".format(a),
        "power_generator_index": b,
        "cleared_numerator": (
            "g*u^i*x^{}*(x-xP1)^{}*(y-yP1)^{} / h^k".format(a, 9-b, b)
        ),
    })
assert len(generic_terms) == 18

edge_records = []
for name in sorted(charts):
    chart = charts[name]
    edge = gluing_charts[name]
    assert chart["surface_equation"] == edge["actual_h92_surface_equation"]
    edge_records.append({
        "name": name,
        "surface_equation": chart["surface_equation"],
        "old_coordinate_pullback": chart["old_coordinate_pullback"],
        "q8_w_cartier_equation": edge["w_cartier_equation"],
        "cleared_test": (
            "substitute the displayed (t,x,y) map into (x-xP1)^9*"
            "({})*f and test membership in t^9*J_P1^9 using the ten "
            "generators above, in this resolved chart and its overlaps".format(
                edge["w_cartier_equation"]
            )
        ),
    })

payload = {
    "schema": "elkies-k3.h92-q8-actual-e7-power-module.v1",
    "status": "PASS_EXACT_Q8_E7_CLEARED_POWER_MODULE",
    "inputs": {
        "actual_pullbacks": {"path": str(args.pullbacks.relative_to(ROOT)), "sha256": digest(args.pullbacks)},
        "q8_actual_gluing": {"path": str(args.gluing.relative_to(ROOT)), "sha256": digest(args.gluing)},
        "q8_e7_target": {"path": str(args.target.relative_to(ROOT)), "sha256": digest(args.target)},
        "q8_generic_frame": {"path": str(args.generic.relative_to(ROOT)), "sha256": digest(args.generic)},
    },
    "q6_marked_module": {
        "fractional_form": "t*J_P1/(x-xP1)",
        "ideal": "J_P1=(x-xP1,y-yP1)",
        "ninth_power_clearing_identity": "(x-xP1)^9*g*f belongs to t^9*J_P1^9",
        "marked_branch_pole_order": 9,
        "power_generators": power_generators,
    },
    "source_q8_generic_terms": generic_terms,
    "actual_edge_charts": edge_records,
    "compiler_instruction": (
        "For an enlarged endpoint monomial, replace i and k in its matching "
        "generic-term template. Reduce the cleared numerator and all ten "
        "generator multiples modulo the listed actual surface equation; retain "
        "the six overlap trivializations. Do not replace this test by scalar "
        "component valuations or by one complete ideal downstairs."
    ),
    "boundary": (
        "This packages the exact cleared membership problem only. It does not "
        "compute a resolved-chart quotient matrix, a q8 kernel, a D13 pencil, "
        "a bisection equation, an extension collision, or generic rank 18/19."
    ),
}
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
print(
    "H92Q8E7POWERMODULE|charts=6|power_generators=10|generic_terms=18|"
    "status=PASS_EXACT_Q8_E7_CLEARED_POWER_MODULE",
    flush=True,
)
