#!/usr/bin/env sage -python
"""Derive the finite integral basis of the exact third-q12 cubic pencil.

The generic resolved member is a monic cubic in the old x-coordinate over
``K(V)(W)``.  Its discriminant has the intrinsic shape ``L^3 Q^2 D``.  The
repeated root modulo the coprime conductor factors ``L`` and ``Q`` determines
an integral element

    e = (z^2 + A*z + B)/(L*Q).

This avoids Sage's unsupported normalization of a relative function-field
tower and certifies integrality by the characteristic polynomial of ``e``.
"""

import argparse
import hashlib
import json
import re
from pathlib import Path

from sage.all import PolynomialRing, QQ, ZZ


ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "artifacts/generated-results"
DEFAULT_INPUT = RESULTS / "q80-third-q12-um2-biquadratic-resolved-pencil-qq.json"
DEFAULT_OPERANDS = RESULTS / "q80-third-q12-um2-biquadratic-closure-operands-p19-hensel-qq.json"
DEFAULT_OUTPUT = RESULTS / "q80-third-q12-um2-biquadratic-integral-basis-qq.json"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
parser.add_argument("--operands", type=Path, default=DEFAULT_OPERANDS)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()
for name in ("input", "operands", "output"):
    setattr(args, name, getattr(args, name).resolve())


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rational(record):
    return QQ(ZZ(record["numerator"])) / ZZ(record["denominator"])


pencil = json.loads(args.input.read_text())
operands = json.loads(args.operands.read_text())
if pencil.get("status") != "PASS_EXACT_QQ_THIRD_Q12_BIQUADRATIC_RESOLVED_PENCIL":
    raise ValueError("exact resolved pencil is not certified")
if operands.get("status") != "PASS_EXACT_QQ_THIRD_Q12_BIQUADRATIC_CLOSURE_OPERANDS_P19_HENSEL":
    raise ValueError("exact biquadratic operands are not certified")

q1 = rational(operands["biquadratic_field"]["q1"])
q2 = rational(operands["biquadratic_field"]["q2"])
eta_ring = PolynomialRing(QQ, "eta_polynomial")
eta_polynomial = eta_ring.gen()
# The resolved pencil descends from the biquadratic horizontal field to the
# quadratic subfield generated by eta=theta^2.
primitive_polynomial = (
    eta_polynomial**2
    - 2 * (q1 + q2) * eta_polynomial
    + (q1 - q2) ** 2
)
field = eta_ring.quotient(primitive_polynomial, "eta")


def field_element(coordinates):
    if len(coordinates) != 1:
        raise ValueError("exact pencil coefficient is not one theta expression")
    # The exact compiler's generic quotient-ring repr is deliberately literal
    # but extremely large.  All 63 coefficients descend to QQ(theta^2), so
    # parse that canonical two-term representation without a symbolic parser.
    match = re.fullmatch(r"(.+)\*theta\^2 ([+-]) (.+)", coordinates[0])
    if match is None:
        raise ValueError("exact pencil coefficient does not descend to QQ(theta^2)")
    quadratic_coefficient = QQ(match.group(1))
    constant_coefficient = QQ(match.group(3))
    if match.group(2) == "-":
        constant_coefficient = -constant_coefficient
    return field(quadratic_coefficient * field.gen() + constant_coefficient)


# Use nested sparse rings.  Their Euclidean arithmetic does not request a
# PARI integral basis for the enormous quartic power-basis presentation.
v_ring = PolynomialRing(field, "V", sparse=True)
V = v_ring.gen()
v_field = v_ring.fraction_field()
w_ring = PolynomialRing(v_field, "W", sparse=True)
W = w_ring.gen()
z_ring = PolynomialRing(w_ring, "z")

coefficients = [w_ring.zero() for unused in range(4)]
for t_degree, w_degree, z_degree, coordinates in pencil["moving_equation"][
    "terms_T_W_x_coefficient_1_r"
]:
    coefficients[z_degree] += (
        field_element(coordinates) * v_field(V) ** t_degree * W**w_degree
    )
print("Q80THIRDQ12INTEGRALBASISQQ|stage=coefficients_loaded", flush=True)
if not coefficients[3] or coefficients[3].degree() != 0:
    raise ArithmeticError("resolved equation is not cubic with W-constant leading term")
monic_coefficients = [value / coefficients[3] for value in coefficients]
f = z_ring(monic_coefficients)
if not f.is_monic() or f.degree() != 3:
    raise ArithmeticError("failed to make the resolved cubic monic")

b, c, d = f[2], f[1], f[0]
discriminant = (
    b**2 * c**2
    - 4 * c**3
    - 4 * b**3 * d
    - 27 * d**2
    + 18 * b * c * d
)
repeated_part = discriminant.gcd(discriminant.derivative()).monic()
L = repeated_part.gcd(repeated_part.derivative()).monic()
Q, remainder = repeated_part.quo_rem(L**2)
if remainder:
    raise ArithmeticError("discriminant repeated part is not divisible by L^2")
Q = Q.monic()
conductor = L * Q
squarefree_discriminant, remainder = discriminant.quo_rem(L**3 * Q**2)
if remainder:
    raise ArithmeticError("discriminant does not have the required L^3 Q^2 divisor")
if (
    L.degree() != 1
    or Q.degree() != 4
    or squarefree_discriminant.degree() != 4
    or Q.gcd(L) != 1
    or squarefree_discriminant.gcd(L * Q) != 1
    or squarefree_discriminant.gcd(squarefree_discriminant.derivative()) != 1
):
    raise ArithmeticError("unexpected exact cubic discriminant stratification")

# Recover the repeated root separately modulo L and Q, then combine by CRT.
w_at_L = -L[0] / L[1]
z_over_v = PolynomialRing(v_field, "z")
f_at_L = z_over_v([coefficient(w_at_L) for coefficient in f.list()])
gcd_at_L = f_at_L.gcd(f_at_L.derivative()).monic()
if gcd_at_L.degree() != 1:
    raise ArithmeticError("cubic does not have one repeated root modulo L")
root_at_L = -gcd_at_L[0]

mod_Q = w_ring.quotient(Q, "W_mod_Q")
z_mod_Q = PolynomialRing(mod_Q, "z")
f_mod_Q = z_mod_Q([mod_Q(coefficient) for coefficient in f.list()])
gcd_at_Q = f_mod_Q.gcd(f_mod_Q.derivative()).monic()
if gcd_at_Q.degree() != 1:
    raise ArithmeticError("cubic does not have one repeated root modulo Q")
root_at_Q = -gcd_at_Q[0]
root = w_ring(
    root_at_L
    + L * ((root_at_Q - mod_Q(root_at_L)) / mod_Q(L)).lift()
) % conductor

# If f=(z-r)^2(z-s) modulo the conductor, then
# (z-r)(z-s)=z^2+(b+r)z-br-2r^2.  Its quotient by LQ is integral.
A = (b + root) % conductor
B = (-b * root - 2 * root**2) % conductor
if B % L:
    raise ArithmeticError("integral-basis constant numerator is not divisible by L")

# Certify integrality without constructing the function-field maximal order.
# resultant_z(f, (LQ)T-(z^2+Az+B)) is the characteristic polynomial numerator;
# its T^i coefficient must be divisible by (LQ)^(3-i).
t_ring = PolynomialRing(w_ring, "T")
T = t_ring.gen()
zt_ring = PolynomialRing(t_ring, "z")
zt = zt_ring.gen()
f_zt = zt_ring([t_ring(coefficient) for coefficient in f.list()])
numerator_zt = zt**2 + t_ring(A) * zt + t_ring(B)
characteristic_numerator = f_zt.resultant(
    zt_ring(t_ring(conductor) * T - numerator_zt)
)
if characteristic_numerator.degree() != 3:
    raise ArithmeticError("integral element has a degenerate characteristic polynomial")
characteristic_coefficients = []
for index, coefficient in enumerate(characteristic_numerator.list()):
    quotient, remainder = w_ring(coefficient).quo_rem(conductor ** (3 - index))
    if remainder:
        raise ArithmeticError(
            f"integral-element characteristic coefficient {index} has a denominator"
        )
    characteristic_coefficients.append(quotient)
if characteristic_coefficients[-1] != 1:
    raise ArithmeticError("integral-element characteristic polynomial is not monic")


def field_coordinates(value):
    coordinates = list(field(value).list())
    coordinates += [QQ.zero()] * (2 - len(coordinates))
    return [str(value) for value in coordinates]


def v_polynomial_record(polynomial):
    polynomial = v_ring(polynomial)
    return [field_coordinates(coefficient) for coefficient in polynomial.list()]


def v_rational_record(value):
    value = v_field(value)
    return {
        "numerator_coefficients_low_to_high_V": v_polynomial_record(value.numerator()),
        "denominator_coefficients_low_to_high_V": v_polynomial_record(value.denominator()),
    }


def w_polynomial_record(polynomial):
    polynomial = w_ring(polynomial)
    return {
        "coefficients_low_to_high_W": [
            v_rational_record(coefficient) for coefficient in polynomial.list()
        ],
        "degree_W": int(polynomial.degree()),
    }


output = {
    "schema": "elkies-k3.q80-third-q12-biquadratic-integral-basis-qq.v1",
    "status": "PASS_EXACT_QQ_THIRD_Q12_BIQUADRATIC_INTEGRAL_BASIS",
    "specialization": {
        "u": "-2",
        "coefficient_field_degree": 2,
        "primitive_element": "eta=theta^2=q1+q2+2*a*b",
        "primitive_polynomial": "eta^2-2*(q1+q2)*eta+(q1-q2)^2",
        "descent_from_biquadratic_field": True,
        "pencil_base": "V",
        "old_base": "W",
        "old_fibre_coordinate": "z",
    },
    "discriminant": {
        "factorization_shape": "unit*L^3*Q^2*D",
        "degrees_W_L_Q_D": [
            int(L.degree()),
            int(Q.degree()),
            int(squarefree_discriminant.degree()),
        ],
        "L": w_polynomial_record(L),
        "Q": w_polynomial_record(Q),
        "D": w_polynomial_record(squarefree_discriminant.monic()),
        "pairwise_coprime_and_D_squarefree": True,
    },
    "integral_basis": {
        "basis": ["1", "z", "e"],
        "e_formula": "(z^2+A*z+B)/(L*Q)",
        "A": w_polynomial_record(A),
        "B": w_polynomial_record(B),
        "B_divisible_by_L": True,
        "degrees_W_A_B": [int(A.degree()), int(B.degree())],
        "characteristic_polynomial_coefficients_low_to_high_T": [
            w_polynomial_record(coefficient)
            for coefficient in characteristic_coefficients
        ],
        "integrality_by_literal_resultant_divisibility": True,
    },
    "inputs": {
        "resolved_pencil": {
            "path": str(args.input.relative_to(ROOT)),
            "sha256": sha256(args.input),
        },
        "biquadratic_operands": {
            "path": str(args.operands.relative_to(ROOT)),
            "sha256": sha256(args.operands),
        },
    },
    "worker": {
        "path": str(Path(__file__).resolve().relative_to(ROOT)),
        "sha256": sha256(Path(__file__).resolve()),
    },
    "claim_boundary": (
        "This exactly derives and certifies a finite integral basis of the "
        "generic characteristic-zero cubic pencil. It does not yet compute "
        "the Riemann--Roch generators, Jacobian, birational maps, minimal "
        "model, fibre marking, or Mordell--Weil rank."
    ),
    "reproduce": (
        "sage -python "
        "elkies-k3/scripts/derive_q80_third_q12_biquadratic_integral_basis_qq.sage"
    ),
}
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(output, indent=2, sort_keys=True) + "\n")
print(
    "Q80THIRDQ12INTEGRALBASISQQ|"
    f"disc=L^3Q^2D:{L.degree()},{Q.degree()},{squarefree_discriminant.degree()}|"
    f"basis=1,z,(z^2+A*z+B)/(LQ)|degrees_A_B={A.degree()},{B.degree()}|"
    "status=PASS_EXACT_QQ_THIRD_Q12_BIQUADRATIC_INTEGRAL_BASIS",
    flush=True,
)
