#!/usr/bin/env sage-python
"""Recover the six eta-only rooted Niemeier residual groups intrinsically.

The remaining root systems D24, D16+E8, A24, A17+E7, A15+D9, and
A11+D7+E6 have no repeated component type. Recover every root component and
simple-root chamber from the supplied Gram matrices, enumerate every product
of component Dynkin-diagram automorphisms, and retain exactly the maps whose
lifts preserve the ambient Niemeier lattice integrally.

This derives the complete chamber residual groups from the lattice data. The
literature statement that each is generated by the class eta of -id is used
only as an independent cross-check.
"""

from __future__ import annotations

import argparse
import itertools
import json
import runpy
from collections import Counter
from pathlib import Path

from sage.all import Graph, QQ, ZZ, identity_matrix, matrix, vector


ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "artifacts/generated-results/elkies-k3-rooted-niemeier-catalog.json"
DEFAULT_OUTPUT = (
    ROOT
    / "artifacts/generated-results/elkies-k3-eta-only-niemeier-residual-groups-v1.json"
)
COMMON_SOURCE = (
    Path(__file__).resolve().parent
    / "enumerate_2a7_2d5_2c_fixed_high_mw_seed.sage"
)
COMMON = runpy.run_path(str(COMMON_SOURCE), run_name="_rank7_fixed_seed_common")

rows = COMMON["rows"]
digest = COMMON["digest"]
matrix_key = COMMON["matrix_key"]
row_module_basis = COMMON["row_module_basis"]
primitive_closure_index = COMMON["primitive_closure_index"]
signed_roots = COMMON["signed_roots"]

CONFIGS = (
    {
        "label": "D24",
        "components": (("D", 24),),
        "root_index": 2,
        "candidate_count": 2,
        "residual_order": 1,
    },
    {
        "label": "D16_E8",
        "components": (("D", 16), ("E", 8)),
        "root_index": 2,
        "candidate_count": 2,
        "residual_order": 1,
    },
    {
        "label": "A24",
        "components": (("A", 24),),
        "root_index": 5,
        "candidate_count": 2,
        "residual_order": 2,
    },
    {
        "label": "A17_E7",
        "components": (("A", 17), ("E", 7)),
        "root_index": 6,
        "candidate_count": 2,
        "residual_order": 2,
    },
    {
        "label": "A15_D9",
        "components": (("A", 15), ("D", 9)),
        "root_index": 8,
        "candidate_count": 4,
        "residual_order": 2,
    },
    {
        "label": "A11_D7_E6",
        "components": (("A", 11), ("D", 7), ("E", 6)),
        "root_index": 12,
        "candidate_count": 8,
        "residual_order": 2,
    },
)


def root_type(rank, root_count):
    candidates = []
    if root_count == rank * (rank + 1):
        candidates.append(("A", rank))
    if root_count == 2 * rank * (rank - 1):
        candidates.append(("D", rank))
    exceptional = {(6, 72): ("E", 6), (7, 126): ("E", 7), (8, 240): ("E", 8)}
    if (rank, root_count) in exceptional:
        candidates.append(exceptional[rank, root_count])
    assert len(candidates) == 1
    return candidates[0]


def component_roots(gram):
    roots = signed_roots(gram)
    unseen = set(range(len(roots)))
    components = []
    while unseen:
        component = {min(unseen)}
        pending = list(component)
        unseen.difference_update(component)
        while pending:
            current = pending.pop()
            adjacent = {
                index
                for index in unseen
                if roots[current] * gram * roots[index] != 0
            }
            component.update(adjacent)
            unseen.difference_update(adjacent)
            pending.extend(sorted(adjacent))
        vectors = [roots[index] for index in sorted(component)]
        rank = int(matrix(ZZ, vectors).rank())
        components.append((root_type(rank, len(vectors)), vectors))
    components.sort(key=lambda row: ("ADE".index(row[0][0]), row[0][1]))
    assert sum(component[0][1] for component in components) == 24
    return components


def dynkin_graph(basis, gram):
    cartan = basis * gram * basis.transpose()
    graph = Graph()
    graph.add_vertices(range(basis.nrows()))
    graph.add_edges(
        (row, column)
        for row in range(basis.nrows())
        for column in range(row)
        if cartan[row, column] == -1
    )
    return graph


def simple_roots(component_type, gram, roots):
    rank = component_type[1]
    for trial in range(1, 100):
        chamber = vector(
            ZZ,
            [
                (index + 1) ** 2 + trial * (index + 1) + trial**2
                for index in range(gram.nrows())
            ],
        )
        values = [root * gram * chamber for root in roots]
        if all(value != 0 for value in values):
            break
    else:
        raise AssertionError("failed to choose a regular chamber")
    positive = [root for root, value in zip(roots, values) if value > 0]
    positive_set = {tuple(map(int, root)) for root in positive}
    basis = matrix(
        ZZ,
        [
            root
            for root in positive
            if not any(
                tuple(map(int, root - other)) in positive_set
                for other in positive
            )
        ],
    )
    cartan = basis * gram * basis.transpose()
    assert basis.nrows() == basis.rank() == rank
    assert all(cartan[index, index] == 2 for index in range(rank))
    assert all(
        cartan[row, column] in (0, -1)
        for row in range(rank)
        for column in range(rank)
        if row != column
    )
    graph = dynkin_graph(basis, gram)
    assert graph.is_tree()
    expected_automorphisms = 1 if component_type in (("E", 7), ("E", 8)) else 2
    assert int(graph.automorphism_group().order()) == expected_automorphisms
    return basis


def graph_variants(basis, gram):
    graph = dynkin_graph(basis, gram)
    variants = [
        [int(automorphism(index)) for index in range(basis.nrows())]
        for automorphism in graph.automorphism_group()
    ]
    variants.sort(key=lambda value: value != list(range(basis.nrows())))
    assert variants[0] == list(range(basis.nrows()))
    return variants


def residue_vector(values):
    return tuple(QQ(value - value.floor()) for value in values)


def add_residues(left, right):
    return residue_vector([a + b for a, b in zip(left, right)])


def quotient_cosets(root_basis_inverse, expected_order):
    generators = []
    for ambient_index in range(24):
        ambient = vector(ZZ, [int(index == ambient_index) for index in range(24)])
        generators.append(residue_vector(ambient * root_basis_inverse))
    cosets = {(QQ(0),) * 24}
    for generator in generators:
        while True:
            enlarged = cosets | {
                add_residues(coset, generator) for coset in cosets
            }
            if enlarged == cosets:
                break
            cosets = enlarged
        assert len(cosets) <= expected_order
    assert len(cosets) == expected_order
    return generators, cosets


def fixed_lattice_data(action, gram):
    identity = identity_matrix(ZZ, 24)
    fixed = row_module_basis(
        (action - identity).transpose().right_kernel_matrix().change_ring(ZZ)
    )
    fixed_rank = fixed.nrows()
    if fixed_rank:
        assert primitive_closure_index(fixed) == 1
        fixed_determinant = int((fixed * gram * fixed.transpose()).det())
    else:
        fixed_determinant = 1
    return fixed_rank, fixed_determinant


def candidate_actions(bases, variants, root_basis_inverse, gram):
    candidates = []
    elements = []
    seen = set()
    selection_ranges = [range(len(component_variants)) for component_variants in variants]
    for selections in itertools.product(*selection_ranges):
        target_basis = matrix(
            QQ,
            [
                bases[component][variants[component][selections[component]][row]]
                for component in range(len(bases))
                for row in range(bases[component].nrows())
            ],
        )
        rational_action = root_basis_inverse * target_basis
        integral = all(entry.denominator() == 1 for entry in rational_action.list())
        candidates.append(
            {
                "component_diagram_variant_indices": list(selections),
                "integral_ambient_lift": integral,
            }
        )
        if not integral:
            continue
        action = matrix(ZZ, rational_action)
        assert abs(action.det()) == 1
        assert action * gram * action.transpose() == gram
        key = matrix_key(action)
        assert key not in seen
        seen.add(key)
        fixed_rank, fixed_determinant = fixed_lattice_data(action, gram)
        elements.append(
            {
                "component_diagram_variant_indices": tuple(selections),
                "matrix": action,
                "action_order": 1 if action == identity_matrix(ZZ, 24) else 2,
                "fixed_rank": fixed_rank,
                "fixed_determinant": fixed_determinant,
            }
        )
    return candidates, elements


def certify_group(elements, label):
    by_key = {matrix_key(row["matrix"]): index for index, row in enumerate(elements)}
    assert len(by_key) == len(elements)
    for left in elements:
        inverse = left["matrix"].inverse().change_ring(ZZ)
        assert matrix_key(inverse) in by_key
        for right in elements:
            assert matrix_key(left["matrix"] * right["matrix"]) in by_key
    classes = []
    for element_index, element in enumerate(elements):
        classes.append(
            {
                "class_id": f"{label}-C{element_index + 1:02d}",
                "class_size": 1,
                "action_order": element["action_order"],
                "fixed_rank": element["fixed_rank"],
                "fixed_determinant": element["fixed_determinant"],
                "representative_component_diagram_variant_indices": list(
                    element["component_diagram_variant_indices"]
                ),
                "representative_matrix": rows(element["matrix"]),
                "element_indices_zero_based": [element_index],
            }
        )
    classes.sort(
        key=lambda row: (
            row["action_order"],
            -row["fixed_rank"],
            row["fixed_determinant"],
            row["representative_component_diagram_variant_indices"],
        )
    )
    for index, row in enumerate(classes, start=1):
        row["class_id"] = f"{label}-C{index:02d}"
    return classes


def build_backend(catalog, config):
    ambient_row = next(
        row
        for row in catalog["rooted_niemeier_lattices"]
        if row["label"] == config["label"]
    )
    gram = matrix(ZZ, ambient_row["gram"])
    components = component_roots(gram)
    assert tuple(component[0] for component in components) == config["components"]
    bases = [
        simple_roots(component_type, gram, roots)
        for component_type, roots in components
    ]
    variants = [graph_variants(basis, gram) for basis in bases]
    root_basis = matrix(ZZ, [root for basis in bases for root in basis.rows()])
    assert root_basis.nrows() == root_basis.ncols() == root_basis.rank() == 24
    assert abs(root_basis.det()) == config["root_index"]
    root_basis_inverse = root_basis.inverse()
    quotient_generators, quotient = quotient_cosets(
        root_basis_inverse, config["root_index"]
    )
    candidates, elements = candidate_actions(
        bases, variants, root_basis_inverse, gram
    )
    assert len(candidates) == config["candidate_count"]
    assert len(elements) == config["residual_order"]
    if config["residual_order"] == 2:
        assert [
            candidate["component_diagram_variant_indices"]
            for candidate in candidates
            if candidate["integral_ambient_lift"]
        ] == [
            [0] * len(config["components"]),
            [len(variants[index]) - 1 for index in range(len(variants))],
        ]
    classes = certify_group(elements, config["label"])
    order_distribution = Counter(row["action_order"] for row in elements)
    fixed_rank_distribution = Counter(row["fixed_rank"] for row in elements)
    return {
        "ambient_label": config["label"],
        "root_components": [
            {"family": family, "rank": rank} for family, rank in config["components"]
        ],
        "root_lattice": {
            "simple_root_bases_in_ambient": [rows(basis) for basis in bases],
            "combined_basis_in_ambient": rows(root_basis),
            "index_in_niemeier": abs(int(root_basis.det())),
        },
        "root_lattice_quotient": {
            "order": len(quotient),
            "ambient_basis_generators_mod_root_basis": [
                [str(value) for value in generator]
                for generator in quotient_generators
            ],
            "cosets_mod_root_basis": [
                [str(value) for value in coset] for coset in sorted(quotient)
            ],
        },
        "candidate_chamber_maps": candidates,
        "residual_group": {
            "order": len(elements),
            "component_permutation_image_order": 1,
            "component_diagram_kernel_order": len(elements),
            "candidate_maps_tested": len(candidates),
            "order_distribution": {
                str(key): value for key, value in sorted(order_distribution.items())
            },
            "fixed_rank_distribution": {
                str(key): value
                for key, value in sorted(fixed_rank_distribution.items())
            },
            "conjugacy_classes": classes,
            "elements": [
                {
                    "component_diagram_variant_indices": list(
                        row["component_diagram_variant_indices"]
                    ),
                    "action_order": row["action_order"],
                    "fixed_rank": row["fixed_rank"],
                    "fixed_determinant": row["fixed_determinant"],
                    "matrix": rows(row["matrix"]),
                }
                for row in elements
            ],
        },
    }


def build(catalog):
    assert catalog["schema"] == "elkies-k3.rooted-niemeier-catalog.v1"
    backends = [build_backend(catalog, config) for config in CONFIGS]
    assert {row["ambient_label"]: row["residual_group"]["order"] for row in backends} == {
        "D24": 1,
        "D16_E8": 1,
        "A24": 2,
        "A17_E7": 2,
        "A15_D9": 2,
        "A11_D7_E6": 2,
    }
    assert [
        (
            row["ambient_label"],
            row["root_lattice"]["index_in_niemeier"],
            row["residual_group"]["candidate_maps_tested"],
            [
                (
                    class_row["action_order"],
                    class_row["fixed_rank"],
                    class_row["fixed_determinant"],
                )
                for class_row in row["residual_group"]["conjugacy_classes"]
            ],
        )
        for row in backends
    ] == [
        ("D24", 2, 2, [(1, 24, 1)]),
        ("D16_E8", 2, 2, [(1, 24, 1)]),
        ("A24", 5, 2, [(1, 24, 1), (2, 12, 4096)]),
        ("A17_E7", 6, 2, [(1, 24, 1), (2, 16, 256)]),
        ("A15_D9", 8, 4, [(1, 24, 1), (2, 16, 256)]),
        ("A11_D7_E6", 12, 8, [(1, 24, 1), (2, 16, 256)]),
    ]
    return {
        "schema": "elkies-k3.eta-only-niemeier-residual-groups.v1",
        "status": "PASS_EXACT_ETA_ONLY_SIX_NIEMEIER_RESIDUAL_GROUPS",
        "proof_scope": {
            "proved": (
                "intrinsic recovery of every irreducible root component and root "
                "quotient; exhaustive component Dynkin-diagram chamber maps; "
                "complete integral residual lift groups, fixed lattices, and classes"
            ),
            "not_proved": (
                "rank-seven auxiliary enumeration, full Weyl embedding orbits, "
                "K3 admissibility, or determinant-band completeness"
            ),
        },
        "backends": backends,
        "literature_cross_check": {
            "citation": (
                "Chenevier, The Characteristic Masses of Niemeier Lattices "
                "(2020), Section 5"
            ),
            "doi": "10.5802/jtnb.1134",
            "expected_structure": (
                "for D24, D16+E8, A24, A17+E7, A15+D9, and A11+D7+E6, "
                "the umbral group is generated by the eta class of -id"
            ),
            "role": (
                "independent naming/order cross-check only; the artifact derives "
                "every retained chamber lift from the supplied lattices"
            ),
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=CATALOG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    payload = build(json.loads(arguments.catalog.read_text()))
    payload["inputs"] = {
        str(arguments.catalog.resolve().relative_to(ROOT)): digest(arguments.catalog),
        str(COMMON_SOURCE.resolve().relative_to(ROOT)): digest(COMMON_SOURCE),
    }
    payload["reproduce"] = (
        "/home/royvanrijn/.local/share/jacobian-sage-10.9/bin/python "
        "elkies-k3/scripts/probe_eta_only_niemeier_residual_groups.sage"
    )
    encoded = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    output = arguments.output.resolve()
    if arguments.check:
        if not output.exists() or output.read_text() != encoded:
            raise SystemExit("eta-only residual-group artifact is stale")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(encoded)
    print(
        "ETAONLYGROUPS|backends={}|nontrivial={}|status=PASS_EXACT".format(
            len(payload["backends"]),
            sum(row["residual_group"]["order"] > 1 for row in payload["backends"]),
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
