from sage.all import *
from pathlib import Path

FRAME=Path("elkies-k3/data/fibrations/q15_mw3_frame.txt")
F=matrix(ZZ,[[ZZ(x) for x in ln.split()] for ln in FRAME.read_text().splitlines() if ln.strip()])
assert F.det()==948 and F.is_positive_definite()

def qform(H):
    co=[]
    for i in range(H.nrows()):
        for j in range(i,H.ncols()):
            co.append(H[i,i]//2 if i==j else H[i,j])
    return QuadraticForm(ZZ,H.nrows(),co)

# All roots, and exact root lattice R.
half=[vector(ZZ,r) for r in qform(F).short_vector_list_up_to_length(2,True)[1]]
signed=half+[-r for r in half]
Rmod=matrix(ZZ,[list(r) for r in signed]).row_module()
RB=Rmod.basis_matrix()
GR=RB*F*RB.transpose()
assert RB.rank()==14 and abs(GR.det())==132
print(f"MW3GLUE|stage=root|rank={RB.rank()}|roots={2*len(half)}|det={abs(GR.det())}",flush=True)

# Integral orthogonal intersection C = R^\perp ∩ F-lattice.
C=(RB*F).right_kernel_matrix()
assert C.rank()==3
GC=C*F*C.transpose()
print(f"MW3GLUE|stage=intersection|rank={C.rank()}|gram={GC}|det={GC.det()}",flush=True)

# A=R+C inside the ambient Z^17 frame lattice.
A=block_matrix([[RB],[C]],subdivide=False)
assert A.nrows()==17 and A.det()!=0
idx=abs(A.det())
print(f"MW3GLUE|stage=index|index_RplusC_in_F={idx}",flush=True)

D,U,V=A.smith_form()
smith=[abs(ZZ(D[i,i])) for i in range(17)]
print(f"MW3GLUE|stage=smith|diag={smith}|product={prod(smith)}",flush=True)
assert prod(smith)==idx

Ainv=A.inverse()
def mod1(q):
    q=QQ(q); return q-floor(q)
def coset_key(z):
    c=vector(QQ,z)*Ainv
    return tuple(mod1(x) for x in c)

# Enumerate F/A by BFS using ambient unit vectors.
zero=vector(ZZ,[0]*17)
cosets={coset_key(zero):zero}
queue=[zero]; head=0
while head<len(queue) and len(cosets)<idx:
    z=queue[head]; head+=1
    for i in range(17):
        e=vector(ZZ,[0]*17); e[i]=1
        for s in (1,-1):
            y=z+s*e; k=coset_key(y)
            if k not in cosets:
                cosets[k]=y; queue.append(y)
                if len(cosets)==idx: break
        if len(cosets)==idx: break
print(f"MW3GLUE|stage=cosets|count={len(cosets)}",flush=True)
assert len(cosets)==idx

# Orthogonal projection away from root lattice.
GRinv=GR.inverse()
def project_mw(x):
    x=vector(QQ,x)
    coeff=(x*F*RB.transpose())*GRinv
    return x-coeff*RB

# Express projected point in C_Q using pairings.
GCinv=GC.inverse()
def ccoords(p):
    return (vector(QQ,p)*F*C.transpose())*GCinv

proj=[]
for z in cosets.values():
    p=project_mw(z)
    c=ccoords(p)
    assert p==c*C
    proj.append(c)

# MW lattice generated by C plus projected glue.
rows=[vector(QQ,[1,0,0]),vector(QQ,[0,1,0]),vector(QQ,[0,0,1])] + proj
den=lcm([QQ(x).denominator() for r in rows for x in r])
Zrows=matrix(ZZ,[[ZZ(den*x) for x in r] for r in rows])
Bz=Zrows.row_module().basis_matrix()
B=Bz.change_ring(QQ)/den
assert B.rank()==3
H=B*GC*B.transpose()
print(f"MW3GLUE|stage=MW|basis_in_C={B}",flush=True)
print(f"MW3GLUE|height_gram={H}|det={H.det()}",flush=True)
assert H.det()==QQ(79)/11

# Clear denominator and reduce.
hden=lcm([QQ(x).denominator() for x in H.list()])
ZH=(hden*H).change_ring(ZZ)
print(f"MW3GLUE|scaled|den={hden}|gram={ZH}",flush=True)
try:
    T=matrix(ZZ,pari(ZH).qflllgram())
    cand=[]
    for X in (T,T.transpose()):
        if X.nrows()==3:
            R=X*ZH*X.transpose()
            if R.is_symmetric() and R.det()==ZH.det():
                cand.append((max(abs(v) for v in R.list()),R,X))
    if cand:
        _,Red,X=min(cand,key=lambda z:z[0])
        print(f"MW3GLUE|reduced_scaled_gram={Red}|scale={hden}|transform={X}",flush=True)
except Exception as e:
    print(f"MW3GLUE|reduce_warning={e}",flush=True)

out=Path("artifacts/local/elkies-k3/mw3-exact-height-lattice.txt")
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text(
    f"root_det={abs(GR.det())}\nindex={idx}\nsmith={smith}\n"
    f"C_gram={GC}\nMW_basis_in_C={B}\nheight_gram={H}\ndet={H.det()}\n"
)
print(f"MW3GLUE|stage=done|out={out}",flush=True)
