#!/usr/bin/env sage
"""Bound the first nonzero-X vertical gate for the CM24 q12 pencil.

The exact CM24 horizontal space is generated by ``1,X,z_Q`` with
``z_Q=(Y+Qy)/(X-Qx)``.  Pure translations of ``z_Q`` have already been
exhausted and miss the transported ``2A6+3A1`` fiber signature.  This small
finite-field experiment tests the next ansatz

    V = z_Q + (a1*W+a0)*X + b2*W^2 + b1*W

over GF(7), where ``sqrt(-6)=1``.  The omitted constant translates V.  It
first permits the X coefficient to be constant (the ``a1=0`` slice), then
the full linear coefficient. For each of the 7^4 tuples it divides out the
known point ``X=Qx`` and computes
the branch polynomial of the resulting cubic cover of the W-line.  Candidates
whose squarefree branch degree is at most eight are printed for subsequent
exact local-component tests.

This is a bounded experiment, not a characteristic-zero existence proof.
"""

from collections import Counter

from sage.all import GF, PolynomialRing


field = GF(7)
parameter_ring = PolynomialRing(field, "V")
V = parameter_ring.gen()
old_base_ring = PolynomialRing(parameter_ring, "W")
W = old_base_ring.gen()
x_ring = PolynomialRing(old_base_ring, "X")
X = x_ring.gen()

# Reduction of the exact QQ(sqrt(-6)) CM24 second-child equation and its
# polynomial q12 section, taking sqrt(-6)=1 modulo seven.
A = (
    -27*W**6+59049*W**4+field(13286025)/8*W**3
    + field(129140163)/8*W**2+field(1162261467)/32*W
    - field(10460353203)/64
)
B = (
    54*W**9-177147*W**7-field(97253703)/8*W**6
    - field(7360989291)/16*W**5-field(331244518095)/32*W**4
    - field(4487491524087)/32*W**3-field(144886352214753)/128*W**2
    - field(1303977169932777)/256*W-field(5147278302366225)/512
)
Qx = (
    -field(8)/27*W**4+22*W**3-field(243)/2*W**2+729*W
    - field(492075)/8
)
Qy = (
    field(16)/243*W**6-field(22)/3*W**5+field(333)/2*W**4
    - field(2025)/4*W**3+field(190269)/4*W**2
    - field(177147)/16*W+field(199290375)/32
)
assert Qy**2 == Qx**3+A*Qx+B


def squarefree_degree(polynomial):
    derivative = polynomial.derivative()
    if not derivative:
        return -1
    return (polynomial//polynomial.gcd(derivative)).degree()


distribution = Counter()
candidates = []
for a1 in field:
    for a0 in field:
        for b2 in field:
            for b1 in field:
                a_numerator = a1*W+a0
                b_numerator = b2*W**2+b1*W
                z_value = V-a_numerator*X-b_numerator
                equation = (
                    (z_value*(X-Qx)-Qy)**2-X**3-A*X-B
                )
                quotient, remainder = equation.quo_rem(X-Qx)
                assert remainder == 0 and quotient.degree() == (
                    2 if not a_numerator else 3
                )
                branch = quotient.discriminant()
                degree = squarefree_degree(branch)
                distribution[(not a_numerator, branch.degree(), degree)] += 1
                if a_numerator and 0 <= degree <= 8:
                    candidates.append(
                        (
                            int(a1), int(a0), int(b2), int(b1),
                            branch.degree(), degree,
                        )
                    )

print(
    f"Q80THIRDXGATE|field=GF(7)|tested={7**4}|"
    f"distribution={tuple(sorted(distribution.items()))}",
    flush=True,
)
print(
    f"Q80THIRDXGATE|nonzero_a_squarefree_degree_le_8={tuple(candidates)}|"
    f"count={len(candidates)}|status=PASS_BOUNDED_EXPERIMENT",
    flush=True,
)
