#!/usr/bin/env sage -python
"""Bound alternative rational source points on the level-474 H3 base.

The published genus-two curve

    Y^2 = -27*X^6 + 198*X^4 - 171*X^2 + 576

has an elliptic quotient under ``X -> -X``.  With

    xE=-27*X^2,  yE=-27*Y,

the quotient is

    yE^2=xE^3+198*xE^2+4617*xE+419904.

Sage proves this elliptic curve has trivial torsion and rank one, generated by
``G=(-27,648)``.  A rational lift to the genus-two curve requires
``-xE/27`` to be a rational square.  This checker applies that necessary
condition modulo good primes to every ``n*G`` in a stated coefficient box.

The result is a bounded obstruction, not a proof that all rational points on
the genus-two curve have been determined.
"""

from sage.all import *

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE_FAMILY = (
    ROOT / "artifacts/generated-results/elkies-k3-h3-level474-source-family.json"
)
SOURCE_FAMILY_SHA256 = (
    "8f5afd11e1d8979d57cb1a569833309f9664c19cd47194af0581a5cbbf8f1d59"
)
DEFAULT_OUTPUT = (
    ROOT / "artifacts/generated-results/elkies-k3-h3-level474-point-sieve.json"
)
DEFAULT_PRIME_LIMIT = 163


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--bound", type=ZZ, default=ZZ(10**6))
parser.add_argument("--prime-limit", type=ZZ, default=ZZ(DEFAULT_PRIME_LIMIT))
parser.add_argument("--source-family", type=Path, default=SOURCE_FAMILY)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()
assert args.bound >= 9
assert args.prime_limit >= 5
assert digest(args.source_family) == SOURCE_FAMILY_SHA256
source_family = json.loads(args.source_family.read_text())
assert source_family["status"] == "PASS_EXACT_H3_SOURCE_FAMILY"

quotient = EllipticCurve(QQ, [0, 198, 0, 4617, 419904])
minimal = quotient.minimal_model()
generator = quotient(-27, 648)
assert quotient.torsion_subgroup().order() == 1
assert quotient.rank(proof=True) == 1
generators = quotient.gens(proof=True)
assert len(generators) == 1 and generators[0] in (generator, -generator)

record_quotient_point = quotient(QQ(-4563) / 49, QQ(-325296) / 343)
assert record_quotient_point == 9 * generator
assert 6 * generator == quotient(0, -648)

candidates = list(range(int(args.bound) + 1))
prime_rows = []
for prime in prime_range(5, int(args.prime_limit) + 1):
    if quotient.discriminant() % prime == 0:
        continue
    finite_curve = quotient.change_ring(GF(prime))
    finite_generator = finite_curve(generator)
    order = ZZ(finite_generator.order())
    allowed = []
    point = finite_curve(0)
    for residue in range(order):
        if point.is_zero():
            allowed.append(residue)
        else:
            square_candidate = -point[0] / GF(prime)(27)
            if square_candidate.is_square():
                allowed.append(residue)
        point += finite_generator
    allowed_set = set(allowed)
    before = len(candidates)
    candidates = [
        coefficient
        for coefficient in candidates
        if coefficient % order in allowed_set
    ]
    prime_rows.append(
        {
            "prime": int(prime),
            "generator_order": int(order),
            "allowed_residue_count": len(allowed),
            "candidates_before": before,
            "candidates_after": len(candidates),
        }
    )

if args.bound == 10**6 and args.prime_limit == DEFAULT_PRIME_LIMIT:
    assert candidates == [0, 1, 6, 9]

known_lifts = {
    "1": {"X": ["-1", "1"], "Y": ["-24", "24"], "type": "CM"},
    "6": {"X": ["0"], "Y": ["-24", "24"], "type": "CM"},
    "9": {
        "X": ["-13/7", "13/7"],
        "Y": ["-12048/343", "12048/343"],
        "type": "non-CM record source orbit",
    },
}

payload = {
    "schema": "elkies-k3.h3-level474-point-sieve.v1",
    "status": "PASS_BOUNDED_H3_SOURCE_POINT_SIEVE",
    "input": {
        "source_family": str(args.source_family.relative_to(ROOT)),
        "sha256": SOURCE_FAMILY_SHA256,
    },
    "genus_two_curve": (
        "Y^2=-27*X^6+198*X^4-171*X^2+576"
    ),
    "elliptic_quotient": {
        "map": ["xE=-27*X^2", "yE=-27*Y"],
        "equation": "yE^2=xE^3+198*xE^2+4617*xE+419904",
        "minimal_model": str(minimal),
        "discriminant_factorization": str(factor(quotient.discriminant())),
        "torsion_order": 1,
        "rank": 1,
        "generator": ["-27", "648"],
        "record_point_multiple": 9,
    },
    "sieve": {
        "coefficient_interval": [int(-args.bound), int(args.bound)],
        "sign_reduction": "x(nG)=x(-nG), so only 0<=n<=bound is tested",
        "prime_limit": int(args.prime_limit),
        "good_primes": [row["prime"] for row in prime_rows],
        "rows": prime_rows,
        "surviving_absolute_coefficients": candidates,
        "necessary_condition": "-x(nG)/27 is a square in every residue field",
    },
    "known_rational_lifts": known_lifts,
    "interpretation": (
        "For every Mordell-Weil coefficient |n| at most the stated bound, "
        "the local square conditions leave only n=0,1,6,9.  The n=0 "
        "quotient point has no rational point at infinity above it because "
        "the sextic leading coefficient -27 is nonsquare.  The other three "
        "coefficients give exactly the displayed CM and record-source points."
    ),
    "proof_boundary": (
        "This is an exact bounded Mordell-Weil-coefficient sieve.  It is not "
        "a global determination of all rational points on the genus-two "
        "curve and does not bound coefficients outside the stated interval."
    ),
}

args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

print(
    f"H3POINTS|quotient_rank=1|torsion=1|bound={args.bound}|"
    f"primes={len(prime_rows)}|survivors="
    + ",".join(map(str, candidates)),
    flush=True,
)
print("H3POINTS|status=PASS_BOUNDED_H3_SOURCE_POINT_SIEVE", flush=True)
