#!/usr/bin/env sage
"""Prove full nefness of the alternate final q6 divisor.

The chamber checker already removes the zero and the two components of the
sole A1 fiber.  This verifier excludes every remaining irreducible (-2)-curve.
Because the reduced divisor has old-fiber degree two, a negative fixed curve
can only be a section or a bisection.  Sections reduce to one exact closest-
vector problem in the rank-17 frame; bisections are excluded by parity and
positive definiteness.
"""

from pathlib import Path

from sage.all import QQ, ZZ, vector
from sage.modules.free_quadratic_module_integer_symmetric import IntegralLattice


HERE = Path(__file__).resolve().parent
load(str(HERE / "analyze_q80_alternate_final_q6_chamber.sage"))

assert intersection(reduced, fiber, alternate_ns) == 2
assert intersection(reduced, zero, alternate_ns) == 1

# Write D=(3,2,v) in U+(-M).  Isotropy gives v.M.v=12.  A section indexed by
# w in M has class ((w.M.w-2)/2,1,w), hence
#
#   D.S = 1+w.M.w-v.M.w
#       = (w-v/2).M.(w-v/2)-2.
v = vector(ZZ, reduced[2:])
assert v*alternate_child*v == 12
assert alternate_child.is_positive_definite()
assert all(alternate_child[index, index] % 2 == 0 for index in range(17))
center = vector(QQ, v)/2
lattice = IntegralLattice(alternate_child)
iterator = lattice.enumerate_close_vectors(center)
closest = vector(ZZ, next(iterator))
closest_distance = (closest-center)*alternate_child*(closest-center)
assert closest_distance >= 2
minimum_section_pairing = closest_distance-2

# The horizontal point needed by the actual pencil is even simpler.  The
# integral frame vector v itself gives the section S=(5,1,v): its norm is 12,
# so S.O=4, and the reduced divisor has the exact decomposition
# D=O+S-F.  On a Weierstrass model the generic-fiber function space is
# therefore generated by 1 and the chord (y+y(S))/(x-x(S)), followed by one
# vertical F cancellation.
horizontal_section = vector(ZZ, [5, 1]+list(v))
assert horizontal_section*alternate_ns*horizontal_section == -2
assert intersection(horizontal_section, fiber, alternate_ns) == 1
assert intersection(horizontal_section, zero, alternate_ns) == 4
assert intersection(horizontal_section, root_curve, alternate_ns) == 1
assert intersection(horizontal_section, affine_curve, alternate_ns) == 0
assert reduced == zero+horizontal_section-fiber
horizontal_section_in_fourth = vector(ZZ, horizontal_section*alternate_transport)
assert horizontal_section_in_fourth*fourth_child_ns*horizontal_section_in_fourth == -2
section_old_degree = intersection(
    horizontal_section_in_fourth, fiber_fifth, fourth_child_ns
)
section_old_zero_pairing = intersection(
    horizontal_section_in_fourth, zero_fifth, fourth_child_ns
)
assert section_old_degree > 0 and section_old_zero_pairing >= 0
assert all(
    intersection(horizontal_section_in_fourth, curve, fourth_child_ns) >= 0
    for _, curve in curves_fifth
)

# A degree-two (-2)-class is C=(k,2,w), with w.M.w=4k+2.  Its intersection
# with D is
#
#   D.C = (w-v).M.(w-v)/2-1.
#
# If this were negative, positive definiteness and even integrality would
# force w=v.  But v.M.v=12 is 0 mod 4, contradicting the required
# w.M.w=2 mod 4.  Thus no negative bisection exists.
assert v*alternate_child*v % 4 == 0
negative_bisection_impossible = True

print(
    "Q80ALTFINALQ6NEF|"
    f"closest_section_vector={tuple(closest)}|"
    f"closest_distance={closest_distance}|"
    f"minimum_section_pairing={minimum_section_pairing}|"
    f"horizontal_section={tuple(horizontal_section)}|section_P.O=4|"
    "decomposition=O+S-F|generic_fiber_RR=<1,(y+yS)/(x-xS)>|"
    f"section_in_fourth={tuple(horizontal_section_in_fourth)}|"
    f"section_old_degree={section_old_degree}|"
    f"section_old_zero_pairing={section_old_zero_pairing}|"
    "negative_bisection_impossible=1|"
    "all_effective_minus2_nonnegative=1|nef=1|"
    "status=PASS_NEF_CHAMBER",
    flush=True,
)
