import GMC2.SpecializationArgument
import Mathlib.RingTheory.FiniteType
import Mathlib.Tactic

/-!
# Descent to the finite coefficient ring

An individual circular polynomial uses finitely many scalar coefficients.
Adjoining those coefficients to `ℤ` gives the finite-type domain to which
the specialization theorem applies.
-/

namespace GMC2

open Polynomial LaurentPolynomial

/-- The finite set of scalar coefficients occurring in a circular
polynomial, expressed through its flattened bidegree representation. -/
noncomputable def scalarCoefficientSet
    {K : Type*} [CommRing K] (P : CircularPolynomial K) : Finset K := by
  classical
  exact (circularBigradedEquiv K P).coeff.support.image
    (circularBigradedEquiv K P).coeff

/-- The `ℤ`-subalgebra generated by all scalar coefficients of `P`. -/
noncomputable def coefficientRing
    {K : Type*} [CommRing K] [Algebra ℤ K]
    (P : CircularPolynomial K) : Subalgebra ℤ K :=
  Algebra.adjoin ℤ (scalarCoefficientSet P : Set K)

private theorem scalarCoefficient_mem_coefficientRing
    {K : Type*} [CommRing K] [Algebra ℤ K]
    (P : CircularPolynomial K) (x : ℤ × ℕ) :
    (circularBigradedEquiv K P).coeff x ∈ coefficientRing P := by
  classical
  by_cases hx : x ∈ (circularBigradedEquiv K P).coeff.support
  · apply Algebra.subset_adjoin
    apply Finset.mem_coe.mpr
    rw [scalarCoefficientSet]
    exact Finset.mem_image.mpr ⟨x, hx, rfl⟩
  · have hz : (circularBigradedEquiv K P).coeff x = 0 :=
      Finsupp.notMem_support_iff.mp hx
    rw [hz]
    exact (coefficientRing P).zero_mem

/-- The same polynomial with coefficients valued in its finite coefficient
ring. -/
noncomputable def polynomialOverCoefficientRing
    {K : Type*} [CommRing K] [Algebra ℤ K]
    (P : CircularPolynomial K) :
    CircularPolynomial (coefficientRing P) := by
  classical
  let f := circularBigradedEquiv K P
  let liftCoeff : ℤ × ℕ → coefficientRing P :=
    fun x ↦ ⟨f.coeff x, scalarCoefficient_mem_coefficientRing P x⟩
  let fcoeff : (ℤ × ℕ) →₀ coefficientRing P :=
    { toFun := liftCoeff
      support := f.coeff.support
      mem_support_toFun := by
        intro x
        simp only [liftCoeff, ne_eq, Subtype.ext_iff]
        exact f.coeff.mem_support_toFun x }
  exact (circularBigradedEquiv (coefficientRing P)).symm ⟨fcoeff⟩

theorem map_polynomialOverCoefficientRing
    {K : Type*} [CommRing K] [Algebra ℤ K]
    (P : CircularPolynomial K) :
    circularMap (Subalgebra.val (coefficientRing P)).toRingHom
        (polynomialOverCoefficientRing P) = P := by
  classical
  ext k j
  rw [circularMap_coeff, Polynomial.coeff_map]
  rw [← circularBigradedEquiv_coeff
    (polynomialOverCoefficientRing P) k j]
  change
    ((polynomialOverCoefficientRing P |> circularBigradedEquiv
      (coefficientRing P)).coeff (k, j) : coefficientRing P).1 =
      (P.coeff k).coeff j
  rfl

private theorem pureMomentsVanish_polynomialOverCoefficientRing
    {K : Type*} [Field K] [CharZero K]
    (P : CircularPolynomial K) (hvan : PureMomentsVanish P) :
    PureMomentsVanish (polynomialOverCoefficientRing P) := by
  intro m hm
  apply Subtype.ext
  change
    (Subalgebra.val (coefficientRing P)).toRingHom
      (pureMoment (polynomialOverCoefficientRing P) m) = 0
  rw [pureMoment, circularExpectation_circularMap]
  rw [map_pow, map_polynomialOverCoefficientRing]
  exact hvan m hm

/-- Vanishing pure moments over any characteristic-zero field exclude a
straddling angular support.  The proof descends to the finite coefficient
ring and invokes the specialization argument there. -/
theorem not_supportStraddlesZero_of_pureMoments
    {K : Type*} [Field K] [CharZero K]
    (P : CircularPolynomial K) (hvan : PureMomentsVanish P) :
    ¬ SupportStraddlesZero P := by
  intro hconv
  let A := coefficientRing P
  let PA := polynomialOverCoefficientRing P
  letI : Algebra.FiniteType ℤ A :=
    Algebra.FiniteType.adjoin_of_finite
      (scalarCoefficientSet P).finite_toSet
  have hvanA : PureMomentsVanish PA :=
    pureMomentsVanish_polynomialOverCoefficientRing P hvan
  have hconvA : SupportStraddlesZero PA := by
    rcases hconv with ⟨⟨a, ha, ha0⟩, ⟨b, hb, hb0⟩⟩
    refine ⟨⟨a, ?_, ha0⟩, ⟨b, ?_, hb0⟩⟩
    · apply Finsupp.mem_support_iff.mpr
      intro hzero
      have hmap := congrArg (fun Q : CircularPolynomial K ↦ Q.coeff a)
        (map_polynomialOverCoefficientRing P)
      rw [circularMap_coeff, hzero, Polynomial.map_zero] at hmap
      exact (Finsupp.mem_support_iff.mp ha) hmap.symm
    · apply Finsupp.mem_support_iff.mpr
      intro hzero
      have hmap := congrArg (fun Q : CircularPolynomial K ↦ Q.coeff b)
        (map_polynomialOverCoefficientRing P)
      rw [circularMap_coeff, hzero, Polynomial.map_zero] at hmap
      exact (Finsupp.mem_support_iff.mp hb) hmap.symm
  exact
    (not_supportStraddlesZero_of_pureMoments_finiteType PA hvanA) hconvA

end GMC2
