#!/usr/bin/env python3
"""Exact terminal residue cover for the F2 (75,125) principal block.

The normalized terminal block is

    P = X^4*y*(1+s),
    Q = -X*(1+3*s+9/5*s^2),
    s = X^17*y^5.

This checker proves:
* [P,Q] = X^4;
* the function field extension is generated by s and has degree six;
* the terminal source ray has pole orders (3,5);
* after the target (5,2) toroidal extraction, the residue map is the
  degree-six Belyi map
      h(s)=125*s*(s+1)^5/(9*s^2+15*s+5)^3;
* its branch passport is (5,1), (3,3), (3,1,1,1);
* every compatible transitive branch-cycle triple generates A6;
* the natural degree-six monodromy action is primitive, so the residue
  cover has no nontrivial intermediate rational cover;
* that action is four-transitive and has trivial centralizer, so the
  target-fixed deck group is trivial;
* over Q(r) the defining polynomial has discriminant squareclass five,
  giving arithmetic monodromy S6 while geometric monodromy remains A6;
* after rescaling the third branch value to one, the cover is a Belyi map
  with regular A6 closure of triangle signature (5,3,3) and genus 25;
* the two target toric nodes have three interior source preimages, fixing
  three attachment points in any resolved boundary realization;
* the transverse different contribution is zero and the residue map is
  independent of the cofactor parameters;
* the one- and two-packet degree contributions are six and twelve.
"""
from __future__ import annotations

from itertools import permutations

import sympy as sp


def compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
    """Return p after q."""
    return tuple(p[q[index]] for index in range(len(p)))


def inverse(p: tuple[int, ...]) -> tuple[int, ...]:
    result = [0] * len(p)
    for index, image in enumerate(p):
        result[image] = index
    return tuple(result)


def cycle_type(p: tuple[int, ...]) -> tuple[int, ...]:
    seen = [False] * len(p)
    lengths: list[int] = []
    for start in range(len(p)):
        if seen[start]:
            continue
        point = start
        length = 0
        while not seen[point]:
            seen[point] = True
            point = p[point]
            length += 1
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


def parity(p: tuple[int, ...]) -> int:
    return sum(
        p[left] > p[right]
        for left in range(len(p))
        for right in range(left + 1, len(p))
    ) % 2


def generated_group(
    generators: tuple[tuple[int, ...], ...],
) -> set[tuple[int, ...]]:
    identity = tuple(range(len(generators[0])))
    moves = (*generators, *(inverse(generator) for generator in generators))
    group = {identity}
    frontier = [identity]
    while frontier:
        current = frontier.pop()
        for move in moves:
            candidate = compose(move, current)
            if candidate not in group:
                group.add(candidate)
                frontier.append(candidate)
    return group


def nontrivial_blocks(
    group: set[tuple[int, ...]],
) -> list[frozenset[int]]:
    """Return nontrivial blocks containing zero in the natural action."""
    degree = len(next(iter(group)))
    blocks: list[frozenset[int]] = []
    # A block size divides the degree; for degree six only 2 and 3 occur.
    for mask in range(1 << degree):
        block = frozenset(index for index in range(degree) if mask & (1 << index))
        if 0 not in block or len(block) not in (2, 3):
            continue
        if all(
            not (image := frozenset(element[index] for index in block)) & block
            or image == block
            for element in group
        ):
            blocks.append(block)
    return blocks


def centralizer(
    group: set[tuple[int, ...]],
) -> set[tuple[int, ...]]:
    """Return the centralizer of a permutation group in its symmetric group."""
    degree = len(next(iter(group)))
    return {
        element
        for element in permutations(range(degree))
        if all(
            compose(element, member) == compose(member, element)
            for member in group
        )
    }


def is_k_transitive(
    group: set[tuple[int, ...]],
    k: int,
) -> bool:
    """Test transitivity on ordered tuples of k distinct sheets."""
    degree = len(next(iter(group)))
    seed = tuple(range(k))
    orbit = {
        tuple(element[index] for index in seed)
        for element in group
    }
    expected = 1
    for offset in range(k):
        expected *= degree - offset
    return len(orbit) == expected


def terminal_block() -> tuple[sp.Expr, sp.Expr, sp.Expr]:
    X, y = sp.symbols("X y")
    s = X**17 * y**5
    P = X**4 * y * (1 + s)
    Q = -X * (1 + 3 * s + sp.Rational(9, 5) * s**2)
    bracket = sp.factor(
        sp.diff(P, X) * sp.diff(Q, y)
        - sp.diff(P, y) * sp.diff(Q, X)
    )
    assert bracket == X**4
    return P, Q, s


def residue_map_audit() -> sp.Expr:
    P, Q, s_xy = terminal_block()
    X, y, s, p, q = sp.symbols("X y s p q")
    F = 1 + 3 * s + sp.Rational(9, 5) * s**2
    G = 1 + s
    denominator = 9 * s**2 + 15 * s + 5
    h = sp.factor(125 * s * (s + 1) ** 5 / denominator**3)

    ratio = sp.factor(
        (P**5 / (-Q) ** 3).subs(X**17 * y**5, s)
    )
    assert sp.factor(ratio - h) == 0

    # Given a root s of h(s)=p^5/(-q)^3, X and y are rationally recovered.
    X_recovered = (-q) / F
    y_recovered = p / (X_recovered**4 * G)
    reconstructed_s = sp.factor(X_recovered**17 * y_recovered**5)
    relation = sp.factor(p**5 / (-q) ** 3 - h)
    quotient = sp.factor(
        reconstructed_s - s
        - relation * F**3 / G**5
    )
    assert quotient == 0

    numerator, map_denominator = map(sp.Poly, sp.fraction(h))
    assert numerator.degree() == map_denominator.degree() == 6
    assert sp.gcd(numerator, map_denominator).degree() == 0

    # The toric source normal to the edge direction (17,12).
    source_ray = (12, -17)
    p_points = ((4, 3), (21, 15))
    q_points = ((1, 1), (18, 13), (35, 25))
    assert {
        a * source_ray[0] + b * source_ray[1]
        for a, b in p_points
    } == {-3}
    assert {
        a * source_ray[0] + b * source_ray[1]
        for a, b in q_points
    } == {-5}

    # At the Q-dominant target-infinity point put a=(-Q)^-1, b=P/(-Q).
    # Their source orders are (5,2), giving the primitive target ray (5,2).
    target_ray = (5, 2)
    assert sp.det(sp.Matrix([[3, 5], [1, 2]])) == 1
    assert sp.det(sp.Matrix([[5, 2], [2, 1]])) == 1
    # In the chart adjacent to (3,1), b^3/a is a transverse uniformizer,
    # while b^5/a^2 is the residue coordinate.
    assert 3 * target_ray[1] - target_ray[0] == 1
    assert 5 * target_ray[1] - 2 * target_ray[0] == 0
    transverse_index = 3 * target_ray[1] - target_ray[0]
    assert transverse_index - 1 == 0
    assert sp.factor(
        (P / (-Q)) ** 5 / ((-Q) ** -1) ** 2
        - h.subs(s, s_xy)
    ) == 0

    print("F2_TERMINAL_BRACKET_PASS")
    print("F2_TERMINAL_FUNCTION_FIELD_DEGREE=6")
    print("F2_SOURCE_TERMINAL_RAY=(12,-17)")
    print("F2_TARGET_EXTRACTION_RAY=(5,2)")
    print("F2_TARGET_TRANSVERSE_INDEX=1")
    print("F2_TERMINAL_TRANSVERSE_DIFFERENT=0")
    print("F2_TERMINAL_RESIDUE_DEGREE=6")
    assert h.free_symbols == {s}
    print("F2_TERMINAL_RESIDUE_PARAMETER_FREE_PASS")
    return h


def branch_passport_audit(h: sp.Expr) -> None:
    s = sp.symbols("s")
    numerator, denominator = map(sp.Poly, sp.fraction(h))
    assert sp.factor(numerator.as_expr()) == 125 * s * (s + 1) ** 5
    assert sp.factor(denominator.as_expr()) == (9 * s**2 + 15 * s + 5) ** 3
    assert sp.discriminant(9 * s**2 + 15 * s + 5, s) == 45

    derivative = sp.factor(sp.diff(h, s))
    assert derivative == (
        625 * (s + 1) ** 4
        / (9 * s**2 + 15 * s + 5) ** 4
    )

    third_value = sp.Rational(125, 729)
    finite_third_fiber = sp.factor(
        729 * numerator.as_expr() - 125 * denominator.as_expr()
    )
    assert sp.expand(
        finite_third_fiber
        + 125 * (135 * s**3 + 405 * s**2 + 396 * s + 125)
    ) == 0
    assert sp.discriminant(
        135 * s**3 + 405 * s**2 + 396 * s + 125,
        s,
    ) == -98415

    r = sp.symbols("r")
    infinity_expansion = sp.factor(
        sp.together(h.subs(s, 1 / r) - third_value)
    )
    infinity_numerator = sp.Poly(
        sp.fraction(infinity_expansion)[0],
        r,
    )
    assert min(
        exponent[0]
        for exponent, coefficient in infinity_numerator.terms()
        if coefficient
    ) == 3

    # Total different: 4 + 2+2 + 2 = 10 = 2*6-2.
    different_packet = (4, 2, 2, 2)
    assert sum(different_packet) == 10
    belyi_map = sp.factor(sp.Rational(729, 125) * h)
    assert sp.limit(belyi_map, s, 0) == 0
    assert sp.limit(belyi_map, s, sp.oo) == 1
    assert sp.factor(belyi_map.subs(s, -1)) == 0
    # The source toric endpoints are s=0,infinity.  The target toric
    # endpoints are h=0,infinity.  Besides s=0, their inverse images are the
    # interior point s=-1 and the two distinct roots of the denominator.
    interior_target_node_preimages = 1 + sp.degree(
        9 * s**2 + 15 * s + 5,
        s,
    )
    assert interior_target_node_preimages == 3

    print("F2_TERMINAL_BRANCH_VALUES=0,infinity,125/729")
    print("F2_TERMINAL_BRANCH_PASSPORT=(5,1)|(3,3)|(3,1,1,1)")
    print("F2_TERMINAL_RESIDUE_DIFFERENT_PACKET=(4,2,2,2)")
    print("F2_TERMINAL_BELYI_BRANCH_VALUES=0,infinity,1")
    print("F2_TERMINAL_SOURCE_ENDPOINT_IMAGES=0,125/729")
    print("F2_TERMINAL_INTERIOR_PREIMAGES_OF_TARGET_NODES=3")
    print("F2_TERMINAL_RIEMANN_HURWITZ_PASS")


def monodromy_audit() -> None:
    sigma_zero = (1, 2, 3, 4, 0, 5)
    assert cycle_type(sigma_zero) == (5, 1)

    compatible = []
    for sigma_infinity in permutations(range(6)):
        if cycle_type(sigma_infinity) != (3, 3):
            continue
        sigma_third = inverse(compose(sigma_zero, sigma_infinity))
        if cycle_type(sigma_third) != (3, 1, 1, 1):
            continue
        group = generated_group((sigma_zero, sigma_infinity))
        if len(group) == 360:
            compatible.append((sigma_infinity, sigma_third, group))

    # With the five-cycle fixed, the five compatible triples form one
    # centralizer orbit. Every compatible transitive passport triple is A6.
    assert len(compatible) == 5
    for sigma_infinity, sigma_third, group in compatible:
        assert compose(
            compose(sigma_zero, sigma_infinity),
            sigma_third,
        ) == tuple(range(6))
        assert len(group) == 360
        assert all(parity(element) == 0 for element in group)
        assert nontrivial_blocks(group) == []
        assert centralizer(group) == {tuple(range(6))}
        assert all(is_k_transitive(group, k) for k in range(1, 5))
        assert not is_k_transitive(group, 5)

    print("F2_TERMINAL_BRANCH_CYCLE_TRIPLES=5")
    print("F2_TERMINAL_MONODROMY=A6")
    print("F2_TERMINAL_MONODROMY_PRIMITIVE_PASS")
    print("F2_TERMINAL_MONODROMY_4_TRANSITIVE_PASS")
    print("F2_TERMINAL_DECK_GROUP=trivial")
    print("F2_TERMINAL_COVER_INDECOMPOSABLE_PASS")
    print("F2_TERMINAL_GLOBAL_MERIDIAN_PASS")


def galois_closure_audit() -> None:
    group_order = 360
    orbifold_degree = (
        -2
        + (1 - sp.Rational(1, 5))
        + (1 - sp.Rational(1, 3))
        + (1 - sp.Rational(1, 3))
    )
    assert orbifold_degree == sp.Rational(2, 15)
    two_genus_minus_two = group_order * orbifold_degree
    assert two_genus_minus_two == 48
    genus = (two_genus_minus_two + 2) // 2
    assert genus == 25
    print("F2_TERMINAL_GALOIS_TRIANGLE_SIGNATURE=(5,3,3)")
    print("F2_TERMINAL_GEOMETRIC_GALOIS_CLOSURE_GENUS=25")


def arithmetic_monodromy_audit() -> None:
    s, r = sp.symbols("s r")
    relation = (
        125 * s * (s + 1) ** 5
        - r * (9 * s**2 + 15 * s + 5) ** 3
    )
    discriminant = sp.factor(sp.discriminant(relation, s))
    expected = 5**17 * r**4 * (729 * r - 125) ** 2
    assert discriminant == expected
    square_factor = 5**8 * r**2 * (729 * r - 125)
    assert sp.factor(discriminant - 5 * square_factor**2) == 0
    assert sp.sqrt(5).is_rational is False

    # Geometric A6 is already checked above.  Its only overgroup in S6 is
    # S6, and the nonsquare discriminant supplies an odd arithmetic element.
    print("F2_TERMINAL_DISCRIMINANT=5^17*r^4*(729*r-125)^2")
    print("F2_TERMINAL_GEOMETRIC_MONODROMY=A6")
    print("F2_TERMINAL_ARITHMETIC_MONODROMY_QR=S6")
    print("F2_TERMINAL_ARITHMETIC_CONSTANT_FIELD=Q(sqrt(5))")


def global_degree_ledger_audit() -> None:
    transverse_index = 1
    residue_degree = 6
    target_orders = (-3, -5)
    packet_degree = transverse_index * residue_degree
    assert all(order < 0 for order in target_orders)
    assert packet_degree == 6
    assert 2 * packet_degree == 12

    print("F2_TERMINAL_GLOBAL_DEGREE_FLOOR=6")
    print("F2_TERMINAL_SAME_TARGET_DOUBLE_DEGREE_FLOOR=12")
    print("F2_TERMINAL_TARGET_CENTER=boundary_at_infinity")
    print("F2_TERMINAL_AFFINE_SHEET_INCREMENT=not_applicable")


def main() -> None:
    h = residue_map_audit()
    branch_passport_audit(h)
    monodromy_audit()
    galois_closure_audit()
    arithmetic_monodromy_audit()
    global_degree_ledger_audit()
    print("F2_TERMINAL_RESIDUE_COVER_PASS")


if __name__ == "__main__":
    main()
