#!/usr/bin/env sage -python
import json
from pathlib import Path
from sage.all import IntegralLattice, QQ, ZZ, lcm, matrix, pari, vector

ROOT=Path(__file__).resolve().parents[2]
SCOUT=ROOT/"artifacts/local/elkies-k3/route-scout"
FRAME=SCOUT/"q32-d12-mw5-root-adapted-frame.txt"
if not FRAME.exists():
    raise SystemExit(f"missing {FRAME}")

G=matrix(ZZ,[
    [ZZ(v) for v in line.split()]
    for line in FRAME.read_text().splitlines()
    if line.strip() and not line.lstrip().startswith("#")
])
assert G.dimensions()==(17,17) and G.det()==948

root=G[:12,:12]
coupling=G[:12,12:]
tail=G[12:,12:]
H=tail-coupling.transpose()*root.inverse()*coupling
assert H.dimensions()==(5,5)

print("Q32D12MW_GRAM|"+",".join(
    ";".join(str(v) for v in row) for row in H.rows()
),flush=True)
print(
    f"Q32D12MW_DET|root_det={root.det()}|mw_det={H.det()}|"
    f"ns_det={G.det()}|status=PASS",
    flush=True,
)

def class_order(dual):
    o=ZZ(1)
    for x in dual:
        o=lcm(o,ZZ(QQ(x).denominator()))
    return o

# D12 discr group: vector class correction 1; spinor classes correction 3.
def correction_for(z):
    z=vector(ZZ,z)
    base=vector(ZZ,[0]*12+list(z))
    pair=vector(QQ,base*G[:,:12])
    dual=pair*root.inverse()
    order=class_order(dual)
    raw=QQ(dual*root*dual)
    def mod2(x):
        x=QQ(x)
        return x-2*(x/2).floor()
    candidates=[QQ(0),QQ(1),QQ(3)]
    corr=[c for c in candidates if mod2(c)==mod2(raw)]
    if order==1:
        return QQ(0),order
    # Distinguish vector vs spinor by order when possible; for D12 all
    # nontrivial classes have order 2, so use the quadratic value mod 2 and
    # choose the correction yielding integral P.O.
    h=QQ(z*H*z)
    valid=[]
    for c in corr:
        po=(h+c-4)/2
        if po in ZZ and po>=0:
            valid.append((c,po))
    if not valid:
        return None,order
    valid.sort(key=lambda t:t[1])
    return valid[0][0],order

# Enumerate MW vectors up through height 12; this is tiny in rank 5.
scale=ZZ(1)
for v in H.list():
    scale=lcm(scale,ZZ(QQ(v).denominator()))
IH=(scale*H).change_ring(ZZ)
bound=ZZ(scale*12)
qf=pari(IH).qfminim(bound)
cols=matrix(ZZ,qf[2]).columns()

rows=[]
seen=set()
for col in cols:
    for sign in (1,-1):
        z=sign*vector(ZZ,col)
        key=tuple(z)
        if key in seen:
            continue
        seen.add(key)
        h=QQ(z*H*z)
        if h>12:
            continue
        corr,order=correction_for(z)
        if corr is None:
            continue
        po=(h+corr-4)/2
        if po not in ZZ or po<0:
            continue
        rows.append((ZZ(po),h,corr,order,z))

rows.sort(key=lambda t:(t[0],t[1],sum(abs(int(x)) for x in t[4]),tuple(t[4])))

counts={}
for po,h,c,o,z in rows:
    counts[int(po)]=counts.get(int(po),0)+1

print(
    "Q32D12MW_POLE_COUNTS|"
    + "|".join(f"PdotO={k}:count={v}" for k,v in sorted(counts.items()))
    + "|status=PASS",
    flush=True,
)

for i,(po,h,c,o,z) in enumerate(rows[:40]):
    print(
        "Q32D12MW_SECTION|"
        f"rank={i}|PdotO={po}|height={h}|correction={c}|"
        f"class_order={o}|mw={','.join(map(str,z))}|"
        f"L1={sum(abs(int(x)) for x in z)}|status=PASS",
        flush=True,
    )

# Find maximum independent rank generated by P.O=0 classes.
zero=[z for po,h,c,o,z in rows if po==0]
rank0=matrix(ZZ,[list(z) for z in zero]).rank() if zero else 0
print(
    "Q32D12MW_ZEROPOLE|"
    f"count={len(zero)}|span_rank={rank0}|"
    f"status={'PROMISING' if rank0>=2 else 'LIMITED'}",
    flush=True,
)

out=SCOUT/"q32-d12-mw5-section-profile.json"
out.write_text(json.dumps({
    "schema":"elkies-k3.h3-q32-d12-mw5-section-profile.v1",
    "status":"PASS_Q32_D12_MW5_SECTION_PROFILE",
    "height_gram":[[str(v) for v in row] for row in H.rows()],
    "height_det":str(H.det()),
    "zero_pole_count":len(zero),
    "zero_pole_span_rank":int(rank0),
    "sections":[
        {
            "P_dot_O":int(po),
            "height":str(h),
            "correction":str(c),
            "class_order":int(o),
            "mw":list(map(int,z)),
        }
        for po,h,c,o,z in rows
    ],
},indent=2,sort_keys=True)+"\n")
print(f"OUTPUT|{out}",flush=True)
