#!/usr/bin/env sage-python
"""Bounded exact NS0031 group/model replay and retained Magma proof audit.

Does not search K3 equations or rational parameters, rebuild old catalogues,
or contact a remote service.  The separate .m file replays the global descent.
Written normalizer, canonical-model and CM theorem inputs are in the note.
"""
from sage.all import (QQ, ZZ, matrix, vector, identity_matrix, Gamma0,
                      ModularSymbols, EllipticCurve, PolynomialRing,
                      PowerSeriesRing)
from sage.env import SAGE_VERSION
from pathlib import Path
from itertools import product
import argparse
import hashlib
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
PACKET = ROOT/'artifacts/generated-results/elkies-k3-ns0031-stable-marking-v1'
MAGMA = ROOT/'elkies-k3/scripts/certify_ns0031_genus2_rational_points.m'
OUTPUT = PACKET/'certificate.json'


def require(test, message):
    if not test:
        raise ArithmeticError(message)


def rows(m):
    return [[int(x) if x in ZZ else str(x) for x in row] for row in m.rows()]


def digest(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def build():
    g = matrix(QQ, [[0,0,4],[0,74,1],[4,1,-2]])
    gi = g.inverse()
    change = matrix(QQ, [[QQ(1)/4,-QQ(1)/4,QQ(1)/4],[0,1,0],[0,0,1]])
    g0 = change.transpose()*g*change
    require(g0 == matrix(QQ, [[0,0,1],[0,74,0],[1,0,0]]), 'overlattice')
    require(list(matrix(ZZ,g).elementary_divisors()) == [1,1,1184], 'cyclic discriminant')
    images = [matrix(QQ, [[0,8],[0,0]]), matrix(QQ, [[-74,2],[0,74]]),
              matrix(QQ, [[0,-2],[74,0]])]
    ambient = matrix(QQ, [b.list() for b in images]).transpose()

    def adj(a):
        return matrix(QQ, [ambient.solve_right(vector(QQ,(a*b*a.inverse()).list()))
                           for b in images]).transpose()

    def integral(m):
        return all(x in ZZ for x in m.list())

    def integral2(m):
        return all(x.denominator() % 2 for x in m.list())

    def discr(m):
        require(integral(m), 'nonintegral isometry')
        u = gi.column(0)
        multiplier = int((1184*(m*u)[0]) * ZZ(149).inverse_mod(1184) % 1184)
        require(all(x in ZZ for x in m*u-multiplier*u), 'discriminant generator')
        return multiplier

    # Gamma(4) projectively intersect Gamma_0(37) is conjugate to Gamma_0(592).
    # Sage's exact Farey-symbol generators provide a finite generating set.
    d = matrix(QQ, [[QQ(1)/4,0],[0,1]])
    kernel_generators = []
    for h in Gamma0(592).gens():
        h = matrix(QQ,2,2,list(h))
        a = d.inverse()*h*d
        m = adj(a)
        require(integral(m) and m.transpose()*g*m == g and discr(m) == 1,
                'principal-kernel generator is not stable')
        kernel_generators.append(rows(a))

    # Exhaust all 48 residues using lifts in Gamma_0(37). The proved stable
    # principal kernel makes the result independent of the chosen lift.
    slift = matrix(QQ, [[28,3],[37,4]])
    tlift = matrix(QQ, [[1,1],[0,1]])
    residue = lambda a: tuple(int(x % 4) for x in a.list())
    lifts = {residue(identity_matrix(QQ,2)): identity_matrix(QQ,2)}
    todo = list(lifts.values())
    while todo:
        a = todo.pop()
        for b in [slift,tlift]:
            c = a*b
            if residue(c) not in lifts:
                lifts[residue(c)] = c
                todo.append(c)
    require(len(lifts) == 48, 'SL2 mod 4 exhaustion')
    cartan = {((a+b)%4,b,b,a) for a,b in product(range(4),repeat=2)
              if ((a+b)*a-b*b)%2}
    norm_one_rows = []
    for key,a in sorted(lifts.items()):
        m = adj(a)
        if integral(m):
            k = discr(m)
            require(k == (1 if key in cartan else 223), 'normalizer discriminant sign')
            norm_one_rows.append({'residue':list(key),'lift':rows(a),'discriminant_multiplier':k})
    require(len(nom := norm_one_rows) == 12 and sum(x['discriminant_multiplier']==1 for x in nom)==6,
            'Cartan/normalizer sizes')
    r = matrix(QQ, [[10,-3],[37,-11]])
    w = matrix(QQ, [[0,-1],[37,0]])
    require(r**3 == 1 and discr(adj(r)) == 1, 'Cartan generator')
    require(discr(adj(w)) == 1183 and integral((-adj(w)-1)*gi), 'stable minus reflection')
    require(-adj(w) == matrix(QQ, [[1,0,0],[0,1,0],[4,1,-1]]), 'retained reflection')

    # Arithmetic descent: include all determinant units, not only norm one.
    # The principal GL2(Z_2) level-4 kernel is topologically generated by
    # these elementary matrices and the two diagonal 1+4 generators.
    local_kernel = [matrix(QQ,aa) for aa in [
        [[1,4],[0,1]], [[1,0],[148,1]], [[5,0],[0,1]], [[1,0],[0,5]]]]
    require(all(integral2((adj(a)-1)*gi) for a in local_kernel), 'local principal kernel')
    arithmetic_rows = []
    for aa,b,c,dd in product(range(4),repeat=4):
        if (aa*dd-b*c)%2 == 0:
            continue
        a = matrix(QQ, [[aa,b],[37*c,dd]])
        m = adj(a)
        if integral2(m):
            plus,minus = integral2((m-1)*gi),integral2((m+1)*gi)
            key = (aa,b,c,dd)
            require(plus != minus and plus == (key in cartan), 'arithmetic Cartan descent')
            arithmetic_rows.append({'residue':list(key),'discriminant_sign':1 if plus else -1})
    require(len(arithmetic_rows)==24 and sum(x['discriminant_sign']==1 for x in arithmetic_rows)==12,
            'GL2 arithmetic normalizer exhaustion')

    def quotient_symbols(n, rr):
        m = ModularSymbols(n,2,sign=0)
        cusp = m.cuspidal_submodule().free_module()
        a = m._action_on_modular_symbols(rr)
        b = m.atkin_lehner_operator().matrix()
        require(a**3 == 1 and b**2 == 1 and b*a*b == a**2, 'S3 quotient relations')
        c3 = cusp.intersection((a-1).left_kernel())
        s3 = c3.intersection((b-1).left_kernel())
        return m,s3,{'cover_genus':int(cusp.dimension()/2),
                     'order_three_quotient_genus':int(c3.dimension()/2),
                     'full_quotient_genus':int(s3.dimension()/2),
                     'fricke_trace_on_c3_h1':str(b.restrict(c3).trace())}

    _,_,genus4 = quotient_symbols(592,[40,-3,592,-44])
    m2,v2,genus2 = quotient_symbols(148,[20,-3,148,-22])
    require(genus4['order_three_quotient_genus']==23 and genus4['full_quotient_genus']==10,
            'full stable genus')
    require(genus2['order_three_quotient_genus']==5 and genus2['full_quotient_genus']==2,
            'level-two quotient genus')

    # Certify the two invariant differentials, including which degeneracy
    # lift of the level-37 form occurs.  In homology, pullback is dual to
    # the level-lowering map; T_3-1 kills the other level-37 cusp form.
    m37 = ModularSymbols(37,2,sign=0)
    c37 = m37.cuspidal_submodule().free_module()
    require(m37.hecke_matrix(3).restrict(c37).charpoly() ==
            (PolynomialRing(QQ,'x').gen()+3)**2*(PolynomialRing(QQ,'x').gen()-1)**2,
            'level-37 eigenspaces')
    lower = m2.degeneracy_map(m37,2).matrix()*(m37.hecke_matrix(3)-1)
    a2 = m2._action_on_modular_symbols([20,-3,148,-22])
    b2 = m2.atkin_lehner_operator().matrix()
    cb = m2.cuspidal_submodule().free_module().basis_matrix()
    require((cb*(a2-1)*lower).is_zero() and (cb*(b2-1)*lower).is_zero(),
            'f_37(q^2) does not descend')
    new148 = m2.cuspidal_submodule().new_submodule().free_module()
    new148 = new148.intersection((m2.hecke_matrix(3)+1).left_kernel())
    require(new148.dimension()==2 and all(z*a2==z and z*b2==z for z in new148.basis()),
            'level-148 newform does not descend')

    # Prove the genus-two equation as a weight-12 modular-form identity.
    e37,e148 = EllipticCurve([0,0,1,-1,0]),EllipticCurve([0,-1,0,-5,1])
    require(e37.conductor()==37 and e148.conductor()==148, 'eigenform conductors')
    require(e37.ap(3)==-3 and e148.ap(3)==-1, 'eigenform identification')
    ps = PowerSeriesRing(QQ,'q',default_prec=300)
    q = ps.gen()
    f = ps(e37.q_eigenform(300)(q*q))
    h = ps(e148.q_eigenform(300))
    bracket = q*(h.derivative()*f-h*f.derivative())
    relation = bracket**2-h**6+4*h**4*f**2-4*f**6
    sturm = int(Gamma0(148).index())  # weight 12
    require(sturm==228 and relation.valuation()>sturm, 'Sturm identity not proved')
    fraction = ps.fraction_field()
    uu = fraction(h)/fraction(f)
    vv = q*uu.derivative()/fraction(f)

    ring = PolynomialRing(QQ,names=('u','v'))
    u,v = ring.gens()
    curve = v*v-u**6+4*u**4-4
    ideal = ring.ideal(curve)
    xx = (u**4-2*u*u-u*v)/2
    yy = (u**6-3*u**4-u**3*v+u*v)/2
    require(ideal.reduce(yy*yy+yy-xx**3+xx)==0, 'elliptic quotient equation')
    require(ideal.reduce(2*v*xx.derivative(u)+(6*u**5-16*u**3)*xx.derivative(v)+4*(2*yy+1))==0,
            'elliptic quotient differential')
    xq = (uu**4-2*uu**2-uu*vv)/2
    require(xq[-4]==1 and xq[-2]==2 and xq[0]==5 and xq[2]==9,
            'cusp/translation normalization')
    point_rows = []
    p = e37(0,0)
    cm = {1:-11,3:-3,-1:-7,-4:-27,6:-67}
    for a,b in [(0,2),(0,-2),*[(a,b) for a in [-1,1] for b in [-1,1]],
                *[(a,b) for a in [-2,2] for b in [-2,2]]]:
        require(curve(a,b)==0, 'rational point')
        image = e37(xx(a,b),yy(a,b))
        n = next(n for n in cm if n*p==image)
        point_rows.append({'point':[a,b],'image':[str(image[0]),str(image[1])],
                           'multiple_of_P':n,'CM_discriminant':cm[n]})
    point_rows += [{'point':'infinity_minus','image':'O','type':'cusp'},
                   {'point':'infinity_plus','image':['1','0'],'multiple_of_P':2,'CM_discriminant':-4}]
    require(2*p==e37(1,0) and len(point_rows)==12, 'boundary points')

    # Audit a separately retained exact Magma proof, including its status
    # booleans and index obligations. This is not a rerun of Magma.
    raw = PACKET/'magma-output.xml'
    receipt = json.loads((PACKET/'magma-replay.json').read_text())
    require(receipt['input_sha256']==digest(MAGMA) and receipt['output_sha256']==digest(raw),
            'Magma proof provenance')
    output = '\n'.join(ET.fromstring(raw.read_bytes()).itertext())
    require(not re.search(r'runtime error|user error|assertion failed|an error occurred|time limit|timed out',output,re.I),
            'Magma reported failure')
    for tag in ['BASE_MW_Z_GENERATED_BY_0_0_PROVED','CUBIC_FIELD_AND_CLASS_GROUP_PROVED',
                'PASS_NS0031_GENUS2_RATIONAL_POINTS_EXACT_12']:
        require(tag in output, 'missing global proof endpoint: '+tag)
    for i in [0,1]:
        require(f'CASE {i} RANK_BOUNDS 1 1 FULL_MW_GROUP_PROVED true' in output,
                'unproved full MW group')
        require(re.search(rf'CASE {i} CHABAUTY_EXACT_BOUND 6 INDEX_CONDITION \d+ RESIDUAL_COSETS_EMPTY true',output),
                'incomplete Chabauty bound')
        require(f'CASE {i} PASS' in output, 'missing descent case')

    return {
        'schema':'elkies-k3.ns0031-stable-marking.v1',
        'status':'PASS_CORRECTED_FULL_STABLE_ARITHMETIC_OBSTRUCTION',
        'date':'2026-09-14','surface_id':'K3-d1b1381f87d69f1c','ns_id':'NS0031',
        'literal_gram':rows(g),'discriminant_group':[1184],
        'overlattice':{'basis_in_T':rows(change),'gram':rows(g0),'index':4,
                      'T_condition':'e-h+f = 0 mod 4'},
        'stable_group':{'norm_one':'Gamma_ns(4) intersect Gamma_0(37)',
                        'projective_group':'Gamma union W_37 Gamma',
                        'W_37':rows(w),'stable_reflection':rows(-adj(w)),
                        'cartan_generator':rows(r),'principal_kernel_generators':kernel_generators,
                        'SL2_mod4_order':48,'normalizer_residues':norm_one_rows,
                        'full_genus':10,'genus_calculation':genus4},
        'arithmetic_model':{'label':'(X_ns(4) x_X(1) X_0(37)) / <w_37 w_ns,4>',
                            'local_GL2_mod4_order':96,'local_normalizer':arithmetic_rows,
                            'local_principal_kernel_generators':[rows(a) for a in local_kernel],
                            'field':'Q','determinant_units_included':True},
        'genus_two_quotient':{'degree_from_full_curve':4,'model':'v^2 = u^6 - 4*u^4 + 4',
                              'rational_point_count':12,'points':point_rows,
                              'genus_calculation':genus2,'weight_12_sturm_bound':sturm,
                              'q_precision':300,'u_qexp':str(uu.add_bigoh(8)),
                              'v_qexp':str(vv.add_bigoh(8)),
                              'map_to_X0_37_plus':[str(xx),str(yy)]},
        'rational_non_CM_locus':'EMPTY',
        'rational_NS0031_rank19_marking':'EXCLUDED',
        'software':{'SageMath':SAGE_VERSION,'Magma':receipt['magma_version']},
        'inputs':{str(MAGMA.relative_to(ROOT)):digest(MAGMA),
                  str(raw.relative_to(ROOT)):digest(raw),
                  str((PACKET/'magma-replay.json').relative_to(ROOT)):digest(PACKET/'magma-replay.json')},
        'proof_boundary':'Exact group and modular-form computations plus a retained unconditional Magma elliptic-Chabauty proof. Normalizer completeness, arithmetic period descent, and the CM coordinate identification use the named written theorem inputs. No equation search, claim about rational CM lifts, independent replay, or formal verification.'}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check',action='store_true')
    args = ap.parse_args()
    data = build()
    encoded = json.dumps(data,indent=2,sort_keys=True)+'\n'
    if args.check:
        require(OUTPUT.read_text()==encoded,'stale NS0031 certificate')
        print('PASS full NS0031 stable group, genus-10 Q curve, genus-2 quotient and retained global obstruction.')
    else:
        OUTPUT.parent.mkdir(parents=True,exist_ok=True)
        OUTPUT.write_text(encoded)
        print('WROTE',OUTPUT)


if __name__ == '__main__':
    main()
