#!/usr/bin/env sage
"""Build the saturated fourth-q12 module and its semistable local arcs.

On the exact CM24 third-child model the fourth horizontal point is
``Q=-P1-3P2-P3`` with denominator ``h^2,h^3`` and ``Q.O=2``.  The naive
chord has vertical poles at the roots of h.  This script constructs the
compensated global generator

    w = z_Q + k/h,

where ``k = Ny/Nx mod h``.  That compensation alone is not the complete
global module: the relative module generated by ``{1,x,h*z_Q}`` must be
Smith saturated at every finite prime and shifted-Popov reduced at infinity.
At the pinned prime this produces ten sections of ``L(Q+2O+3F)`` before the
vertical correction is imposed.

For each split multiplicative fiber it also builds exact formal arcs on every
nonidentity component.  If alpha is the formal critical point of the cubic,
put ``X=x-alpha`` and solve

    u = y-X*sqrt(3*alpha+X),
    v = y+X*sqrt(3*alpha+X),
    u*v = C(t).

The component-j arc is ``u=lambda*t^j``, ``v=C/u``.  The saturated global
generators are evaluated on these arcs, and the correction-cycle valuations
give the remaining linear vertical gates.  A two-dimensional kernel is only
accepted after this saturation; the old raw six-column chord calculation is
not a certificate.
"""

import argparse

from sage.all import (
    GF,
    Matrix,
    PolynomialRing,
    PowerSeriesRing,
)


# Use the prime-field implementation consistently in the exact local and
# global-function-field calculations.
finite = GF(73, impl="modn")
polynomial_ring = PolynomialRing(finite, "V")
V = polynomial_ring.gen()
local_finite = GF(73**2, "q")
lambda_ring = PolynomialRing(finite, "lam")
lambda_field = lambda_ring.fraction_field()
extension_lambda_ring = PolynomialRing(local_finite, "lam")
extension_lambda_field = extension_lambda_ring.fraction_field()

parser = argparse.ArgumentParser()
parser.add_argument("--candidate", type=int, choices=(1, 2, 3, 4), default=1)
parser.add_argument("--module-only", action="store_true")
parser.add_argument("--genus-gate", action="store_true")
parser.add_argument("--generic-only", action="store_true")
parser.add_argument("--scan-degenerations", action="store_true")
parser.add_argument("--write-artifact", action="store_true")
parser.add_argument("--selected-i2", type=int, choices=(5, 43, 56), default=5)
arguments = parser.parse_args()

A = (
    6*V**8 + 16*V**7 + 47*V**6 + 33*V**5 + 58*V**4
    + 2*V**3 + 63*V**2 + 17*V + 23
)
B = (
    33*V**12 + 64*V**10 + 61*V**9 + 45*V**8 + 14*V**7
    + 20*V**6 + 54*V**5 + 8*V**4 + 50*V**3 + 57*V**2
    + 47*V + 43
)
horizontal_data = {
    1: (
        (53, 60, 1),
        (38, 69, 69, 7, 45, 4, 4, 3, 70),
        (50, 62, 5, 24, 56, 68, 27, 62, 46, 38, 56, 40, 34),
    ),
    2: (
        (40, 10, 1),
        (6, 49, 40, 68, 42, 4, 67, 51, 57),
        (38, 66, 37, 31, 16, 57, 7, 30, 32, 46, 62, 2, 32),
    ),
    3: (
        (53, 60, 1),
        (38, 69, 69, 7, 45, 4, 4, 3, 70),
        (23, 11, 68, 49, 17, 5, 46, 11, 27, 35, 17, 33, 39),
    ),
    4: (
        (40, 10, 1),
        (6, 49, 40, 68, 42, 4, 67, 51, 57),
        (35, 7, 36, 42, 57, 16, 66, 43, 41, 27, 11, 71, 41),
    ),
}
h_coefficients, nx_coefficients, ny_coefficients = horizontal_data[
    arguments.candidate
]
h = polynomial_ring(h_coefficients)
Nx = polynomial_ring(nx_coefficients)
Ny = polynomial_ring(ny_coefficients)
assert (Ny**2 - Nx**3 - A*Nx*h**4 - B*h**6) == 0

k = (Ny.mod(h) * Nx.inverse_mod(h)).mod(h)
assert (Ny-k*Nx) % h == 0
w_constant = (Ny-k*Nx)//h
w_x = k*h
w_y = h**2
# w=(w_constant+w_x*x+w_y*y)/(h^2*x-Nx).
assert max(
    w_constant.degree(), w_x.degree()+4, w_y.degree()+6
) - max((h**2).degree()+4, Nx.degree()) == 2

# Saturate the complete relative module, not just the h-primary chord.
# With common denominator D0=h^2*x-Nx, the columns {1,x,hz} in numerator
# rows [1,x,x^2,x^3,y,xy] are the following 6x3 matrix.  Smith saturation
# automatically adds every missing finite-prime generator.
module_matrix = Matrix(
    polynomial_ring,
    (
        (-Nx, 0, Ny),
        (h**2, -Nx, 0),
        (0, h**2, 0),
        (0, 0, 0),
        (0, 0, h**3),
        (0, 0, 0),
    ),
)
smith, smith_left, smith_right = module_matrix.smith_form()
assert smith == smith_left*module_matrix*smith_right
assert smith_left.is_invertible() and smith_right.is_invertible()
smith_degrees = tuple(smith[index, index].degree() for index in range(3))
saturated_module = smith_left.inverse()[:, :3]

row_weights = (0, 4, 8, 12, 6, 10)


def column_pivot(column):
    candidates = tuple(
        (entry.degree()+row_weights[row], row)
        for row, entry in enumerate(column)
        if entry
    )
    assert candidates
    return max(candidates)


def shifted_weak_popov(basis):
    basis = Matrix(polynomial_ring, basis)
    column_count = basis.ncols()
    while True:
        pivots = tuple(
            column_pivot(basis.column(index)) for index in range(column_count)
        )
        collision = None
        for left_index in range(column_count):
            for right_index in range(left_index+1, column_count):
                if pivots[left_index][1] == pivots[right_index][1]:
                    collision = (left_index, right_index)
                    break
            if collision is not None:
                break
        if collision is None:
            return basis
        first, second = collision
        if pivots[first][0] > pivots[second][0]:
            first, second = second, first
        pivot_row = pivots[first][1]
        reducer = basis[pivot_row, first]
        target = basis[pivot_row, second]
        degree_delta = target.degree()-reducer.degree()
        factor = target.leading_coefficient()/reducer.leading_coefficient()
        basis.set_column(
            second,
            basis.column(second)-factor*V**degree_delta*basis.column(first),
        )


popov_module = shifted_weak_popov(saturated_module)
popov_pivots = tuple(
    column_pivot(popov_module.column(index)) for index in range(3)
)
generator_weights = tuple(degree-8 for degree, _ in popov_pivots)
global_columns = []
global_column_labels = []
for generator, weight in enumerate(generator_weights):
    degree_bound = 3-weight
    if degree_bound < 0:
        continue
    for degree in range(degree_bound+1):
        global_columns.append(V**degree*popov_module.column(generator))
        global_column_labels.append((generator, degree))

fiber_data = (
    (finite(-20), 7, finite(41)),
    (finite(-67), 7, finite(2)),
    (finite(-17), 2, finite(11)),
    (finite(-30), 2, finite(53)),
    (finite(-68), 2, finite(51)),
)


def component_geometry_series(root, multiplicity, node, component, precision=16):
    split = finite(3*node).is_square()
    coefficient_field = lambda_field if split else extension_lambda_field
    lam = coefficient_field.gen()
    series_ring = PowerSeriesRing(coefficient_field, "e", default_prec=precision)
    e = series_ring.gen()
    base = series_ring(root) + e
    A_series = series_ring(A(base))
    B_series = series_ring(B(base))

    alpha = series_ring(node)
    for _ in range(8):
        alpha -= (3*alpha**2+A_series)/(6*alpha)
    assert (3*alpha**2+A_series).valuation() >= precision-1
    critical_value = alpha**3+A_series*alpha+B_series
    assert critical_value.valuation() == multiplicity

    slope_base = finite if split else local_finite
    slope_roots = slope_base(3*node).sqrt(all=True)
    assert len(slope_roots) == 2
    slope = series_ring(slope_roots[0])
    u = series_ring(lam)*e**component
    v = series_ring(critical_value/u)
    Z = (v-u)/2
    s = slope
    for _ in range(8):
        s -= (s**3-3*alpha*s-Z)/(3*s**2-3*alpha)
    X = Z/s
    x_arc = alpha+X
    y_arc = (u+v)/2
    curve_residual = y_arc**2-x_arc**3-A_series*x_arc-B_series
    assert curve_residual.valuation() >= precision-multiplicity-2

    denominator = h(base)**2*x_arc-Nx(base)
    return base, x_arc, y_arc, denominator


def component_basis_series(root, multiplicity, node, component, precision=16):
    base, x_arc, y_arc, denominator = component_geometry_series(
        root, multiplicity, node, component, precision=precision
    )
    numerator_basis = (
        base.parent().one(),
        x_arc,
        x_arc**2,
        x_arc**3,
        y_arc,
        x_arc*y_arc,
    )
    values = []
    for column in global_columns:
        numerator = sum(
            entry(base)*basis_value
            for entry, basis_value in zip(column, numerator_basis)
        )
        values.append(numerator/denominator)
    return tuple(values)


def component_arc(root, multiplicity, node, component, precision=24):
    basis = component_basis_series(
        root, multiplicity, node, component, precision=precision
    )
    coefficient_field = basis[0].base_ring()
    return tuple(
        (
            value.valuation(),
            value[value.valuation()] if value else coefficient_field.zero(),
        )
        for value in basis
    )


print(
    "Q80FOURTHLOCALGF73|prime=73|"
    f"candidate={arguments.candidate}|"
    f"h={h}|k={k}|w_constant={w_constant}|w_x={w_x}|w_y={w_y}|"
    f"smith_degrees={smith_degrees}|popov_pivots={popov_pivots}|"
    f"generator_weights={generator_weights}|"
    f"saturated_ambient_dimension={len(global_columns)}|"
    "status=PASS_SMITH_SATURATED_MODULE",
    flush=True,
)
if arguments.module_only:
    raise SystemExit(0)
arc_bases = {}
for root, multiplicity, node in fiber_data:
    for component in range(1, multiplicity):
        basis = component_basis_series(root, multiplicity, node, component)
        arc_bases[(int(root), component)] = basis
        coefficient_field = basis[0].base_ring()
        arc_data = tuple(
            (
                value.valuation(),
                value[value.valuation()] if value else coefficient_field.zero(),
            )
            for value in basis
        )
        print(
            f"Q80FOURTHLOCALGF73|fiber={int(root)}|I={multiplicity}|"
            f"component={component}|basis_valuation_lead={arc_data}|"
            "status=PASS_COMPONENT_ARC",
            flush=True,
        )


def rational_function_rows(values):
    """Expand one lambda-rational identity into GF(73) matrix rows."""
    rational_field = values[0].parent()
    coefficient_base = rational_field.base_ring()
    common_denominator = rational_field.one().denominator()
    for value in values:
        common_denominator = common_denominator.lcm(value.denominator())
    numerators = tuple(
        value.numerator()*(common_denominator//value.denominator())
        for value in values
    )
    maximum_degree = max(
        (numerator.degree() for numerator in numerators if numerator),
        default=-1,
    )
    rows = []
    extension_degree = coefficient_base.degree()
    assert extension_degree in (1, 2)
    for power in range(maximum_degree+1):
        coefficients = tuple(numerator[power] for numerator in numerators)
        for coordinate in range(extension_degree):
            row = []
            for coefficient in coefficients:
                if extension_degree == 1:
                    row.append(finite(coefficient))
                else:
                    row.append(finite(coefficient._vector_()[coordinate]))
            if any(row):
                rows.append(tuple(row))
    return tuple(rows)


def component_gate_rows(root, component, required_order):
    basis = arc_bases[(root, component)]
    rows = []
    for order in range(required_order):
        rows.extend(
            rational_function_rows(tuple(value[order] for value in basis))
        )
    return tuple(rows)


# The exact lattice chains determine the two I7 correction cycles up to the
# two geometric chain orientations.  Q has correction 6/7 at V=53 and 10/7
# at V=6, so the abstract endpoint chain belongs to 53 and the position-two
# chain to 6.  Of the three I2 fibers, V=56 is the identity-component fiber
# and has correction coefficient one; exactly one of V=43,5 has the other
# coefficient one.  Test these eight finite marking choices.
if arguments.candidate in (1, 3):
    i7_cycle_53 = (1, 2, 2, 2, 1, 0)
    i7_cycle_6 = (1, 1, 2, 2, 2, 1)
    identity_i2 = 56
    hit_i2 = (43, 5)
else:
    i7_cycle_53 = (1, 1, 2, 2, 2, 1)
    i7_cycle_6 = (1, 2, 2, 2, 1, 0)
    identity_i2 = 5
    hit_i2 = (56, 43)
gate_results = []
for reverse_53 in (False, True):
    cycle_53 = tuple(reversed(i7_cycle_53)) if reverse_53 else i7_cycle_53
    for reverse_6 in (False, True):
        cycle_6 = tuple(reversed(i7_cycle_6)) if reverse_6 else i7_cycle_6
        for second_fixed_i2 in hit_i2:
            cycles = {
                53: cycle_53,
                6: cycle_6,
                identity_i2: (1,),
                hit_i2[0]: (1 if second_fixed_i2 == hit_i2[0] else 0,),
                hit_i2[1]: (1 if second_fixed_i2 == hit_i2[1] else 0,),
            }
            rows = []
            for root, cycle in cycles.items():
                for component, required_order in enumerate(cycle, 1):
                    rows.extend(
                        component_gate_rows(root, component, required_order)
                    )
            gate_matrix = Matrix(finite, rows)
            gate_results.append(
                (
                    reverse_53,
                    reverse_6,
                    second_fixed_i2,
                    gate_matrix.nrows(),
                    gate_matrix.rank(),
                    gate_matrix.right_kernel().dimension(),
                    tuple(
                        tuple(map(int, row))
                        for row in gate_matrix.right_kernel().basis()
                    ),
                )
            )

for result in gate_results:
    reverse_53, reverse_6, second_fixed_i2, row_count, rank, nullity, kernel = result
    print(
        "Q80FOURTHLOCALGF73|"
        f"reverse_53={int(reverse_53)}|reverse_6={int(reverse_6)}|"
        f"second_fixed_i2={second_fixed_i2}|rows={row_count}|rank={rank}|"
        f"nullity={nullity}|kernel={kernel}|status=PASS_MARKING_GATE_RANK",
        flush=True,
    )

if arguments.genus_gate:
    from sage.interfaces.singular import singular

    surface_ring = PolynomialRing(finite, names=("v", "x", "y"))
    v_surface, x_surface, y_surface = surface_ring.gens()
    surface_equation = (
        y_surface**2-x_surface**3-A(v_surface)*x_surface-B(v_surface)
    )
    plane_ring = PolynomialRing(finite, names=("v", "x"))
    v_plane, x_plane = plane_ring.gens()
    singular.lib("normal.lib")

    def kernel_numerator(coefficients):
        numerator_column = sum(
            (
                coefficient*global_columns[index]
                for index, coefficient in enumerate(coefficients)
            ),
            popov_module.column(0).parent().zero(),
        )
        monomials = (
            surface_ring.one(),
            x_surface,
            x_surface**2,
            x_surface**3,
            y_surface,
            x_surface*y_surface,
        )
        return sum(
            entry(v_surface)*monomial
            for entry, monomial in zip(numerator_column, monomials)
        )

    genus_rows = []
    for result in gate_results:
        (
            reverse_53,
            reverse_6,
            second_fixed_i2,
            _,
            _,
            nullity,
            kernel,
        ) = result
        if nullity != 2 or second_fixed_i2 != arguments.selected_i2:
            continue
        numerator_zero = kernel_numerator(kernel[0])
        numerator_one = kernel_numerator(kernel[1])
        for new_base in (() if arguments.generic_only else (1, 7)):
            relation = numerator_one-finite(new_base)*numerator_zero
            resultant = relation.resultant(surface_equation, y_surface)
            plane_equation = plane_ring(resultant(v_plane, x_plane, 0))
            factorization = tuple(plane_equation.factor())
            factor_data = []
            for factor, exponent in factorization:
                genus = int(plane_ring.ideal(factor)._singular_().genus())
                factor_data.append(
                    (
                        factor.degree(v_plane),
                        factor.degree(x_plane),
                        int(exponent),
                        genus,
                    )
                )
            genus_rows.append(
                (
                    reverse_53,
                    reverse_6,
                    second_fixed_i2,
                    new_base,
                    tuple(factor_data),
                )
            )
            print(
                "Q80FOURTHLOCALGF73|"
                f"reverse_53={int(reverse_53)}|reverse_6={int(reverse_6)}|"
                f"second_fixed_i2={second_fixed_i2}|new_base={new_base}|"
                f"factors={tuple(factor_data)}|status=PASS_NORMALIZATION_GATE",
                flush=True,
            )
    assert arguments.generic_only or genus_rows

    # Compute the generic moving component without a multivariate function-
    # field factorization.  If N0,N1 are the two kernel numerators, then
    # eliminating y from N1-T*N0 and y^2=x^3+A*x+B gives a quadratic in T.
    # The gcd of its three T-coefficients is exactly the fixed part.
    selected_result = next(
        result
        for result in gate_results
        if result[2] == arguments.selected_i2
        and result[5] == 2
    )
    selected_kernel = selected_result[6]

    coefficient_plane = PolynomialRing(finite, names=("v0", "x0"))
    v0, x0 = coefficient_plane.gens()
    parameter_polynomials = PolynomialRing(coefficient_plane, "Tnew")
    Tnew = parameter_polynomials.gen()

    def numerator_vector(coefficients):
        return sum(
            (
                coefficient*global_columns[index]
                for index, coefficient in enumerate(coefficients)
            ),
            popov_module.column(0).parent().zero(),
        )

    def split_numerator(coefficients):
        column = numerator_vector(coefficients)
        even = sum(column[index](v0)*x0**index for index in range(4))
        odd = column[4](v0)+column[5](v0)*x0
        return even, odd

    even_zero, odd_zero = split_numerator(selected_kernel[0])
    even_one, odd_one = split_numerator(selected_kernel[1])
    even_relation = even_one-Tnew*even_zero
    odd_relation = odd_one-Tnew*odd_zero
    old_cubic = x0**3+A(v0)*x0+B(v0)
    eliminated = even_relation**2-odd_relation**2*old_cubic
    nonzero_coefficients = tuple(
        coefficient for coefficient in eliminated.list() if coefficient
    )
    fixed_factor = nonzero_coefficients[0]
    for coefficient in nonzero_coefficients[1:]:
        fixed_factor = fixed_factor.gcd(coefficient)
    moving = parameter_polynomials(
        [coefficient//fixed_factor for coefficient in eliminated.list()]
    )
    assert eliminated == fixed_factor*moving
    assert moving.degree() == 2

    parameter_base = PolynomialRing(finite, "t")
    t = parameter_base.gen()
    parameter_field = parameter_base.fraction_field()
    old_base_ring = PolynomialRing(parameter_field, "v")
    old_base = old_base_ring.gen()
    x_ring = PolynomialRing(old_base_ring, "x")
    x_generic = x_ring.gen()

    def lift_plane(polynomial):
        return sum(
            parameter_field(coefficient)
            * old_base**exponents[0]
            * x_generic**exponents[1]
            for exponents, coefficient in polynomial.dict().items()
        )

    moving_generic = sum(
        parameter_field(t)**degree*lift_plane(coefficient)
        for degree, coefficient in enumerate(moving.list())
    )
    if moving_generic.degree() != 2:
        from sage.all import FunctionField

        function_field = FunctionField(finite, "vff")
        vff = function_field.gen()
        function_polynomials = PolynomialRing(function_field, "xff")
        xff = function_polynomials.gen()
        def specialized_function_polynomial(parameter_value):
            specialized = sum(
                finite(parameter_value)**degree*coefficient
                for degree, coefficient in enumerate(moving.list())
            )
            return sum(
                finite(coefficient)*vff**exponents[0]*xff**exponents[1]
                for exponents, coefficient in specialized.dict().items()
            )

        function_polynomial = specialized_function_polynomial(1)
        assert function_polynomial.is_irreducible()
        function_extension = function_field.extension(
            function_polynomial, "zff"
        )
        function_genus = int(function_extension.genus())
        assert function_genus == 1
        rational_degenerations = []
        degeneration_factor_data = []
        infinity_data = None
        if arguments.scan_degenerations:
            for parameter_value in finite:
                specialized = specialized_function_polynomial(parameter_value)
                factorization = specialized.factor()
                factor_degrees = tuple(
                    sorted(
                        factor.degree()
                        for factor, exponent in factorization
                        for _ in range(int(exponent))
                    )
                )
                if factor_degrees != (3,):
                    rational_degenerations.append(
                        (int(parameter_value), "reducible", factor_degrees)
                    )
                    degeneration_factor_data.append(
                        [
                            int(parameter_value),
                            [
                                [int(factor.degree()), int(exponent)]
                                for factor, exponent in factorization
                            ],
                        ]
                    )
            infinity_polynomial = sum(
                finite(coefficient)*vff**exponents[0]*xff**exponents[1]
                for exponents, coefficient in moving[moving.degree()].dict().items()
            )
            infinity_factorization = infinity_polynomial.factor()
            infinity_factor_degrees = tuple(
                sorted(
                    factor.degree()
                    for factor, exponent in infinity_factorization
                    for _ in range(int(exponent))
                )
            )
            if infinity_factor_degrees == (3,):
                infinity_data = ("irreducible", infinity_factor_degrees)
            else:
                infinity_data = ("reducible", infinity_factor_degrees)
            print(
                "Q80FOURTHLOCALGF73|"
                f"rational_degenerations={tuple(rational_degenerations)}|"
                f"infinity={infinity_data}|"
                "status=PASS_FUNCTION_FIELD_DEGENERATION_SCAN",
                flush=True,
            )
        if arguments.write_artifact:
            import json
            from pathlib import Path

            def polynomial_coefficients(polynomial):
                return [int(coefficient) for coefficient in polynomial.list()]

            moving_terms = []
            for parameter_degree, coefficient in enumerate(moving.list()):
                for exponents, scalar in coefficient.dict().items():
                    moving_terms.append(
                        [
                            parameter_degree,
                            int(exponents[0]),
                            int(exponents[1]),
                            int(scalar),
                        ]
                    )
            fixed_terms = [
                [int(exponents[0]), int(exponents[1]), int(scalar)]
                for exponents, scalar in fixed_factor.dict().items()
            ]
            artifact = {
                "schema": "q80-fourth-q12-cm24-moving-cubic-gf73-v1",
                "prime": int(73),
                "candidate": int(arguments.candidate),
                "selected_i2": int(arguments.selected_i2),
                "orientation": {
                    "reverse_53": bool(selected_result[0]),
                    "reverse_6": bool(selected_result[1]),
                },
                "old_surface": {
                    "A_coefficients": polynomial_coefficients(A),
                    "B_coefficients": polynomial_coefficients(B),
                },
                "horizontal_section": {
                    "h_coefficients": polynomial_coefficients(h),
                    "x_numerator_coefficients": polynomial_coefficients(Nx),
                    "y_numerator_coefficients": polynomial_coefficients(Ny),
                },
                "smith_degrees": list(map(int, smith_degrees)),
                "generator_weights": list(map(int, generator_weights)),
                "ambient_dimension": int(len(global_columns)),
                "kernel": [list(map(int, row)) for row in selected_kernel],
                "fixed_factor_terms_v_x_coefficient": sorted(fixed_terms),
                "moving_terms_T_v_x_coefficient": sorted(moving_terms),
                "moving_degrees_T_v_x": [
                    int(moving.degree()),
                    int(max(coefficient.degree(v0) for coefficient in moving.list())),
                    int(moving_generic.degree()),
                ],
                "specialized_T1": {
                    "irreducible": True,
                    "function_field_genus": int(function_genus),
                },
                "rational_reducible_support": degeneration_factor_data,
                "infinity_factorization": (
                    None
                    if infinity_data is None
                    else [
                        infinity_data[0],
                        list(map(int, infinity_data[1])),
                    ]
                ),
                "reproduce": (
                    "sage elkies-k3/scripts/"
                    "derive_q80_fourth_q12_local_gates_gf73.sage "
                    "--candidate 1 --selected-i2 5 --genus-gate "
                    "--generic-only --scan-degenerations --write-artifact"
                ),
            }
            artifact_path = (
                Path(__file__).resolve().parents[2]
                / "artifacts/generated-results/"
                "q80-fourth-q12-cm24-moving-cubic-gf73.json"
            )
            encoded_artifact = json.dumps(
                artifact, indent=2, sort_keys=True
            )+"\n"
            artifact_path.write_text(encoded_artifact)
            import hashlib
            artifact_hash = hashlib.sha256(
                encoded_artifact.encode("utf-8")
            ).hexdigest()
            print(
                f"Q80FOURTHLOCALGF73|artifact={artifact_path}|"
                f"sha256={artifact_hash}|"
                "status=PASS_ARTIFACT_WRITE",
                flush=True,
            )
        print(
            "Q80FOURTHLOCALGF73|"
            f"selected_i2={arguments.selected_i2}|"
            f"fixed_degrees_v,x={fixed_factor.degree(v0)},{fixed_factor.degree(x0)}|"
            f"moving_degrees_T,v,x={moving.degree()},"
            f"{max(coefficient.degree(v0) for coefficient in moving.list())},"
            f"{moving_generic.degree()}|"
            f"specialized_T=1|irreducible=1|function_field_genus={function_genus}|"
            "status=PASS_CUBIC_GENUS_ONE_GATE",
            flush=True,
        )
        raise SystemExit(0)
    moving_discriminant = old_base_ring(moving_generic.discriminant())
    discriminant_factorization = moving_discriminant.factor()
    squarefree_model = old_base_ring(discriminant_factorization.unit())
    for factor, exponent in discriminant_factorization:
        if exponent % 2:
            squarefree_model *= factor
    squarefree_model = squarefree_model.monic()
    assert squarefree_model.degree() in (3, 4)

    quartic_coefficients = [squarefree_model[index] for index in range(5)]
    q0, q1, q2, q3, q4 = quartic_coefficients
    invariant_i = 12*q4*q0-3*q3*q1+q2**2
    invariant_j = (
        72*q4*q2*q0+9*q3*q2*q1-27*q4*q1**2
        -27*q3**2*q0-2*q2**3
    )
    jacobian_a = -27*invariant_i
    jacobian_b = -27*invariant_j
    assert 4*jacobian_a**3+27*jacobian_b**2 != 0
    quartic_scale = parameter_base.one()
    for coefficient in squarefree_model.list():
        quartic_scale = quartic_scale.lcm(coefficient.denominator())
    polynomial_a = parameter_base(jacobian_a*quartic_scale**2)
    polynomial_b = parameter_base(jacobian_b*quartic_scale**3)
    polynomial_discriminant = 4*polynomial_a**3+27*polynomial_b**2
    polynomial_discriminant_factors = tuple(
        (factor.monic(), int(exponent))
        for factor, exponent in polynomial_discriminant.factor()
    )
    assert polynomial_a.degree() <= 8 and polynomial_b.degree() <= 12
    assert sum(
        factor.degree()*exponent
        for factor, exponent in polynomial_discriminant_factors
    ) == polynomial_discriminant.degree()
    print(
        "Q80FOURTHLOCALGF73|"
        f"selected_i2={arguments.selected_i2}|"
        f"fixed_degrees_v,x={fixed_factor.degree(v0)},{fixed_factor.degree(x0)}|"
        f"moving_degrees_T,v,x={moving.degree()},"
        f"{max(coefficient.degree(v0) for coefficient in moving.list())},"
        f"{max(coefficient.degree(x0) for coefficient in moving.list())}|"
        f"disc_factor_degrees={tuple((factor.degree(), int(exponent)) for factor, exponent in discriminant_factorization)}|"
        f"squarefree={squarefree_model}|quartic_scale={quartic_scale}|"
        f"jacobian_A={polynomial_a}|jacobian_B={polynomial_b}|"
        f"Delta_factors={tuple((str(factor), exponent) for factor, exponent in polynomial_discriminant_factors)}|"
        "status=PASS_GENERIC_GENUS_ONE_MODEL",
        flush=True,
    )
