#!/usr/bin/env sage -python
"""Derive the exact finite component-nef module in the transported q_regular frame.

Let tau_-P0 translate the physical horizontal divisor P0+Q to O+S, and let

    q_std = (m_std-p)/h - R/Nx

be the already normalized standard chord.  Its physical pullback is
q_phys=q_std o tau_-P0.

For the component-nef q8 class, the exact negative exceptional cycles at
II* and IV* impose the complete ideal (u^2,x,y).  In the quotient by this
ideal, x=y=0 and u^2=0.  Translation does NOT imply q_phys=0 there.
We therefore evaluate tau_-P0 at the contracted singular origin exactly and
compute

    rho = q_phys(0,0) mod f_II^2 f_IV^2.

A coefficient C+B*q_phys satisfies both finite additive conditions iff

    C+B*rho == 0 mod M,   M=f_II^2*f_IV^2.

Thus the exact finite module is generated by

    q_phys-rho,   M.

Under tau_-P0 the same coefficient module is represented in standard
coordinates by q_std-rho and M.  This is the correct handoff for the infinity
intersection and branch screen.
"""

import argparse
import hashlib
import json
from pathlib import Path

from sage.all import EllipticCurve, PolynomialRing, QQ, vector, ZZ


ROOT = Path(__file__).resolve().parents[2]
CHILD = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-child-jacobian.json"
ZERO = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-child-zero-section.json"
MARKING = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-child-q8-marking.json"
NORMALIZER = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-child-q8-q-pole-normalization-crt.json"
DEFAULT_TARGET = ROOT / "artifacts/local/elkies-k3/q8-target-component-nef.json"
DEFAULT_OUTPUT = ROOT / "artifacts/local/elkies-k3/q8-component-nef-qreg-finite-module.json"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def polynomial(ring, coefficients):
    return ring([QQ(value) for value in coefficients])


def rational(field, ring, data, numerator, denominator):
    return field(polynomial(ring, data[numerator])) / field(polynomial(ring, data[denominator]))


def monic_power_root(value, exponent):
    root = value.parent().one()
    for factor, multiplicity in value.factor():
        assert multiplicity % exponent == 0
        root *= factor.monic() ** (multiplicity // exponent)
    return root.monic()


def reduce_rational(value, modulus):
    ring = modulus.parent()
    numerator = ring(value.numerator())
    denominator = ring(value.denominator())
    assert denominator.gcd(modulus) in QQ
    return (numerator * denominator.inverse_mod(modulus)).mod(modulus)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--target", type=Path, default=DEFAULT_TARGET)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()
args.target = args.target.resolve()
args.output = args.output.resolve()

child = json.loads(CHILD.read_text())
zero = json.loads(ZERO.read_text())
marking = json.loads(MARKING.read_text())
normalizer = json.loads(NORMALIZER.read_text())
target = json.loads(args.target.read_text())
assert child["status"] == "PASS_EXACT_E8_E6_CHILD_JACOBIAN"
assert zero["status"] == "PASS_EXACT_CHILD_ZERO_SECTION_TRANSPORT"
assert marking["status"] == "PASS_EXACT_Q6_CHILD_Q8_MARKING"
assert normalizer["status"] == "PASS_EXACT_CRT_PRINCIPAL_PART_NORMALIZATION"
assert target["status"] == "PASS_EXACT_Q6_CHILD_Q8_PHYSICAL_ROOT_TARGET"
assert target["normalization"]["representative"] == "component-nef"

ring = PolynomialRing(QQ, "T")
T = ring.gen()
field = ring.fraction_field()
A = field(polynomial(ring, child["minimal_short_weierstrass"]["A_coefficients_low_to_high"]))
Bcurve = field(polynomial(ring, child["minimal_short_weierstrass"]["B_coefficients_low_to_high"]))
curve = EllipticCurve(field, [0, 0, 0, A, Bcurve])

p0_data = zero["section"]
p0 = curve(
    rational(field, ring, p0_data,
             "x_numerator_coefficients_low_to_high",
             "x_denominator_coefficients_low_to_high"),
    rational(field, ring, p0_data,
             "y_numerator_coefficients_low_to_high",
             "y_denominator_coefficients_low_to_high"),
)
s_data = marking["selected_q8"]["relative_child_section_standard_jacobian_coordinates"]
s = curve(
    rational(field, ring, s_data,
             "x_numerator_coefficients_low_to_high",
             "x_denominator_coefficients_low_to_high"),
    rational(field, ring, s_data,
             "y_numerator_coefficients_low_to_high",
             "y_denominator_coefficients_low_to_high"),
)
px, py = p0.xy()
sx, sy = s.xy()
nx = ring(sx.numerator())
dx = ring(sx.denominator())
ny = ring(sy.numerator())
dy = ring(sy.denominator())
h = monic_power_root(dx, 2)
assert dx // h**2 in QQ and dy // h**3 in QQ
R = polynomial(ring, normalizer["normalizer"]["R_coefficients_low_to_high"])
assert (R*h*dy-ny) % nx == 0
p = -sy/sx

fibres = {
    item["kodaira"]: ring(item["factor"]).monic()
    for item in child["finite_fibres"]
    if item["kodaira"] in ("II*", "IV*")
}
assert set(fibres) == {"II*", "IV*"}
ii, iv = fibres["II*"], fibres["IV*"]
assert ii.degree() == iv.degree() == 1 and ii.gcd(iv) in QQ
M = ii**2 * iv**2
assert M.degree() == 4
assert nx.gcd(M) in QQ and h.gcd(M) in QQ

# Certify that the physical component cycles impose (u^2,x,y).
e8_cycle = vector(ZZ, target["selected_q8"]["E8"]["vertical_cycle"])
e6_cycle = vector(ZZ, target["selected_q8"]["E6"]["vertical_cycle"])
assert list(e8_cycle) == [-4,-5,-7,-10,-8,-6,-4,-2]
assert list(e6_cycle) == [-2,-3,-4,-3,-2,-2]
# These are minus the x-coordinate valuation cycles in the actual resolutions.
assert [-value for value in e8_cycle] == [4,5,7,10,8,6,4,2]
# Physical E6 order differs from chart order; both orientations give x-cycle
# (2,2,2,3,3,4), as already established by the exact IV* script.

# Evaluate tau_-P0 at the contracted singular origin x=y=0.
# lambda=(y+y0)/(x-x0), x'=lambda^2-x-x0,
# y'=lambda*(x-x')-y.
lam0 = -py/px
xprime0 = lam0**2 - px
yprime0 = -lam0*xprime0
mphys0 = (yprime0 + sy)/(xprime0 - sx)
qphys0 = (mphys0 - p)/field(h) - field(R)/field(nx)

# Every denominator used above is a unit at both additive fibres.
for value in (px, sx, xprime0-sx, h, field(nx), qphys0.denominator()):
    denominator = ring(value.denominator()) if hasattr(value, "denominator") else ring.one()
    numerator = ring(value.numerator()) if hasattr(value, "numerator") else ring(value)
    # px/sx/xprime0-sx must themselves be units; h,nx are polynomials.
    if value in (px, sx, xprime0-sx):
        assert numerator.gcd(M) in QQ and denominator.gcd(M) in QQ
    else:
        assert denominator.gcd(M) in QQ

rho = reduce_rational(qphys0, M)
assert rho.degree() < 4
assert reduce_rational(qphys0-field(rho), M) == 0
first_c = (-rho).mod(M)

local_records = {}
for kind, factor in fibres.items():
    modulus = factor**2
    local_rho = rho.mod(modulus)
    local_records[kind] = {
        "factor": str(factor),
        "rho_mod_f2": str(local_rho),
        "rho_mod_f2_coefficients_low_to_high": [str(value) for value in local_rho.list()],
        "rho_is_zero": bool(not local_rho),
    }

payload = {
    "schema": "elkies-k3.h92-q6-child-q8-component-nef-qreg-finite-module.v1",
    "status": "PASS_EXACT_COMPONENT_NEF_QREG_FINITE_MODULE",
    "inputs": {
        "child": digest(CHILD),
        "zero": digest(ZERO),
        "marking": digest(MARKING),
        "normalizer": digest(NORMALIZER),
        "component_nef_target": digest(args.target),
    },
    "physical_frame": {
        "translation": "tau_-P0",
        "q_phys": "((m_phys-p)/h)-R/Nx = q_std o tau_-P0",
        "singular_origin_evaluation": "x=y=0 before reduction modulo (u^2,x,y)",
        "q_phys_at_singular_origin": str(qphys0),
    },
    "finite_conditions": {
        "II*": "(u^2,x,y)",
        "IV*": "(u^2,x,y)",
        "CRT_modulus": str(M),
        "CRT_modulus_degree": 4,
        "local_residues": local_records,
    },
    "module": {
        "rank": 2,
        "finite_codimension": 4,
        "determinant_degree": 4,
        "smith_degrees": [0,4],
        "coordinate_order": ["B","C"],
        "basis": [
            ["1", "-rho"],
            ["0", "f_II*^2*f_IV*^2"],
        ],
        "rho": str(rho),
        "rho_coefficients_low_to_high": [str(value) for value in rho.list()],
        "first_C_lift_coefficients_low_to_high": [str(value) for value in first_c.list()],
        "standard_coordinate_functions": [
            "q_regular-rho",
            "M",
        ],
        "physical_coordinate_functions": [
            "q_phys-rho",
            "M",
        ],
    },
    "boundary": (
        "This certifies the complete finite additive coefficient module in the "
        "transported q_regular frame.  The infinity intersection, pencil, child "
        "equation and rank consequences are separate."
    ),
}
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(payload, indent=2, sort_keys=True)+"\n")
print(
    "Q8QREGRES|rho_deg={}|rho_zero={}|II_zero={}|IV_zero={}|M_deg=4|"
    "status=PASS_EXACT_COMPONENT_NEF_QREG_FINITE_MODULE".format(
        rho.degree(), int(not rho),
        int(local_records["II*"]["rho_is_zero"]),
        int(local_records["IV*"]["rho_is_zero"]),
    ),
    flush=True,
)
