#!/usr/bin/env sage
"""Pin the CM24 marked section for the third q80 neighbor.

The first two q=4 pencils give the CM24 second-child short Weierstrass model
with fibers D7+E6+3A1.  Exact lattice transport says that the next q=12
divisor has abstract MW coordinates `(2,-1)` in a saturated CM basis with
height Gram

    [[5/12,-1/6],[-1/6,2/3]].

Exact I2 profiles identify the abstract basis as `e1=P2`,
`e2=-(P1+P2)`, up to simultaneous sign, so the horizontal point is the much
simpler polynomial section `Q=P1+3*P2`. This verifier checks explicit P1 and
P2 over QQ(sqrt(-6)), computes Q by exact function-field group law, and
certifies its polynomial formula. It also
checks that the generic-fiber Riemann--Roch calculation reduces to the chord
space generated by 1, X, and (Y+Qy)/(X-Qx).  The remaining problem is the
vertical D7+D5 component gate on the non-CM family; this script is a CM
boundary seed, not an algebraization of the third neighbor.
"""

from sage.all import Matrix, PolynomialRing, QQ, QuadraticField, vector


K = QuadraticField(-6, "s")
s = K.gen()
base = PolynomialRing(K, "W")
W = base.gen()
function_field = base.fraction_field()

A = function_field(
    -27*W**6+59049*W**4+K(13286025)/8*W**3
    +K(129140163)/8*W**2+K(1162261467)/32*W-K(10460353203)/64
)
B = function_field(
    54*W**9-177147*W**7-K(97253703)/8*W**6
    -K(7360989291)/16*W**5-K(331244518095)/32*W**4
    -K(4487491524087)/32*W**3-K(144886352214753)/128*W**2
    -K(1303977169932777)/256*W-K(5147278302366225)/512
)

P1 = (
    function_field(3*W**3+K(6561)/4*W+K(59049)/8),
    function_field(
        s*(K(2187)/2*W**3+K(177147)/8*W**2
           +K(4782969)/16*W+K(43046721)/32)
    ),
)
P2 = (
    function_field(3*W**3-K(6561)/4*W-K(59049)/4),
    function_field(
        s*(K(2187)/2*W**3+K(295245)/8*W**2
           +K(1594323)/4*W+K(43046721)/32)
    ),
)


def on_curve(point):
    x_coordinate, y_coordinate = point
    return y_coordinate**2 == x_coordinate**3+A*x_coordinate+B


def negate(point):
    return None if point is None else (point[0], -point[1])


def add_points(left, right):
    if left is None:
        return right
    if right is None:
        return left
    x_left, y_left = left
    x_right, y_right = right
    if x_left == x_right and y_left == -y_right:
        return None
    if x_left == x_right:
        slope = (3*x_left**2+A)/(2*y_left)
    else:
        slope = (y_right-y_left)/(x_right-x_left)
    x_sum = slope**2-x_left-x_right
    y_sum = -y_left+slope*(x_left-x_sum)
    return function_field(x_sum), function_field(y_sum)


def multiply_point(multiplier, point):
    if multiplier < 0:
        return multiply_point(-multiplier, negate(point))
    answer = None
    addend = point
    while multiplier:
        if multiplier & 1:
            answer = add_points(answer, addend)
        multiplier >>= 1
        if multiplier:
            addend = add_points(addend, addend)
    return answer


assert on_curve(P1) and on_curve(P2)
P3 = multiply_point(-2, P2)
assert on_curve(P3)
Q = add_points(P1, multiply_point(3, P2))
assert on_curve(Q)

transported_height = Matrix(
    QQ, [[QQ(5)/12, -QQ(1)/6], [-QQ(1)/6, QQ(2)/3]]
)
q_coordinates = vector(QQ, (2, -1))
assert transported_height.det() == QQ(1)/4
assert q_coordinates*transported_height*q_coordinates == 3

Qx, Qy = Q
expected_Qx = (
    -K(8)/27*W**4+22*W**3-K(243)/2*W**2+729*W-K(492075)/8
)
expected_Qy = s*(
    K(16)/243*W**6-K(22)/3*W**5+K(333)/2*W**4
    -K(2025)/4*W**3+K(190269)/4*W**2-K(177147)/16*W
    +K(199290375)/32
)
assert Qx == expected_Qx and Qy == expected_Qy
Nx = base(Qx.numerator())
Ny = base(Qy.numerator())
assert (Nx.degree(), Ny.degree()) == (4, 6)

# The line of slope z through -Q meets the cubic in two residual points.
# This is the generic-fiber form of the three-dimensional chord space
# L(2O+Q): 1, X, z_Q.
z_ring = PolynomialRing(function_field, "z")
z = z_ring.gen()
x_ring = PolynomialRing(z_ring, "X")
X = x_ring.gen()
chord_substitution = z*(X-z_ring(Qx))-z_ring(Qy)
chord_equation = chord_substitution**2-X**3-z_ring(A)*X-z_ring(B)
chord_quotient, chord_remainder = chord_equation.quo_rem(X-z_ring(Qx))
assert chord_remainder == 0 and chord_quotient.degree() == 2

# The uncorrected chord is not yet the q=12 base coordinate.  Reversing the
# coefficient order and taking the quadratic discriminant in X gives a
# squarefree degree-eight cover of the old W-line (genus three).  The desired
# genus-one pencil therefore needs the vertical D7+D5 gates to select a
# nontrivial combination of 1, X, and z_Q.
parameter_ring = PolynomialRing(K, "V")
V = parameter_ring.gen()
old_base_ring = PolynomialRing(parameter_ring, "w")
w = old_base_ring.gen()
x_polynomial_ring = PolynomialRing(old_base_ring, "x")
x = x_polynomial_ring.gen()
A_polynomial = old_base_ring(base(A.numerator()))
B_polynomial = old_base_ring(base(B.numerator()))
Qx_polynomial = old_base_ring(Nx)
Qy_polynomial = old_base_ring(Ny)
raw_chord = (
    V*(x-Qx_polynomial)-Qy_polynomial
)**2-x**3-A_polynomial*x-B_polynomial
raw_quotient, raw_remainder = raw_chord.quo_rem(x-Qx_polynomial)
assert raw_remainder == 0 and raw_quotient.degree() == 2
raw_discriminant = (
    raw_quotient[1]**2-4*raw_quotient[2]*raw_quotient[0]
)
assert raw_discriminant.degree() == 8
raw_factorization = tuple(raw_discriminant.factor())
assert len(raw_factorization) == 1 and raw_factorization[0][1] == 1

# Exhaust the smallest possible vertical correction, namely a translation
# V=z+k2*W^2+k1*W+k0 with no X term.  The constant k0 only translates the new
# base and may be set to zero.  Vanishing of the W^8,...,W^5 coefficients of
# the residual quadratic discriminant first gives
#
#   c8=(k2-2s/3)(k2+2s/9)^3,
#   c7=4(k2+2s/9)^2(k2*k1-4s*k1/9-33).
#
# The simple root k2=2s/3 is inconsistent at c6.  On the triple root
# k2=-2s/9, c7=c6=0 and
# c5=(-8s/9)(k1-15s/4)(k1-21s/2)^2.
coefficient_ring = PolynomialRing(K, names=("k2", "k1", "v_parameter"))
k2, k1, v_parameter = coefficient_ring.gens()
symbolic_old_base = PolynomialRing(coefficient_ring, "w_symbolic")
w_symbolic = symbolic_old_base.gen()
symbolic_x_ring = PolynomialRing(symbolic_old_base, "x_symbolic")
x_symbolic = symbolic_x_ring.gen()


def lift_polynomial(poly):
    return symbolic_old_base([coefficient_ring(value) for value in poly.list()])


symbolic_A = lift_polynomial(base(A.numerator()))
symbolic_B = lift_polynomial(base(B.numerator()))
symbolic_Qx = lift_polynomial(Nx)
symbolic_Qy = lift_polynomial(Ny)
symbolic_z = v_parameter-(k2*w_symbolic**2+k1*w_symbolic)
symbolic_chord = (
    symbolic_z*(x_symbolic-symbolic_Qx)-symbolic_Qy
)**2-x_symbolic**3-symbolic_A*x_symbolic-symbolic_B
symbolic_quotient, symbolic_remainder = symbolic_chord.quo_rem(
    x_symbolic-symbolic_Qx
)
assert symbolic_remainder == 0
symbolic_discriminant = (
    symbolic_quotient[1]**2
    - 4*symbolic_quotient[2]*symbolic_quotient[0]
)
assert symbolic_discriminant[8] == (
    k2-K(2)/3*s
)*(k2+K(2)/9*s)**3
assert symbolic_discriminant[7] == (
    4*(k2+K(2)/9*s)**2*(k2*k1-K(4)/9*s*k1-33)
)
other_substitution = {k2: K(2)/3*s, k1: -K(99)/4*s}
assert coefficient_ring(symbolic_discriminant[6]).subs(
    other_substitution
) == K(1024)/243*s*(v_parameter-K(43497)/128*s)
live_substitution = {k2: -K(2)/9*s}
assert coefficient_ring(symbolic_discriminant[7]).subs(live_substitution) == 0
assert coefficient_ring(symbolic_discriminant[6]).subs(live_substitution) == 0
assert coefficient_ring(symbolic_discriminant[5]).subs(
    live_substitution
) == (
    -K(8)/9*s*(k1-K(15)/4*s)*(k1-K(21)/2*s)**2
)


def polynomial_valuation(poly, factor):
    value = 0
    while poly % factor == 0:
        poly //= factor
        value += 1
    return value


def translated_chord_signature(k1_value):
    correction = -K(2)/9*s*w**2+k1_value*w
    equation = (
        ((V-correction)*(x-Qx_polynomial)-Qy_polynomial)**2
        - x**3-A_polynomial*x-B_polynomial
    )
    quotient, remainder = equation.quo_rem(x-Qx_polynomial)
    assert remainder == 0
    quartic = quotient[1]**2-4*quotient[2]*quotient[0]
    coefficients = [parameter_ring(quartic[index]) for index in range(5)]
    e4, d4, c4, b4, a4 = coefficients
    invariant_i = 12*a4*e4-3*b4*d4+c4**2
    invariant_j = (
        72*a4*c4*e4+9*b4*c4*d4-27*a4*d4**2
        - 27*b4**2*e4-2*c4**3
    )
    jacobian_A = -27*invariant_i
    jacobian_B = -27*invariant_j
    jacobian_delta = -16*(4*jacobian_A**3+27*jacobian_B**2)
    finite = tuple(
        sorted(
            (
                factor.degree(), multiplicity,
                polynomial_valuation(jacobian_A, factor),
                polynomial_valuation(jacobian_B, factor),
            )
            for factor, multiplicity in jacobian_delta.factor()
        )
    )
    infinity = (
        8-jacobian_A.degree(),
        12-jacobian_B.degree(),
        24-jacobian_delta.degree(),
    )
    return quartic.degree(), finite, infinity


simple_translation = translated_chord_signature(K(15)/4*s)
double_translation = translated_chord_signature(K(21)/2*s)
assert simple_translation == (
    4,
    ((1, 1, 0, 0), (1, 2, 0, 0), (1, 9, 3, 5), (2, 1, 0, 0)),
    (2, 3, 10),
)
assert double_translation == (
    3,
    ((1, 2, 0, 0), (1, 4, 0, 0), (1, 8, 3, 4), (3, 1, 0, 0)),
    (2, 3, 7),
)

print(
    "Q80THIRDQ12|field=QQ(sqrt(-6))|s^2=-6|"
    "height_gram=(1/12)[5,-2;-2,8]|abstract_Q_coordinates=2,-1|"
    "basis_map=e1:P2,e2:-(P1+P2)|Q=P1+3P2|height_Q=3",
    flush=True,
)
print(
    f"Q80THIRDQ12|P1x={P1[0]}|P1y={P1[1]}|P2x={P2[0]}|P2y={P2[1]}",
    flush=True,
)
print(
    f"Q80THIRDQ12|Qx={Nx}|Qy={Ny}|"
    "degrees_Qx,Qy=4,6|P.O=0|profile=quadratic_I2_pair_only",
    flush=True,
)
print(
    "Q80THIRDQ12|generic_fiber_basis=1,X,(Y+Qy)/(X-Qx)|"
    "chord_residual_degree=2|raw_chord_cover_degree=8|raw_chord_genus=3|"
    "translation_candidates=k1:15s/4,21s/2|"
    "candidate_ADE=D8+E7+A1,D5+E6+A3+A1|"
    "transported_CM24_ADE=2A6+3A1|pure_translation_excluded=1|"
    "vertical_gate=nonzero_X_coefficient_required|status=PASS_CM24_SEED",
    flush=True,
)
