#!/usr/bin/env sage -python
"""Apply the generic resolved-E7_3 q=8 module condition modulo p.

This is the fast generic-point component of the full all-edge compiler.  At
the E7_4--E7_3 edge, the actual chart has reduced E7_3 parameter Y and

    ord(t,x,y)=(4,6,9),  ord(x(P1),y(P1))=(8,12).

Thus ord(m)=3.  The q8 Cartier factor is Z^4 Y^6, with E7_3 order six.
At this generic point x-x(P1) has lower order than y-y(P1), so the fractional
q6 marked module t*J_P1/(x-x(P1)) is generated by t.  Consequently a q8 term
u^i*x^a*m^b/h^k must have nonnegative residual order

    6 + 4*(4*k-i-9) + 6*a + 3*b.

The script uses only *unique* negative-order support terms, in increasing
pole order, so each resulting coordinate equation is a necessary condition
without assuming cancellation between different leading residues.
"""

import argparse
import json
from pathlib import Path

from sage.all import GF, ZZ, matrix, vector


ROOT = Path(__file__).resolve().parents[2]
KERNEL = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-smooth-principal-parts-mod-43-extra4.json"
ATLAS = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-actual-e7-valuation-atlas.json"
GLUING = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-actual-e7-gluing.json"
DEFAULT_OUTPUT = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-e3-generic-module-mod-43-extra4.json"


def path_label(path):
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--kernel", type=Path, default=KERNEL)
parser.add_argument("--atlas", type=Path, default=ATLAS)
parser.add_argument("--gluing", type=Path, default=GLUING)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()

kernel = json.loads(args.kernel.read_text())
atlas = json.loads(args.atlas.read_text())
gluing = json.loads(args.gluing.read_text())
assert kernel["status"] == "EXPERIMENTAL_MODULAR_SMOOTH_BLOCK_RANK"
assert atlas["status"] == "PASS_EXACT_H92_E7_VALUATION_ATLAS"
assert gluing["status"] == "PASS_EXACT_Q8_ACTUAL_E7_GLUING"
prime = int(kernel["prime"])
finite = GF(prime)
basis = kernel["ambient_basis"]
smooth_rows = matrix(finite, [[finite(int(value)) for value in row] for row in kernel["kernel_basis_rows"]])
assert smooth_rows.nrows() == int(kernel["dimensions"]["kernel"])

e3 = next(entry for entry in atlas["entries"] if entry["component"] == "E7_3")
assert e3["edge_chart"] == "E7_4--E7_3"
assert e3["reduced_parameter"] == "Y; U is a unit times Y^2"
assert tuple(e3["old_coordinate_orders"][key] for key in ("t", "x", "y")) == (4, 6, 9)
edge = next(entry for entry in gluing["actual_edge_chart_gluing"] if entry["name"] == "E7_4--E7_3")
assert edge["w_cartier_equation"] == "Z^4*Y^6"
assert edge["components"] == [
    {"name": "E7_4", "equation": "Z", "w_coefficient": 4},
    {"name": "E7_3", "equation": "Y", "w_coefficient": 6},
]

# The exact P1 entrance has t-orders 2 and 3 for x and y.  Pullback through
# ord_E7_3(t)=4 gives 8 and 12, strictly above the chart orders 6 and 9;
# the two displayed min computations are therefore exact, without a leading
# coefficient cancellation.  Hence ord_E7_3(m)=9-6=3.
t_order, x_order, y_order = 4, 6, 9
xp_order, yp_order = 2*t_order, 3*t_order
assert (xp_order, yp_order) == (8, 12)
assert x_order < xp_order and y_order < yp_order
m_order, g_order, q6_ninth_order = y_order-x_order, 6, 9*t_order
assert (m_order, g_order, q6_ninth_order) == (3, 6, 36)


def residual_order(entry):
    a, b, i, k = (int(entry[key]) for key in ("x_power", "m_power", "u_power", "h_power"))
    return g_order + (4*k-i)*t_order + a*x_order + b*m_order - q6_ninth_order


support = [
    index for index in range(len(basis))
    if any(smooth_rows[row, index] for row in range(smooth_rows.nrows()))
]
by_order = {}
for index in support:
    by_order.setdefault(residual_order(basis[index]), []).append(index)

# A term that is unique at its negative residual order cannot be cancelled by
# any other supported term.  In increasing order, add its coefficient row as
# a necessary equation whenever it cuts the residual smooth-kernel space.
constraints = []
rank = 0
for order in sorted(by_order):
    labels = by_order[order]
    if order >= 0 or len(labels) != 1:
        continue
    label = labels[0]
    coefficient_row = vector(finite, [smooth_rows[row, label] for row in range(smooth_rows.nrows())])
    next_rank = matrix(finite, constraints + [coefficient_row]).rank()
    if next_rank > rank:
        constraints.append(coefficient_row)
        rank = next_rank
    if rank == smooth_rows.nrows():
        break

constraint_matrix = matrix(finite, len(constraints), smooth_rows.nrows(), constraints)
survivor_dimension = smooth_rows.nrows()-constraint_matrix.rank()
records = []
for row in constraint_matrix.rows():
    # Recover the unique supported label supplying this independent equation.
    matches = []
    for order in sorted(by_order):
        labels = by_order[order]
        if order < 0 and len(labels) == 1:
            label = labels[0]
            if vector(finite, [smooth_rows[index, label] for index in range(smooth_rows.nrows())]) == row:
                matches.append((order, label))
    assert len(matches) == 1
    order, label = matches[0]
    records.append({
        "residual_order": int(order),
        "basis_index": int(label),
        "basis_label": basis[label],
        "coefficient_on_smooth_kernel_basis": [int(value) for value in row],
    })

payload = {
    "schema": "elkies-k3.h92-q8-e3-generic-module-modp.v1",
    "status": "EXPERIMENTAL_MODULAR_E3_GENERIC_MODULE_OBSTRUCTION",
    "prime": int(prime),
    "inputs": {
        "smooth_kernel": path_label(args.kernel),
        "actual_e7_atlas": path_label(args.atlas),
        "q8_actual_gluing": path_label(args.gluing),
    },
    "generic_component": {
        "component": "E7_3",
        "chart": "E7_4--E7_3",
        "orders": {"t": t_order, "x": x_order, "y": y_order, "xP1": xp_order, "yP1": yp_order, "m": m_order, "g": g_order},
        "q6_module_generator": "t at the generic E7_3 point",
        "residual_order_formula": "6 + 4*(4*k-i-9) + 6*a + 3*b",
    },
    "smooth_kernel_dimension": int(smooth_rows.nrows()),
    "independent_unique_leading_constraints": records,
    "survivor_dimension_after_E7_3_generic_condition": int(survivor_dimension),
    "boundary": "This is a necessary generic-point E7_3 cut on the declared mod-p smooth kernel. It does not test the E7_3--E7_4 node germ, the other four unmarked edges, overlap gluing, characteristic-zero lifting, a q8 pencil, a bisection cover, or generic rank.",
}
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(payload, indent=2, sort_keys=True)+"\n")
print(
    "H92Q8E3GENERIC|prime={}|smooth_kernel={}|constraints={}|survivor={}|"
    "status=EXPERIMENTAL_MODULAR_E3_GENERIC_MODULE_OBSTRUCTION".format(
        prime, smooth_rows.nrows(), constraint_matrix.rank(), survivor_dimension
    ),
    flush=True,
)
