#!/usr/bin/env sage -python
"""Apply necessary leading node conditions on the actual E7_4--E7_3 chart.

At this resolved edge origin the surface equation solves U as a unit times
Y^2.  The actual pullbacks therefore have leading bidegrees in (Z,Y)

    t=(3,4), x=(4,6), m=(2,3), g=Z^4*Y^6=(4,6).

Since x-x(P1) is the lower-order generator of J_P1 and y-y(P1) divided by it
is regular at the node, the q6 fractional marked module is generated by t.
For a q8 monomial u^i*x^a*m^b/h^k, the necessary node bidegree after division
by t^9 is

    (4+3*(4k-i)+4a+2b-27, 6+4*(4k-i)+6a+3b-36).

The checker imposes only a unique Pareto-minimal negative leading term at a
time, then restricts the candidate subspace.  Thus it never assumes a
spurious cancellation between incomparable bidegrees or between equal
leading monomials.  It remains a modular leading-term screen, not the full
chart/overlap membership calculation.
"""

import argparse
import json
from pathlib import Path

from sage.all import GF, matrix, vector


ROOT = Path(__file__).resolve().parents[2]
KERNEL = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-smooth-principal-parts-mod-43-extra7.json"
GENERIC = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-unmarked-e7-generic-module-mod-43-extra7.json"
ATLAS = ROOT / "artifacts/generated-results/elkies-k3-h92-q6-actual-e7-valuation-atlas.json"
GLUING = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-actual-e7-gluing.json"
DEFAULT_OUTPUT = ROOT / "artifacts/generated-results/elkies-k3-h92-q8-e7-4-3-node-module-mod-43-extra7.json"


def path_label(path):
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--kernel", type=Path, default=KERNEL)
parser.add_argument("--generic", type=Path, default=GENERIC)
parser.add_argument("--atlas", type=Path, default=ATLAS)
parser.add_argument("--gluing", type=Path, default=GLUING)
parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
args = parser.parse_args()

kernel = json.loads(args.kernel.read_text())
generic = json.loads(args.generic.read_text())
atlas = json.loads(args.atlas.read_text())
gluing = json.loads(args.gluing.read_text())
assert kernel["status"] == "EXPERIMENTAL_MODULAR_SMOOTH_BLOCK_RANK"
assert generic["status"] == "EXPERIMENTAL_MODULAR_UNMARKED_E7_GENERIC_MODULE_SCREEN"
assert atlas["status"] == "PASS_EXACT_H92_E7_VALUATION_ATLAS"
assert gluing["status"] == "PASS_EXACT_Q8_ACTUAL_E7_GLUING"
assert int(kernel["prime"]) == int(generic["prime"])
finite = GF(int(kernel["prime"]))
basis = kernel["ambient_basis"]
smooth = matrix(finite, [[finite(int(value)) for value in row] for row in kernel["kernel_basis_rows"]])
assert smooth.nrows() == int(generic["smooth_kernel_dimension"])

# The listed generic rows are coefficient functionals on the smooth-kernel
# basis.  Their common nullspace is exactly the candidate subspace reaching
# this node screen.
generic_rows = [
    [finite(int(value)) for value in entry["coefficient_on_smooth_kernel_basis"]]
    for entry in generic["independent_unique_leading_constraints"]
]
generic_matrix = matrix(finite, len(generic_rows), smooth.nrows(), generic_rows)
candidate = matrix(finite, generic_matrix.right_kernel().basis_matrix()) * smooth
assert candidate.nrows() == int(generic["survivor_dimension_after_generic_unmarked_E7_conditions"])

e3 = next(entry for entry in atlas["entries"] if entry["component"] == "E7_3")
assert e3["reduced_parameter"] == "Y; U is a unit times Y^2"
edge = next(entry for entry in gluing["actual_edge_chart_gluing"] if entry["name"] == "E7_4--E7_3")
assert edge["w_cartier_equation"] == "Z^4*Y^6"


def node_bidegree(entry):
    a, b, i, k = (int(entry[key]) for key in ("x_power", "m_power", "u_power", "h_power"))
    d = 4*k-i
    return (4 + 3*d + 4*a + 2*b - 27, 6 + 4*d + 6*a + 3*b - 36)


def support_pairs(rows):
    pairs = {}
    for label in range(rows.ncols()):
        if any(rows[row, label] for row in range(rows.nrows())):
            pairs.setdefault(node_bidegree(basis[label]), []).append(label)
    return pairs


def pareto_minima(pairs):
    result = []
    for degree, labels in pairs.items():
        if min(degree) >= 0:
            continue
        if not any(
            other != degree and other[0] <= degree[0] and other[1] <= degree[1]
            for other in pairs
        ):
            result.append((degree, labels))
    return sorted(result)


records = []
while candidate.nrows():
    minima = pareto_minima(support_pairs(candidate))
    unique = [(degree, labels[0]) for degree, labels in minima if len(labels) == 1]
    if not unique:
        break
    degree, label = unique[0]
    coefficient = vector(finite, [candidate[row, label] for row in range(candidate.nrows())])
    assert coefficient
    records.append({
        "bidegree_after_t9": [int(value) for value in degree],
        "basis_index": int(label),
        "basis_label": basis[label],
        "coefficient_on_current_candidate_basis": [int(value) for value in coefficient],
    })
    candidate = matrix(finite, matrix(finite, 1, candidate.nrows(), [coefficient]).right_kernel().basis_matrix()) * candidate

payload = {
    "schema": "elkies-k3.h92-q8-e7-4-3-node-module-modp.v1",
    "status": "EXPERIMENTAL_MODULAR_E7_4_3_NODE_MODULE_OBSTRUCTION",
    "prime": int(kernel["prime"]),
    "inputs": {"smooth_kernel": path_label(args.kernel), "generic_screen": path_label(args.generic), "atlas": path_label(args.atlas), "gluing": path_label(args.gluing)},
    "node": {
        "chart": "E7_4--E7_3",
        "surface_local_fact": "U is a unit times Y^2",
        "leading_bidegrees": {"t": [3, 4], "x": [4, 6], "m": [2, 3], "g": [4, 6]},
        "q6_module_generator": "t",
        "residual_formula": "(4+3*(4k-i)+4a+2b-27, 6+4*(4k-i)+6a+3b-36)",
    },
    "generic_candidate_dimension": int(generic_matrix.right_kernel().dimension()),
    "independent_unique_pareto_constraints": records,
    "survivor_dimension_after_node_leading_conditions": int(candidate.nrows()),
    "boundary": "This is a necessary leading-term screen at one edge node. It does not establish full local ideal membership, the remaining E7 charts, overlap gluing, characteristic-zero lifting, a pencil, a bisection, or a rank claim.",
}
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(payload, indent=2, sort_keys=True)+"\n")
print("H92Q8E743NODE|prime={}|generic_candidate={}|constraints={}|survivor={}|status=EXPERIMENTAL_MODULAR_E7_4_3_NODE_MODULE_OBSTRUCTION".format(kernel["prime"], generic_matrix.right_kernel().dimension(), len(records), candidate.nrows()), flush=True)
