from sage.all import *
from pathlib import Path

OUT=Path("artifacts/local/elkies-k3")
OUT.mkdir(parents=True,exist_ok=True)

# Same CM lattice / generic complement as previous scripts.
U=matrix(ZZ,[[0,1],[1,0]])
E8=matrix(ZZ,[
[2,-1,0,0,0,0,0,0],
[-1,2,-1,0,0,0,0,0],
[0,-1,2,-1,0,0,0,-1],
[0,0,-1,2,-1,0,0,0],
[0,0,0,-1,2,-1,0,0],
[0,0,0,0,-1,2,-1,0],
[0,0,0,0,0,-1,2,0],
[0,0,-1,0,0,0,0,2],
])
A2=matrix(ZZ,[[2,-1],[-1,2]])
NS=block_diagonal_matrix(U,-E8,-E8,-A2)

ve8=vector(ZZ,[9,-2,-10,-7,-4,4,3,-7])
w=vector(ZZ,[0]*20)
for i,x in enumerate(ve8): w[2+i]=x
assert w*NS*w==-316

# S = generic NS = w^\perp as an abstract rank-19 lattice.
K=matrix(ZZ,1,20,list(w*NS)).right_kernel_matrix()
Sgram=K*NS*K.transpose()
assert Sgram.rank()==19 and abs(Sgram.det())==948

# Broken first-E8 root lattice.
def qform_from_hessian(H):
    co=[]
    for i in range(H.nrows()):
        for j in range(i,H.ncols()):
            co.append(H[i,i]//2 if i==j else H[i,j])
    return QuadraticForm(ZZ,H.nrows(),co)

Q8=qform_from_hessian(E8)
roots_half=[vector(ZZ,r) for r in Q8.short_vector_list_up_to_length(2,True)[1]]
roots=[r for r in roots_half if r*E8*ve8==0]
signed=roots+[-r for r in roots]
Lroot=matrix(ZZ,signed).row_module()
Lb=Lroot.basis_matrix()
assert Lb.rank()==4
assert (Lb*E8*Lb.transpose()).det()==9

# Retain the two A2 factors separately so the final MW basis can be assigned
# exact reducible-fiber component classes.
root_graph=Graph()
root_graph.add_vertices(range(len(signed)))
for i in range(len(signed)):
    for j in range(i):
        if signed[i]*E8*signed[j] != 0:
            root_graph.add_edge(i,j)
root_components=sorted(root_graph.connected_components(sort=False),key=len)
assert [len(component) for component in root_components]==[6,6]
broken_component_bases=[
    matrix(ZZ,[signed[index] for index in component]).row_module().basis_matrix()
    for component in root_components
]
assert all(basis.rank()==2 for basis in broken_component_bases)
assert all((basis*E8*basis.transpose()).det()==3 for basis in broken_component_bases)

# Trivial lattice in ambient NS coordinates: U + A2^2 + E8 + A2.
triv=[]
for i in range(2):
    e=vector(ZZ,[0]*20); e[i]=1; triv.append(e)
for r in Lb.rows():
    e=vector(ZZ,[0]*20)
    for j,x in enumerate(r): e[2+j]=x
    triv.append(e)
for i in range(8):
    e=vector(ZZ,[0]*20); e[10+i]=1; triv.append(e)
for i in range(2):
    e=vector(ZZ,[0]*20); e[18+i]=1; triv.append(e)
Triv=matrix(ZZ,triv)
assert Triv.rank()==16

# Exact generic essential intersection C3 = S ∩ Triv^\perp in ambient coordinates.
constraints=matrix(ZZ,list((Triv*NS).rows())+[list(w*NS)])
C3=constraints.right_kernel_matrix()
assert C3.rank()==3
G3=C3*NS*C3.transpose()
print(f"MWGLUE|stage=essential_intersection|G3={G3}|det={G3.det()}",flush=True)

# Build A = Triv + C3 inside S.  All rows lie in S.
Aamb=block_matrix([[Triv],[C3]], subdivide=False)
assert Aamb.rank()==19
assert all((r*NS*w)==0 for r in Aamb.rows())

# Convert ambient NS vectors to coordinates in S basis K.
# K is 19x20 full row rank. Solve K^T c^T = v^T.
def coords_in_S(v):
    c=K.transpose().solve_right(vector(QQ,v))
    if not all(QQ(x).denominator()==1 for x in c):
        raise RuntimeError(f"vector not integral in S basis: {c}")
    return vector(ZZ,[ZZ(x) for x in c])

Acoords=matrix(ZZ,[coords_in_S(r) for r in Aamb.rows()])
assert Acoords.det()!=0
idx=abs(Acoords.det())
print(f"MWGLUE|stage=index|index_A_in_S={idx}",flush=True)
assert idx==9

# Smith normal form of inclusion A -> S.
# Row lattice generated by Acoords inside Z^19.
Dsnf,Usnf,Vsnf=Acoords.smith_form()
smith=[abs(ZZ(Dsnf[i,i])) for i in range(19)]
print(f"MWGLUE|stage=smith|diag={smith}",flush=True)
assert prod(smith)==9

# We need actual coset representatives S/A.  HNF gives a canonical reduction.
# Sage row_module quotient APIs vary; enumerate small S-coordinate vectors and
# reduce modulo row lattice A until all 9 cosets are found.
LA=Acoords.row_module()

# Membership test via rational solve against Acoords.
Ainv=Acoords.inverse()
def coset_key(z):
    # Coordinates of z in A basis; fractional parts identify S/A.
    c=vector(QQ,z)*Ainv
    return tuple(QQ(x)-floor(QQ(x)) for x in c)

cosets={}
zero=vector(ZZ,[0]*19)
cosets[coset_key(zero)]=zero
# Unit S basis vectors generate quotient.
changed=True
while changed and len(cosets)<idx:
    changed=False
    current=list(cosets.values())
    for z in current:
        for i in range(19):
            e=vector(ZZ,[0]*19); e[i]=1
            for sgn in (1,-1):
                q=z+sgn*e
                k=coset_key(q)
                if k not in cosets:
                    cosets[k]=q
                    changed=True
                    if len(cosets)==idx: break
            if len(cosets)==idx: break
        if len(cosets)==idx: break
print(f"MWGLUE|stage=cosets|count={len(cosets)}",flush=True)
assert len(cosets)==9

# Projection to essential space = orthogonal complement of Triv over QQ.
# For ambient row x, solve correction x - a*Triv perpendicular to Triv.
GT=Triv*NS*Triv.transpose()
assert GT.det()!=0
GTinv=GT.inverse()

def project_essential(x):
    x=vector(QQ,x)
    pair=x*NS*Triv.transpose()
    a=pair*GTinv
    return x-a*Triv

# Existing C3 spans essential QQ-space.  Express projected cosets in C3 coordinates.
# Gram G3 is nondegenerate, so coordinates from pairings:
# if p = c*C3 then p NS C3^T = c G3.
def essential_coords(p):
    pair=vector(QQ,p)*NS*C3.transpose()
    return pair*G3.inverse()

proj_coords=[]
projected_cosets=[]
for k,zS in cosets.items():
    amb=vector(QQ,zS)*K
    p=project_essential(amb)
    c=essential_coords(p)
    # sanity reconstruct
    assert p==c*C3
    proj_coords.append(c)
    projected_cosets.append((c,zS))
    print(f"MWGLUE|coset|Scoords={tuple(zS)}|essential={tuple(c)}",flush=True)

# Actual MW lattice is generated by Z^3 (C3) plus projected glue cosets.
rows=[vector(QQ,[1,0,0]),vector(QQ,[0,1,0]),vector(QQ,[0,0,1])] + proj_coords
den=lcm([QQ(x).denominator() for r in rows for x in r])
Zrows=matrix(ZZ,[[ZZ(den*x) for x in r] for r in rows])
Lz=Zrows.row_module()
Bz=Lz.basis_matrix()
B=Bz.change_ring(QQ)/den
assert B.nrows()==3

# Height pairing is positive = -intersection on essential space.
HMW=-(B*G3*B.transpose())
print(f"MWGLUE|stage=MW|basis_in_C3={B}",flush=True)
print(f"MWGLUE|height_gram={HMW}|det={HMW.det()}",flush=True)
assert HMW.det()==QQ(316)/9

# Index of C3 inside MW coordinate lattice should be 9.
index=abs(QQ(1)/B.det())
print(f"MWGLUE|index_C3_in_MW={index}",flush=True)
assert index==9

# Try PARI reduction of cleared rational Gram.
gden=lcm([QQ(x).denominator() for x in HMW.list()])
ZG=(gden*HMW).change_ring(ZZ)
print(f"MWGLUE|scaled_height_gram|den={gden}|G={ZG}",flush=True)
try:
    T=matrix(ZZ,pari(ZG).qflllgram())
    # PARI convention can vary; test both orientations.
    candidates=[]
    if T.nrows()==3 and T.ncols()==3:
        for R in (T, T.transpose()):
            Gred=R*ZG*R.transpose()
            if Gred.is_symmetric() and Gred.det()==ZG.det():
                candidates.append((max(abs(x) for x in Gred.list()),Gred,R))
        if candidates:
            _,Gred,R=min(candidates,key=lambda x:x[0])
            print(f"MWGLUE|reduced_scaled_gram={Gred}|transform={R}",flush=True)
except Exception as e:
    print(f"MWGLUE|reduction_warning={e}",flush=True)

# Pin a reduced basis and recover its three A2 component profiles.  The first
# two A2 factors are the broken E8 components; the third is the original A2.
target_scaled=matrix(ZZ,[[8,-1,0],[-1,10,0],[0,0,12]])
reduced_transform=matrix(ZZ,[[-8,3,3],[-1,1,0],[3,0,-2]])
assert reduced_transform.det()==1
assert reduced_transform*ZG*reduced_transform.transpose()==target_scaled
target_basis=reduced_transform*B
assert target_basis*(-G3)*target_basis.transpose()==target_scaled/3

triv_components=[]
for i in range(2):
    e=vector(ZZ,[0]*20); e[i]=1; triv_components.append(e)
for basis in broken_component_bases:
    for root in basis.rows():
        e=vector(ZZ,[0]*20)
        for j,x in enumerate(root): e[2+j]=x
        triv_components.append(e)
for i in range(8):
    e=vector(ZZ,[0]*20); e[10+i]=1; triv_components.append(e)
for i in range(2):
    e=vector(ZZ,[0]*20); e[18+i]=1; triv_components.append(e)
TrivComponents=matrix(ZZ,triv_components)
assert TrivComponents.row_module()==Triv.row_module()
GTrivComponents=TrivComponents*NS*TrivComponents.transpose()

component_bounds=((2,4),(4,6),(14,16))
root_classes=[]
for target_vector in target_basis.rows():
    lift=None
    for projected,zS in projected_cosets:
        difference=target_vector-projected
        if all(QQ(value).denominator()==1 for value in difference):
            lift=vector(QQ,zS)*K+difference*C3
            break
    assert lift is not None
    essential=target_vector*C3
    trivial_part=lift-essential
    trivial_coordinates=(
        trivial_part*NS*TrivComponents.transpose()*GTrivComponents.inverse()
    )
    assert trivial_part==trivial_coordinates*TrivComponents
    root_classes.append([
        tuple(value-floor(value) for value in trivial_coordinates[left:right])
        for left,right in component_bounds
    ])

def class_multiple(multiplier,point):
    return tuple(multiplier*value-floor(multiplier*value) for value in point)

profiles=[[] for _ in range(3)]
for component in range(3):
    classes=[root_classes[row][component] for row in range(3)]
    zero=tuple(QQ(0) for _ in classes[0])
    if all(point==zero for point in classes):
        for row in range(3): profiles[row].append(0)
        continue
    generator=next(point for point in classes if point!=zero)
    assert class_multiple(3,generator)==zero
    for row,point in enumerate(classes):
        label=next(
            multiplier for multiplier in range(3)
            if class_multiple(multiplier,generator)==point
        )
        profiles[row].append(label)
profiles=tuple(tuple(profile) for profile in profiles)
nonzero_counts=tuple(sum(label!=0 for label in profile) for profile in profiles)
assert nonzero_counts==(2,1,0)

def a2_bilinear(label1,label2):
    if label1==0 or label2==0: return QQ(0)
    return QQ(2)/3 if label1==label2 else QQ(1)/3

pair_intersections={}
for i in range(3):
    for j in range(i):
        correction=QQ(0)
        for component in range(3):
            correction += a2_bilinear(
                profiles[i][component],profiles[j][component]
            )
        # For a K3 and P_i.O=P_j.O=0:
        # <P_i,P_j> = 2 - P_i.P_j - sum(component corrections).
        intersection=QQ(2)-correction-QQ(target_scaled[i,j])/3
        pair_intersections[(j+1,i+1)]=intersection
assert set(pair_intersections.values())=={QQ(2)}
print(
    "MWGLUE|profiles="+";".join(
        f"P{index+1}:"+",".join(map(str,profile))
        for index,profile in enumerate(profiles)
    ),
    flush=True,
)
print(f"MWGLUE|profile_nonzero_counts={nonzero_counts}|heights=8/3,10/3,4",flush=True)
print("MWGLUE|pair_intersections=P1.P2=2,P1.P3=2,P2.P3=2",flush=True)

(OUT/"mw-rank3-exact-glue.txt").write_text(
    f"index={idx}\n"
    f"smith={smith}\n"
    f"C3_intersection_gram={G3}\n"
    f"MW_basis_in_C3={B}\n"
    f"MW_height_gram={HMW}\n"
    f"reduced_3height_gram={target_scaled}\n"
    f"component_profiles={profiles}\n"
    f"pair_intersections={pair_intersections}\n"
    f"det={HMW.det()}\n"
)
print(f"MWGLUE|stage=done|out={OUT/'mw-rank3-exact-glue.txt'}",flush=True)
