from sage.all import *
from pathlib import Path
import itertools

OUT=Path("artifacts/local/elkies-k3")
OUT.mkdir(parents=True,exist_ok=True)

# Positive essential lattice from the previous exact computation.
G=matrix(ZZ,[
[4,4,-20],
[4,34,73],
[-20,73,412],
])
assert G.det()==2844

TARGET_DET=QQ(316)/9
INDEX=9
assert QQ(G.det())/(INDEX^2)==TARGET_DET

print(f"MWSAT|stage=start|det_sub={G.det()}|index={INDEX}|target_det={TARGET_DET}",flush=True)

# Discriminant group L*/L represented by G^{-1} z mod Z^3.
Gi=G.inverse()
D,U,V=G.smith_form()
diag=[abs(ZZ(D[i,i])) for i in range(3)]
print(f"MWSAT|smith={diag}|disc_order={prod(diag)}",flush=True)

def mod1(q):
    q=QQ(q)
    return q-floor(q)

def key_frac(v):
    return tuple(mod1(QQ(x)) for x in v)

def order_modZ(v):
    return lcm([QQ(x).denominator() for x in v])

def qmod2(v):
    # q(x)=x G x /? Height pairing Gram is G, so discriminant quadratic
    # form uses x^T G x modulo 2Z for integral even lattice.
    return QQ(v*G*v) - 2*floor(QQ(v*G*v)/2)

def bmod1(v,w):
    return mod1(QQ(v*G*w))

# Enumerate all discriminant classes via z representatives in a box derived from SNF.
# Easier and robust in rank 3: enumerate z_i modulo det then dedupe G^-1 z mod Z.
classes={}
# Generate using combinations of columns of G^-1 with coefficients up to SNF invariants.
gens=[Gi*vector(ZZ,[1 if i==j else 0 for i in range(3)]) for j in range(3)]
# BFS additive closure to avoid 2844^3.
zero=vector(QQ,[0,0,0])
queue=[zero]
classes[key_frac(zero)]=zero
head=0
while head<len(queue):
    x=queue[head]; head+=1
    for g in gens:
        y=x+g
        k=key_frac(y)
        if k not in classes:
            # canonical fractional representative
            yc=vector(QQ,list(k))
            classes[k]=yc
            queue.append(yc)
assert len(classes)==abs(G.det())
print(f"MWSAT|disc_classes={len(classes)}",flush=True)

# An integral overlattice of index 9 corresponds to an isotropic subgroup H
# of A_L of order 9 for the discriminant bilinear/quadratic form.
iso=[v for v in classes.values() if qmod2(v)==0]
print(f"MWSAT|isotropic_elements={len(iso)}",flush=True)

# Build cyclic order-9 subgroups and Z/3 x Z/3 subgroups, dedupe by class keys.
subgroups={}
def addkey(a,b):
    return key_frac(a+b)

def cyclic_subgroup(v):
    cur=zero
    out=[]
    for k in range(order_modZ(v)):
        out.append(key_frac(cur))
        cur=cur+v
    return frozenset(out)

for v in iso:
    if order_modZ(v)==9:
        H=cyclic_subgroup(v)
        if len(H)==9:
            subgroups[H]=("Z9",v)

iso3=[v for v in iso if order_modZ(v)==3]
for i,v in enumerate(iso3):
    for w in iso3[i+1:]:
        if bmod1(v,w)!=0: continue
        elems=set()
        for a in range(3):
            for b in range(3):
                elems.add(key_frac(a*v+b*w))
        if len(elems)==9:
            H=frozenset(elems)
            subgroups.setdefault(H,("Z3xZ3",(v,w)))

print(f"MWSAT|isotropic_subgroups_order9={len(subgroups)}",flush=True)

def overlattice_from_H(H):
    # L' generated by Z^3 plus fractional discriminant representatives in H.
    rows=[vector(QQ,[1,0,0]),vector(QQ,[0,1,0]),vector(QQ,[0,0,1])]
    rows += [classes[k] for k in H if k!=(QQ(0),QQ(0),QQ(0))]
    den=lcm([QQ(x).denominator() for r in rows for x in r])
    Zmat=matrix(ZZ,[[ZZ(den*x) for x in r] for r in rows])
    Lz=Zmat.row_module()
    Bz=Lz.basis_matrix()
    B=Bz.change_ring(QQ)/den
    # B rows form basis of overlattice in original coordinates.
    GG=B*G*B.transpose()
    return B,GG

good=[]
for idx,(H,desc) in enumerate(subgroups.items()):
    B,GG=overlattice_from_H(H)
    det=QQ(GG.det())
    if det!=TARGET_DET: continue
    # Height pairing only needs positive definite rational Gram.
    if not GG.is_positive_definite(): continue
    good.append((desc,B,GG))
    print(f"MWSAT|candidate={len(good)}|type={desc[0]}|det={det}|B={B}|Gram={GG}",flush=True)

print(f"MWSAT|stage=candidates|count={len(good)}",flush=True)

# Reduce each rational Gram by clearing denominator and LLL, then transform back.
lines=[]
for i,(desc,B,GG) in enumerate(good,1):
    den=lcm([QQ(x).denominator() for x in GG.list()])
    ZG=(den*GG).change_ring(ZZ)
    # LLL transformation for positive definite Gram: use matrix whose rows are a lattice
    # basis for Cholesky is awkward; use quadratic form reduced_form if available.
    red=None
    try:
        # PARI qflllgram gives unimodular transformation.
        T=matrix(ZZ, pari(ZG).qflllgram())
        if T.nrows()==3:
            red=(T.transpose()*ZG*T) if (T.transpose()*ZG*T).is_symmetric() else None
    except Exception:
        pass
    print(f"MWSAT|final={i}|type={desc[0]}|den={den}|gram={GG}",flush=True)
    if red is not None:
        print(f"MWSAT|final_reduced={i}|scaled_gram={red}|scale={den}",flush=True)
    lines.append(f"candidate={i}\ntype={desc[0]}\nB={B}\nGram={GG}\ndet={GG.det()}\n")

(OUT/"mw-rank3-saturation-candidates.txt").write_text("\n".join(lines))
print(f"MWSAT|stage=done|out={OUT/'mw-rank3-saturation-candidates.txt'}",flush=True)
