#!/usr/bin/env sage
"""Search coherent pair23 gauges generated by explicit secant sections.

The deforming degree-47 q4 class has the pair23 horizontal torsion lift, but
the first marked gauge has genus three.  On every compact fourth-child cubic
this script closes the five known rational sections under one secant, records
their values in the pair23 projection, recognizes those values over GF(73)(T)
with eight withheld samples, and tests every pair as a global affine gauge.

This is a finite exact equation search.  A degree-four squarefree branch hit
is a genus-one candidate; its Kodaira/root signature still requires the
unit-corrected Jacobian audit.
"""

import glob
import hashlib
import json
from itertools import combinations
from pathlib import Path

from sage.all import GF, PolynomialRing, gcd


ROOT = Path(__file__).resolve().parents[2]
PAIR23 = (
    ROOT / "artifacts/generated-results/"
    "q80-fifth-q4-marked-projection-pair23-gf73.json"
)
pair23_bytes = PAIR23.read_bytes()
assert hashlib.sha256(pair23_bytes).hexdigest() == (
    "6e9952d0a8c4748a499cd881585a615ce8b6538687779b69b536783a9c242f2e"
)
pair23 = json.loads(pair23_bytes)

finite = GF(73, impl="modn")
plane_ring = PolynomialRing(finite, names=("v", "w", "u"))
v, w, u = plane_ring.gens()
root_ring = PolynomialRing(finite, "z")
z = root_ring.gen()
parameter_ring = PolynomialRing(finite, "t")
t = parameter_ring.gen()


def polynomial_from_terms(rows):
    return plane_ring({tuple(row[:-1]): finite(row[-1]) for row in rows})


def depressed_plane(payload):
    plane = polynomial_from_terms(
        payload["plane_cubic_terms_v_w_u_coefficient"]
    )
    translation = (
        plane.monomial_coefficient(v*w**2)*v
        + plane.monomial_coefficient(w**2)
    )/finite(3)
    result = plane_ring(plane(w=w-translation))
    assert result.monomial_coefficient(v*w**2) == 0
    assert result.monomial_coefficient(w**2) == 0
    return result


def line_third_point(plane, left, right):
    left_v, left_w = left
    right_v, right_w = right
    if left_v == right_v:
        raise ZeroDivisionError("vertical secant")
    slope = (right_w-left_w)/(right_v-left_v)
    line = left_w+slope*(z-left_v)
    intersection = root_ring(sum(
        coefficient*z**exponents[0]*line**exponents[1]
        for exponents, coefficient in plane.dict().items()
    ))
    quotient, remainder = intersection.quo_rem(
        (z-left_v)*(z-right_v)
    )
    if remainder or quotient.degree() != 1:
        raise ArithmeticError("secant residual point failure")
    third_v = -quotient[0]/quotient[1]
    third_w = left_w+slope*(third_v-left_v)
    assert plane(v=third_v, w=third_w) == 0
    return third_v, third_w


def nullspace(rows, column_count):
    reduced = [list(map(finite, row)) for row in rows]
    pivots = []
    pivot_row = 0
    for column in range(column_count):
        source = next(
            (row for row in range(pivot_row, len(reduced))
             if reduced[row][column]), None
        )
        if source is None:
            continue
        reduced[pivot_row], reduced[source] = reduced[source], reduced[pivot_row]
        scale = reduced[pivot_row][column]**(-1)
        reduced[pivot_row] = [scale*value for value in reduced[pivot_row]]
        for row in range(len(reduced)):
            if row == pivot_row or not reduced[row][column]:
                continue
            scale = reduced[row][column]
            reduced[row] = [
                left-scale*right
                for left, right in zip(reduced[row], reduced[pivot_row])
            ]
        pivots.append(column)
        pivot_row += 1
    free = [column for column in range(column_count) if column not in pivots]
    basis = []
    for free_column in free:
        row = [finite(0)]*column_count
        row[free_column] = finite(1)
        for index, pivot in enumerate(pivots):
            row[pivot] = -reduced[index][free_column]
        basis.append(row)
    return basis, len(pivots)


def rational_interpolate(values, withheld=8, max_total_degree=24):
    values = sorted(values)
    if len(values) <= withheld+2:
        return None
    training = values[:-withheld]
    for total_degree in range(max_total_degree+1):
        candidates = []
        for numerator_degree in range(total_degree+1):
            denominator_degree = total_degree-numerator_degree
            unknowns = numerator_degree+denominator_degree+2
            if unknowns > len(training)+1:
                continue
            rows = []
            for parameter, value in training:
                parameter = finite(parameter)
                rows.append(
                    [parameter**degree for degree in range(numerator_degree+1)]
                    + [-value*parameter**degree
                       for degree in range(denominator_degree+1)]
                )
            basis, rank = nullspace(rows, unknowns)
            if len(basis) != 1:
                continue
            row = basis[0]
            numerator = parameter_ring(row[:numerator_degree+1])
            denominator = parameter_ring(row[numerator_degree+1:])
            if not denominator:
                continue
            if any(
                denominator(finite(parameter)) == 0
                or numerator(finite(parameter))
                   != value*denominator(finite(parameter))
                for parameter, value in values
            ):
                continue
            scale = denominator[denominator.degree()]**(-1)
            candidates.append((
                numerator_degree, denominator_degree,
                len(values)-rank, numerator*scale, denominator*scale,
            ))
        if len(candidates) == 1:
            return candidates[0]
        if candidates:
            return None
    return None


value_samples = {}
sample_parameters = []
for path_string in sorted(glob.glob(str(
    ROOT / "artifacts/generated-results/"
    "q80-fifth-q4-compensated-projection-gf73-T*.json"
))):
    payload = json.loads(Path(path_string).read_text())
    point_rows = payload.get("explicit_section_points")
    if not point_rows or any(row.get("at_v_infinity") for row in point_rows):
        continue
    parameter = int(payload["T"])
    points = tuple(
        (finite(row["v"]), finite(row["w_depressed"])) for row in point_rows
    )
    plane = depressed_plane(payload)
    try:
        center = line_third_point(plane, points[2], points[3])
        center_v, center_w = center

        def raw_slope(point):
            if point[0] == center_v:
                raise ZeroDivisionError("point over projection center")
            return (point[1]-center_w)/(point[0]-center_v)

        slope_zero = raw_slope(points[0])
        slope_scale = raw_slope(points[1])-slope_zero
        if not slope_scale:
            raise ZeroDivisionError("pair01 slopes coincide")

        def marked_value(point):
            return (raw_slope(point)-slope_zero)/slope_scale

        candidates = {
            "P0": points[0],
            "P1": points[1],
            "P4": points[4],
        }
        for left, right in combinations(range(5), 2):
            if (left, right) == (2, 3):
                continue
            try:
                candidates[f"L{left}{right}"] = line_third_point(
                    plane, points[left], points[right]
                )
            except (ArithmeticError, ZeroDivisionError):
                continue
        for key, point in candidates.items():
            try:
                value_samples.setdefault(key, []).append(
                    (parameter, marked_value(point))
                )
            except ZeroDivisionError:
                pass
        sample_parameters.append(parameter)
    except (ArithmeticError, ZeroDivisionError):
        continue

recognized = {}
for key, values in sorted(value_samples.items()):
    candidate = rational_interpolate(values)
    if candidate is None:
        continue
    numerator_degree, denominator_degree, margin, numerator, denominator = candidate
    canonical = (tuple(numerator.list()), tuple(denominator.list()))
    recognized.setdefault(canonical, {
        "keys": [],
        "numerator": numerator,
        "denominator": denominator,
        "degrees": (numerator_degree, denominator_degree),
        "margin": margin,
    })["keys"].append(key)
    print(
        "Q80PAIR23SECANT|"
        f"key={key}|samples={len(values)}|degrees={numerator_degree},{denominator_degree}|"
        f"margin={margin}|value=({numerator})/({denominator})|status=PASS_RECOGNIZED",
        flush=True,
    )

branch_ring = PolynomialRing(finite, names=("T", "U"))
T, U = branch_ring.gens()
integral_cover = sum(
    finite(coefficient)*T**t_degree*U**u_degree
    for t_degree, u_degree, coefficient
    in pair23["integral_double_cover_terms_T_U_coefficient"]
)
branch_factor = next(
    factor for factor, exponent in integral_cover.factor()
    if factor.degree(T) == 8 and exponent == 1
)
gauge_ring = PolynomialRing(finite, names=("S", "X"))
S, X = gauge_ring.gens()

functions = list(recognized.values())
gauge_rows = []
for left_index, right_index in combinations(range(len(functions)), 2):
    left = functions[left_index]
    right = functions[right_index]
    left_num = gauge_ring(left["numerator"](X))
    left_den = gauge_ring(left["denominator"](X))
    right_num = gauge_ring(right["numerator"](X))
    right_den = gauge_ring(right["denominator"](X))
    denominator = left_den*right_den
    numerator = left_num*right_den*(1-S)+right_num*left_den*S
    transformed = sum(
        gauge_ring(coefficient)*X**t_degree
        *numerator**u_degree*denominator**(4-u_degree)
        for (t_degree, u_degree), coefficient in branch_factor.dict().items()
    )
    factorization = tuple(transformed.factor())
    odd_degree = sum(
        factor.degree(X) for factor, exponent in factorization
        if int(exponent) % 2
    )
    row = {
        "left_keys": left["keys"],
        "right_keys": right["keys"],
        "squarefree_degree_T": int(odd_degree),
        "factor_degrees_exponents": [
            [int(factor.degree(X)), int(exponent)]
            for factor, exponent in factorization
        ],
    }
    if odd_degree in (3, 4):
        row["integral_double_cover_terms_T_U_coefficient"] = [
            [int(exponents[1]), int(exponents[0]), int(coefficient)]
            for exponents, coefficient in sorted(transformed.dict().items())
        ]
    gauge_rows.append(row)
    if odd_degree <= 6:
        print(
            "Q80PAIR23SECANT|"
            f"left={tuple(left['keys'])}|right={tuple(right['keys'])}|"
            f"factor_degrees={tuple(map(tuple, row['factor_degrees_exponents']))}|"
            f"squarefree_degree_T={odd_degree}|"
            f"status={'HIT_GENUS_ONE' if odd_degree in (3,4) else 'LOW_GENUS_CONTROL'}",
            flush=True,
        )

payload = {
    "schema": "q80-pair23-secant-reference-gauge-search-gf73-v1",
    "status": "finite_exact_one_secant_closure_search",
    "prime": 73,
    "sample_parameters": sorted(set(sample_parameters)),
    "minimum_withheld": 8,
    "recognized_function_count": len(functions),
    "recognized_functions": [
        {
            "keys": row["keys"],
            "numerator_coefficients_low_to_high": list(map(int, row["numerator"].list())),
            "denominator_coefficients_low_to_high": list(map(int, row["denominator"].list())),
            "degrees": list(map(int, row["degrees"])),
            "equation_margin": int(row["margin"]),
        }
        for row in functions
    ],
    "gauges": gauge_rows,
    "genus_one_hits": [
        row for row in gauge_rows if row["squarefree_degree_T"] in (3, 4)
    ],
    "rank_claim": None,
    "reproduce": (
        "sage elkies-k3/scripts/"
        "search_q80_pair23_secant_reference_gauges_gf73.sage"
    ),
}
output = (
    ROOT / "artifacts/local/"
    "q80-pair23-secant-reference-gauge-search-gf73.json"
)
output.write_text(json.dumps(payload, indent=2, sort_keys=True, default=int)+"\n")
print(
    "Q80PAIR23SECANT|"
    f"recognized={len(functions)}|gauges={len(gauge_rows)}|"
    f"genus_one_hits={len(payload['genus_one_hits'])}|artifact={output}|"
    "status=PASS_FINITE_EXACT_SEARCH",
    flush=True,
)
