#!/usr/bin/env python3
"""Classify the eight multiplier classes generated by one cubic unit orbit."""
import argparse
from fractions import Fraction as F
from pathlib import Path
import retrospective as r
import nonscalar_cup_control as ex
import nonscalar_unramified_lifts as lifts
import verify_nonscalar_cup_control as a

OUTPUT=r.OUT/"rank_jump_nonscalar_cup_orbit_v1.json"
one=[F(1),F(0),F(0)]
theta=[F(0),F(1),F(0)]


def substitute(poly,value):
    out=[F(0)]*3;power=one
    for c in poly:
        out=[x+c*y for x,y in zip(out,power)]
        power=a.mul(power,value)
    return out


def build(check=False):
    source=r.read(ex.OUTPUT);proof=r.read(lifts.OUTPUT)
    assert proof["status"]=="PASS" and proof["analysis_sha256"]==r.digest(ex.OUTPUT.read_bytes())
    derivative=[F(-14),F(-22),F(3)]
    inv=lifts.inverse(derivative)
    conjugate=[(F(c)+163*v)/2 for c,v in zip([11,-1,0],inv)]
    assert substitute(a.POLY,conjugate)==[0,0,0]
    second=substitute(conjugate,conjugate)
    assert substitute(conjugate,second)==theta and conjugate!=theta and second!=theta
    roots=[theta,conjugate,second]
    units=[[-x-y for x,y in zip(one,t)] for t in roots]
    assert a.mul(a.mul(units[0],units[1]),units[2])==one
    assert all(a.norm(u)==1 for u in units)
    # The conjugate real sign vectors are the three nonzero even-parity vectors.
    signs=[6,5,3]
    assert r.rank(signs)==2 and signs[0]^signs[1]^signs[2]==0
    assert r.rank(signs[:2]+[7])==3
    assert source["records"][1]["matrix"]==[[0,0],[0,0]]
    H=r.read(ex.old.CONTROL)["independent_norm_cup_matrix"]
    assert H==[[0,1],[1,0]]
    rows=[]
    for mask in range(8):
        gamma=one
        for j,g in enumerate(units[:2]+[[-1,0,0]]):
            if mask>>j&1:gamma=a.mul(gamma,g)
        negative=(mask>>2)&1;norm=a.norm(gamma)
        assert norm==(-1 if negative else 1)
        rows.append({"mask":mask,"gamma":list(map(str,gamma)),"norm":str(norm),
                     "cup_matrix":H if negative else [[0,0],[0,0]],
                     "unramified_norm_image_dimension_on_U":0 if negative else 2,
                     "derivation":"Galois equivariance and cup bilinearity from the two independently verified matrices"})
    out={"schema":"rank-jump.nonscalar-cup-orbit.v1","status":"PASS",
         "automorphism_theta":list(map(str,conjugate)),"unit_conjugates":list(map(lambda x:list(map(str,x)),units)),
         "multiplier_class_dimension":3,"norm_one_class_dimension":2,"records":rows,
         "control_sha256":r.digest(ex.OUTPUT.read_bytes()),"explicit_lifts_sha256":r.digest(lifts.OUTPUT.read_bytes()),
         "producer_sha256":r.digest(Path(__file__).read_bytes()),
         "boundary":"Exact on this eight-class unit subgroup in the cyclic cubic control; no S3 production-family criterion."}
    if check:assert out==r.read(OUTPUT)
    else:r.write_new(OUTPUT,out)
    print("PASS eight multiplier classes: norm sign determines the two-dimensional unramified norm image")
    print(list(map(str,conjugate)))


if __name__=="__main__":
    parser=argparse.ArgumentParser();parser.add_argument("--check",action="store_true")
    build(parser.parse_args().check)
