#!/usr/bin/env python3
"""Render the analysis-owned CSV and per-fibre table, never repository STATUS.md."""
import argparse
import csv
import io
from pathlib import Path
import retrospective as r
import blocks

CSV=r.OUT/'rank_jump_comparison_panel_v1.csv'
TABLE=Path(__file__).resolve().parent/'FIBRE_REPORTS.md'


def render(check=False):
    d=r.read(r.RESULT);b=r.read(blocks.OUTPUT)
    maps={x['id']:x for x in d['chart_maps']}
    heights={x['id'] for x in b['height_profiles']}
    fields=['id','family','parameter','rank_lower_bound','reference_rank','certified_free_quotient_rank',
      'full_rank_upper_bound','epsilon_scope','origin','galois_group','coefficient_bits','score_units','chart_count']
    stream=io.StringIO(newline='');writer=csv.DictWriter(stream,fieldnames=fields,lineterminator="\n");writer.writeheader()
    lines=['# Per-fibre rank-jump reports','',
      'Generated by `python3 elliptic-curves/rank-jump/render.py`. See [the analysis](ANALYSIS.md) for definitions and causal limits.',
      '', 'Every +d below is the exact free rank of a certified witness quotient and a lower bound for the full quotient. All full rank upper bounds and target Selmer complements are UNKNOWN. The soluble spans are proved; whether their generators arise through a common arithmetic construction remains UNKNOWN on every row. All 91 main-panel rows have S3 two-division Galois group and epsilon_M=0. Repeated curve presentations are identified in the block artifact.', '',
      '| Fibre / marked family | Reference rank | Certified +d | Largest one-chart image rank | Greedy chart span cover | Height projection available |',
      '|---|---:|---:|---:|---|---|']
    for x in sorted(d['panel'],key=lambda x:(-x['certified_independent_quotient_rank_exact'],x['id'])):
        q=x['certified_independent_quotient_rank_exact']
        writer.writerow(dict(zip(fields,[x['id'],x['family'],x['parameter'],x['curve_rank_lower_bound'],x['generic_subgroup_rank_exact'],q,
           'UNKNOWN','full epsilon_M=0',x['origin'],x['galois']['galois_group'],x['short_coefficient_bits'],x['score_units'],x['chart_count']])))
        if q>=5:
            m=maps.get(x['id'])
            largest=m['maximum_single_chart_rank'] if m else 'unmapped'
            cover=', '.join(str(i+1) for i in m['greedy_span_cover_chart_indices']) if m else 'unmapped'
            lines.append(f"| {x['id']} | {x['generic_subgroup_rank_exact']} | {q} | {largest} | {cover} | {'yes (numerical)' if x['id'] in heights else 'not in new audit'} |")
    lines+=['','Chart numbers are one-based. Greedy cover refers to spanning the observed finite Kummer image; it is not claimed minimal. A chart is a birational presentation, not an exceptional Selmer class. No chart allocation follows from this retrospective table.','',
      '## Earlier MW12 families','',
      '| Fibre | Generic rank | Free quotient in displayed L | dim (L/M)[2] | dim (L/M)/2 |',
      '|---|---:|---:|---:|---:|']
    for x in b['legacy_comparison_panel']:
        writer.writerow(dict(zip(fields,[x['id'],x['family'],x['parameter'],x['curve_rank_lower_bound'],x['generic_rank'],x['free_quotient_rank_inside_displayed_L'],
          'UNKNOWN','inside L only: '+str(x['two_torsion_dimension_of_L_over_M']),'historic_oracle',x['galois']['galois_group'],'','',''])))
        lines.append(f"| {x['id']} | {x['generic_rank']} | {x['free_quotient_rank_inside_displayed_L']} | {x['two_torsion_dimension_of_L_over_M']} | {x['tensor_mod2_dimension_of_L_over_M']} |")
    lines+=['','These Smith calculations replay integer subgroup embeddings. They do not certify full Mordell–Weil saturation. Fermigier E22’s weight-two K11 matroid is generated from a chosen exceptional basis; it is not a point-blind construction of ten directions.','',
      '## Record curves without a certified parent in this panel','',
      'Curves 273 and 302 have certified lower bounds 30 and 31. Their masked rank-17 coordinate subgroups leave displayed quotients of dimensions 13 and 14, but those are not certified generic subgroups of a recovered family. Their family-relative jumps remain UNKNOWN here. On the prefix-d17 controls, the initial wave recovered 10/13 and 3/14 respectively; changing the selected coordinates changes recovery.']
    for cid,rank in [('ICARM-273',30),('ICARM-302',31)]:
        writer.writerow(dict(zip(fields,[cid,'UNKNOWN','',''+str(rank),'UNKNOWN','UNKNOWN','UNKNOWN','selected coordinate subgroup is not generic','historic_masked_control','not recomputed','','',''])))
    outputs={CSV:stream.getvalue(),TABLE:'\n'.join(lines)+'\n'}
    for path,text in outputs.items():
        if check:
            if path.read_text()!=text:raise ValueError('render mismatch '+str(path))
        else:
            with path.open('x') as f:f.write(text)
    print('PASS render comparison' if check else 'Rendered panel and fibre reports')

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();render(a.check)
