/-
Copyright (c) 2026 Roy van Rijn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Roy van Rijn
-/
import FiniteEtaleKeller.ExplicitFiber
import FiniteEtaleKeller.GeneratedPaperExample

/-!
# Paper-to-Lean correspondence for the explicit quintic

The generated definitions in `GeneratedPaperExample` are rendered from the
same JSON specification as the TeX, SymPy, Sage, and portable JSON views.
The theorems here close the human-risk interface by comparing those generated
paper definitions with the independently authored Lean development.
-/

noncomputable section

open Matrix Function
open MvPolynomial

namespace FiniteEtaleKeller.ExplicitQuintic

open FiniteEtaleKeller.GeneratedPaperExample

/-- The polynomial displayed in the paper is exactly Lean's `p5`. -/
theorem p5_eq_generatedPaperP5 : p5 = paperP5 := by
  rfl

/-- The translated seed displayed in the paper is exactly Lean's `g5`. -/
theorem g5_eq_generatedPaperG5 : g5 = paperG5 := by
  rfl

/-- The paper abbreviation `t = 1 + xy` is definitionally Lean's `t`. -/
theorem t_eq_generatedPaperT : t = paperT := rfl

/-- The paper abbreviation `q` is definitionally Lean's recurrent `q`. -/
theorem q_eq_generatedPaperQ : q = paperQ := rfl

/-- All three displayed TeX coordinates are literally Lean's integral map. -/
theorem integralMap_eq_generatedPaperMap :
    integralMap = paperIntegralMap := rfl

/-- The generated normalized target gives exactly Lean's inverse polynomial. -/
theorem generatedPaperInversePolynomial :
    generalGaugeInversePolynomial g5
        (paperNormalizedTarget 0)
        (paperNormalizedTarget 1)
        (paperNormalizedTarget 2) =
      paperP5 := by
  simpa [paperNormalizedTarget, p5_eq_generatedPaperP5] using
    generalGaugeInversePolynomial_explicitTarget

/-- The generated integral target is the coordinatewise image of the
normalized target under the generated output scaling. -/
theorem generatedPaperTarget_scaling :
    paperIntegralTarget =
      fun i => paperIntegralOutputScaling i * paperNormalizedTarget i := by
  funext i
  fin_cases i <;>
    norm_num [paperIntegralTarget, paperIntegralOutputScaling, paperNormalizedTarget]

/-- The distinguished target built into `IntegralFiberPoint` is exactly the
generated paper target in every commutative rational test algebra. -/
theorem integralFiberPoint_eval_eq_generatedTarget
    {A : Type*} [CommRing A] [Algebra ℚ A]
    (p : IntegralFiberPoint A) (i : Fin 3) :
    MvPolynomial.eval₂ (algebraMap ℚ A) p.point (integralMap i) =
      algebraMap ℚ A (paperIntegralTarget i) := by
  fin_cases i
  · simpa [paperIntegralTarget] using p.first_eq
  · simpa [paperIntegralTarget] using p.second_eq
  · simpa [paperIntegralTarget] using p.third_eq

/-- The determinant-one target is generated by the same coordinatewise
normalization that defines `jacobianOneMap`. -/
theorem generatedPaperJacobianOneTarget_scaling :
    paperJacobianOneTarget =
      fun i => paperJacobianOneOutputScaling i * paperNormalizedTarget i := by
  funext i
  fin_cases i <;>
    norm_num [paperJacobianOneTarget, paperJacobianOneOutputScaling,
      paperNormalizedTarget]

/-- The two paper output scalings reproduce the formal integral and
Jacobian-one maps from the same normalized map. -/
theorem generatedPaper_map_scalings :
    integralMap =
        scaleOutput
          (paperIntegralOutputScaling 0)
          (paperIntegralOutputScaling 1)
          (paperIntegralOutputScaling 2)
          normalizedMap ∧
      jacobianOneMap =
        scaleOutput
          (paperJacobianOneOutputScaling 0)
          (paperJacobianOneOutputScaling 1)
          (paperJacobianOneOutputScaling 2)
          normalizedMap := by
  constructor
  · simpa [paperIntegralOutputScaling] using integralMap_eq_scaled_normalized
  · rfl

/-- The final diagonal scaling displayed in the paper sends its integral map
to Lean's determinant-one map. -/
theorem generatedPaper_integral_to_jacobianOne :
    scaleOutput
        (paperIntegralToJacobianOneScaling 0)
        (paperIntegralToJacobianOneScaling 1)
        (paperIntegralToJacobianOneScaling 2)
        integralMap =
      jacobianOneMap := by
  rw [integralMap_eq_scaled_normalized]
  funext i
  fin_cases i
  · change
      MvPolynomial.C (1 : ℚ) *
          (MvPolynomial.C 1 * normalizedMap 0) =
        MvPolynomial.C 1 * normalizedMap 0
    simp
  · change
      MvPolynomial.C (-1 / 38 : ℚ) *
          (MvPolynomial.C 19 * normalizedMap 1) =
        MvPolynomial.C (-1 / 2 : ℚ) * normalizedMap 1
    rw [← mul_assoc, ← MvPolynomial.C_mul]
    norm_num
  · change
      MvPolynomial.C (1 / 19 : ℚ) *
          (MvPolynomial.C 19 * normalizedMap 2) =
        MvPolynomial.C 1 * normalizedMap 2
    rw [← mul_assoc, ← MvPolynomial.C_mul]
    norm_num

#print axioms p5_eq_generatedPaperP5
#print axioms g5_eq_generatedPaperG5
#print axioms integralMap_eq_generatedPaperMap
#print axioms generatedPaperInversePolynomial
#print axioms generatedPaperTarget_scaling
#print axioms integralFiberPoint_eval_eq_generatedTarget
#print axioms generatedPaperJacobianOneTarget_scaling
#print axioms generatedPaper_map_scalings
#print axioms generatedPaper_integral_to_jacobianOne

end FiniteEtaleKeller.ExplicitQuintic
