#!/usr/bin/env sage-python
"""Exact indices of the full known section span over the certified subset."""
import sys,json,argparse
from pathlib import Path
from sage.all import matrix,ZZ,QQ,lcm
ROOT=Path(__file__).resolve().parents[2];CAS=ROOT/'elliptic-curves/cas';sys.path.insert(0,str(CAS))
import certify_compact_r17_candidates as cert
from research_runtime.store import checkpoint
INPUT=ROOT/'artifacts/generated-results/elliptic-curves/endpoint_section_relations_v1.json';OUT=INPUT.with_name('endpoint_section_lattice_indices_v1.json')

def expected():
    data=cert.read(INPUT);rows=[]
    if data['status']!='PASS' or data['completed_span_ranks']!=21:raise ArithmeticError('all exact section-span proofs required')
    for r in data['rows']:
        rank=r['generic_section_span_rank'];coords=matrix(QQ,[[QQ(c)/q['denominator'] for c in q['coefficients']] for q in r['relations']]);den=int(lcm(v.denominator() for v in coords.list()));a=matrix(ZZ,coords*den);h,u=a.hermite_form(transformation=True,include_zero_rows=True)
        if abs(u.det())!=1 or h!=u*a:raise ArithmeticError('integral unimodular section lattice transport differs')
        h0=h[:rank,:]
        if h0.det()==0 or any(h[i,j] for i in range(rank,h.nrows()) for j in range(rank)):raise ArithmeticError('rational section lattice rank differs')
        for j,P in enumerate(r['independent_points']):
            matches=[i for i,Q in enumerate(r['generic_points']) if Q==P]
            if not matches or list(coords.row(matches[0]))!=[int(j==k) for k in range(rank)]:raise ArithmeticError('certified subset identity columns differ')
        index=QQ(den**rank)/abs(h0.det())
        if index.denominator()!=1:raise ArithmeticError('subset lattice inclusion differs')
        rows.append({'family':r['family'],'endpoint':r['endpoint'],'rank':rank,'coordinate_denominator':den,'integer_coordinate_matrix':[list(map(int,row)) for row in a.rows()],'hermite_matrix':[list(map(int,row)) for row in h.rows()],'unimodular_transform':[list(map(int,row)) for row in u.rows()],'index_of_certified_subset_in_known_section_lattice':int(index)})
    return {'schema':'elliptic-curves.endpoint-section-lattice-indices.v1','status':'PASS','sources':{str(p.relative_to(ROOT)):cert.hashed(p) for p in (Path(__file__).resolve(),INPUT)},'rows':rows,'proper_subset_lattices':sum(r['index_of_certified_subset_in_known_section_lattice']>1 for r in rows),'claim_boundary':'Indices concern the two explicitly known subgroups after quotienting torsion: the independently certified subset inside the subgroup generated by all transported generic sections. Exact integer point relations identify rational coordinates, and a checked unimodular Hermite transformation gives the index. This neither saturates the whole Mordell-Weil group nor constructs new points or establishes whole-curve rank. The frozen endpoint point trial continues to use its original subset.'}
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();d=expected()
    if a.check:
        if cert.read(OUT)!=json.loads(json.dumps(d)):raise ArithmeticError('exact section lattice indices differ')
    else:
        if OUT.exists():raise FileExistsError('preserve section lattice indices')
        checkpoint(OUT,d)
    print('ENDPOINT KNOWN SECTION LATTICES',d['proper_subset_lattices'],'proper subset lattices',flush=True)
    print([(r['family'],r['endpoint'],r['index_of_certified_subset_in_known_section_lattice']) for r in d['rows']],flush=True)
