#!/usr/bin/env python3
"""Extract the displayed302 group's 2-saturation from its pinned rank proof.

This derives a subgroup statement from ECR31; it does not rerun the original
finite elliptic groups or prove odd saturation or an exact rank upper bound.
"""
import argparse
import gzip
from hashlib import sha256
import json
from math import gcd
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
SOURCE=ROOT/'artifacts/generated-results/elliptic-curves/icarm_curve302_rank31_v1.json.gz'
OUT=SOURCE.with_name('curve302_displayed_group_parity_domain_v1.json')


def left_inverse(rows,ncols):
    masks=[sum(int(v)<<i for i,v in enumerate(row)) for row in rows]
    changes=[1<<i for i in range(len(rows))];rank=0
    for col in range(ncols):
        pivot=next((i for i in range(rank,len(rows)) if (masks[i]>>col)&1),None)
        assert pivot is not None
        masks[rank],masks[pivot]=masks[pivot],masks[rank]
        changes[rank],changes[pivot]=changes[pivot],changes[rank]
        for i in range(len(rows)):
            if i!=rank and (masks[i]>>col)&1:masks[i]^=masks[rank];changes[i]^=changes[rank]
        rank+=1
    assert masks[:ncols]==[1<<i for i in range(ncols)]
    for col,c in enumerate(changes[:ncols]):
        row=[sum(rows[i][j] for i in range(len(rows)) if (c>>i)&1)%2 for j in range(ncols)]
        assert row==[int(j==col) for j in range(ncols)]
    return changes[:ncols]


def build():
    compressed=SOURCE.read_bytes();assert sha256(compressed).hexdigest()=='fc50b4b9ec5fe1dd1fe31aa299f13d8bc3476d43f3ed98e2ade5a4fc8972aa04'
    data=gzip.decompress(compressed);assert sha256(data).hexdigest()=='3be0d6fe82c58e0f9284df5d9340332944a1d906508ea986d4abe00357036991'
    d=json.loads(data);cert=d['independence_certificate'];assert cert['relation_prime']==2
    rows=[row for signature in cert['signatures'] for row in signature['matrix_rows']]
    assert len(rows)==32 and all(len(r)==31 and set(r)<={0,1} for r in rows)
    inverse=left_inverse(rows,31);cross=d['quadratic_character_cross_check']['matrix_rows'];cross_inverse=left_inverse(cross,31)
    torsion=d['torsion_certificate'];assert gcd(*torsion['finite_group_orders'].values())==1
    return {'schema':'curve302.displayed-parity-domain.v1','status':'PASS_DISPLAYED_GROUP_2_SATURATED',
        'input_sha256':{str(p.relative_to(ROOT)):sha256(p.read_bytes()).hexdigest() for p in [Path(__file__),SOURCE]},
        'source_authority':'ECR31','displayed_rank':31,'binary_matrix_rows':rows,
        'left_inverse_row_masks':inverse,'cross_check_left_inverse_row_masks':cross_inverse,
        'rational_torsion_order':1,
        'statement':'For D generated by the displayed31 points, D intersection 2E(Q)=2D. Consequently D is saturated at every power of2, and every primitive integral sublattice B of D satisfies B intersection 2E(Q)=2B.',
        'proof':'A left inverse to the finite-reduction matrix makes D/2D inject into the product of E(Fp)/2E(Fp). If 2R is in D, its displayed coefficients are even, so 2R=2S for S in D. Trivial rational2-torsion gives R=S. Induct for powers of2. If B is primitive in D and 2R lies in B, the first argument places R in D and primitivity places R in B.',
        'recognition_consequence':'For points Qi in a primitive candidate B, a quartic interpretation Qi=2Ri-C with rational Ri forces every Qi-Q0 into2B. The same-parity test in the integral B coordinates therefore loses no rational halves of such displayed points.',
        'boundary':'This does not prove odd saturation, full Mordell-Weil rank31, generic saturation of a proposed family, or existence of a parent. Finite group arithmetic is inherited from the pinned ECR31 certificate; this checker only replays the binary inverses and derives their consequence.'}


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args();d=build()
    if args.check:assert d==json.loads(OUT.read_text())
    else:OUT.write_text(json.dumps(d,sort_keys=True,indent=2)+'\n')
    print(d['status'])
