#!/usr/bin/env sage-python
"""Independent exact replay of the fixed-bank unit-relation obstruction.

No call to the support-construction script, factoring, or ideal reduction.
The private-prime proof is recorded in the accompanying note.
"""
import hashlib, json, signal
from pathlib import Path
from sage.all import QQ, ZZ, PolynomialRing, pari, matrix, gcd, prod

signal.alarm(25)
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/generated-results/elliptic-curves'
OUT = ART / 'det1092_saved_unit_relations_v1'
def read(path): return json.loads(path.read_text())
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
protocol = read(OUT / 'protocol.json')
for name, expected in protocol['inputs'].items(): assert sha(ROOT / name) == expected
assert sha(ROOT / 'elliptic-curves/cas/audit_det1092_saved_unit_relations.sage') == protocol['script_sha256']
support = read(OUT / 'support.json')
assert support['protocol_sha256'] == sha(OUT / 'protocol.json')
ar = read(ART / 'rank_jump_curve302_strict_constructor_arithmetic_v1.json')
R = PolynomialRing(QQ, 'z')
nf = pari.nfinit([pari(R(ar['cubic_ascending'])), ar['S_finite']])
assert str(nf[2]) == ar['field_discriminant']
assert list(map(str, nf.nf_get_zk())) == ar['maximal_order_basis']
bank = read(ART / 'rank_jump_curve302_arithmetic_unit_class_v1.json')

group_data = {}
for row in support['groups']:
    J = matrix(ZZ, row['matrix'])
    assert J.nrows() == J.ncols() == 3
    assert gcd(J.list()) == 1 and J.det() > 0
    assert pari.idealhnf(nf, pari(J)) == pari(J)
    assert ZZ(pari.idealnorm(nf, pari(J))) == ZZ(row['norm']) == J.det()
    group_data[row['id']] = {'ideal': J, 'norm': J.det(), 'occurrences': []}
assert len(group_data) == 486 and sorted(group_data) == list(range(486))
assert len({tuple(g['ideal'].list()) for g in group_data.values()}) == 486
trial_index = {(r['source'], r['trial']): r for r in support['trials']}
assert len(trial_index) == 567
start_norms = []
checked = 0
scalar_count = 0
for source_index, entry in enumerate(bank['trials']):
    source = read(ROOT / entry['path'])
    I = pari(source['starting_ideal_hnf'])
    start_norms.append(ZZ(pari.idealnorm(nf, I)))
    assert len(source['trials']) == 81
    for index, item in enumerate(source['trials']):
        row = trial_index[source_index, index]
        group = group_data[row['group']]
        content = ZZ(row['content'])
        J = pari(item['reduced_ideal_hnf'])
        a = pari(item['multiplier_GP'])
        assert content > 0 and matrix(QQ, J.sage()) == content * group['ideal']
        assert pari.idealmul(nf, J, a) == I
        algebraic = pari.nfbasistoalg(nf, a)
        group['occurrences'].append((source_index, index))
        if 'representative' not in group:
            group['representative'] = algebraic * content
            group['source'] = source_index
        else:
            assert group['source'] == source_index
            assert algebraic * content / group['representative'] in [1, -1]
        if row['group'] in support['unpeeled_nonunit_groups'] + support['primitive_unit_ideal_groups']:
            # In this particular bank every residual multiplier is exactly1.
            assert algebraic == 1
            scalar_count += 1
        checked += 1

assert list(map(str, start_norms)) == support['starting_norms']
for record in support['groups']:
    assert list(map(list, group_data[record['id']]['occurrences'])) == record['occurrences']
    assert len({s for s, _ in group_data[record['id']]['occurrences']}) == 1
active = {i: g['norm'] for i, g in group_data.items() if g['norm'] != 1}
blocked = abs(ZZ(ar['field_discriminant'])) * prod(start_norms)
for row in support['peeling']:
    i = row['group']
    N = active.pop(i)
    blocker = blocked * prod(active.values())
    private = ZZ(row['private_part'])
    assert private > 1 and N % private == 0 and gcd(private, blocker) == 1
    remainder = N
    for removal in row['removed_gcds']:
        removal = ZZ(removal)
        assert removal > 1 and removal == gcd(remainder, blocker)
        remainder //= removal
    assert remainder == private
assert sorted(active) == support['unpeeled_nonunit_groups']
assert len(support['peeling']) == 479 and len(active) == 6
assert checked == 567 and scalar_count == 88
report = {
    'status': 'PASS_INDEPENDENT_SAVED_BANK_UNIT_RELATION_OBSTRUCTION',
    'classification': 'verified application of the proved private-unramified-prime lemma',
    'exact_ideal_identities': checked,
    'distinct_primitive_reduced_ideals': len(group_data),
    'independent_nonconstant_generators_mod_rational_scalars_and_units': 479,
    'remaining_trials_with_multiplier_exactly_one': scalar_count,
    'conclusion': 'The multiplicative group generated by Q* and all567 saved multipliers intersects the maximal-order unit group in exactly{+1,-1}. Exponents are arbitrary integers, not bounded.',
    'boundary': 'Only the sealed bank is excluded. No statement of nonprincipality for the two unresolved seed-relative ideals, and no exclusion of other unit constructions or independent seeds.',
    'inputs': {str(p.relative_to(ROOT)): sha(p) for p in [OUT / 'protocol.json', OUT / 'support.json', Path(__file__)]},
}
dest = OUT / 'independent-replay.json'
if dest.exists(): assert read(dest) == report
else:
    with dest.open('x') as stream:
        json.dump(report, stream, indent=2, sort_keys=True)
        stream.write('\n')
print(report['status'], '567 identities; 479 free generators; 88 trivial trials', flush=True)
