#!/usr/bin/env python3
"""Build fixture-separated MW17-only Selmer replays for records 356 and 385.

The builder may inspect the public controls in order to bind an unblinding
commitment.  The generated Magma executables cannot: each contains only the
minimal curve and the seventeen specialized generic points, computes the full
unconditional 2-Selmer group, and freezes its quotient by MW17.  In particular
the executables contain no coordinates or half-ideals for P18,...,P29.
"""

from __future__ import annotations

import argparse
from dataclasses import replace
from hashlib import sha256
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
CAS = ROOT / "elliptic-curves/cas"
OUTPUT_DIR = (
    ROOT
    / "artifacts/local/elliptic-curves"
    / "r17-mw17-only-selmer-control-v1/programs"
)
OUTPUT = (
    ROOT
    / "artifacts/generated-results/elliptic-curves"
    / "r17_mw17_only_selmer_control_inputs_v1.json"
)
SOURCE = Path(__file__).resolve()
SCHEMA = "elliptic-curves.r17-mw17-only-selmer-control-input.v1"
STATUS = "FROZEN_FIXTURE_SEPARATED_MW17_REPLAY_EXECUTION_REQUIRED"
PROTOCOL = "R17MW17SELMER"
GENERIC_RANK = 17
CONTROL_JUMP = 12

import sys

sys.path.insert(0, str(CAS))

from build_elkies_2026_relative_2selmer_suite import (  # noqa: E402
    build_magma,
    load_record_pair_cases,
)


def digest_bytes(value: bytes) -> str:
    return sha256(value).hexdigest()


def digest(path: Path) -> str:
    return digest_bytes(path.read_bytes())


def relative(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT))


def canonical_hash(value: Any) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":"))
    return digest_bytes(payload.encode())


def exceptional_commitment(case: Any) -> str:
    return canonical_hash(
        [[str(x), str(y)] for x, y in case.exceptional_points]
    )


def blind_case(case: Any) -> Any:
    curve_id = int(case.case_id.rsplit("-", 1)[1])
    return replace(
        case,
        case_id=f"mw17-only-control-{curve_id}",
        role="prospective-mw17-only-selmer-control",
        exceptional_points=(),
        certified_rank_lower_bound=None,
        rigid_quotient_rows=(),
        rigid_direction_labels=(),
        rigid_complement_point_labels=(),
    )


def build_blind_program(case: Any) -> str:
    """Return a Magma program ending before any held-out fixture can be read."""

    program = build_magma(
        blind_case(case), search_bound=0, enumerate_class_limit=1
    )
    marker = "nonzero_class_count := 2^residual_dim - 1;"
    if program.count(marker) != 1:
        raise ArithmeticError("the relative-Selmer template freeze point changed")
    program = program.split(marker, 1)[0]
    program = program.replace(
        "// Generated by build_elkies_2026_relative_2selmer_suite.py\n"
        "// Protocol ELKIESR17REL2 v1. Public exceptional points occur only after blind_end.\n",
        "// Generated by build_r17_mw17_only_selmer_replay.py\n"
        "// Fixture-separated MW17-only record replay; no post-MW17 point data are present.\n",
    )
    program = program.replace("ELKIESR17REL2", PROTOCOL)
    program = program.replace(
        "|held_out_exceptional_count=0|search_bound=0|enumerate_class_limit=1",
        "|known_subgroup=MW17|fixture_access=false",
    )
    program += f'''printf "{PROTOCOL}|stage=blind_freeze|status=complete|total_dim=%o|generic_kummer_rank=%o|residual_dim=%o\\n",
    selmer_dim, generic_kummer_rank, residual_dim;
quit;
'''
    return program


def audit_program(case: Any, program: str) -> dict[str, Any]:
    forbidden_rows = [
        f"E![{x.numerator if x.denominator == 1 else f'({x.numerator}/{x.denominator})'}, "
        f"{y.numerator if y.denominator == 1 else f'({y.numerator}/{y.denominator})'}, 1]"
        for x, y in case.exceptional_points
    ]
    forbidden_tokens = [
        "exceptional",
        "MW29",
        "rank29",
        *[f"P{index}" for index in range(18, 30)],
    ]
    checks = {
        "declares_exactly_seventeen_affine_points": program.count("E![")
        == GENERIC_RANK,
        "contains_no_held_out_coordinate_row": not any(
            row in program for row in forbidden_rows
        ),
        "contains_no_held_out_label_or_mw29_token": not any(
            token in program for token in forbidden_tokens
        ),
        "reads_no_external_file": all(
            token not in program for token in ("load ", "Load(", "Read(")
        ),
        "requests_unconditional_selmer_group": (
            "SelmerGroup(" in program and "Bound := -1" in program
        ),
        "supplies_only_generic_hints": (
            "Hints := generic_hints" in program
            and "generic_hints := { P[1] : P in generic };" in program
        ),
        "freezes_after_quotienting_only_mw17": (
            f"{PROTOCOL}|stage=blind_freeze" in program
            and "generic_kummer_rank" in program
        ),
        "performs_no_cover_or_point_search": (
            "TwoCover(" not in program and "Points(" not in program
        ),
    }
    if not all(checks.values()):
        failed = [name for name, passed in checks.items() if not passed]
        raise ArithmeticError(f"blind program audit failed: {', '.join(failed)}")
    return checks


def build(output_dir: Path = OUTPUT_DIR) -> tuple[dict[str, Any], dict[Path, str]]:
    records = []
    programs: dict[Path, str] = {}
    for case in load_record_pair_cases():
        curve_id = int(case.case_id.rsplit("-", 1)[1])
        program = build_blind_program(case)
        audit = audit_program(case, program)
        path = output_dir / f"mw17-only-control-{curve_id}.m"
        programs[path] = program
        records.append(
            {
                "case_id": f"mw17-only-control-{curve_id}",
                "curve_id": curve_id,
                "role": "prospective-mw17-only-selmer-control",
                "parameter": case.parameter,
                "global_minimal_model": [str(value) for value in case.model],
                "known_subgroup": "specialized MW17",
                "known_subgroup_point_count": GENERIC_RANK,
                "program": relative(path),
                "program_sha256": digest_bytes(program.encode()),
                "program_audit": audit,
            }
        )

    cases = load_record_pair_cases()
    unblinding = {
        "access_boundary": "not available to either generated Magma executable",
        "release_condition": (
            "both complete blind_freeze transcripts are hash-pinned"
        ),
        "expected_control_jump_over_mw17": CONTROL_JUMP,
        "point_coordinate_commitments_sha256": {
            str(int(case.case_id.rsplit("-", 1)[1])): exceptional_commitment(case)
            for case in cases
        },
        "truth_source": relative(
            ROOT
            / "artifacts/generated-results"
            / "elkies-k3-r17-norm12-icarm-public-fibres-v1.json"
        ),
    }
    provenance = {
        path: value for case in cases for path, value in case.provenance.items()
    }
    document = {
        "schema": SCHEMA,
        "status": STATUS,
        "case_count": len(records),
        "cases": records,
        "execution_contract": {
            "backend": "Magma SelmerGroup on multiplication by 2",
            "unconditional_class_group_request": "Bound=-1",
            "input_visible_to_backend": "minimal curve plus the specialized MW17 points",
            "quotient_formed_after_full_selmer_computation": "Sel_2(E)/im(MW17/2)",
            "mw29_quotient_forbidden": True,
            "post_mw17_point_coordinates_forbidden": True,
            "half_ideal_shortcut_forbidden": True,
            "cover_search_in_calibration_replay": False,
        },
        "unblinding_commitment": unblinding,
        "operational_gate": {
            "selmer_candidate_gate_operationally_calibrated": False,
            "record_replays_completed": 0,
            "required_record_replays": 2,
            "acceptance_rule": (
                "Each sealed replay must complete unconditionally, certify MW17 Kummer "
                "rank 17, and report residual Selmer dimension at least 12 before the "
                "public twelve-dimensional control image is consulted."
            ),
            "mw29_relative_calculations_role": "post-discovery closure diagnostic only",
        },
        "claim_boundary": [
            "This artifact freezes exact executable inputs; it is not a completed Selmer calculation.",
            "No MW29-relative calculation can satisfy the prospective MW17-only control gate.",
            "No candidate or prospective sample stage is authorized by frozen inputs or an incomplete transcript.",
        ],
        "inputs": provenance,
        "generation": {
            "script": relative(SOURCE),
            "script_sha256": digest(SOURCE),
            "command": (
                "python3 elliptic-curves/cas/build_r17_mw17_only_selmer_replay.py"
            ),
        },
    }
    return document, programs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    document, programs = build(args.output_dir.resolve())
    payload = json.dumps(document, indent=2, sort_keys=True) + "\n"
    output = args.output.resolve()
    if args.check:
        if not output.exists() or output.read_text() != payload:
            raise ArithmeticError("stored MW17-only replay input differs")
    else:
        if not args.overwrite and (
            output.exists() or any(path.exists() for path in programs)
        ):
            raise FileExistsError("use --overwrite to replace the frozen replay")
        for path, program in programs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(program)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(payload)
    print(
        f"{PROTOCOL}|stage=inputs|cases=2|fixture_access=false|"
        f"operational=false|status={STATUS}"
    )


if __name__ == "__main__":
    main()
