#!/usr/bin/env python3
"""Build a pinned Magma relative 2-descent job for the Fermigier rank-20 curve.

This script performs no descent itself.  It reconstructs the exact 20-point
subgroup from the pinned near-miss manifest and emits a self-contained Magma
program.  The Magma output is deliberately machine-readable so a completed run
can be classified without interpreting partial console prose.
"""

from __future__ import annotations

import argparse
from fractions import Fraction
import json
from pathlib import Path
import sys


PROGRAM_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROGRAM_ROOT))

from ecsearch.fermigier_near_miss import FERMIGIER_RANK20_PARAMETER  # noqa: E402
from ecsearch.fermigier_rank import (  # noqa: E402
    canonical_ratpoints_output,
    parse_ratpoints_output,
    section_and_point_cloud_differences,
    specialize_fermigier_rank_sections,
)


def magma_q(value: Fraction | int) -> str:
    value = Fraction(value)
    if value.denominator == 1:
        return str(value.numerator)
    return f"({value.numerator}/{value.denominator})"


def load_selected_points(manifest_path: Path):
    manifest = json.loads(manifest_path.read_text())
    if manifest.get("schema") != "elliptic-curves.fermigier-rank20-near-miss.v1":
        raise ValueError("unexpected near-miss manifest schema")
    if manifest["family"]["adapter_parameter"] != "28917/20":
        raise ValueError("unexpected Fermigier adapter parameter")
    if manifest["point_cloud"]["selected_count"] != 20:
        raise ValueError("manifest no longer contains exactly 20 selected points")

    specialization = specialize_fermigier_rank_sections(FERMIGIER_RANK20_PARAMETER)
    abscissas = tuple(Fraction(text) for text in manifest["bounded_search"]["abscissas"])
    raw = canonical_ratpoints_output(abscissas)
    searched = parse_ratpoints_output(specialization.quartic_model, raw)
    cloud = section_and_point_cloud_differences(specialization, searched)
    indices = tuple(manifest["point_cloud"]["selected_indices"])
    if len(indices) != 20 or len(set(indices)) != 20:
        raise ValueError("selected indices are not 20 distinct entries")
    if max(indices) >= len(cloud):
        raise ValueError("selected point index exceeds reconstructed cloud")
    return specialization.canonical_model, tuple(cloud[i] for i in indices)


def build_magma(model, points, point_bound: int) -> str:
    coeffs = ", ".join(magma_q(c) for c in model)
    rows = ",\n    ".join(
        f"E![{magma_q(x)}, {magma_q(y)}, 1]" for x, y in points
    )
    return f'''// Generated by elliptic-curves/cas/build_fermigier_rank20_relative_descent.py
// Classification protocol: elliptic-curves/notes/FERMIGIER_RANK20_RELATIVE_DESCENT_EXPERIMENT.md

Q := Rationals();
E := EllipticCurve([{coeffs}]);
known := [
    {rows}
];

printf "R20DESCENT|stage=input|magma=%o|known=%o\\n", GetVersion(), #known;
assert #known eq 20;
assert &and[P in E : P in known];

// Quotient the 2-descent by the already certified subgroup.  A failure here is
// classification R4 and must not be interpreted mathematically.
covers, maps, aux := TwoDescent(
    E : RemoveGens := SequenceToSet(known), RemoveTorsion := true
);
printf "R20DESCENT|stage=two_descent|residual_covers=%o\\n", #covers;

if #covers eq 0 then
    printf "R20DESCENT|classification=R0|reason=no_residual_2_cover\\n";
    quit;
end if;

// Cassels--Tate matrix on the residual 2-covers.
M := ZeroMatrix(Integers(), #covers, #covers);
for i in [1..#covers] do
    for j in [1..#covers] do
        M[i,j] := CasselsTatePairing(covers[i], covers[j]);
    end for;
end for;
printf "R20DESCENT|stage=cassels_tate|matrix=%o\\n", Eltseq(M);

nonzero := exists{{ M[i,j] : i,j in [1..#covers] | M[i,j] ne 0 }};
if nonzero then
    printf "R20DESCENT|classification=R1|reason=nonzero_cassels_tate_pairing\\n";
end if;

// Continue every residual class whose row pairs trivially with all residual
// classes.  FourDescent returning [] is recorded, not silently treated as a
// proof of Sha.
radical := [ i : i in [1..#covers] |
    &and[M[i,j] eq 0 : j in [1..#covers]]
];
printf "R20DESCENT|stage=radical|indices=%o\\n", radical;

found_candidate := false;
for i in radical do
    fours := FourDescent(covers[i] : RemoveTorsion := true);
    printf "R20DESCENT|stage=four_descent|cover=%o|four_covers=%o\\n", i, #fours;
    for k in [1..#fours] do
        pts := PointsQI(fours[k], {point_bound});
        printf "R20DESCENT|stage=points_qi|cover=%o|four=%o|bound={point_bound}|points=%o\\n",
            i, k, #pts;
        if #pts gt 0 then
            found_candidate := true;
            printf "R20DESCENT|candidate|cover=%o|four=%o|point=%o\\n", i, k, pts[1];
        end if;
    end for;
end for;

if found_candidate then
    printf "R20DESCENT|classification=R3|reason=rational_point_on_four_cover\\n";
elif #radical gt 0 then
    printf "R20DESCENT|classification=R2|reason=radical_without_bounded_point\\n";
elif not nonzero then
    printf "R20DESCENT|classification=R4|reason=residual_classes_but_no_radical_classification\\n";
end if;
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("artifacts/generated-results/elliptic-curves/fermigier_rank20_near_miss_v1.json"),
    )
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--point-bound",
        type=int,
        default=100_000,
        help="bounded PointsQI search parameter for each 4-cover",
    )
    args = parser.parse_args()
    if args.point_bound <= 0:
        raise ValueError("--point-bound must be positive")

    model, points = load_selected_points(args.manifest)
    text = build_magma(model, points, args.point_bound)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"WROTE {args.output}")
    print("CLASSIFICATION=experiment_external_cas")
    print("KNOWN_POINTS=20")


if __name__ == "__main__":
    main()
