#!/usr/bin/env python3
"""Build quotient-first rank-jump fingerprints for the four R17 controls.

The output concerns the certified subgroup generated by each public point
list.  It does not assume that this subgroup is the full Mordell--Weil group.
For a specialized generic subgroup ``M`` inside a displayed subgroup ``L`` it
records

* the exact Smith structure of ``L/M``;
* its exact dimensions after tensoring with F_2, F_3, and F_5;
* the canonical-height quotient lattice obtained by orthogonal projection
  away from ``M_R``;
* complete degree-two bisection visibility as a binary quotient-code matroid.

The quotient heights are numerical canonical heights at the declared PARI
precision.  The Smith, finite-code, and cover-square calculations are exact.
"""

from __future__ import annotations

import argparse
from collections import Counter
from fractions import Fraction
from hashlib import sha256
import importlib
from itertools import combinations
import json
from math import prod
from pathlib import Path
import sys
from typing import Iterable, Sequence


ROOT = Path(__file__).resolve().parents[2]
ELLIPTIC = ROOT / "elliptic-curves"
sys.path[:0] = [str(ELLIPTIC), str(ELLIPTIC / "cas")]

from latent_lattice import EllipticCurve, height_gram  # noqa: E402
from latent_lattice.pari import gp_matrix, run_gp  # noqa: E402


TRUTH = (
    ROOT
    / "artifacts/generated-results/elliptic-curves"
    / "latent_lattice_calibration_truth_v1.json"
)
CONTROLS = (
    ROOT
    / "artifacts/generated-results/elliptic-curves"
    / "elkies_2026_high_rank_positive_controls_v2.json"
)
BISECTION_CONTROLS = (
    ROOT
    / "artifacts/generated-results/elliptic-curves"
    / "elkies_2026_bisection_specialization_controls_v1.json"
)
MECHANISM_CONTROL = (
    ROOT
    / "artifacts/generated-results/elliptic-curves"
    / "icarm_curve394_rank21_v1.json"
)
OUTPUT = (
    ROOT
    / "artifacts/generated-results/elliptic-curves"
    / "elkies_2026_rank_jump_fingerprints_v1.json"
)
RELATION_PRIMES = (2, 3, 5)


def digest(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def display(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT))


def rank_mod_prime(rows: Sequence[Sequence[int]], prime: int) -> int:
    """Exact row rank over a prime field, including empty matrices."""

    if not rows:
        return 0
    width = len(rows[0])
    matrix = [[int(value) % prime for value in row] for row in rows]
    if any(len(row) != width for row in matrix):
        raise ValueError("inconsistent matrix widths")
    rank = 0
    for column in range(width):
        pivot = next(
            (row for row in range(rank, len(matrix)) if matrix[row][column]),
            None,
        )
        if pivot is None:
            continue
        matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
        inverse = pow(matrix[rank][column], -1, prime)
        matrix[rank] = [(value * inverse) % prime for value in matrix[rank]]
        for row in range(len(matrix)):
            if row == rank or matrix[row][column] == 0:
                continue
            scale = matrix[row][column]
            matrix[row] = [
                (left - scale * right) % prime
                for left, right in zip(matrix[row], matrix[rank])
            ]
        rank += 1
        if rank == len(matrix):
            break
    return rank


def smith_quotient_record(
    *, ambient_rank: int, subgroup_rank: int, smith_factors: Sequence[int]
) -> dict[str, object]:
    """Describe ``Z^ambient / M`` from the nonzero Smith factors of ``M``."""

    factors = tuple(abs(int(value)) for value in smith_factors)
    if len(factors) != subgroup_rank or any(value == 0 for value in factors):
        raise ValueError("Smith factors do not have the declared subgroup rank")
    free_rank = ambient_rank - subgroup_rank
    if free_rank < 0:
        raise ValueError("subgroup rank exceeds ambient rank")
    torsion = tuple(value for value in factors if value != 1)
    mod_dimensions = {
        str(prime): free_rank + sum(value % prime == 0 for value in factors)
        for prime in RELATION_PRIMES
    }
    return {
        "ambient_certified_subgroup_rank": ambient_rank,
        "specialized_generic_subgroup_rank": subgroup_rank,
        "free_quotient_rank_lower_bound": free_rank,
        "smith_invariant_factors": list(factors),
        "torsion_invariant_factors": list(torsion),
        "specialized_generic_saturation_index_in_displayed_subgroup": prod(factors),
        "specialized_generic_is_primitive_in_displayed_subgroup": not torsion,
        "tensor_dimensions_over_f_ell": mod_dimensions,
        "formula": (
            "dim_Fell((L/M) tensor F_ell) = free_rank(L/M) + "
            "number of Smith factors divisible by ell"
        ),
        "scope": (
            "L is the certified subgroup generated by the displayed public basis; "
            "the full E(Q)/M quotient may be larger or less saturated"
        ),
    }


def _real_matrix(rows: Sequence[Sequence[str]]) -> str:
    return "[" + ";".join(",".join(map(str, row)) for row in rows) + "]"


def _parse_block(lines: Sequence[str], begin: str, end: str) -> list[str]:
    start = lines.index(begin) + 1
    stop = lines.index(end, start)
    return list(lines[start:stop])


def quotient_height_geometry(
    ambient_gram: Sequence[Sequence[str]],
    embedding_columns: Sequence[Sequence[int]],
    *,
    digits: int,
    maximum_vectors: int,
    shortest_vector_count: int,
    timeout: float,
) -> dict[str, object]:
    """Compute the projected quotient Gram and its complete successive minima.

    The columns express the specialized generic basis in the displayed ambient
    basis.  Smith completion supplies an integral basis after quotienting by
    the saturation of its real span; any finite Smith torsion is recorded
    separately by :func:`smith_quotient_record`.  Fincke--Pohst enumeration is run
    through the largest diagonal entry of an LLL-reduced quotient Gram; those
    diagonal vectors already span, so this bound is sufficient for every
    successive minimum.
    """

    columns = tuple(tuple(map(int, column)) for column in embedding_columns)
    if not columns:
        raise ValueError("the generic embedding is empty")
    ambient_rank = len(columns[0])
    subgroup_rank = len(columns)
    if any(len(column) != ambient_rank for column in columns):
        raise ValueError("embedding columns have inconsistent lengths")
    if len(ambient_gram) != ambient_rank or any(
        len(row) != ambient_rank for row in ambient_gram
    ):
        raise ValueError("ambient Gram and embedding dimensions differ")
    embedding_rows = tuple(zip(*columns))
    program = f"""
default(parisizemax,4000000000);default(parisize,500000000);
default(realprecision,{int(digits)});
H={_real_matrix(ambient_gram)};A={gp_matrix(embedding_rows)};
S=matsnf(A,1);U=S[1];D=S[3];n=matsize(A)[1];r=matsize(A)[2];
z=List();for(i=1,n,if(sum(j=1,r,abs(D[i,j]))==0,listput(z,i)));
if(#z!=n-r,error("unexpected free quotient dimension"));
Ui=U^-1;zv=Vec(z);C=matrix(n,n-r,i,j,Ui[i,zv[j]]);HM=A~*H*A;X=A~*H*C;
G=C~*H*C-X~*HM^-1*X;
T=qflllgram(G);R=T~*G*T;b=vecmax(vector(n-r,i,R[i,i]));
Q=qfminim(R,b,{int(maximum_vectors)},2);V=Q[3];
if(Q[1]>=2*{int(maximum_vectors)},error("quotient vector cap reached"));
W=T*V;m=matsize(W)[2];L=vector(m,j,W[,j]~*G*W[,j]);
ord=vecsort(L,,1);B=matrix(n-r,0);rk=0;mins=List();
for(k=1,m,j=ord[k];B=matconcat([B,W[,j]]);nr=matrank(B);if(nr>rk,listput(mins,L[j]);rk=nr));
if(rk!=n-r,error("successive minima enumeration did not span"));
print("META|",n,"|",r,"|",n-r,"|",Q[1],"|",b,"|",matdet(G));
print("MINIMA|",Vec(mins));
print("GRAM_BEGIN");for(i=1,n-r,for(j=1,n-r,if(j>1,print1("|"));print1(G[i,j]));print());print("GRAM_END");
print("SHORT_BEGIN");
for(k=1,min(m,{int(shortest_vector_count)}),j=ord[k];print1(L[j]);for(i=1,n-r,print1("|",W[i,j]));print());
print("SHORT_END");
"""
    lines = run_gp(program, timeout=timeout)
    meta = next(line.split("|")[1:] for line in lines if line.startswith("META|"))
    returned_ambient, returned_subgroup, quotient_rank, enumerated = map(
        int, meta[:4]
    )
    if (returned_ambient, returned_subgroup) != (ambient_rank, subgroup_rank):
        raise ArithmeticError("PARI quotient dimensions changed")
    minima_line = next(line for line in lines if line.startswith("MINIMA|"))
    minima_literal = minima_line.split("|", 1)[1].strip()
    if not minima_literal.startswith("[") or not minima_literal.endswith("]"):
        raise ArithmeticError("PARI successive-minima output changed")
    minima = [
        value.strip()
        for value in minima_literal[1:-1].split(",")
        if value.strip()
    ]
    if len(minima) != quotient_rank:
        raise ArithmeticError("PARI returned the wrong number of successive minima")
    gram = [line.split("|") for line in _parse_block(lines, "GRAM_BEGIN", "GRAM_END")]
    shortest = []
    for line in _parse_block(lines, "SHORT_BEGIN", "SHORT_END"):
        fields = line.split("|")
        shortest.append(
            {
                "projected_height": fields[0],
                "coordinates_in_smith_quotient_basis": list(map(int, fields[1:])),
            }
        )
    return {
        "definition": (
            "orthogonal projection of the displayed height lattice away from "
            "the real span of the specialized generic subgroup"
        ),
        "quotient_rank": quotient_rank,
        "quotient_gram": gram,
        "quotient_determinant": meta[5],
        "successive_minima": minima,
        "shortest_quotient_vectors": shortest,
        "enumeration": {
            "algorithm": "PARI qflllgram plus complete qfminim/Fincke-Pohst",
            "enumerated_signed_vector_count": enumerated,
            "sufficient_height_bound": meta[4],
            "maximum_stored_half_vectors": maximum_vectors,
            "complete_for_successive_minima": True,
        },
        "numerical_boundary": (
            f"canonical heights and projected Gram use PARI realprecision={digits}; "
            "the point identities and quotient basis are exact, but these real "
            "height decimals are not interval certificates"
        ),
    }


def _subset_rank_histogram(vectors: Sequence[Sequence[int]]) -> dict[str, object]:
    """Exact subset-rank distribution via binary row-space dynamic programming."""

    if not vectors:
        return {"0": {"0": 1}}
    width = len(vectors[0])
    if any(len(vector) != width for vector in vectors):
        raise ValueError("inconsistent binary vector widths")

    def add(space: tuple[int, ...], vector: Sequence[int]) -> tuple[int, ...]:
        value = sum((int(bit) & 1) << index for index, bit in enumerate(vector))
        rows = list(space)
        for row in rows:
            value = min(value, value ^ row)
        if value == 0:
            return space
        rows = [min(row, row ^ value) for row in rows]
        rows.append(value)
        rows.sort(reverse=True)
        return tuple(rows)

    states: dict[tuple[int, tuple[int, ...]], int] = {(0, ()): 1}
    for vector in vectors:
        updated = dict(states)
        for (size, space), count in states.items():
            key = (size + 1, add(space, vector))
            updated[key] = updated.get(key, 0) + count
        states = updated
    by_size: dict[str, dict[str, int]] = {}
    for (size, space), count in states.items():
        bucket = by_size.setdefault(str(size), {})
        rank = str(len(space))
        bucket[rank] = bucket.get(rank, 0) + count
    return {
        size: {rank: counts[rank] for rank in sorted(counts, key=int)}
        for size, counts in sorted(by_size.items(), key=lambda item: int(item[0]))
    }


def _minimal_binary_circuits(
    labels: Sequence[str], vectors: Sequence[Sequence[int]]
) -> list[list[str]]:
    circuits: list[tuple[int, ...]] = []
    maximum_size = min(len(vectors), (len(vectors[0]) if vectors else 0) + 1)
    for size in range(1, maximum_size + 1):
        for subset in combinations(range(len(vectors)), size):
            rows = tuple(vectors[index] for index in subset)
            if rank_mod_prime(rows, 2) != size - 1:
                continue
            if any(
                rank_mod_prime(
                    tuple(vectors[index] for index in subset if index != removed), 2
                )
                != size - 1
                for removed in subset
            ):
                continue
            circuits.append(subset)
    return [[labels[index] for index in subset] for subset in circuits]


def _binary_circuit_record(
    labels: Sequence[str], vectors: Sequence[Sequence[int]], *, example_limit: int = 128
) -> dict[str, object]:
    circuits = _minimal_binary_circuits(labels, vectors)
    counts = Counter(len(circuit) for circuit in circuits)
    return {
        "count_by_cardinality": {
            str(size): count for size, count in sorted(counts.items())
        },
        "total_count": len(circuits),
        "examples": circuits[:example_limit],
        "examples_truncated": len(circuits) > example_limit,
        "example_limit": example_limit,
    }


def degree_two_visibility_record(fibre: dict[str, object]) -> dict[str, object]:
    labels = tuple(str(hit["label"]) for hit in fibre["hits"])
    vectors = tuple(
        tuple(
            int(value)
            for value in hit["finite_quotient_class_modulo_generic_17"][
                "coordinates_over_f2"
            ]
        )
        for hit in fibre["hits"]
    )
    span = rank_mod_prime(vectors, 2)
    nonzero = tuple(vector for vector in vectors if any(vector))
    multiplicities = Counter(nonzero)
    full_rank_subset_count = sum(
        rank_mod_prime(tuple(vectors[index] for index in subset), 2) == span
        for subset in combinations(range(len(vectors)), span)
    ) if span else 1
    return {
        "cover_degree": 2,
        "atlas_status": "complete_equation_level_atlas",
        "atlas_size": 39120,
        "split_cover_count": len(vectors),
        "nonzero_visible_cover_count": len(nonzero),
        "distinct_nonzero_quotient_classes": len(multiplicities),
        "visible_exceptional_span_dimension_over_f2": span,
        "visible_cover_labels": list(labels),
        "class_multiplicity_histogram": {
            str(multiplicity): count
            for multiplicity, count in sorted(Counter(multiplicities.values()).items())
        },
        "minimum_spanning_packet_size": span,
        "spanning_packet_count_at_minimum_size": full_rank_subset_count,
        "subset_rank_histogram_by_cardinality": _subset_rank_histogram(vectors),
        "minimal_dependency_circuits": _binary_circuit_record(labels, vectors),
        "interpretation": (
            "This is the exact vector matroid of split bisection classes in the "
            "certified mod-2 quotient coordinates. It measures cover overlap and "
            "intersection of visible directions, not full Mordell--Weil dependence."
        ),
    }


def degree_visibility_ledger(fibre: dict[str, object]) -> list[dict[str, object]]:
    return [
        degree_two_visibility_record(fibre),
        {
            "cover_degree": 3,
            "atlas_status": "not_available_for_this_family",
            "visible_exceptional_span_dimension": None,
            "reason": (
                "The foundry has exact lattice coset censuses on selected frames, "
                "but no complete equation-level trisection atlas specialized to "
                "these four published R17 fibres. Missing is not zero."
            ),
        },
        {
            "cover_degree": 4,
            "atlas_status": "not_available_for_this_family",
            "visible_exceptional_span_dimension": None,
            "reason": (
                "Current quadrisection data are sampled lattice candidates, not a "
                "complete descended cover atlas. Missing is not zero."
            ),
        },
    ]


def build_fingerprint(
    truth: dict[str, object],
    control: dict[str, object],
    bisection: dict[str, object],
    *,
    digits: int,
    maximum_vectors: int,
    shortest_vector_count: int,
    timeout: float,
) -> dict[str, object]:
    if not (truth["label"] == control["label"] == bisection["label"]):
        raise ValueError("control labels do not align")
    if not (truth["parameter"] == control["parameter"] == bisection["parameter"]):
        raise ValueError("control parameters do not align")
    rank = int(control["published_rank_lower_bound"])
    module = importlib.import_module(f"elkies_rank{rank}")
    curve = EllipticCurve(module.GENERAL_WEIERSTRASS_COEFFICIENTS)
    public_points = tuple(module.POINTS)
    if len(public_points) != rank:
        raise ArithmeticError("public point count and advertised rank differ")
    gram = height_gram(curve, public_points, digits=digits, timeout=timeout)
    smith = smith_quotient_record(
        ambient_rank=rank,
        subgroup_rank=int(truth["truth_rank"]),
        smith_factors=truth["smith_invariant_factors"],
    )
    geometry = quotient_height_geometry(
        gram,
        truth["embedding_matrix_columns"],
        digits=digits,
        maximum_vectors=maximum_vectors,
        shortest_vector_count=shortest_vector_count,
        timeout=timeout,
    )
    return {
        "label": control["label"],
        "parameter": control["parameter"],
        "global_minimal_model": control["minimal_model"],
        "certified_rank_lower_bound": rank,
        "generic_rank": int(truth["truth_rank"]),
        "quotient_structure": smith,
        "quotient_height_geometry": geometry,
        "degree_visibility": degree_visibility_ledger(bisection),
        "response_variables": {
            "primary_lower_bound": smith["free_quotient_rank_lower_bound"],
            "prime_local_dimensions": smith["tensor_dimensions_over_f_ell"],
            "degree_two_visible_dimension_over_f2": bisection["split_class_span"],
        },
    }


def build_mechanism_fingerprint(
    certificate: dict[str, object],
    bisection: dict[str, object],
    *,
    digits: int,
    maximum_vectors: int,
    shortest_vector_count: int,
    timeout: float,
) -> dict[str, object]:
    """Build the lower-jump t=3/8 control from its certified mixed basis."""

    if not (certificate["parameter"] == bisection["parameter"] == "3/8"):
        raise ValueError("the mechanism-control parameter changed")
    rank_record = certificate["rank_lower_bound"]
    rank = int(rank_record["certified_rank"])
    generic_rank = int(certificate["compact_specialization"]["generic_section_count"])
    points = tuple(
        tuple(Fraction(value) for value in point)
        for point in rank_record["combined_points"]
    )
    model = tuple(Fraction(value) for value in certificate["curve"]["global_minimal_model"])
    if len(points) != rank or generic_rank != 17 or rank != 21:
        raise ArithmeticError("the t=3/8 certified basis changed")
    embedding = tuple(
        tuple(int(row == column) for row in range(rank))
        for column in range(generic_rank)
    )
    curve = EllipticCurve(model)
    gram = height_gram(curve, points, digits=digits, timeout=timeout)
    smith = smith_quotient_record(
        ambient_rank=rank,
        subgroup_rank=generic_rank,
        smith_factors=(1,) * generic_rank,
    )
    geometry = quotient_height_geometry(
        gram,
        embedding,
        digits=digits,
        maximum_vectors=maximum_vectors,
        shortest_vector_count=shortest_vector_count,
        timeout=timeout,
    )
    visibility = degree_visibility_ledger(bisection)
    return {
        "label": bisection["label"],
        "parameter": "3/8",
        "global_minimal_model": [str(value) for value in model],
        "certified_rank_lower_bound": rank,
        "generic_rank": generic_rank,
        "control_role": (
            "lower-jump mechanism control; added after the four published high-rank "
            "controls and not used to retune their feature construction"
        ),
        "quotient_structure": smith,
        "quotient_height_geometry": geometry,
        "degree_visibility": visibility,
        "response_variables": {
            "primary_lower_bound": smith["free_quotient_rank_lower_bound"],
            "prime_local_dimensions": smith["tensor_dimensions_over_f_ell"],
            "degree_two_visible_dimension_over_f2": visibility[0][
                "visible_exceptional_span_dimension_over_f2"
            ],
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--truth", type=Path, default=TRUTH)
    parser.add_argument("--controls", type=Path, default=CONTROLS)
    parser.add_argument("--bisection-controls", type=Path, default=BISECTION_CONTROLS)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--digits", type=int, default=80)
    parser.add_argument("--maximum-vectors", type=int, default=500000)
    parser.add_argument("--shortest-vector-count", type=int, default=16)
    parser.add_argument("--timeout", type=float, default=300.0)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.digits < 50:
        raise SystemExit("--digits must be at least 50")
    truth_document = json.loads(args.truth.read_text())
    control_document = json.loads(args.controls.read_text())
    bisection_document = json.loads(args.bisection_controls.read_text())
    mechanism_document = json.loads(MECHANISM_CONTROL.read_text())
    truths = {row["label"]: row for row in truth_document["positive_controls"]}
    bisections = {row["label"]: row for row in bisection_document["fibres"]}
    fingerprints = [build_mechanism_fingerprint(
        mechanism_document,
        bisections["icarm_curve394_rank_at_least_21"],
        digits=args.digits,
        maximum_vectors=args.maximum_vectors,
        shortest_vector_count=args.shortest_vector_count,
        timeout=args.timeout,
    )] + [
        build_fingerprint(
            truths[control["label"]],
            control,
            bisections[control["label"]],
            digits=args.digits,
            maximum_vectors=args.maximum_vectors,
            shortest_vector_count=args.shortest_vector_count,
            timeout=args.timeout,
        )
        for control in control_document["fibres"]
    ]
    payload = {
        "schema": "elliptic-curves.elkies-2026-rank-jump-fingerprints.v1",
        "status": "PASS_CERTIFIED_SUBGROUP_QUOTIENT_FINGERPRINTS",
        "target": (
            "escape from the specialized generic Mordell--Weil lattice, not "
            "direct prediction of total fibre rank"
        ),
        "inputs": {
            display(args.truth): digest(args.truth),
            display(args.controls): digest(args.controls),
            display(args.bisection_controls): digest(args.bisection_controls),
            display(MECHANISM_CONTROL): digest(MECHANISM_CONTROL),
            **{
                f"elliptic-curves/cas/elkies_rank{rank}.py": digest(
                    ELLIPTIC / "cas" / f"elkies_rank{rank}.py"
                )
                for rank in range(25, 29)
            },
        },
        "height_precision_decimal_digits": args.digits,
        "fingerprints": fingerprints,
        "modeling_guidance": {
            "primary_response": (
                "certified lower bound for rank of L_t / sp_t(MW_generic)"
            ),
            "prime_local_responses": [
                "dim_F2((L_t/M_t) tensor F2)",
                "dim_F3((L_t/M_t) tensor F3)",
                "dim_F5((L_t/M_t) tensor F5)",
            ],
            "geometric_responses": [
                "successive minima of the projected quotient height lattice",
                "shortest projected quotient-vector heights",
            ],
            "mechanism_responses": [
                "degree-d visible quotient-code dimension",
                "cover-code matroid circuits and spanning packets",
            ],
            "rank32_gate": (
                "rank 32 from generic rank 17 requires at least 15 free "
                "quotient directions; prime-local torsion dimensions alone do "
                "not supply those directions"
            ),
        },
        "proof_boundary": (
            "Smith data, finite quotient codes, and degree-two cover evaluation "
            "are exact for the displayed certified subgroups. Canonical heights "
            "are high-precision numerical values. The public bases give rank "
            "lower bounds and are not asserted to be saturated full E(Q) bases. "
            "Degree-three and degree-four visibility are explicitly missing, not zero."
        ),
        "reproducing_command": (
            "PYTHONPATH=elliptic-curves:elliptic-curves/cas python3 "
            "elliptic-curves/cas/build_elkies_2026_rank_jump_fingerprints.py"
        ),
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.check:
        if not args.output.exists() or args.output.read_text() != encoded:
            raise SystemExit(f"stale or missing fingerprint artifact: {args.output}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(encoded)
    summary = ",".join(
        str(row["quotient_structure"]["free_quotient_rank_lower_bound"])
        for row in fingerprints
    )
    degree_two = ",".join(
        str(row["degree_visibility"][0]["visible_exceptional_span_dimension_over_f2"])
        for row in fingerprints
    )
    print(
        "ELKIES2026RANKJUMPFINGERPRINTS|"
        f"quotient_ranks={summary}|degree2_visible={degree_two}|"
        f"status={payload['status']}|output={display(args.output)}"
    )


if __name__ == "__main__":
    main()
