#!/usr/bin/env python3
"""Generate a source-pinned Magma relative 2-Selmer job for one near miss.

The generated program calls ``TwoDescent`` with ``RemoveGens`` equal to the
exact mod-2-independent subgroup in the conductor-first target manifest.  A
zero quotient therefore closes the fixed fibre.  Nonzero covers and their
Cassels--Tate pairing are printed explicitly for the next higher-descent gate.
No GRH class-group bounds are enabled.
"""

from __future__ import annotations

import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = (
    ROOT
    / "artifacts/generated-results/elliptic-curves/"
    "conductor_first_near_miss_descent_targets_v1.json"
)
EXPECTED_SCHEMA = "elliptic-curves.conductor-first-near-miss-descent-targets.v1"


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def magma_q(value: str | int) -> str:
    value = Fraction(value)
    return f"({value.numerator}/{value.denominator})"


def load_target(path: Path, target_id: str) -> tuple[dict[str, Any], dict[str, Any]]:
    manifest = json.loads(path.read_text())
    if manifest.get("schema") != EXPECTED_SCHEMA:
        raise ValueError("input is not the conductor-first target manifest")
    matches = [target for target in manifest["targets"] if target["id"] == target_id]
    if len(matches) != 1:
        available = ", ".join(target["id"] for target in manifest["targets"])
        raise ValueError(f"unknown target {target_id}; choose one of {available}")
    target = matches[0]
    if target["known_kummer_image_dimension"] != target["certified_known_rank"]:
        raise ArithmeticError("target subgroup is not certified full-dimensional mod 2")
    if target["rational_two_torsion_dimension"] != 0:
        raise ArithmeticError("this job expects trivial rational 2-torsion")
    return manifest, target


def build_magma(
    target: dict[str, Any], *, manifest_sha256: str, pairing_cover_cap: int
) -> str:
    target_id = target["id"]
    known_rank = int(target["certified_known_rank"])
    model = ", ".join(magma_q(value) for value in target["descent_model"])
    points = ",\n    ".join(
        f"E![{magma_q(point[0])}, {magma_q(point[1])}, 1]"
        for point in target["known_basis"]
    )
    return f'''// Generated by build_conductor_first_near_miss_magma.py
// Protocol CFNMSEL v1. No SetClassGroupBounds("GRH") is used.
// Target manifest SHA-256: {manifest_sha256}

Q := Rationals();
E := EllipticCurve([{model}]);
known := [
    {points}
];

function ExactLog2(n)
    assert n ge 1;
    d := 0;
    m := 1;
    while m lt n do
        m *:= 2;
        d +:= 1;
    end while;
    assert m eq n;
    return d;
end function;

printf "CFNMSEL|version=1|target={target_id}|stage=input|magma=%o|known=%o|manifest_sha256={manifest_sha256}\\n",
    GetVersion(), #known;
assert #known eq {known_rank};
assert &and[P in E : P in known];

T2, T2map := TwoTorsionSubgroup(E);
t2dim := ExactLog2(#T2);
printf "CFNMSEL|target={target_id}|stage=torsion|order=%o|dimension=%o\\n", #T2, t2dim;
assert t2dim eq 0;

printf "CFNMSEL|target={target_id}|stage=two_descent|status=start\\n";
started := Realtime();
covers, maps, quotient_map := TwoDescent(
    E :
    RemoveGens := SequenceToSet(known),
    RemoveTorsion := true
);
seconds := Realtime(started);
residual_count := #covers;
residual_dim := ExactLog2(residual_count + 1);
selmer_dim := {known_rank} + residual_dim;
printf "CFNMSEL|target={target_id}|stage=two_descent|status=complete|seconds=%o|residual_nonzero_classes=%o|residual_dim=%o|selmer_dim=%o\\n",
    seconds, residual_count, residual_dim, selmer_dim;

for i in [1..#covers] do
    f, h := HyperellipticPolynomials(covers[i]);
    printf "CFNMSEL|target={target_id}|stage=two_cover|index=%o|f=%o|h=%o\\n", i, f, h;
end for;

if residual_count eq 0 then
    printf "CFNMSEL|target={target_id}|classification=CLOSED_EXACT_RANK_{known_rank}|rank_lower={known_rank}|rank_upper={known_rank}|reason=zero_residual_2_selmer\\n";
    quit;
end if;

if residual_count gt {pairing_cover_cap} then
    printf "CFNMSEL|target={target_id}|classification=RESIDUAL_COVERS_UNPAIRED|residual_dim=%o|nonzero_classes=%o|pairing_cap={pairing_cover_cap}\\n",
        residual_dim, residual_count;
    quit;
end if;

printf "CFNMSEL|target={target_id}|stage=cassels_tate|status=start|classes=%o\\n", residual_count;
pair_started := Realtime();
M := ZeroMatrix(Integers(), residual_count, residual_count);
for i in [1..residual_count] do
    for j in [i+1..residual_count] do
        value := CasselsTatePairing(covers[i], covers[j]);
        M[i,j] := value;
        M[j,i] := value;
        printf "CFNMSEL|target={target_id}|stage=cassels_tate_entry|i=%o|j=%o|value=%o\\n",
            i, j, value;
    end for;
end for;
pair_seconds := Realtime(pair_started);
radical := [
    i : i in [1..residual_count] |
    &and[M[i,j] eq 0 : j in [1..residual_count]]
];
radical_dim := ExactLog2(#radical + 1);
rank_upper_after_pairing := {known_rank} + radical_dim;
printf "CFNMSEL|target={target_id}|stage=cassels_tate|status=complete|seconds=%o|matrix=%o|radical_indices=%o|radical_dim=%o|rank_upper_after_pairing=%o\\n",
    pair_seconds, Eltseq(M), radical, radical_dim, rank_upper_after_pairing;

if radical_dim eq 0 then
    printf "CFNMSEL|target={target_id}|classification=CLOSED_EXACT_RANK_{known_rank}_CT|rank_lower={known_rank}|rank_upper={known_rank}|reason=zero_residual_pairing_radical\\n";
else
    printf "CFNMSEL|target={target_id}|classification=HIGHER_DESCENT_REQUIRED|residual_dim=%o|radical_dim=%o|radical_indices=%o|action=four_descent_only_on_radical_classes\\n",
        residual_dim, radical_dim, radical;
end if;
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--target", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--pairing-cover-cap", type=int, default=63)
    args = parser.parse_args()
    if args.pairing_cover_cap < 1:
        parser.error("--pairing-cover-cap must be positive")
    _, target = load_target(args.manifest, args.target)
    text = build_magma(
        target,
        manifest_sha256=sha256_file(args.manifest),
        pairing_cover_cap=args.pairing_cover_cap,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"WROTE {args.output}")
    print(f"TARGET={target['id']}")
    print("PROTOCOL=CFNMSEL_v1")


if __name__ == "__main__":
    main()
