#!/usr/bin/env python3
"""Certify 2,3,5-saturation of each of the six own27-point search subgroups."""
import argparse,json
from dataclasses import asdict
from pathlib import Path
import certify_compact_r17_candidates as cert
from memory_rank_certificate import checked_rank
import audit_retained_cloud_modl as odd
from research_runtime.store import checkpoint
ROOT=Path(__file__).resolve().parents[2];ART=ROOT/'artifacts/generated-results/elliptic-curves';INDEX=ART/'new_high_rank_curve_index_v12.json';OUT=ART/'new27_small_prime_saturation_v1.json'

def expected():
    paths={Path(__file__).resolve(),INDEX,ROOT/'elliptic-curves/cas/memory_rank_certificate.py'};paths.update(ROOT/n for n in odd.sources());rows=[]
    for row in sorted((r for r in cert.read(INDEX)['curves'] if r['rank_lower_bound']==27),key=lambda r:r['id']):
        model=tuple(map(cert.F,row['curve']));points=[tuple(map(cert.F,P)) for P in row['points']];old=row['rank_certificate']
        proof=checked_rank(model,points,[r['prime'] for r in old['signatures']],old['no_rational_2_torsion_prime'])
        path=ART/('new27_specialized_'+row['id'].split('-')[-1]+'_modl_v1.json');paths.add(path);cloud=cert.read(path)
        if cloud['curve']!=row['curve'] or cloud['points'][:27]!=row['points'] or len(points)!=27:raise ArithmeticError('same own27 search subgroup required')
        audits=[]
        for audit in cloud['audits']:
            ell=audit['modulus'];torsion_prime=audit['no_rational_ell_torsion_prime'];signatures=[];matrix=[]
            if ell not in (3,5) or not odd.ml.no_rational_l_torsion_reduction_certificate(model,torsion_prime,ell):raise ArithmeticError('exact no rational ell torsion witness required')
            for original in audit['signatures']:
                sig=odd.finite.signature(model,points,original['prime'],ell)
                if [list(r) for r in sig.rows]!=[r[:27] for r in original['rows']]:raise ArithmeticError('recomputed own27 finite columns differ')
                signatures.append(asdict(sig));matrix.extend(sig.rows)
            if odd.finite.pivots(matrix,ell)!=list(range(27)):raise ArithmeticError('own27 columns not independent: saturation UNKNOWN')
            audits.append({'modulus':ell,'no_rational_ell_torsion_prime':torsion_prime,'finite_column_rank':27,'signatures':signatures})
        if [r['modulus'] for r in audits]!=[3,5]:raise ArithmeticError('both fixed odd prime proofs required')
        rows.append({'id':row['id'],'family':row['family'],'parameter':row['parameter'],'curve':row['curve'],'points':row['points'],'mod2_rank_and_injectivity_certificate':proof,'odd_prime_injectivity_certificates':audits,'saturated_at_primes':[2,3,5]})
    if len(rows)!=6:raise ArithmeticError('all and only six V12 rank27 curves required')
    return {'schema':'elliptic-curves.new27-small-prime-saturation.v1','status':'PASS','sources':{str(p.relative_to(ROOT)):cert.hashed(p) for p in sorted(paths)},'rows':rows,'lemma':'Let H be generated by r points whose images are independent in a product of E(F_p)/ell E(F_p), and suppose E(Q)[ell]=0. If ell Q=sum a_i P_i, reduction forces every a_i divisible by ell. Hence ell(Q-sum(a_i/ell)P_i)=0, and the torsion hypothesis gives Q in H. Thus H is ell-saturated in E(Q).','claim_boundary':'This verifies the fixed own27-point subgroups at ell2,3,5 using exact finite reductions, with no new rational-point search. It rules out the index3or5 known-section defect seen at five endpoints for these six particular subgroups. Larger-prime divisions, full saturation, whole-curve exact rank, independent directions beyond27 and improved search exposure remain unresolved.'}
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();d=expected()
    if a.check:
        if cert.read(OUT)!=json.loads(json.dumps(d)):raise ArithmeticError('small-prime saturation proof differs')
    else:
        if OUT.exists():raise FileExistsError('preserve small-prime saturation proof')
        checkpoint(OUT,d)
    print('ALL SIX OWN27 SUBGROUPS EXACTLY SATURATED AT2,3,5',flush=True)
