#!/usr/bin/env python3
"""Search Fermigier accidental directions through their auxiliary Jacobians.

The published rank-22 specialization supplies eleven non-generic quartic
points.  For each point and each slope ``m in {-1,+1}``, substitution

    X = m*T+n

in the Fermigier quartic produces a pointed genus-one quartic in ``T``.  The
earlier searches enumerated rational points in direct height boxes.  This
script instead maps all twenty-two pointed quartics to auxiliary elliptic
curves, constructs the subgroup generated by their intersections with the
thirteen generic sections, saturates it through 20, and enumerates a bounded
coefficient ball in that group.  This reaches parameter heights far outside
the direct boxes without claiming that the auxiliary Mordell--Weil groups are
known completely.

Every inverse image is checked exactly on both the auxiliary slice and the
specialized Fermigier quartic.  The even symmetry ``T -> -T``, all generic
intersections, and a pinned 590-parameter prior manifest are removed.  A
small-prime radical upper proxy and an independent good-prime score choose a
bounded exact-conductor tranche.  Only completed conductors below 182.72 are
sent to point/rank triage, and an exact finite-reduction certificate is
attempted immediately if the numerical rank reaches 21.

This remains a bounded search.  Numerical height ranks and radical proxies
are selection evidence, not rank or conductor theorems.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from fractions import Fraction
import hashlib
import heapq
import itertools
import json
from math import isqrt, log
from pathlib import Path
import platform
import re
import shlex
import sys
from typing import Any, Iterable, Sequence

from ek_k3 import rational_square_root, rational_to_string
from fermigier_mestre import (
    DISCRIMINANT_FACTOR_COEFFICIENTS,
    ROOTS,
    FermigierMestreFamily,
)
from pari_bridge import pari_version
from search_extra_points import gp_rational, gp_vector, run_gp
from search_fermigier_published_pair_fiber_products import (
    EXPECTED_PRIOR_PARAMETER_COUNT,
    EXPECTED_PRIOR_PARAMETER_SHA256,
    EXPECTED_PUBLISHED_PREIMAGE_SHA256,
    LEGACY_ACCIDENTAL_PARAMETERS,
    PRIMARY_ARTIFACT,
    extract_parameter_values,
    exact_slices,
    published_accidentals,
    published_preimage_digest,
    rational_digest,
    sha256_file,
    triage_specialization,
)
from search_fermigier_rank22_accidental_slices import (
    T0,
    conductor_probe,
    quartic_group_pullback,
)
from search_nagao_section7_auxiliary_group_orbits import parse_gp_exact
from search_nagao_section7_auxiliary_jacobians import (
    coefficient_vectors,
    translate_polynomial,
    weierstrass_add,
    weierstrass_multiply,
)
from search_record_residue_class import build_score_tables, score_rational
from triage_nagao_rank13_finalists import (
    height_matrix_replay,
    point_digest,
    point_on_short_curve,
    stable_height_rank,
)


Q = Fraction
if hasattr(sys, "set_int_max_str_digits"):
    sys.set_int_max_str_digits(0)
TARGET_LOG_CONDUCTOR = Decimal("182.72")
PRIOR_MANIFEST_ARTIFACT = (
    "elliptic_fermigier_published_pair_fiber_products_h50000.json"
)
EXPECTED_MANIFEST_ARTIFACT_SHA256 = (
    "cdca612edcce38150f77785f1fa24cd0208b38e19be6be6a872703c7625f1e52"
)
DEFAULT_MAX_ABSOLUTE_COEFFICIENT = 3
DEFAULT_MAX_L1_NORM = 5
DEFAULT_PROXY_PRIME_BOUND = 97
DEFAULT_SCORE_BOUND = 200
DEFAULT_PROXY_KEEP = 512
DEFAULT_CONDUCTOR_KEEP = 32
DEFAULT_SPECIALIZATION_HEIGHT = 50_000


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def projective_height(value: Fraction) -> int:
    value = Q(value)
    return max(abs(value.numerator), value.denominator)


def polynomial_value(
    coefficients: Sequence[Fraction], value: Fraction
) -> Fraction:
    answer = Q(0)
    for coefficient in reversed(coefficients):
        answer = answer * Q(value) + Q(coefficient)
    return answer


def first_nonzero_positive(vector: Sequence[int]) -> bool:
    """Choose one representative of ``v`` and ``-v``."""

    for value in vector:
        if value:
            return value > 0
    return False


def orbit_vectors(
    dimension: int,
    *,
    maximum_absolute_coefficient: int,
    maximum_l1_norm: int,
) -> tuple[tuple[int, ...], ...]:
    return tuple(
        vector
        for vector in coefficient_vectors(
            dimension,
            maximum_absolute_coefficient=maximum_absolute_coefficient,
            maximum_l1_norm=maximum_l1_norm,
        )
        if first_nonzero_positive(vector)
    )


@dataclass(frozen=True)
class AuxiliaryFermigierSlice:
    slice_id: str
    source_label: str
    slope: int
    intercept: Fraction
    source_x: Fraction
    source_y: Fraction
    quartic_coefficients: tuple[Fraction, ...]
    shifted_coefficients: tuple[Fraction, ...]
    weierstrass_coefficients: tuple[Fraction, ...]

    def quartic_value(self, parameter: Fraction) -> Fraction:
        return polynomial_value(self.quartic_coefficients, Q(parameter))

    def original_x(self, signed_parameter: Fraction) -> Fraction:
        return self.slope * Q(signed_parameter) + self.intercept

    def forward(
        self, point: tuple[Fraction, Fraction]
    ) -> tuple[Fraction, Fraction]:
        parameter, ordinate = (Q(value) for value in point)
        if ordinate**2 != self.quartic_value(parameter):
            raise ValueError("the point missed the auxiliary quartic")
        u_value = parameter - T0
        if u_value == 0:
            raise ValueError("the pointed base maps to infinity")
        _, d_value, c_value, _, _ = self.shifted_coefficients
        q_value = self.source_y
        x_value = (
            2 * q_value * (ordinate + q_value) + d_value * u_value
        ) / u_value**2
        y_value = (
            4 * q_value**2 * (ordinate + q_value)
            + 2 * q_value * (d_value * u_value + c_value * u_value**2)
            - d_value**2 * u_value**2 / (2 * q_value)
        ) / u_value**3
        image = x_value, y_value
        if not point_on_short_curve(self.weierstrass_coefficients, image):
            raise AssertionError("the exact pointed-quartic map failed")
        return image

    def inverse(
        self, point: tuple[Fraction, Fraction] | None
    ) -> tuple[Fraction, Fraction] | None:
        if point is None:
            return T0, self.source_y
        if not point_on_short_curve(self.weierstrass_coefficients, point):
            raise ValueError("the point missed the auxiliary Weierstrass model")
        x_value, y_value = point
        if y_value == 0:
            return None
        _, d_value, c_value, _, _ = self.shifted_coefficients
        q_value = self.source_y
        u_value = (
            4 * q_value**2 * (x_value + c_value) - d_value**2
        ) / (2 * q_value * y_value)
        if u_value == 0:
            return None
        ordinate = (
            (x_value * u_value**2 - d_value * u_value) / (2 * q_value)
            - q_value
        )
        parameter = T0 + u_value
        if ordinate**2 != self.quartic_value(parameter):
            raise AssertionError("the inverse pointed-quartic map failed")
        return parameter, ordinate


def make_auxiliary_slice(slice_data: Any) -> AuxiliaryFermigierSlice:
    coefficients = tuple(Q(value) for value in slice_data.coefficients)
    shifted = translate_polynomial(coefficients, T0)
    q_value = Q(slice_data.source_point[1])
    if len(shifted) != 5 or shifted[0] != q_value**2:
        raise AssertionError("the source point missed its auxiliary quartic")
    _, d_value, c_value, b_value, a_value = shifted
    weierstrass = (
        d_value / q_value,
        c_value - d_value**2 / (4 * q_value**2),
        2 * q_value * b_value,
        -4 * q_value**2 * a_value,
        a_value * (d_value**2 - 4 * q_value**2 * c_value),
    )
    return AuxiliaryFermigierSlice(
        slice_id=slice_data.identifier,
        source_label=slice_data.accidental_label,
        slope=int(slice_data.slope),
        intercept=Q(slice_data.intercept),
        source_x=Q(slice_data.source_point[0]),
        source_y=q_value,
        quartic_coefficients=coefficients,
        shifted_coefficients=shifted,
        weierstrass_coefficients=weierstrass,
    )


GENERIC_SECTION_LINES = tuple(
    (Q(sign), Q(root), f"visible-{root}-{'plus' if sign == 1 else 'minus'}")
    for root in ROOTS
    for sign in (-1, 1)
) + ((Q(-17, 35), Q(1256, 5), "Mestre-extra"),)


def generic_intersections(
    auxiliary: AuxiliaryFermigierSlice,
) -> tuple[tuple[Fraction, tuple[str, ...]], ...]:
    found: dict[Fraction, set[str]] = {}
    for slope, intercept, label in GENERIC_SECTION_LINES:
        if slope == auxiliary.slope:
            if intercept == auxiliary.intercept:
                raise AssertionError("an accidental slice became a generic section")
            continue
        parameter = Q(
            intercept - auxiliary.intercept,
            auxiliary.slope - slope,
        )
        square_root = rational_square_root(auxiliary.quartic_value(parameter))
        if square_root is None:
            raise AssertionError("a generic section intersection was not rational")
        found.setdefault(parameter, set()).add(label)
    return tuple(
        (parameter, tuple(sorted(labels)))
        for parameter, labels in sorted(
            found.items(), key=lambda item: (projective_height(item[0]), item[0])
        )
    )


def exact_seed_points(
    auxiliary: AuxiliaryFermigierSlice,
) -> tuple[tuple[tuple[Fraction, Fraction], ...], tuple[dict[str, Any], ...]]:
    points: list[tuple[Fraction, Fraction]] = []
    records = []
    for parameter, labels in generic_intersections(auxiliary):
        ordinate = rational_square_root(auxiliary.quartic_value(parameter))
        if ordinate is None:
            raise AssertionError("a generic ordinate disappeared")
        images = []
        if parameter != T0:
            for signed_ordinate in (ordinate, -ordinate):
                image = auxiliary.forward((parameter, signed_ordinate))
                if image not in points:
                    points.append(image)
                images.append(image)
        records.append(
            {
                "parameter_t": rational_to_string(parameter),
                "section_labels": list(labels),
                "mapped_sign_count": len(images),
            }
        )
    return tuple(points), tuple(records)


def saturate_basis(
    coefficients: Sequence[Fraction],
    basis: Sequence[tuple[Fraction, Fraction]],
    *,
    timeout: float,
    stack_bytes: int,
) -> tuple[tuple[tuple[Fraction, Fraction], ...], dict[str, Any]]:
    curve = ",".join(gp_rational(Q(value)) for value in coefficients)
    points = ",".join(gp_vector(point) for point in basis)
    program = "\n".join(
        (
            f"E=ellinit([{curve}]);K=[{points}];",
            "default(realprecision,120);",
            "D0=matdet(ellheightmatrix(E,K));W=ellsaturation(E,K,20);",
            "D1=matdet(ellheightmatrix(E,W));SI=round(sqrt(D0/D1));",
            'print("SATURATION ",SI,"|",W,"|",D1);',
            "quit",
            "",
        )
    )
    try:
        output, wall_seconds = run_gp(
            program, timeout=timeout, stack_bytes=stack_bytes
        )
    except Exception as error:
        return tuple(basis), {
            "status": "failed",
            "error": str(error)[:500],
            "fallback_used": "unsaturated exact independent basis",
        }
    match = re.search(r"SATURATION (\d+)\|(.*?)\|([^|\n]+)$", output, re.MULTILINE)
    if match is None:
        raise AssertionError("PARI omitted saturation markers")
    parsed = parse_gp_exact(match.group(2))
    saturated = tuple((Q(point[0]), Q(point[1])) for point in parsed)
    if len(saturated) != len(basis) or any(
        not point_on_short_curve(coefficients, point) for point in saturated
    ):
        raise AssertionError("the saturated auxiliary basis failed exact replay")
    return saturated, {
        "status": "completed",
        "prime_bound": 20,
        "index_improvement": int(match.group(1)),
        "height_determinant": match.group(3),
        "wall_seconds": wall_seconds,
        "basis_point_sha256": point_digest(saturated),
    }


def prior_parameter_manifest(
    artifact_directory: Path,
) -> tuple[set[Fraction], dict[str, Any]]:
    manifest_path = artifact_directory / PRIOR_MANIFEST_ARTIFACT
    if file_sha256(manifest_path) != EXPECTED_MANIFEST_ARTIFACT_SHA256:
        raise AssertionError("the pinned prior-manifest artifact changed")
    manifest = json.loads(manifest_path.read_text())
    source_rows = manifest["prior_decontamination"]["artifact_sources"]
    parameters = {abs(T0), *(abs(value) for value in LEGACY_ACCIDENTAL_PARAMETERS)}
    replayed = {}
    for name, source in sorted(source_rows.items()):
        path = artifact_directory / name
        observed = file_sha256(path)
        if observed != source["sha256"]:
            raise AssertionError(f"pinned prior source changed: {name}")
        extracted = extract_parameter_values(json.loads(path.read_text()))
        parameters.update(extracted)
        replayed[name] = {
            "sha256": observed,
            "extracted_parameter_count": len(extracted),
        }
    digest = rational_digest(sorted(parameters))
    if (
        len(parameters) != EXPECTED_PRIOR_PARAMETER_COUNT
        or digest != EXPECTED_PRIOR_PARAMETER_SHA256
    ):
        raise AssertionError("the pinned prior parameter population changed")
    return parameters, {
        "manifest_artifact": str(manifest_path),
        "manifest_artifact_sha256": EXPECTED_MANIFEST_ARTIFACT_SHA256,
        "unique_parameter_count": len(parameters),
        "parameter_sha256": digest,
        "source_artifacts": replayed,
    }


def linear_combination(
    coefficients: Sequence[Fraction],
    basis: Sequence[tuple[Fraction, Fraction]],
    vector: Sequence[int],
) -> tuple[Fraction, Fraction] | None:
    answer = None
    for point, scalar in zip(basis, vector, strict=True):
        if scalar:
            answer = weierstrass_add(
                coefficients,
                answer,
                weierstrass_multiply(coefficients, point, scalar),
            )
    return answer


@dataclass
class CandidateIncidence:
    source_labels: set[str]
    slice_ids: set[str]
    first_slice_id: str
    first_vector: tuple[int, ...]
    signed_parameter: Fraction
    ordinate: Fraction


def generate_orbits(
    auxiliaries: Sequence[AuxiliaryFermigierSlice],
    bases: dict[str, tuple[tuple[Fraction, Fraction], ...]],
    prior_parameters: set[Fraction],
    *,
    maximum_absolute_coefficient: int,
    maximum_l1_norm: int,
) -> tuple[dict[Fraction, CandidateIncidence], list[dict[str, Any]], dict[str, int]]:
    generic = {
        abs(parameter)
        for auxiliary in auxiliaries
        for parameter, _ in generic_intersections(auxiliary)
    }
    candidates: dict[Fraction, CandidateIncidence] = {}
    slice_records = []
    totals = {
        "coefficient_vectors": 0,
        "exceptional_inverse_images": 0,
        "record_or_zero": 0,
        "generic_intersections": 0,
        "prior_parameters": 0,
        "singular_parameters": 0,
        "accepted_incidences": 0,
    }
    for auxiliary in auxiliaries:
        basis = bases[auxiliary.slice_id]
        vectors = orbit_vectors(
            len(basis),
            maximum_absolute_coefficient=maximum_absolute_coefficient,
            maximum_l1_norm=maximum_l1_norm,
        )
        accepted = 0
        for vector in vectors:
            totals["coefficient_vectors"] += 1
            point = linear_combination(
                auxiliary.weierstrass_coefficients, basis, vector
            )
            inverse = auxiliary.inverse(point)
            if inverse is None:
                totals["exceptional_inverse_images"] += 1
                continue
            signed_parameter, ordinate = inverse
            parameter = abs(signed_parameter)
            if parameter in (Q(0), abs(T0)):
                totals["record_or_zero"] += 1
                continue
            if parameter in generic:
                totals["generic_intersections"] += 1
                continue
            if parameter in prior_parameters:
                totals["prior_parameters"] += 1
                continue
            if FermigierMestreFamily.discriminant_factor(parameter) == 0:
                totals["singular_parameters"] += 1
                continue
            x_value = auxiliary.original_x(signed_parameter)
            if ordinate**2 != FermigierMestreFamily.quartic_value(
                parameter, x_value
            ):
                raise AssertionError("an orbit point missed the canonical Fermigier fiber")
            existing = candidates.get(parameter)
            if existing is None:
                candidates[parameter] = CandidateIncidence(
                    source_labels={auxiliary.source_label},
                    slice_ids={auxiliary.slice_id},
                    first_slice_id=auxiliary.slice_id,
                    first_vector=tuple(vector),
                    signed_parameter=signed_parameter,
                    ordinate=ordinate,
                )
            else:
                existing.source_labels.add(auxiliary.source_label)
                existing.slice_ids.add(auxiliary.slice_id)
            accepted += 1
            totals["accepted_incidences"] += 1
        slice_records.append(
            {
                "slice_id": auxiliary.slice_id,
                "source_label": auxiliary.source_label,
                "basis_rank": len(basis),
                "sign_quotiented_vector_count": len(vectors),
                "accepted_incidence_count": accepted,
            }
        )
        print(
            f"orbit {auxiliary.slice_id}: vectors={len(vectors)} "
            f"accepted={accepted} unique_global={len(candidates)}",
            flush=True,
        )
    totals["unique_parameters"] = len(candidates)
    totals["multiple_source_parameters"] = sum(
        len(record.source_labels) >= 2 for record in candidates.values()
    )
    return candidates, slice_records, totals


def homogenized_discriminant_factor(parameter: Fraction) -> int:
    parameter = Q(parameter)
    numerator, denominator = parameter.numerator, parameter.denominator
    degree = len(DISCRIMINANT_FACTOR_COEFFICIENTS) - 1
    return sum(
        int(coefficient)
        * numerator**power
        * denominator ** (degree - power)
        for power, coefficient in enumerate(DISCRIMINANT_FACTOR_COEFFICIENTS)
    )


def primes_up_to(bound: int) -> tuple[int, ...]:
    if bound < 2:
        return ()
    sieve = bytearray(b"\x01") * (bound + 1)
    sieve[:2] = b"\x00\x00"
    for value in range(2, isqrt(bound) + 1):
        if sieve[value]:
            sieve[value * value : bound + 1 : value] = b"\x00" * (
                (bound - value * value) // value + 1
            )
    return tuple(index for index, flag in enumerate(sieve) if flag)


def radical_upper_proxy(
    parameter: Fraction, *, prime_bound: int
) -> dict[str, Any]:
    parameter = Q(parameter)
    remaining = abs(homogenized_discriminant_factor(parameter))
    denominator_remaining = parameter.denominator
    support = {2, 3}
    valuations = {}
    for prime in primes_up_to(prime_bound):
        valuation = 0
        while remaining % prime == 0:
            remaining //= prime
            valuation += 1
        if valuation:
            support.add(prime)
            valuations[str(prime)] = valuation
        while denominator_remaining % prime == 0:
            denominator_remaining //= prime
            support.add(prime)
    log_upper = sum(log(prime) for prime in support)
    if remaining > 1:
        log_upper += log(remaining)
    if denominator_remaining > 1:
        log_upper += log(denominator_remaining)
    return {
        "log_radical_upper_proxy": log_upper,
        "trial_prime_bound": prime_bound,
        "small_prime_valuations": valuations,
        "unfactored_discriminant_cofactor_digits": len(str(remaining)),
        "unfactored_denominator_cofactor": denominator_remaining,
    }


def candidate_stream_digest(parameters: Iterable[Fraction]) -> str:
    digest = hashlib.sha256()
    for parameter in sorted(
        parameters,
        key=lambda value: (
            projective_height(value),
            value.numerator,
            value.denominator,
        ),
    ):
        digest.update((rational_to_string(parameter) + "\n").encode())
    return digest.hexdigest()


def selected_proxy_records(
    candidates: dict[Fraction, CandidateIncidence],
    *,
    prime_bound: int,
    score_bound: int,
    keep: int,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    tables = build_score_tables(score_bound, "fermigier-good")
    # Keep a bounded heap while still evaluating every generated parameter.
    heap: list[tuple[float, int, int, int, Fraction, dict[str, Any]]] = []
    minimum_proxy = float("inf")
    below_190 = 0
    for index, (parameter, incidence) in enumerate(candidates.items(), start=1):
        proxy = radical_upper_proxy(parameter, prime_bound=prime_bound)
        proxy_value = float(proxy["log_radical_upper_proxy"])
        minimum_proxy = min(minimum_proxy, proxy_value)
        if proxy_value < 190.0:
            below_190 += 1
        score = score_rational(
            parameter.numerator, parameter.denominator, tables
        )
        record = {
            "parameter_t": rational_to_string(parameter),
            "projective_height": projective_height(parameter),
            "source_labels": sorted(incidence.source_labels),
            "slice_ids": sorted(incidence.slice_ids),
            "first_slice_id": incidence.first_slice_id,
            "first_coefficient_vector": list(incidence.first_vector),
            "signed_parameter_t": rational_to_string(incidence.signed_parameter),
            "ordinate": rational_to_string(incidence.ordinate),
            "radical_proxy": proxy,
            "good_prime_score_B200": score,
        }
        # The heap root is the worst retained key.  Negating the desired
        # ascending key avoids materializing proxy records for every orbit.
        key = (
            -proxy_value,
            -len(incidence.source_labels),
            -projective_height(parameter),
            -parameter.numerator,
            parameter,
            record,
        )
        if len(heap) < keep:
            heapq.heappush(heap, key)
        elif key > heap[0]:
            heapq.heapreplace(heap, key)
        if index % 10_000 == 0:
            print(
                f"proxy {index}/{len(candidates)} minimum={minimum_proxy:.6f} "
                f"below190={below_190}",
                flush=True,
            )
    records = [item[-1] for item in heap]
    records.sort(
        key=lambda record: (
            record["radical_proxy"]["log_radical_upper_proxy"],
            -len(record["source_labels"]),
            -record["good_prime_score_B200"]["value"],
            record["projective_height"],
            Q(record["parameter_t"]),
        )
    )
    return records, {
        "evaluated_parameter_count": len(candidates),
        "minimum_log_radical_upper_proxy": minimum_proxy,
        "proxy_below_190_count": below_190,
        "retained_count": len(records),
        "score_bound": score_bound,
        "proxy_prime_bound": prime_bound,
    }


def conductor_selection(
    proxy_records: Sequence[dict[str, Any]], *, keep: int
) -> list[dict[str, Any]]:
    feasible = [
        record
        for record in proxy_records
        if record["radical_proxy"]["log_radical_upper_proxy"] < 195.0
    ]
    selected: dict[str, dict[str, Any]] = {}
    for record in feasible[: keep // 2]:
        selected[record["parameter_t"]] = record
    for record in sorted(
        feasible,
        key=lambda item: (
            -item["good_prime_score_B200"]["value"],
            item["radical_proxy"]["log_radical_upper_proxy"],
            item["projective_height"],
        ),
    )[:keep]:
        selected.setdefault(record["parameter_t"], record)
        if len(selected) >= keep:
            break
    return sorted(
        selected.values(),
        key=lambda item: (
            item["radical_proxy"]["log_radical_upper_proxy"],
            -item["good_prime_score_B200"]["value"],
            item["projective_height"],
        ),
    )


def build_parser() -> argparse.ArgumentParser:
    root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--max-absolute-coefficient",
        type=int,
        default=DEFAULT_MAX_ABSOLUTE_COEFFICIENT,
    )
    parser.add_argument("--max-l1-norm", type=int, default=DEFAULT_MAX_L1_NORM)
    parser.add_argument("--proxy-prime-bound", type=int, default=DEFAULT_PROXY_PRIME_BOUND)
    parser.add_argument("--score-bound", type=int, default=DEFAULT_SCORE_BOUND)
    parser.add_argument("--proxy-keep", type=int, default=DEFAULT_PROXY_KEEP)
    parser.add_argument("--conductor-keep", type=int, default=DEFAULT_CONDUCTOR_KEEP)
    parser.add_argument("--conductor-timeout", type=float, default=15.0)
    parser.add_argument("--height-timeout", type=float, default=20.0)
    parser.add_argument("--saturation-timeout", type=float, default=20.0)
    parser.add_argument("--specialization-timeout", type=float, default=30.0)
    parser.add_argument("--specialization-height", type=int, default=DEFAULT_SPECIALIZATION_HEIGHT)
    parser.add_argument("--certificate-prime-bound", type=int, default=2_000)
    parser.add_argument("--stack-bytes", type=int, default=512_000_000)
    parser.add_argument(
        "--output",
        type=Path,
        default=root
        / "artifacts"
        / "generated-results"
        / "elliptic_fermigier_rank22_auxiliary_orbits.json",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    if not 1 <= args.max_absolute_coefficient <= 5:
        raise SystemExit("--max-absolute-coefficient must lie in [1,5]")
    if not 1 <= args.max_l1_norm <= 10:
        raise SystemExit("--max-l1-norm must lie in [1,10]")
    if not 5 <= args.proxy_prime_bound <= 10_000:
        raise SystemExit("--proxy-prime-bound must lie in [5,10000]")
    if not 5 <= args.score_bound <= 2_000:
        raise SystemExit("--score-bound must lie in [5,2000]")
    if min(
        args.proxy_keep,
        args.conductor_keep,
        args.specialization_height,
        args.certificate_prime_bound,
        args.stack_bytes,
    ) <= 0:
        raise SystemExit("all count, height, and memory bounds must be positive")
    if args.specialization_height != DEFAULT_SPECIALIZATION_HEIGHT:
        raise SystemExit(
            "the shared exact triage engine is pinned at specialization height 50000"
        )
    if min(
        args.conductor_timeout,
        args.height_timeout,
        args.saturation_timeout,
        args.specialization_timeout,
    ) <= 0:
        raise SystemExit("all subprocess timeouts must be positive")

    root = Path(__file__).resolve().parents[2]
    if not args.output.is_absolute():
        args.output = (root / args.output).resolve()
    artifact_directory = root / "artifacts" / "generated-results"
    primary_path = artifact_directory / PRIMARY_ARTIFACT
    primary = json.loads(primary_path.read_text())
    if published_preimage_digest(primary) != EXPECTED_PUBLISHED_PREIMAGE_SHA256:
        raise AssertionError("the exact published accidental population changed")
    slices = exact_slices(published_accidentals(primary))
    auxiliaries = tuple(make_auxiliary_slice(slice_data) for slice_data in slices)
    prior_parameters, prior_record = prior_parameter_manifest(artifact_directory)

    bases: dict[str, tuple[tuple[Fraction, Fraction], ...]] = {}
    auxiliary_records = []
    for auxiliary in auxiliaries:
        seeds, intersection_records = exact_seed_points(auxiliary)
        height_runs = height_matrix_replay(
            auxiliary.weierstrass_coefficients,
            seeds,
            precisions=(72, 120),
            timeout=args.height_timeout,
            stack_bytes=args.stack_bytes,
        )
        numerical_rank = stable_height_rank(height_runs)
        if any(run["numerical_rank"] != numerical_rank for run in height_runs):
            raise AssertionError("an auxiliary height rank was precision-unstable")
        indices = tuple(height_runs[-1]["subset_indices_one_based"])
        if any(tuple(run["subset_indices_one_based"]) != indices for run in height_runs):
            raise AssertionError("an auxiliary height subset was precision-unstable")
        independent = tuple(seeds[index - 1] for index in indices)
        saturated, saturation = saturate_basis(
            auxiliary.weierstrass_coefficients,
            independent,
            timeout=args.saturation_timeout,
            stack_bytes=args.stack_bytes,
        )
        bases[auxiliary.slice_id] = saturated
        auxiliary_records.append(
            {
                "slice_id": auxiliary.slice_id,
                "source_label": auxiliary.source_label,
                "slope": auxiliary.slope,
                "intercept": rational_to_string(auxiliary.intercept),
                "quartic_coefficients_ascending": [
                    rational_to_string(value)
                    for value in auxiliary.quartic_coefficients
                ],
                "weierstrass_coefficients": [
                    rational_to_string(value)
                    for value in auxiliary.weierstrass_coefficients
                ],
                "generic_intersections": list(intersection_records),
                "signed_seed_point_count": len(seeds),
                "height_replay": list(height_runs),
                "stable_numerical_rank": numerical_rank,
                "selected_subset_indices_one_based": list(indices),
                "selected_point_sha256": point_digest(independent),
                "saturation": saturation,
                "saturated_basis": [
                    [rational_to_string(value) for value in point]
                    for point in saturated
                ],
            }
        )
        print(
            f"{auxiliary.slice_id}: rank={numerical_rank} "
            f"saturation={saturation.get('index_improvement')}"
        )

    candidates, slice_orbits, orbit_counts = generate_orbits(
        auxiliaries,
        bases,
        prior_parameters,
        maximum_absolute_coefficient=args.max_absolute_coefficient,
        maximum_l1_norm=args.max_l1_norm,
    )
    stream_sha256 = candidate_stream_digest(candidates)
    print(
        f"orbit parameters={len(candidates)} "
        f"multiple-source={orbit_counts['multiple_source_parameters']}"
    )

    proxy_records, proxy_summary = selected_proxy_records(
        candidates,
        prime_bound=args.proxy_prime_bound,
        score_bound=args.score_bound,
        keep=args.proxy_keep,
    )
    selected = conductor_selection(proxy_records, keep=args.conductor_keep)
    conductor_records = []
    target_hits = []
    for selected_record in selected:
        parameter = Q(selected_record["parameter_t"])
        conductor = conductor_probe(
            parameter,
            timeout=args.conductor_timeout,
            stack_bytes=args.stack_bytes,
        )
        record = {**selected_record, "conductor_probe": conductor}
        incidence = candidates[parameter]
        signed_parameter = incidence.signed_parameter
        auxiliary = next(
            item for item in auxiliaries if item.slice_id == incidence.first_slice_id
        )
        x_value = auxiliary.original_x(signed_parameter)
        ordinate = incidence.ordinate
        forced_pullback = quartic_group_pullback(
            parameter, (x_value, ordinate)
        )
        if forced_pullback is None:
            raise AssertionError("the generated accidental point pulled back to zero")
        record["forced_point"] = {
            "quartic_x": rational_to_string(x_value),
            "quartic_z": rational_to_string(ordinate),
            "basepoint_group_pullback": {
                "jacobian_x": rational_to_string(forced_pullback[0]),
                "jacobian_y": rational_to_string(forced_pullback[1]),
                "exact_membership_checked": True,
            },
        }
        if conductor.get("below_strict_log_conductor_target"):
            candidate = {
                "parameter_t": rational_to_string(parameter),
                "forced_points": [record["forced_point"]],
            }
            triage = triage_specialization(
                candidate,
                search_timeout=args.specialization_timeout,
                height_timeout=args.height_timeout,
                precisions=(72, 120),
                stack_bytes=args.stack_bytes,
                saturation_timeout=args.saturation_timeout,
                certificate_prime_bound=args.certificate_prime_bound,
            )
            record["rank_triage"] = triage
            certificate = triage.get("finite_reduction_attempt")
            if (
                certificate is not None
                and certificate.get("certified_algebraic_rank_lower_bound", 0) >= 21
            ):
                target_hits.append(record)
        conductor_records.append(record)
        print(
            f"T={parameter} conductor={conductor.get('log_conductor')} "
            f"rank={(record.get('rank_triage') or {}).get('full_pool_stable_numerical_rank')}"
        )

    script_path = Path(__file__).resolve()
    artifact = {
        "schema_version": 1,
        "status": (
            "target hit certified"
            if target_hits
            else "bounded auxiliary-Jacobian orbit search; no target hit"
        ),
        "target": {
            "rank_at_least": 21,
            "strict_log_conductor_below": "182.72",
            "alternative_rank_at_least": 30,
            "target_hit": bool(target_hits),
        },
        "parameters": {
            "maximum_absolute_coefficient": args.max_absolute_coefficient,
            "maximum_l1_norm": args.max_l1_norm,
            "global_sign_quotient": True,
            "proxy_prime_bound": args.proxy_prime_bound,
            "score_bound": args.score_bound,
            "proxy_keep": args.proxy_keep,
            "conductor_keep": args.conductor_keep,
            "conductor_timeout_seconds": args.conductor_timeout,
            "height_timeout_seconds": args.height_timeout,
            "saturation_timeout_seconds": args.saturation_timeout,
            "specialization_timeout_seconds": args.specialization_timeout,
            "specialization_height": args.specialization_height,
            "certificate_prime_bound": args.certificate_prime_bound,
            "stack_bytes": args.stack_bytes,
        },
        "source": {
            "primary_artifact": str(primary_path),
            "primary_artifact_sha256": file_sha256(primary_path),
            "published_preimage_sha256": published_preimage_digest(primary),
            "prior_manifest": prior_record,
        },
        "auxiliary_curves": auxiliary_records,
        "orbit_generation": {
            "slice_records": slice_orbits,
            "counts": orbit_counts,
            "candidate_parameter_sha256": stream_sha256,
            "scope": (
                "saturated-through-20 subgroup coefficient vectors only; "
                "not a complete Mordell-Weil or rational-point enumeration"
            ),
        },
        "proxy_selection": {
            "summary": proxy_summary,
            "records": proxy_records,
        },
        "conductor_and_rank_tranche": conductor_records,
        "target_hits": target_hits,
        "outcome": {
            "unique_orbit_parameters": len(candidates),
            "multiple_source_parameters": orbit_counts[
                "multiple_source_parameters"
            ],
            "completed_conductors": sum(
                record["conductor_probe"].get("status") == "completed"
                for record in conductor_records
            ),
            "subtarget_conductors": sum(
                bool(record["conductor_probe"].get("below_strict_log_conductor_target"))
                for record in conductor_records
            ),
            "maximum_stable_numerical_rank": max(
                (
                    record.get("rank_triage", {}).get(
                        "full_pool_stable_numerical_rank", 0
                    )
                    for record in conductor_records
                ),
                default=0,
            ),
            "certified_target_hits": len(target_hits),
        },
        "software": {
            "python": platform.python_version(),
            "pari_gp": pari_version(),
        },
        "script_sha256": file_sha256(script_path),
        "reproducing_command": " ".join(
            shlex.quote(part)
            for part in (
                "env",
                "PYTHONPATH=elliptic-curves/cas",
                ".venv/bin/python",
                str(script_path.relative_to(root)),
                "--max-absolute-coefficient",
                str(args.max_absolute_coefficient),
                "--max-l1-norm",
                str(args.max_l1_norm),
                "--proxy-prime-bound",
                str(args.proxy_prime_bound),
                "--score-bound",
                str(args.score_bound),
                "--proxy-keep",
                str(args.proxy_keep),
                "--conductor-keep",
                str(args.conductor_keep),
                "--conductor-timeout",
                str(args.conductor_timeout),
                "--height-timeout",
                str(args.height_timeout),
                "--saturation-timeout",
                str(args.saturation_timeout),
                "--specialization-timeout",
                str(args.specialization_timeout),
                "--specialization-height",
                str(args.specialization_height),
                "--certificate-prime-bound",
                str(args.certificate_prime_bound),
                "--stack-bytes",
                str(args.stack_bytes),
                "--output",
                str(args.output.relative_to(root)),
            )
        ),
        "completed_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(artifact, indent=2, sort_keys=True) + "\n")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
