#!/usr/bin/env python3
"""Audit sextic Lie sectors and exclude corrections of quartic defects.

For the stored cubic vector field H, two exact torus gradings split

    L_H : Sym^6 -> Sym^8

into 220 blocks.  This audit classifies every block with at most 3000 source
monomials: 192 blocks and 73548 of the 230230 sextic monomials.  Modulo the
good prime 1000003, all those blocks are injective except sectors (0,6),
(1,5), and (2,4), whose one-dimensional kernels are exactly the expected
directions X_20^6, X_20^4*Q, and X_20^2*Q^2 for
Q=X_18*X_20-X_6*X_8.  Exact rational differentiation verifies that these
three displayed directions are in the Lie kernel.  The modular ranks
therefore give characteristic-zero certificates.

The degree-eight defects of X_20^2*Q and Q^2 lie in sectors (1,3) and (2,2).
Their blocks have ranks 103 and 1604 (full column rank), and appending the
corresponding defect raises each rank.  Thus no sextic correction rescues
either lower-degree near-invariant direction.

Recursive unique-row peeling completely certifies 25 of the 28 larger
blocks.  Only sectors (2,0), (3,3), and (4,6) leave residual cores, with
1596, 1956, and 2170 columns.  Their modular ranks are respectively 1596,
1955, and 2170.  Exact differentiation supplies Q^3 in the one-dimensional
(3,3) kernel.  Consequently the complete rational sextic Lie kernel is

    <X_20^6, X_20^4*Q, X_20^2*Q^2, Q^3>.

Their exact pullback defects show that only X_20^6 is fixed by the full map.

Finally, exact monomial enumeration identifies the two degree-seven
correction blocks as X_20 times the already excluded sextic defect blocks:
(1,4)=X_20*(1,3) and (2,3)=X_20*(2,2).  Since L_H(X_20*P)=X_20*L_H(P),
neither quintic near-invariant direction admits a degree-seven correction.
For the remaining pure septic problem, reduction modulo X_20 has 657800
source monomials in 204 sectors.  Unique-row peeling removes 451891 columns
and leaves a 205909-column core in 79 sectors.  This is an exact support
reduction, not a classification of the residual quotient kernel or its lifts.

The reduced derivation has an exact vertical form: it fixes X_0,...,X_13
and sends X_14,...,X_19 to cubics in those fourteen base variables.  Hence
the first s-adic lifting obstruction for a base polynomial takes values
modulo the ideal generated by those six cubics.  The extreme class X_9^7 is
already nonliftable: L_H(X_9^7)=7*s*X_0^2*X_9^6, while the required sextic
correction sector (-14,-50) is empty.
"""

from __future__ import annotations

from collections import Counter, defaultdict, deque
from fractions import Fraction
from itertools import combinations_with_replacement
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = (
    ROOT
    / "artifacts"
    / "generated-results"
    / "essential_bcw_21_counterexample.json"
)
PRIME = 1_000_003
DIMENSION = 21
DEGREE = 6

WEIGHT_1 = (-1, 1, 2, 1, 1, 0, 1, 2, 0, -2, 0, 1, 1, 2, -1, 1, 2, 1, 1, 0, 0)
WEIGHT_2 = (-4, 2, 5, 2, 2, -1, 2, 5, -1, -7, -1, 2, 2, 5, -6, 0, 3, 0, 0, -3, 1)

PackedPoly = dict[int, int]
ExactPackedPoly = dict[int, Fraction]
DecodedComponent = list[tuple[int, int]]
ExactDecodedComponent = list[tuple[int, Fraction]]


def rational_mod(value: str) -> int:
    number = Fraction(value)
    return number.numerator * pow(number.denominator, -1, PRIME) % PRIME


def pack(exponent: list[int] | tuple[int, ...]) -> int:
    return sum(power << (4 * variable) for variable, power in enumerate(exponent))


def add_term(poly: PackedPoly, monomial: int, coefficient: int) -> None:
    updated = (poly.get(monomial, 0) + coefficient) % PRIME
    if updated:
        poly[monomial] = updated
    else:
        poly.pop(monomial, None)


def bidegree(exponent: list[int] | tuple[int, ...]) -> tuple[int, int]:
    return (
        sum(weight * power for weight, power in zip(WEIGHT_1, exponent)),
        sum(weight * power for weight, power in zip(WEIGHT_2, exponent)),
    )


def decode_h(source: dict[str, object]) -> list[DecodedComponent]:
    components = []
    for output, component in enumerate(source["H"]):
        decoded = []
        for term in component:
            exponent = [0] * DIMENSION
            for variable, power in term["monomial"]:
                exponent[variable] = power
            # Both gradings make every H_output term have the weight of X_output.
            assert bidegree(exponent) == (
                WEIGHT_1[output],
                WEIGHT_2[output],
            )
            decoded.append((pack(exponent), rational_mod(term["coefficient"])))
        components.append(decoded)
    return components


def decode_h_exact(source: dict[str, object]) -> list[ExactDecodedComponent]:
    components = []
    for component in source["H"]:
        decoded = []
        for term in component:
            exponent = [0] * DIMENSION
            for variable, power in term["monomial"]:
                exponent[variable] = power
            decoded.append((pack(exponent), Fraction(term["coefficient"])))
        components.append(decoded)
    return components


def reduce_column(
    column: PackedPoly, pivots: dict[int, PackedPoly]
) -> tuple[bool, PackedPoly]:
    while column:
        pivot = min(column)
        coefficient = column[pivot]
        if pivot not in pivots:
            return False, column
        for monomial, value in pivots[pivot].items():
            add_term(column, monomial, -coefficient * value)
    return True, column


def column_from_indices(
    components: list[DecodedComponent], indices: tuple[int, ...]
) -> PackedPoly:
    exponent = [0] * DIMENSION
    packed_exponent = 0
    for index in indices:
        exponent[index] += 1
        packed_exponent += 1 << (4 * index)
    column: PackedPoly = {}
    for variable, power in enumerate(exponent):
        if not power:
            continue
        base = packed_exponent - (1 << (4 * variable))
        for h_monomial, coefficient in components[variable]:
            add_term(column, base + h_monomial, power * coefficient)
    return column


def sector_columns(
    components: list[DecodedComponent], sector: tuple[int, int]
) -> list[PackedPoly]:
    columns = []
    for indices in combinations_with_replacement(range(DIMENSION), DEGREE):
        if (
            sum(WEIGHT_1[index] for index in indices),
            sum(WEIGHT_2[index] for index in indices),
        ) != sector:
            continue
        columns.append(column_from_indices(components, indices))
    return columns


def column_pivots(columns: list[PackedPoly]) -> dict[int, PackedPoly]:
    pivots: dict[int, PackedPoly] = {}
    for original in columns:
        inside, residual = reduce_column(dict(original), pivots)
        if inside:
            continue
        pivot = min(residual)
        inverse = pow(residual[pivot], -1, PRIME)
        pivots[pivot] = {
            monomial: coefficient * inverse % PRIME
            for monomial, coefficient in residual.items()
        }
    return pivots


def rank_and_target(
    columns: list[PackedPoly], target: PackedPoly
) -> tuple[int, bool, int]:
    pivots = column_pivots(columns)
    inside, residual = reduce_column(dict(target), pivots)
    return len(pivots), inside, len(residual)


def exact_lie_derivative(
    components: list[ExactDecodedComponent], polynomial: ExactPackedPoly
) -> ExactPackedPoly:
    answer: ExactPackedPoly = {}
    for packed_exponent, polynomial_coefficient in polynomial.items():
        for variable in range(DIMENSION):
            shift = 4 * variable
            power = (packed_exponent >> shift) & 15
            if not power:
                continue
            base = packed_exponent - (1 << shift)
            for h_monomial, h_coefficient in components[variable]:
                monomial = base + h_monomial
                updated = answer.get(monomial, Fraction(0))
                updated += polynomial_coefficient * power * h_coefficient
                if updated:
                    answer[monomial] = updated
                else:
                    answer.pop(monomial, None)
    return answer


def packed_monomial(**powers: int) -> int:
    exponent = [0] * DIMENSION
    for variable_text, power in powers.items():
        exponent[int(variable_text[1:])] = power
    return pack(exponent)


def verify_expected_exact_kernels(
    components: list[ExactDecodedComponent],
) -> None:
    s6 = {packed_monomial(X20=6): Fraction(1)}
    s4_q = {
        packed_monomial(X18=1, X20=5): Fraction(1),
        packed_monomial(X6=1, X8=1, X20=4): Fraction(-1),
    }
    s2_q2 = {
        packed_monomial(X18=2, X20=4): Fraction(1),
        packed_monomial(X6=1, X8=1, X18=1, X20=3): Fraction(-2),
        packed_monomial(X6=2, X8=2, X20=2): Fraction(1),
    }
    q3 = {
        packed_monomial(X18=3, X20=3): Fraction(1),
        packed_monomial(X6=1, X8=1, X18=2, X20=2): Fraction(-3),
        packed_monomial(X6=2, X8=2, X18=1, X20=1): Fraction(3),
        packed_monomial(X6=3, X8=3): Fraction(-1),
    }
    for polynomial in (s6, s4_q, s2_q2, q3):
        assert exact_lie_derivative(components, polynomial) == {}


def peel_unique_rows(
    columns: list[PackedPoly],
) -> tuple[int, list[PackedPoly]]:
    """Split off columns certified by recursive degree-one support rows."""
    row_columns: defaultdict[int, set[int]] = defaultdict(set)
    for column_index, column in enumerate(columns):
        for row in column:
            row_columns[row].add(column_index)

    active = [True] * len(columns)
    queue = deque(row for row, support in row_columns.items() if len(support) == 1)
    peeled = 0
    while queue:
        row = queue.popleft()
        support = row_columns[row]
        if len(support) != 1:
            continue
        column_index = next(iter(support))
        if not active[column_index]:
            continue
        active[column_index] = False
        peeled += 1
        for incident_row in columns[column_index]:
            incident_support = row_columns[incident_row]
            incident_support.discard(column_index)
            if len(incident_support) == 1:
                queue.append(incident_row)

    core_rows = {row for row, support in row_columns.items() if support}
    core_columns = [
        {
            row: coefficient
            for row, coefficient in column.items()
            if row in core_rows
        }
        for column, is_active in zip(columns, active)
        if is_active
    ]
    return peeled, core_columns


def small_sector_ledger(
    components: list[DecodedComponent],
) -> tuple[dict[tuple[int, int], tuple[int, int]], int, int]:
    counts: Counter[tuple[int, int]] = Counter()
    for indices in combinations_with_replacement(range(DIMENSION), DEGREE):
        sector = (
            sum(WEIGHT_1[index] for index in indices),
            sum(WEIGHT_2[index] for index in indices),
        )
        counts[sector] += 1

    selected = {sector for sector, size in counts.items() if size <= 3000}
    buckets = {sector: [] for sector in selected}
    for indices in combinations_with_replacement(range(DIMENSION), DEGREE):
        sector = (
            sum(WEIGHT_1[index] for index in indices),
            sum(WEIGHT_2[index] for index in indices),
        )
        if sector in buckets:
            buckets[sector].append(indices)

    ledger = {}
    for sector, indices_list in sorted(buckets.items()):
        columns = [
            column_from_indices(components, indices) for indices in indices_list
        ]
        ledger[sector] = (len(columns), len(column_pivots(columns)))

    unresolved_sectors = len(counts) - len(ledger)
    unresolved_monomials = sum(
        size for sector, size in counts.items() if sector not in ledger
    )
    return ledger, unresolved_sectors, unresolved_monomials


def dense_sector_ledger(
    components: list[DecodedComponent],
) -> dict[tuple[int, int], tuple[int, int, int, int]]:
    """Return size, peeled columns, core size, and rank for dense sectors."""
    counts: Counter[tuple[int, int]] = Counter()
    for indices in combinations_with_replacement(range(DIMENSION), DEGREE):
        sector = (
            sum(WEIGHT_1[index] for index in indices),
            sum(WEIGHT_2[index] for index in indices),
        )
        counts[sector] += 1

    selected = {sector for sector, size in counts.items() if size > 3000}
    buckets = {sector: [] for sector in selected}
    for indices in combinations_with_replacement(range(DIMENSION), DEGREE):
        sector = (
            sum(WEIGHT_1[index] for index in indices),
            sum(WEIGHT_2[index] for index in indices),
        )
        if sector in buckets:
            buckets[sector].append(indices)

    ledger = {}
    for sector, indices_list in sorted(buckets.items()):
        columns = [
            column_from_indices(components, indices) for indices in indices_list
        ]
        peeled, core = peel_unique_rows(columns)
        rank = peeled + len(column_pivots(core))
        ledger[sector] = (len(columns), peeled, len(core), rank)
    return ledger


def sector_indices(degree: int, sector: tuple[int, int]) -> list[tuple[int, ...]]:
    return [
        indices
        for indices in combinations_with_replacement(range(DIMENSION), degree)
        if (
            sum(WEIGHT_1[index] for index in indices),
            sum(WEIGHT_2[index] for index in indices),
        )
        == sector
    ]


def verify_degree_seven_shift() -> None:
    for degree_seven_sector, sextic_sector in (
        ((1, 4), (1, 3)),
        ((2, 3), (2, 2)),
    ):
        degree_seven = sector_indices(7, degree_seven_sector)
        sextic = sector_indices(6, sextic_sector)
        assert all(indices[-1] == 20 for indices in degree_seven)
        assert [indices[:-1] for indices in degree_seven] == sextic


def degree_seven_quotient_peeling(
    components: list[DecodedComponent],
) -> tuple[int, int, int, int, int]:
    """Peel the degree-seven Lie map after reducing source and target mod s."""
    buckets: defaultdict[tuple[int, int], list[tuple[int, ...]]] = defaultdict(
        list
    )
    for indices in combinations_with_replacement(range(20), 7):
        sector = (
            sum(WEIGHT_1[index] for index in indices),
            sum(WEIGHT_2[index] for index in indices),
        )
        buckets[sector].append(indices)

    total_columns = 0
    total_peeled = 0
    total_core = 0
    residual_sectors = 0
    for indices_list in buckets.values():
        columns = []
        for indices in indices_list:
            column = {
                row: coefficient
                for row, coefficient in column_from_indices(
                    components, indices
                ).items()
                if not ((row >> (4 * 20)) & 15)
            }
            columns.append(column)
        peeled, core = peel_unique_rows(columns)
        total_columns += len(columns)
        total_peeled += peeled
        total_core += len(core)
        residual_sectors += bool(core)
    return (
        len(buckets),
        total_columns,
        total_peeled,
        residual_sectors,
        total_core,
    )


def verify_vertical_reduction_and_extreme_obstruction(
    source: dict[str, object],
    exact_components: list[ExactDecodedComponent],
) -> None:
    for component in source["H"][:14]:
        assert all(
            any(variable == 20 for variable, _ in term["monomial"])
            for term in component
        )
    for component in source["H"][14:20]:
        for term in component:
            if any(variable == 20 for variable, _ in term["monomial"]):
                continue
            assert all(variable < 14 for variable, _ in term["monomial"])

    extreme_source = sector_indices(7, (-14, -49))
    assert extreme_source == [(9, 9, 9, 9, 9, 9, 9)]
    assert sector_indices(6, (-14, -50)) == []
    x9_seventh = {packed_monomial(X9=7): Fraction(1)}
    expected = {
        packed_monomial(X0=2, X9=6, X20=1): Fraction(7),
    }
    assert exact_lie_derivative(exact_components, x9_seventh) == expected


def main() -> None:
    source = json.loads(SOURCE.read_text())
    assert source["dimension"] == DIMENSION
    assert source["H"][20] == []
    components = decode_h(source)
    exact_components = decode_h_exact(source)
    verify_expected_exact_kernels(exact_components)
    verify_degree_seven_shift()
    verify_vertical_reduction_and_extreme_obstruction(
        source, exact_components
    )
    quotient_peeling = degree_seven_quotient_peeling(components)
    assert quotient_peeling == (204, 657_800, 451_891, 79, 205_909)

    ledger, unresolved_sectors, unresolved_monomials = small_sector_ledger(
        components
    )
    assert len(ledger) == 192
    assert sum(size for size, _ in ledger.values()) == 73_548
    assert unresolved_sectors == 28
    assert unresolved_monomials == 156_682
    noninjective = {
        sector: (size, rank)
        for sector, (size, rank) in ledger.items()
        if rank != size
    }
    assert noninjective == {
        (0, 6): (1, 0),
        (1, 5): (24, 23),
        (2, 4): (486, 485),
    }

    dense_ledger = dense_sector_ledger(components)
    assert len(dense_ledger) == 28
    assert sum(size for size, _, _, _ in dense_ledger.values()) == 156_682
    residual_cores = {
        sector: result
        for sector, result in dense_ledger.items()
        if result[2]
    }
    assert residual_cores == {
        (2, 0): (4670, 3074, 1596, 4670),
        (3, 3): (5657, 3701, 1956, 5656),
        (4, 6): (6101, 3931, 2170, 6101),
    }
    dense_noninjective = {
        sector: (size, rank)
        for sector, (size, _, _, rank) in dense_ledger.items()
        if rank != size
    }
    assert dense_noninjective == {(3, 3): (5657, 5656)}

    # M=X_0^2*X_1*X_2 and s=X_20.
    first_target_exponent = [0] * DIMENSION
    first_target_exponent[0] = 2
    first_target_exponent[1] = 1
    first_target_exponent[2] = 1
    first_target_exponent[20] = 4
    first_target = {pack(first_target_exponent): 1}  # M*s^4
    assert bidegree(first_target_exponent) == (1, 3)

    # M*s^2*Q = M*X_18*s^3 - M*X_6*X_8*s^2.
    second_left = [0] * DIMENSION
    second_left[0] = 2
    second_left[1] = 1
    second_left[2] = 1
    second_left[18] = 1
    second_left[20] = 3
    second_right = [0] * DIMENSION
    second_right[0] = 2
    second_right[1] = 1
    second_right[2] = 1
    second_right[6] = 1
    second_right[8] = 1
    second_right[20] = 2
    assert bidegree(second_left) == bidegree(second_right) == (2, 2)
    second_target = {
        pack(second_left): 1,
        pack(second_right): PRIME - 1,
    }

    first_columns = sector_columns(components, (1, 3))
    first_rank, first_inside, first_residual = rank_and_target(
        first_columns, first_target
    )
    assert len(first_columns) == first_rank == 103
    assert not first_inside
    assert first_residual

    second_columns = sector_columns(components, (2, 2))
    second_rank, second_inside, second_residual = rank_and_target(
        second_columns, second_target
    )
    assert len(second_columns) == second_rank == 1604
    assert not second_inside
    assert second_residual

    print("PASS sextic sector audit: both stored torus gradings are exact")
    print(f"PASS sextic sector (1,3): rank {first_rank}/103 mod {PRIME}")
    print("PASS sextic sector (1,3): M*X_20^4 is outside the Lie image")
    print(f"PASS sextic sector (2,2): rank {second_rank}/1604 mod {PRIME}")
    print("PASS sextic sector (2,2): M*X_20^2*Q is outside the Lie image")
    print("PASS sextic ledger: exact ranks for 192/220 sectors (73548 columns)")
    print("PASS sextic ledger: only s^6, s^4*Q, s^2*Q^2 occur as kernels")
    print("PASS dense sextic ledger: 25/28 sectors certify by peeling alone")
    print("PASS dense cores: ranks 1596, 1955, 2170 in the three residual cores")
    print("PASS sextic sector (3,3): peel 3701, core rank 1955/1956")
    print("PASS sextic sector (3,3): rational Lie kernel is exactly <Q^3>")
    print("THEOREM: no sextic correction rescues the lower-degree Q directions")
    print("THEOREM: fixed polynomials through degree 6 are Q[X_20]_{<=6}")
    print("THEOREM: no degree-7 correction rescues the quintic Q directions")
    print("PASS septic mod-s peeling: 451891 columns peel, 205909 remain")
    print("PASS mod-s Lie map: constant vertical derivation over 14 base variables")
    print("PASS septic sector (-14,-49): X_9^7 has no s-adic lift")
    print("OPEN: residual mod-s septic kernel and its s-adic lifts")


if __name__ == "__main__":
    main()
