#!/usr/bin/env python3
"""Exact/modular tangent-space calculation for the degree <= 7 Keller locus."""

from itertools import product
import sympy as sp
from sympy.polys.matrices import DomainMatrix


x, y, z = sp.symbols("x y z")
vars_ = (x, y, z)
u = 1 + x*y
F = sp.Matrix([
    u**3*z + y**2*u*(4 + 3*x*y),
    y + 3*x*u**2*z + 3*x*y**2*(4 + 3*x*y),
    2*x - 3*x**2*y - x**3*z,
])


def monomials_upto(d):
    return [(i, j, k) for i in range(d + 1)
            for j in range(d + 1 - i)
            for k in range(d + 1 - i - j)]


def coefficient_matrix(polys):
    """Rows are monomials and columns are the supplied polynomials."""
    dicts = [sp.Poly(sp.expand(f), *vars_).as_dict() for f in polys]
    support = sorted(set().union(*(d.keys() for d in dicts)))
    return sp.MutableSparseMatrix(len(support), len(polys), {
        (i, j): d[m] for j, d in enumerate(dicts)
        for i, m in enumerate(support) if m in d
    }), support


def rank_mod_p(M, p):
    """Sparse Gaussian elimination over F_p."""
    rows = []
    for i in range(M.rows):
        row = {j: int(M[i, j]) % p for j in range(M.cols) if M[i, j] % p}
        rows.append(row)
    pivots = {}
    rank = 0
    for row in rows:
        while row:
            c = min(row)
            if c not in pivots:
                inv = pow(row[c], -1, p)
                row = {j: (v * inv) % p for j, v in row.items() if v % p}
                pivots[c] = row
                rank += 1
                break
            q = row[c]
            pivot = pivots[c]
            for j, v in pivot.items():
                nv = (row.get(j, 0) - q*v) % p
                if nv:
                    row[j] = nv
                else:
                    row.pop(j, None)
    return rank


J = F.jacobian(vars_)
adj = J.adjugate()
mons = monomials_upto(7)
tangent_images = []
labels = []
for component, exp in product(range(3), mons):
    m = x**exp[0] * y**exp[1] * z**exp[2]
    # d(det)_F(H) = trace(adj(DF) DH).
    image = sum(adj[j, component] * sp.diff(m, vars_[j]) for j in range(3))
    tangent_images.append(sp.expand(image))
    labels.append((component, exp))

M, equation_support = coefficient_matrix(tangent_images)
modular_ranks = {p: rank_mod_p(M, p) for p in (1000003, 1000033, 1000037)}
rank = DomainMatrix.from_Matrix(M).rank()

# Infinitesimal affine left-right action: A F + a + DF (B X + b), with
# tr(A)+tr(B)=0.  Eliminate A_22 using the trace relation.
Avars = sp.symbols("A0:9")
Bvars = sp.symbols("B0:9")
avars = sp.symbols("a0:3")
bvars = sp.symbols("b0:3")
A = sp.Matrix(3, 3, Avars)
B = sp.Matrix(3, 3, Bvars)
A = A.subs(Avars[8], -Avars[0]-Avars[4]-Bvars[0]-Bvars[4]-Bvars[8])
X = sp.Matrix(vars_)
Haff = sp.expand(A*F + sp.Matrix(avars) + J*(B*X + sp.Matrix(bvars)))
params = list(Avars[:8]) + list(Bvars) + list(avars) + list(bvars)
affine_columns = []
for par in params:
    affine_columns.append([sp.diff(Haff[i], par) for i in range(3)])

coord_mons = mons
coord_index = {(c, e): c*len(mons)+i for c in range(3)
               for i, e in enumerate(mons)}
O = sp.zeros(3*len(mons), len(params))
for col, vec in enumerate(affine_columns):
    for c, f in enumerate(vec):
        for e, coeff in sp.Poly(f, *vars_).as_dict().items():
            O[coord_index[c, e], col] = coeff
orbit_rank = O.rank()

print("ambient coefficient dimension:", 3*len(mons))
print("linearized determinant equation monomials:", len(equation_support))
print("modular ranks:", modular_ranks)
print("exact rational rank:", rank)
print("Zariski tangent dimension:", 3*len(mons) - rank)
print("affine source/target orbit tangent dimension:", orbit_rank)
print("tangent quotient by affine directions:", 3*len(mons) - rank - orbit_rank)


def bounded_coordinate_orbit(source_degree=7, target_degree=2):
    """Rank of bounded polynomial-coordinate directions that remain degree <= 7.

    A dual-number coordinate change is generated by a polynomial vector field.
    The paired source/target action preserves the fixed determinant precisely
    when the sum of the two (constant) divergences is zero.
    """
    smons = monomials_upto(source_degree)
    tmons = monomials_upto(target_degree)
    U = sp.symbols("U0:3")
    columns = []
    divergences = []
    for side, basis in (("source", smons), ("target", tmons)):
        for c, exp in product(range(3), basis):
            m = x**exp[0]*y**exp[1]*z**exp[2]
            if side == "source":
                vec = J[:, c]*m
                div = sp.diff(m, vars_[c])
            else:
                mt = m.subs(dict(zip(vars_, F)), simultaneous=True)
                vec = sp.eye(3)[:, c]*mt
                div = sp.diff(U[0]**exp[0]*U[1]**exp[1]*U[2]**exp[2], U[c])
                div = div.subs(dict(zip(U, F)), simultaneous=True)
            columns.append([sp.expand(q) for q in vec])
            divergences.append(sp.expand(div))

    # Constraint coefficients: no output terms above degree 7, no nonconstant
    # divergence, and zero total constant divergence.
    constraint_dicts = []
    low_dicts = []
    constraint_keys = set()
    low_keys = set()
    for vec, div in zip(columns, divergences):
        cd = {}
        ld = {}
        for c, f in enumerate(vec):
            for e, coefficient in sp.Poly(f, *vars_).as_dict().items():
                if sum(e) <= 7:
                    ld[(c, e)] = coefficient
                    low_keys.add((c, e))
                else:
                    cd[("high", c, e)] = coefficient
                    constraint_keys.add(("high", c, e))
        for e, coefficient in sp.Poly(div, *vars_).as_dict().items():
            key = ("div", e)
            cd[key] = cd.get(key, 0) + coefficient
            constraint_keys.add(key)
        constraint_dicts.append(cd)
        low_dicts.append(ld)
    constraint_keys = sorted(constraint_keys, key=str)
    low_keys = sorted(low_keys, key=str)
    C = sp.MutableSparseMatrix(len(constraint_keys), len(columns), {})
    D = sp.MutableSparseMatrix(len(low_keys), len(columns), {})
    ci = {k: i for i, k in enumerate(constraint_keys)}
    di = {k: i for i, k in enumerate(low_keys)}
    for j, (cd, ld) in enumerate(zip(constraint_dicts, low_dicts)):
        for k, v in cd.items(): C[ci[k], j] = v
        for k, v in ld.items(): D[di[k], j] = v
    p = 1000003
    rc = rank_mod_p(C, p)
    rcd = rank_mod_p(C.col_join(D), p)
    return len(columns), rc, rcd-rc


for td in (1, 2):
    nfields, constraints_rank, image_rank = bounded_coordinate_orbit(7, td)
    print(f"polynomial-coordinate bound (source 7, target {td}):",
          {"vector_fields": nfields, "constraint_rank": constraints_rank,
           "orbit_tangent_rank": image_rank})
