#!/usr/bin/env python3
"""Reconstruct one characteristic-zero chart of the degree-seven zero scheme.

The modular scans find isolated parameter points where the strong order-five
section vanishes.  This script works over ``QQ(sigma,tau)``.  It uses a fixed
68-column/68-row pivot chart selected at ``(sigma,tau)=(1,0)``, proves that
every remaining strong column lies in that span, projects the constant defect
to the resulting cokernel, and computes the bivariate ideal generated by the
numerators of all residual coordinates.

The chart is valid away from the recorded pivot denominators.  Modular point
coverage is checked explicitly; points on a missing chart are not silently
discarded.  No order-seven calculation is performed here.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess

from sympy.polys.domains import QQ
from sympy.polys.matrices.sdm import sdm_irref, sdm_rref_den

from explore_degree_five_quantum_residue import add, scale
from verify_degree_seven_relative_quantization_obstruction import (
    family_presentation,
)


PIVOT_COLUMNS = (
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18,
    19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
    35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 65, 69, 70, 72, 73,
    74, 76,
)


def polynomial_text(polynomial) -> str:
    return str(polynomial.as_expr()).replace("**", "^")


def primitive_numerator(element):
    content, primitive = element.numer.primitive()
    del content
    if primitive:
        leading = primitive.LC
        if leading < 0:
            primitive = -primitive
    return primitive


def evaluate_mod(polynomial, sigma: int, tau: int, prime: int) -> int:
    value = 0
    for (sigma_degree, tau_degree), coefficient in polynomial.items():
        numerator = int(coefficient.numerator) % prime
        denominator = int(coefficient.denominator) % prime
        if denominator == 0:
            raise ZeroDivisionError("coefficient denominator is zero modulo prime")
        value += (
            numerator
            * pow(denominator, -1, prime)
            * pow(sigma, sigma_degree, prime)
            * pow(tau, tau_degree, prime)
        )
    return value % prime


def singular_groebner(numerators):
    singular = shutil.which("Singular")
    if singular is None:
        raise SystemExit("Singular is required for the zero-scheme reconstruction")
    ideal = ",".join(polynomial_text(polynomial) for polynomial in numerators)
    program = f"""ring r=0,(sigma,tau),dp;
option(redSB);
ideal I={ideal};
ideal G=std(I);
print("GB_SIZE="+string(size(G)));
print("DIMENSION="+string(dim(G)));
print("VDIM="+string(vdim(G)));
for (int i=1; i<=size(G); i++) {{ print("GB_"+string(i)+"="+string(G[i])); }}
"""
    result = subprocess.run(
        [singular, "-q"],
        input=program,
        text=True,
        capture_output=True,
        check=True,
    )
    if result.stderr.strip() or "   ?" in result.stdout:
        raise AssertionError(result.stdout + result.stderr)
    values = {}
    basis = []
    for line in result.stdout.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key.startswith("GB_") and key != "GB_SIZE":
            basis.append(value)
        else:
            values[key] = value
    return values, basis, hashlib.sha256(program.encode()).hexdigest()


def load_modular_points(paths: list[Path]):
    points = []
    for path in paths:
        scan = json.loads(path.read_text())
        for point in scan["order_five_consistent_points"]:
            points.append((scan["prime"], point["sigma"], point["tau"]))
    return sorted(set(points))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scan", nargs="*", type=Path, default=[])
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--rank-only",
        action="store_true",
        help="stop after the exact function-field strong-rank certificate",
    )
    args = parser.parse_args()

    function_field = QQ.frac_field("sigma", "tau")
    sigma, tau = function_field.gens
    print("BUILD: exact QQ(sigma,tau) presentation", flush=True)
    presentation = family_presentation(function_field, sigma, tau)
    strong_columns = presentation["strong_columns"]
    constant = presentation["constant"]
    assert len(strong_columns) == 107
    assert len(PIVOT_COLUMNS) == 68

    monomials = sorted(
        set(constant).union(*(set(column) for column in strong_columns))
    )
    assert len(monomials) == 178
    pivot_monomials = monomials[:68]
    basis = [strong_columns[index] for index in PIVOT_COLUMNS]
    remaining = [
        column
        for index, column in enumerate(strong_columns)
        if index not in PIVOT_COLUMNS
    ]
    assert len(remaining) == 39

    # One augmented reduction proves that all 39 remaining strong columns
    # lie in the selected 68-column span over the function field.
    strong_rows = {}
    for row_index, monomial in enumerate(monomials):
        row = {}
        for column_index, column in enumerate(basis):
            coefficient = column.get(monomial, function_field.zero)
            if coefficient:
                row[column_index] = coefficient
        for offset, column in enumerate(remaining, start=68):
            coefficient = column.get(monomial, function_field.zero)
            if coefficient:
                row[offset] = coefficient
        if row:
            strong_rows[row_index] = row
    _, strong_pivots, _ = sdm_irref(strong_rows)
    assert strong_pivots == list(range(68))
    print("RANK: all strong columns have exact rank 68", flush=True)
    if args.rank_only:
        certificate = {
            "scope": (
                "exact QQ(sigma,tau) strong order-five rank; constant-section "
                "zero scheme not reconstructed"
            ),
            "strong_columns": len(strong_columns),
            "strong_rank": len(strong_pivots),
            "ambient_dimension": len(monomials),
            "pivot_columns_zero_based": list(PIVOT_COLUMNS),
            "remaining_columns_verified_dependent": len(remaining),
        }
        rendered = json.dumps(certificate, indent=2, sort_keys=True) + "\n"
        if args.output:
            output = args.output.resolve()
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(rendered)
        print("PASS: exact strong-rank certificate complete")
        print("SCOPE: constant-section zero scheme remains open")
        return

    # Solve for the coordinates of the constant on the fixed 68 pivot rows.
    solve_rows = {}
    for row_index, monomial in enumerate(pivot_monomials):
        row = {}
        for column_index, column in enumerate(basis):
            coefficient = column.get(monomial, function_field.zero)
            if coefficient:
                row[column_index] = coefficient
        coefficient = constant.get(monomial, function_field.zero)
        if coefficient:
            row[68] = coefficient
        solve_rows[row_index] = row
    # Repeated normalization in QQ(sigma,tau) causes severe gcd swell on this
    # square solve.  Clear each row denominator and use fraction-free
    # Gauss--Jordan over QQ[sigma,tau] instead.
    polynomial_ring = function_field.field.ring
    polynomial_domain = function_field.get_ring()
    polynomial_rows = {}
    for row_index, row in solve_rows.items():
        common_denominator = polynomial_ring.one
        for coefficient in row.values():
            common_denominator = common_denominator.lcm(coefficient.denom)
        polynomial_rows[row_index] = {
            column_index: coefficient.numer
            * common_denominator.exquo(coefficient.denom)
            for column_index, coefficient in row.items()
        }
    reduced, solve_denominator, solve_pivots = sdm_rref_den(
        polynomial_rows,
        polynomial_domain,
    )
    assert solve_pivots == list(range(68))
    print("SOLVE: fraction-free constant coordinates complete", flush=True)
    coordinates = [
        function_field.convert(
            reduced[index].get(68, polynomial_ring.zero),
            polynomial_domain,
        )
        / function_field.convert(solve_denominator, polynomial_domain)
        for index in range(68)
    ]

    residual = dict(constant)
    for coefficient, column in zip(coordinates, basis):
        residual = add(residual, scale(column, -coefficient))
    assert all(monomial not in residual for monomial in pivot_monomials)
    assert residual

    numerators_by_text = {}
    denominators_by_text = {}
    for coefficient in residual.values():
        numerator = primitive_numerator(coefficient)
        denominator = coefficient.denom
        numerators_by_text[str(numerator)] = numerator
        denominators_by_text[str(denominator)] = denominator
    numerators = list(numerators_by_text.values())
    denominators = list(denominators_by_text.values())
    print(
        f"RESIDUAL: {len(numerators)} numerators, "
        f"{len(denominators)} denominators",
        flush=True,
    )
    values, basis_text, digest = singular_groebner(numerators)
    assert int(values["DIMENSION"]) == 0

    modular_coverage = []
    for prime, sigma_value, tau_value in load_modular_points(args.scan):
        denominator_zero = any(
            evaluate_mod(denominator, sigma_value, tau_value, prime) == 0
            for denominator in denominators
        )
        numerator_zero = all(
            evaluate_mod(numerator, sigma_value, tau_value, prime) == 0
            for numerator in numerators
        )
        modular_coverage.append(
            {
                "prime": prime,
                "sigma": sigma_value,
                "tau": tau_value,
                "pivot_chart": not denominator_zero,
                "all_residual_numerators_zero": numerator_zero,
            }
        )

    certificate = {
        "scope": (
            "strong order-five obstruction zero scheme on one rational pivot "
            "chart; no nonlinear characteristic-zero lift or order-seven claim"
        ),
        "presentation": {
            "strong_columns": len(strong_columns),
            "strong_rank": len(strong_pivots),
            "ambient_dimension": len(monomials),
            "residual_coordinates": len(residual),
            "distinct_numerators": len(numerators),
            "distinct_denominators": len(denominators),
        },
        "zero_scheme": {
            "dimension": int(values["DIMENSION"]),
            "vector_space_dimension": int(values["VDIM"]),
            "groebner_basis": basis_text,
        },
        "modular_coverage": modular_coverage,
        "singular_program_sha256": digest,
    }
    rendered = json.dumps(certificate, indent=2, sort_keys=True) + "\n"
    if args.output:
        output = args.output.resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered)

    print("PASS: all 39 remaining strong columns lie in the 68-column span")
    print(
        "PASS: residual chart ideal has dimension 0 and vector-space dimension {}".format(
            values["VDIM"]
        )
    )
    for index, polynomial in enumerate(basis_text, start=1):
        print(f"GB[{index}] = {polynomial}")
    if modular_coverage:
        covered = sum(
            record["pivot_chart"]
            and record["all_residual_numerators_zero"]
            for record in modular_coverage
        )
        print(
            f"PASS: pivot chart covers {covered}/{len(modular_coverage)} "
            "recorded modular survivors"
        )
    print("SCOPE: reconstruct nonlinear lift over Q before order seven")


if __name__ == "__main__":
    main()
