#!/usr/bin/env python3
"""Render the compact mathematical status summary from THEOREMS.yml.

THEOREMS.yml deliberately uses JSON syntax, which is a strict subset of YAML,
so this repository does not need a YAML package merely to rebuild STATUS.md.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INDEX_PATH = ROOT / "THEOREMS.yml"
STATUS_PATH = ROOT / "STATUS.md"
FIELDS = {
    "id",
    "theorem",
    "status",
    "canonical_source",
    "dependencies",
    "checker",
    "external_review",
    "supersedes",
}


def load_index() -> dict:
    return json.loads(INDEX_PATH.read_text())


def validate_index(index: dict) -> None:
    assert index.get("schema_version") == 1, "unsupported theorem-index schema"
    theorems = index.get("theorems")
    assert isinstance(theorems, list) and theorems, "the theorem index is empty"

    ids = [item.get("id") for item in theorems]
    assert len(ids) == len(set(ids)), "theorem IDs must be unique"
    known = set(ids)

    for item in theorems:
        assert set(item) == FIELDS, f"{item.get('id', '?')}: unexpected schema"
        theorem_id = item["id"]
        assert theorem_id and item["theorem"] and item["status"]
        assert item["external_review"] in {"none", "Lean certificate", "under audit"}
        assert isinstance(item["dependencies"], list)
        assert isinstance(item["supersedes"], list)
        for dependency in item["dependencies"]:
            assert dependency in known or dependency.startswith("external: "), (
                f"{theorem_id}: unresolved dependency {dependency}"
            )
        source = ROOT / item["canonical_source"]
        assert source.is_file(), (
            f"{theorem_id}: missing canonical_source {item['canonical_source']}"
        )
        checker = item["checker"]
        assert checker is None or isinstance(checker, str)
        if checker is not None:
            assert (ROOT / checker).is_file(), f"{theorem_id}: missing checker {checker}"


def _link(label: str, path: str) -> str:
    return f"[{label}]({path})"


def _items(values: list[str]) -> str:
    if not values:
        return "—"
    return ", ".join(f"`{value}`" if not value.startswith("external: ") else value for value in values)


def render(index: dict) -> str:
    lines = [
        "# Mathematical status",
        "",
        "<!-- Generated by scripts/render_status.py from THEOREMS.yml; do not edit. -->",
        "",
        "This is a rendered summary of the active theorem chain. "
        "[`THEOREMS.yml`](THEOREMS.yml) is the single source of truth for theorem "
        "status, dependencies, checkers, and review state; full statements and "
        "qualification live in the canonical sources.",
        "",
        "A repository checker is evidence for reproducibility, not external review. "
        "“Proved” means that the canonical source contains a written argument.",
        "",
        "| ID | Theorem | Status | Canonical source | Dependencies | Checker | External review | Supersedes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for item in index["theorems"]:
        source = _link("source", item["canonical_source"])
        checker = _link("checker", item["checker"]) if item["checker"] else "—"
        lines.append(
            f"| {item['id']} | {item['theorem']} | {item['status']} | {source} | "
            f"{_items(item['dependencies'])} | {checker} | {item['external_review']} | "
            f"{_items(item['supersedes'])} |"
        )

    lines.extend(
        [
            "",
            "The index covers the active dependency chain, not every consequence or "
            "external reproduction in the repository. Those results remain scoped in "
            "their own canonical notes and do not become dependencies unless listed here.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if STATUS.md is not up to date"
    )
    args = parser.parse_args()

    index = load_index()
    validate_index(index)
    rendered = render(index)
    if args.check:
        assert STATUS_PATH.read_text() == rendered, (
            "STATUS.md is stale; run python3 scripts/render_status.py"
        )
    else:
        STATUS_PATH.write_text(rendered)


if __name__ == "__main__":
    main()
