#!/usr/bin/env python3
"""Search translation-linked Taylor rows for non-flat period collisions.

For the translated monomial ``(z+Y)^d``, a finite cyclic character twist of
its Taylor channels has the form

    h_e(t) = sum_j e_j * binomial(d, j) * t**j,

where every ``e_j`` is a root of unity.  The default ``C2`` search uses
``+1`` and ``-1``.  The optional exact ``C3`` and ``C4`` searches compute in
``Z[zeta_3]`` and ``Z[i]`` without floating-point arithmetic.  At radial
slope ``r`` the associated pure row is

    a_{e,r}(n) = [t**(r*n)] h_e(t)**n
               = CT((t**(-r) * h_e(t))**n).

Two twists have flat relative translation curvature when

    e'_j / e_j = eta**j

for one C2 character ``eta``.  Such a pair differs only by the torus
change ``t -> eta*t``.  It is therefore a scale-compatible symmetry,
not an affine Hall/carry obstruction.

The other known symmetry is coordinate reversal
``h(t) -> t**d*h(t**-1)``.  It exchanges slopes ``r`` and ``d-r`` and
preserves the centered row when ``d=2*r``.  The search quotients by the
group generated by scalar sign, torus sign, and reversal.

This script enumerates the exact character twists, groups their moving
constant-term rows through a declared depth, and reports a survivor only
when two rows agree without being related by that torus symmetry.
With ``--rectangles`` it also tests the two-variable Taylor rectangles
of bidegrees ``(2,2)`` and ``(3,2)``, quotienting the two torus signs,
the coordinate reversals, and coordinate exchange when available.

The search is a bounded experiment, not a proof of translation
rigidity.  Its role is to distinguish genuine non-flat isoperiodicity
from collisions already explained by a finite torus action.
"""

from __future__ import annotations

import argparse
import itertools
from math import comb


Signs = tuple[int, ...]
Point = tuple[int, int]
Cyclotomic = tuple[int, int]


def multiply_dense(left: list[int], right: list[int]) -> list[int]:
    answer = [0] * (len(left) + len(right) - 1)
    for left_degree, left_value in enumerate(left):
        if not left_value:
            continue
        for right_degree, right_value in enumerate(right):
            if right_value:
                answer[left_degree + right_degree] += (
                    left_value * right_value
                )
    return answer


def multiply_bivariate(
    left: dict[Point, int],
    right: dict[Point, int],
) -> dict[Point, int]:
    answer: dict[Point, int] = {}
    for (left_x, left_y), left_value in left.items():
        for (right_x, right_y), right_value in right.items():
            exponent = (left_x + right_x, left_y + right_y)
            answer[exponent] = (
                answer.get(exponent, 0) + left_value * right_value
            )
    return {
        exponent: value
        for exponent, value in answer.items()
        if value
    }


def twisted_binomial(signs: Signs) -> list[int]:
    degree = len(signs) - 1
    return [
        sign * comb(degree, exponent)
        for exponent, sign in enumerate(signs)
    ]


def moving_rows(
    signs: Signs,
    depth: int,
) -> dict[int, tuple[int, ...]]:
    degree = len(signs) - 1
    polynomial = twisted_binomial(signs)
    rows = {
        slope: []
        for slope in range(1, degree)
    }
    current = [1]
    for moment in range(1, depth + 1):
        current = multiply_dense(current, polynomial)
        for slope, values in rows.items():
            values.append(current[slope * moment])
    return {
        slope: tuple(values)
        for slope, values in rows.items()
    }


def alternating_twist(signs: Signs) -> Signs:
    return tuple(
        sign if exponent % 2 == 0 else -sign
        for exponent, sign in enumerate(signs)
    )


def symmetry_class(signs: Signs) -> Signs:
    """Canonicalize scalar sign, torus sign, and reversal."""

    reversed_signs = tuple(reversed(signs))
    raw_orbit = (
        signs,
        alternating_twist(signs),
        reversed_signs,
        alternating_twist(reversed_signs),
    )
    orbit = tuple(
        tuple(entry * candidate[0] for entry in candidate)
        for candidate in raw_orbit
    )
    return min(orbit)


def verify_known_flat_collision(depth: int) -> None:
    first = (1, -1, -1, 1)
    second = (1, 1, -1, -1)
    assert second == alternating_twist(first)
    assert symmetry_class(first) == symmetry_class(second)
    # h_second(t) = h_first(-t), and slope two is even.
    assert moving_rows(first, depth)[2] == moving_rows(second, depth)[2]

    third = (1, -1, -1, -1, 1, -1, 1)
    fourth = (1, -1, 1, -1, -1, -1, 1)
    assert fourth == tuple(reversed(third))
    assert symmetry_class(third) == symmetry_class(fourth)
    # Reversal preserves the centered slope three in degree six.
    assert moving_rows(third, depth)[3] == moving_rows(fourth, depth)[3]


def search_univariate(max_degree: int, extra_depth: int) -> bool:
    verify_known_flat_collision(2 * max_degree + extra_depth)

    patterns_tested = 0
    rows_tested = 0
    flat_collisions = 0
    for degree in range(2, max_degree + 1):
        depth = 2 * degree + extra_depth
        seen: dict[
            tuple[int, tuple[int, ...]],
            tuple[Signs, Signs],
        ] = {}
        degree_patterns = 0

        # Fix e_0=1 to remove an irrelevant common sign.
        for tail in itertools.product((-1, 1), repeat=degree):
            signs = (1, *tail)
            degree_patterns += 1
            patterns_tested += 1
            canonical = symmetry_class(signs)
            for slope, row in moving_rows(signs, depth).items():
                rows_tested += 1
                key = (slope, row)
                previous = seen.get(key)
                if previous is None:
                    seen[key] = (signs, canonical)
                    continue

                previous_signs, previous_class = previous
                if previous_class == canonical:
                    if previous_signs != signs:
                        flat_collisions += 1
                    continue

                print(
                    "SURVIVOR unexplained translation-period collision "
                    f"through depth {depth}"
                )
                print(f"degree={degree}")
                print(f"slope={slope}")
                print(f"first={previous_signs}")
                print(f"second={signs}")
                print(f"row={row}")
                return True

        print(
            f"PASS degree={degree} patterns={degree_patterns} "
            f"depth={depth}"
        )

    print(
        "NO unexplained translation-period collision through the "
        "declared bounds after torus/reversal reduction"
    )
    print(f"patterns={patterns_tested}")
    print(f"moving_rows={rows_tested}")
    print(f"symmetry_explained_collisions={flat_collisions}")
    print(
        "STATUS: bounded evidence for relative translation-curvature "
        "rigidity; not a proof"
    )
    return False


def cyclotomic_root(order: int, exponent: int) -> Cyclotomic:
    if order == 3:
        # Basis (1,zeta), with zeta^2=-1-zeta.
        return ((1, 0), (0, 1), (-1, -1))[exponent % order]
    if order == 4:
        # Gaussian basis (1,i).
        return ((1, 0), (0, 1), (-1, 0), (0, -1))[exponent % order]
    raise ValueError(f"unsupported exact character order: {order}")


def add_cyclotomic(
    left: Cyclotomic,
    right: Cyclotomic,
) -> Cyclotomic:
    return (left[0] + right[0], left[1] + right[1])


def multiply_cyclotomic(
    left: Cyclotomic,
    right: Cyclotomic,
    order: int,
) -> Cyclotomic:
    a, b = left
    c, d = right
    if order == 3:
        return (a * c - b * d, a * d + b * c - b * d)
    if order == 4:
        return (a * c - b * d, a * d + b * c)
    raise ValueError(f"unsupported exact character order: {order}")


def multiply_dense_cyclotomic(
    left: list[Cyclotomic],
    right: list[Cyclotomic],
    order: int,
) -> list[Cyclotomic]:
    answer = [(0, 0)] * (len(left) + len(right) - 1)
    for left_degree, left_value in enumerate(left):
        if left_value == (0, 0):
            continue
        for right_degree, right_value in enumerate(right):
            if right_value == (0, 0):
                continue
            product = multiply_cyclotomic(
                left_value,
                right_value,
                order,
            )
            answer[left_degree + right_degree] = add_cyclotomic(
                answer[left_degree + right_degree],
                product,
            )
    return answer


def moving_character_rows(
    phases: Signs,
    order: int,
    depth: int,
) -> dict[int, tuple[Cyclotomic, ...]]:
    degree = len(phases) - 1
    polynomial = [
        tuple(
            comb(degree, exponent) * coordinate
            for coordinate in cyclotomic_root(order, phase)
        )
        for exponent, phase in enumerate(phases)
    ]
    rows: dict[int, list[Cyclotomic]] = {
        slope: []
        for slope in range(1, degree)
    }
    current = [(1, 0)]
    for moment in range(1, depth + 1):
        current = multiply_dense_cyclotomic(
            current,
            polynomial,
            order,
        )
        for slope, values in rows.items():
            values.append(current[slope * moment])
    return {
        slope: tuple(values)
        for slope, values in rows.items()
    }


def phase_symmetry_class(phases: Signs, order: int) -> Signs:
    """Canonicalize scalar phase, torus phase, and reversal."""

    degree = len(phases) - 1
    orbit = []
    for reverse in (False, True):
        candidate = tuple(reversed(phases)) if reverse else phases
        for torus_phase in range(order):
            twisted = tuple(
                (candidate[exponent] + torus_phase * exponent) % order
                for exponent in range(degree + 1)
            )
            scalar_phase = twisted[0]
            orbit.append(
                tuple(
                    (phase - scalar_phase) % order
                    for phase in twisted
                )
            )
    return min(orbit)


def search_character_order(
    order: int,
    max_degree: int,
    extra_depth: int,
) -> bool:
    if order not in (3, 4):
        raise ValueError("the exact non-sign search supports C3 and C4")

    patterns_tested = 0
    rows_tested = 0
    symmetry_collisions = 0
    for degree in range(2, max_degree + 1):
        depth = 2 * degree + extra_depth
        seen: dict[
            tuple[int, tuple[Cyclotomic, ...]],
            tuple[Signs, Signs],
        ] = {}
        degree_patterns = 0

        # Fix the constant-channel phase to zero to remove a common scalar.
        for tail in itertools.product(range(order), repeat=degree):
            phases = (0, *tail)
            degree_patterns += 1
            patterns_tested += 1
            canonical = phase_symmetry_class(phases, order)
            for slope, row in moving_character_rows(
                phases,
                order,
                depth,
            ).items():
                rows_tested += 1
                key = (slope, row)
                previous = seen.get(key)
                if previous is None:
                    seen[key] = (phases, canonical)
                    continue

                previous_phases, previous_class = previous
                if previous_class == canonical:
                    if previous_phases != phases:
                        symmetry_collisions += 1
                    continue

                print(
                    "SURVIVOR unexplained translation-period collision "
                    f"for C{order} through depth {depth}"
                )
                print(f"degree={degree}")
                print(f"slope={slope}")
                print(f"first={previous_phases}")
                print(f"second={phases}")
                print(f"row={row}")
                return True

        print(
            f"PASS C{order} degree={degree} patterns={degree_patterns} "
            f"depth={depth}"
        )

    print(
        f"NO unexplained C{order} translation-period collision through "
        "the declared bounds after torus/reversal reduction"
    )
    print(f"patterns={patterns_tested}")
    print(f"moving_rows={rows_tested}")
    print(f"symmetry_explained_collisions={symmetry_collisions}")
    print(
        f"STATUS: bounded exact C{order} evidence for relative "
        "translation-curvature rigidity; not a proof"
    )
    return False


def rectangle_index(
    x_degree: int,
    y_degree: int,
    y_bound: int,
) -> int:
    return x_degree * (y_bound + 1) + y_degree


def twisted_rectangle(
    signs: Signs,
    x_bound: int,
    y_bound: int,
) -> dict[Point, int]:
    return {
        (x_degree, y_degree): (
            signs[rectangle_index(x_degree, y_degree, y_bound)]
            * comb(x_bound, x_degree)
            * comb(y_bound, y_degree)
        )
        for x_degree in range(x_bound + 1)
        for y_degree in range(y_bound + 1)
    }


def rectangle_rows(
    signs: Signs,
    x_bound: int,
    y_bound: int,
    depth: int,
) -> dict[Point, tuple[int, ...]]:
    polynomial = twisted_rectangle(signs, x_bound, y_bound)
    rows = {
        (x_slope, y_slope): []
        for x_slope in range(1, x_bound)
        for y_slope in range(1, y_bound)
    }
    current = {(0, 0): 1}
    for moment in range(1, depth + 1):
        current = multiply_bivariate(current, polynomial)
        for (x_slope, y_slope), values in rows.items():
            values.append(
                current.get(
                    (x_slope * moment, y_slope * moment),
                    0,
                )
            )
    return {
        slope: tuple(values)
        for slope, values in rows.items()
    }


def transform_rectangle(
    signs: Signs,
    x_bound: int,
    y_bound: int,
    reverse_x: bool,
    reverse_y: bool,
    swap: bool,
) -> Signs:
    transformed = []
    for x_degree in range(x_bound + 1):
        for y_degree in range(y_bound + 1):
            source_x = x_bound - x_degree if reverse_x else x_degree
            source_y = y_bound - y_degree if reverse_y else y_degree
            if swap:
                source_x, source_y = source_y, source_x
            transformed.append(
                signs[rectangle_index(source_x, source_y, y_bound)]
            )
    return tuple(transformed)


def rectangle_symmetry_class(
    signs: Signs,
    x_bound: int,
    y_bound: int,
) -> Signs:
    orbit = []
    swap_options = (False, True) if x_bound == y_bound else (False,)
    for reverse_x, reverse_y, swap, torus_x, torus_y in itertools.product(
        (False, True),
        (False, True),
        swap_options,
        (-1, 1),
        (-1, 1),
    ):
        candidate = transform_rectangle(
            signs,
            x_bound,
            y_bound,
            reverse_x,
            reverse_y,
            swap,
        )
        twisted = tuple(
            sign * torus_x**x_degree * torus_y**y_degree
            for x_degree in range(x_bound + 1)
            for y_degree, sign in enumerate(
                candidate[
                    x_degree * (y_bound + 1):
                    (x_degree + 1) * (y_bound + 1)
                ]
            )
        )
        orbit.append(
            tuple(entry * twisted[0] for entry in twisted)
        )
    return min(orbit)


def search_rectangles(extra_depth: int) -> bool:
    patterns_tested = 0
    rows_tested = 0
    symmetry_collisions = 0
    for x_bound, y_bound in ((2, 2), (3, 2)):
        depth = 2 * (x_bound + y_bound) + extra_depth
        coefficient_count = (x_bound + 1) * (y_bound + 1)
        seen: dict[
            tuple[Point, tuple[int, ...]],
            tuple[Signs, Signs],
        ] = {}
        rectangle_patterns = 0
        for tail in itertools.product(
            (-1, 1),
            repeat=coefficient_count - 1,
        ):
            signs = (1, *tail)
            rectangle_patterns += 1
            patterns_tested += 1
            canonical = rectangle_symmetry_class(
                signs,
                x_bound,
                y_bound,
            )
            for slope, row in rectangle_rows(
                signs,
                x_bound,
                y_bound,
                depth,
            ).items():
                rows_tested += 1
                key = (slope, row)
                previous = seen.get(key)
                if previous is None:
                    seen[key] = (signs, canonical)
                    continue
                previous_signs, previous_class = previous
                if previous_class == canonical:
                    if previous_signs != signs:
                        symmetry_collisions += 1
                    continue
                print(
                    "SURVIVOR unexplained rectangular translation-period "
                    f"collision through depth {depth}"
                )
                print(f"rectangle=({x_bound},{y_bound})")
                print(f"slope={slope}")
                print(f"first={previous_signs}")
                print(f"second={signs}")
                print(f"row={row}")
                return True
        print(
            f"PASS rectangle=({x_bound},{y_bound}) "
            f"patterns={rectangle_patterns} depth={depth}"
        )

    print(
        "NO unexplained rectangular translation-period collision "
        "through the declared bounds"
    )
    print(f"rectangle_patterns={patterns_tested}")
    print(f"rectangle_moving_rows={rows_tested}")
    print(
        "rectangle_symmetry_explained_collisions="
        f"{symmetry_collisions}"
    )
    print(
        "STATUS: bounded two-direction evidence; not a proof"
    )
    return False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-degree", type=int, default=10)
    parser.add_argument("--extra-depth", type=int, default=4)
    parser.add_argument(
        "--character-order",
        type=int,
        choices=(2, 3, 4),
        default=2,
        help=(
            "cyclic Taylor-character order; C2 is the original sign "
            "search, while C3 and C4 use exact quadratic cyclotomic rings"
        ),
    )
    parser.add_argument(
        "--rectangles",
        action="store_true",
        help="also search the (2,2) and (3,2) Taylor rectangles",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.max_degree < 3:
        raise SystemExit("max-degree must be at least three")
    if args.extra_depth < 0:
        raise SystemExit("extra-depth must be nonnegative")
    if args.character_order == 2:
        search_univariate(args.max_degree, args.extra_depth)
    else:
        search_character_order(
            args.character_order,
            args.max_degree,
            args.extra_depth,
        )
    if args.rectangles:
        if args.character_order != 2:
            raise SystemExit("rectangles currently support character order two")
        search_rectangles(args.extra_depth)


if __name__ == "__main__":
    main()
