#!/usr/bin/env python3
"""Finite-field scout for cubic K12 graph coordinates and bilinear repairs.

The exact K12 coordinate-pair frontier leaves open the nine normalized
linear target-coordinate families whose pullbacks have genuinely cubic graph
corrections.  This script enumerates sparse integer parameter points in those
families.  At each point it restricts K12 to the collision graph and asks,
for every retained component of source degree greater than three, whether
its high-degree defect belongs to the span generated by all linear and
quadratic target monomials in the other ten retained raw outputs.

All arithmetic after construction of K12 and the graph families is over the
listed finite fields.  A survivor is only a discovery candidate; absence of
survivors is only a bounded modular experiment.  The same signed integer
parameter points are evaluated independently at every requested prime so
that characteristic-specific false positives are visible.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import sympy as sp

from audit_k12_coordinate_pair_frontier import build_k12


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    ROOT
    / "artifacts"
    / "generated-results"
    / "k12_cubic_graph_bilinear_modular_search.json"
)
DESIRED_DEGREE = 3

Exponent = tuple[int, ...]
SparsePolynomial = dict[Exponent, int]


def residue(value: sp.Expr, prime: int) -> int:
    rational = sp.Rational(value)
    denominator = int(rational.q) % prime
    if not denominator:
        raise ZeroDivisionError(
            f"coefficient denominator is zero modulo {prime}"
        )
    return (
        int(rational.p) % prime
    ) * pow(denominator, prime - 2, prime) % prime


def sparse_add_scaled(
    target: SparsePolynomial,
    source: SparsePolynomial,
    scale: int,
    prime: int,
) -> None:
    if not scale:
        return
    for exponents, coefficient in source.items():
        value = (target.get(exponents, 0) + scale * coefficient) % prime
        if value:
            target[exponents] = value
        else:
            target.pop(exponents, None)


def sparse_multiply(
    left: SparsePolynomial,
    right: SparsePolynomial,
    prime: int,
) -> SparsePolynomial:
    result: SparsePolynomial = {}
    for left_exponents, left_coefficient in left.items():
        for right_exponents, right_coefficient in right.items():
            exponents = tuple(
                a + b for a, b in zip(left_exponents, right_exponents)
            )
            value = (
                result.get(exponents, 0)
                + left_coefficient * right_coefficient
            ) % prime
            if value:
                result[exponents] = value
            else:
                result.pop(exponents, None)
    return result


def sparse_power(
    polynomial: SparsePolynomial,
    exponent: int,
    variable_count: int,
    prime: int,
) -> SparsePolynomial:
    result = {(0,) * variable_count: 1}
    factor = polynomial
    power = exponent
    while power:
        if power & 1:
            result = sparse_multiply(result, factor, prime)
        power //= 2
        if power:
            factor = sparse_multiply(factor, factor, prime)
    return result


def high_degree_part(polynomial: SparsePolynomial) -> SparsePolynomial:
    return {
        exponents: coefficient
        for exponents, coefficient in polynomial.items()
        if sum(exponents) > DESIRED_DEGREE
    }


def polynomial_degree(polynomial: SparsePolynomial) -> int:
    return max((sum(exponents) for exponents in polynomial), default=-1)


class SparseColumnSpace:
    """Normalized sparse column echelon form over a prime field."""

    def __init__(self, prime: int) -> None:
        self.prime = prime
        self.pivots: dict[Exponent, SparsePolynomial] = {}

    @property
    def rank(self) -> int:
        return len(self.pivots)

    def reduce(self, source: SparsePolynomial) -> SparsePolynomial:
        column = dict(source)
        while column:
            pivot = min(column)
            existing = self.pivots.get(pivot)
            if existing is None:
                break
            coefficient = column[pivot]
            sparse_add_scaled(
                column, existing, -coefficient, self.prime
            )
        return column

    def add(self, source: SparsePolynomial) -> bool:
        column = self.reduce(source)
        if not column:
            return False
        pivot = min(column)
        inverse = pow(column[pivot], self.prime - 2, self.prime)
        self.pivots[pivot] = {
            exponents: coefficient * inverse % self.prime
            for exponents, coefficient in column.items()
        }
        return True


@dataclass(frozen=True)
class GraphFamily:
    pivot: int
    coefficients: tuple[sp.Expr, ...]
    parameters: tuple[sp.Symbol, ...]


def linear_graph_families(
    k12: list[sp.Expr],
    variables: tuple[sp.Symbol, ...],
) -> list[GraphFamily]:
    """Reconstruct the nine normalized graph-coordinate families exactly."""

    nonlinear = [
        sp.expand(component - variable)
        for component, variable in zip(k12, variables)
    ]
    polynomials = [
        sp.Poly(component, *variables, domain=sp.QQ)
        for component in nonlinear
    ]
    monomials = sorted(
        set().union(
            *[
                {
                    exponents
                    for exponents, coefficient in polynomial.terms()
                    if coefficient
                }
                for polynomial in polynomials
            ]
        )
    )
    families: list[GraphFamily] = []
    for pivot in range(12):
        constraints = [
            [
                polynomial.coeff_monomial(exponents)
                for polynomial in polynomials
            ]
            for exponents in monomials
            if exponents[pivot]
        ]
        matrix = sp.Matrix(constraints)
        pivot_row = [sp.Integer(0)] * 12
        pivot_row[pivot] = sp.Integer(1)
        system = sp.Matrix.vstack(matrix, sp.Matrix([pivot_row]))
        right_hand_side = sp.Matrix(
            [sp.Integer(0)] * matrix.rows + [sp.Integer(1)]
        )
        solution_set = sp.linsolve((system, right_hand_side))
        if solution_set is sp.EmptySet:
            continue
        coefficients = tuple(next(iter(solution_set)))
        parameters = tuple(
            sorted(
                set().union(
                    *[
                        coefficient.free_symbols
                        for coefficient in coefficients
                    ]
                ),
                key=str,
            )
        )
        if not parameters and coefficients[pivot] != 1:
            continue
        families.append(GraphFamily(pivot, coefficients, parameters))
    assert [family.pivot for family in families] == list(range(3, 12))
    return families


def as_sparse_rational(
    expression: sp.Expr,
    variables: tuple[sp.Symbol, ...],
) -> dict[Exponent, sp.Rational]:
    return {
        exponents: sp.Rational(coefficient)
        for exponents, coefficient in sp.Poly(
            expression, *variables, domain=sp.QQ
        ).terms()
        if coefficient
    }


def reduce_exponents(exponents: Exponent, pivot: int) -> Exponent:
    return exponents[:pivot] + exponents[pivot + 1 :]


def build_graph_mod_prime(
    family: GraphFamily,
    parameter_point: tuple[int, ...],
    nonlinear_sparse: list[dict[Exponent, sp.Rational]],
    collision_image: tuple[sp.Rational, ...],
    prime: int,
) -> tuple[SparsePolynomial, tuple[int, ...]]:
    substitution = dict(zip(family.parameters, parameter_point))
    coefficients = tuple(
        residue(coefficient.subs(substitution), prime)
        for coefficient in family.coefficients
    )
    retained_count = 11
    graph: SparsePolynomial = {}
    slice_value = sum(
        coefficient * residue(value, prime)
        for coefficient, value in zip(coefficients, collision_image)
    ) % prime
    if slice_value:
        graph[(0,) * retained_count] = slice_value
    for index, coefficient in enumerate(coefficients):
        if not coefficient:
            continue
        if index != family.pivot:
            linear_exponents = [0] * retained_count
            retained_index = index if index < family.pivot else index - 1
            linear_exponents[retained_index] = 1
            sparse_add_scaled(
                graph,
                {tuple(linear_exponents): 1},
                -coefficient,
                prime,
            )
        correction = {
            reduce_exponents(exponents, family.pivot): residue(value, prime)
            for exponents, value in nonlinear_sparse[index].items()
            if value
        }
        assert all(
            exponents[family.pivot] == 0
            for exponents in nonlinear_sparse[index]
        )
        sparse_add_scaled(graph, correction, -coefficient, prime)
    return graph, coefficients


def restrict_polynomial(
    polynomial: dict[Exponent, sp.Rational],
    graph: SparsePolynomial,
    pivot: int,
    prime: int,
) -> SparsePolynomial:
    retained_count = 11
    graph_powers: dict[int, SparsePolynomial] = {0: {(0,) * retained_count: 1}}
    result: SparsePolynomial = {}
    for exponents, rational_coefficient in polynomial.items():
        pivot_exponent = exponents[pivot]
        if pivot_exponent not in graph_powers:
            graph_powers[pivot_exponent] = sparse_power(
                graph, pivot_exponent, retained_count, prime
            )
        base_exponents = reduce_exponents(exponents, pivot)
        base = {base_exponents: residue(rational_coefficient, prime)}
        term = sparse_multiply(base, graph_powers[pivot_exponent], prime)
        sparse_add_scaled(result, term, 1, prime)
    return result


def screen_component(
    restricted: list[SparsePolynomial],
    component: int,
    prime: int,
) -> dict[str, object]:
    available = [
        polynomial
        for index, polynomial in enumerate(restricted)
        if index != component
    ]
    columns: list[SparsePolynomial] = []
    columns.extend(high_degree_part(polynomial) for polynomial in available)
    for left in range(len(available)):
        for right in range(left, len(available)):
            columns.append(
                high_degree_part(
                    sparse_multiply(
                        available[left], available[right], prime
                    )
                )
            )
    space = SparseColumnSpace(prime)
    nonzero_columns = 0
    for column in columns:
        if column:
            nonzero_columns += 1
            space.add(column)
    target = high_degree_part(restricted[component])
    residual = space.reduce(target)
    return {
        "retained_component": component,
        "target_term_count": len(target),
        "basis_count": len(columns),
        "nonzero_column_count": nonzero_columns,
        "completion_rank": space.rank,
        "solvable": not residual,
        "residual_term_count": len(residual),
        "residual_leading_monomial": (
            list(min(residual)) if residual else None
        ),
    }


def parameter_points(
    parameter_count: int,
    support_maximum: int,
    values: tuple[int, ...],
    random_samples: int,
    random_seed: int,
) -> list[tuple[int, ...]]:
    points: set[tuple[int, ...]] = {(0,) * parameter_count}
    for support_size in range(1, support_maximum + 1):
        for support in itertools.combinations(range(parameter_count), support_size):
            for assigned in itertools.product(values, repeat=support_size):
                point = [0] * parameter_count
                for index, value in zip(support, assigned):
                    point[index] = value
                points.add(tuple(point))
    generator = random.Random(random_seed + 1009 * parameter_count)
    for _ in range(random_samples):
        points.add(
            tuple(generator.choice((0,) + values) for _ in range(parameter_count))
        )
    return sorted(points)


def signed_mod(value: int, prime: int) -> int:
    return value % prime


def audit_point(
    family: GraphFamily,
    integer_point: tuple[int, ...],
    prime: int,
    k12_sparse: list[dict[Exponent, sp.Rational]],
    nonlinear_sparse: list[dict[Exponent, sp.Rational]],
    collision_image: tuple[sp.Rational, ...],
) -> dict[str, object]:
    modular_point = tuple(signed_mod(value, prime) for value in integer_point)
    graph, coefficients = build_graph_mod_prime(
        family,
        modular_point,
        nonlinear_sparse,
        collision_image,
        prime,
    )
    restricted = [
        restrict_polynomial(polynomial, graph, family.pivot, prime)
        for index, polynomial in enumerate(k12_sparse)
        if index != family.pivot
    ]
    degrees = [polynomial_degree(polynomial) for polynomial in restricted]
    bad = [index for index, degree in enumerate(degrees) if degree > 3]
    screens = []
    for component in sorted(
        bad,
        key=lambda index: len(high_degree_part(restricted[index])),
    ):
        screen = screen_component(restricted, component, prime)
        screens.append(screen)
        if not screen["solvable"]:
            break
    all_solvable = len(screens) == len(bad) and all(
        bool(screen["solvable"]) for screen in screens
    )
    return {
        "parameter_point": list(integer_point),
        "linear_target_coefficients_mod_prime": list(coefficients),
        "graph_degree": polynomial_degree(graph),
        "graph_term_count": len(graph),
        "restricted_maximum_degree": max(degrees),
        "bad_retained_components": bad,
        "screened_components": screens,
        "all_bad_components_bilinearly_solvable": all_solvable,
        "score": [
            0 if all_solvable else 1,
            screens[-1]["residual_term_count"] if screens else 0,
            len(bad),
            len(graph),
        ],
    }


def parse_integer_list(raw: str) -> tuple[int, ...]:
    values = tuple(dict.fromkeys(int(value.strip()) for value in raw.split(",")))
    if not values or 0 in values:
        raise argparse.ArgumentTypeError("values must be a nonempty list excluding zero")
    return values


def parse_primes(raw: str) -> tuple[int, ...]:
    primes = tuple(dict.fromkeys(int(value.strip()) for value in raw.split(",")))
    if not primes or any(not sp.isprime(prime) for prime in primes):
        raise argparse.ArgumentTypeError("--primes requires a nonempty list of primes")
    return primes


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--primes", type=parse_primes, default=(101, 103))
    parser.add_argument("--support-max", type=int, default=1)
    parser.add_argument("--values", type=parse_integer_list, default=(-1, 1))
    parser.add_argument("--random-samples", type=int, default=0)
    parser.add_argument("--random-seed", type=int, default=20260804)
    parser.add_argument("--keep-closest", type=int, default=5)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    if args.support_max < 0 or args.random_samples < 0 or args.keep_closest < 1:
        parser.error("support/random bounds must be nonnegative and --keep-closest positive")

    z, k12 = build_k12()
    nonlinear = [
        sp.expand(component - variable)
        for component, variable in zip(k12, z)
    ]
    k12_sparse = [as_sparse_rational(component, z) for component in k12]
    nonlinear_sparse = [
        as_sparse_rational(component, z) for component in nonlinear
    ]
    collision_image = (
        sp.Integer(0),
        sp.Integer(0),
        -sp.Rational(1, 4),
        *([sp.Integer(0)] * 9),
    )
    families = linear_graph_families(k12, z)

    records = []
    cross_prime_survivors = []
    total_evaluations = 0
    for family in families:
        points = parameter_points(
            len(family.parameters),
            args.support_max,
            args.values,
            args.random_samples,
            args.random_seed + family.pivot,
        )
        prime_records = []
        survivor_sets = []
        for prime in args.primes:
            audits = []
            survivor_points = set()
            cubic_graph_count = 0
            for point in points:
                audit = audit_point(
                    family,
                    point,
                    prime,
                    k12_sparse,
                    nonlinear_sparse,
                    collision_image,
                )
                total_evaluations += 1
                if audit["graph_degree"] == 3:
                    cubic_graph_count += 1
                if audit["all_bad_components_bilinearly_solvable"]:
                    survivor_points.add(point)
                    audits.append(audit)
                elif audit["graph_degree"] == 3:
                    audits.append(audit)
            audits.sort(key=lambda audit: (audit["score"], audit["parameter_point"]))
            survivor_sets.append(survivor_points)
            prime_records.append(
                {
                    "prime": prime,
                    "point_count": len(points),
                    "genuinely_cubic_graph_count": cubic_graph_count,
                    "survivor_count": len(survivor_points),
                    "survivors": [
                        audit
                        for audit in audits
                        if audit["all_bad_components_bilinearly_solvable"]
                    ],
                    "closest_cubic_graph_points": [
                        audit
                        for audit in audits
                        if audit["graph_degree"] == 3
                        and not audit["all_bad_components_bilinearly_solvable"]
                    ][: args.keep_closest],
                }
            )
        common_survivors = set.intersection(*survivor_sets)
        cross_prime_survivors.extend(
            {
                "source_pivot": family.pivot + 1,
                "parameter_point": list(point),
            }
            for point in sorted(common_survivors)
        )
        records.append(
            {
                "source_pivot": family.pivot + 1,
                "parameter_count": len(family.parameters),
                "normalized_linear_target_coefficients": [
                    str(coefficient) for coefficient in family.coefficients
                ],
                "point_count_per_prime": len(points),
                "prime_records": prime_records,
                "cross_prime_survivor_count": len(common_survivors),
            }
        )
        print(
            f"pivot z{family.pivot + 1}: {len(points)} points x "
            f"{len(args.primes)} primes; cross-prime survivors="
            f"{len(common_survivors)}"
        )

    artifact = {
        "format": "k12-cubic-graph-bilinear-modular-search-v1",
        "status": "bounded finite-field discovery experiment; not a proof",
        "primes": list(args.primes),
        "support_maximum": args.support_max,
        "nonzero_integer_values": list(args.values),
        "random_samples_per_parameter_count": args.random_samples,
        "random_seed": args.random_seed,
        "desired_source_degree": DESIRED_DEGREE,
        "target_completion_degree": 2,
        "target_completion_basis": (
            "all 10 linear and 55 quadratic monomials in the other retained raw outputs"
        ),
        "total_modular_point_evaluations": total_evaluations,
        "families": records,
        "cross_prime_survivors": cross_prime_survivors,
        "scope": (
            "The search enumerates only the stated sparse integer parameter points in "
            "the nine exact normalized linear graph-coordinate families. A modular "
            "survivor would require reconstruction over Q and a full target-automorphism, "
            "determinant, degree, and collision audit. No-survivor output is not a "
            "dimension-eleven obstruction."
        ),
    }
    output = args.output
    if not output.is_absolute():
        output = ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(artifact, indent=2) + "\n")
    digest = hashlib.sha256(output.read_bytes()).hexdigest()
    try:
        displayed_output = output.relative_to(ROOT)
    except ValueError:
        displayed_output = output
    print(f"PASS wrote {displayed_output}")
    print(f"SHA256 {digest}")
    if cross_prime_survivors:
        print(
            "DISCOVERY: cross-prime modular survivors require exact rational reconstruction"
        )
    else:
        print("NO CROSS-PRIME SURVIVOR IN THE DECLARED BOUNDED SEARCH")


if __name__ == "__main__":
    main()
