#!/usr/bin/env python3
"""Exact certificate for the cotangent-graph Weyl pair and its first commutant.

For the normalized foundational map F0=(S,T,R), let delta_S, delta_T,
delta_R be the inverse-Jacobian derivations.  The cotangent-graph normal pair

    a = delta_S,        b = S-delta_T

satisfies [a,b]=1.  The transported target centralizer is generated by

    R, delta_R, delta_T, T-delta_S.

The accompanying proof note shows that these generators exhaust every
differential operator of order at most one commuting with a and b.  This
script checks all polynomial identities used in that proof, including the
adapted rational presentation that makes the common constant field k(R).
"""

from __future__ import annotations

import sympy as sp


x, y, z = sp.symbols("x y z")
variables = (x, y, z)
u = 1 + x * y

# The first coordinate is divided by two so det D(S,T,R)=-1.
S = (u**3 * z + y**2 * u * (4 + 3 * x * y)) / 2
T = y + 3 * x * u**2 * z + 3 * x * y**2 * (4 + 3 * x * y)
R = 2 * x - 3 * x**2 * y - x**3 * z
F0 = sp.Matrix([S, T, R])
J0 = F0.jacobian(variables)
B0 = -J0.adjugate()

assert sp.factor(J0.det()) == -1
assert (J0 * B0).applyfunc(sp.expand) == sp.eye(3)


def apply(vector_field: sp.Matrix, polynomial: sp.Expr) -> sp.Expr:
    return sp.expand(
        sum(
            vector_field[index] * sp.diff(polynomial, variable)
            for index, variable in enumerate(variables)
        )
    )


def lie(left: sp.Matrix, right: sp.Matrix) -> sp.Matrix:
    return sp.Matrix(
        [
            sp.expand(apply(left, right[index]) - apply(right, left[index]))
            for index in range(3)
        ]
    )


# A first-order differential operator is represented in left normal order as
# (vector field, multiplication term).  Its commutator has the usual Lie
# bracket and the induced scalar term.
Operator = tuple[sp.Matrix, sp.Expr]


def commutator(left: Operator, right: Operator) -> Operator:
    left_vector, left_scalar = left
    right_vector, right_scalar = right
    return (
        lie(left_vector, right_vector),
        sp.expand(
            apply(left_vector, right_scalar)
            - apply(right_vector, left_scalar)
        ),
    )


zero_vector = sp.zeros(3, 1)
one = (zero_vector, sp.Integer(1))
zero = (zero_vector, sp.Integer(0))

delta_s, delta_t, delta_r = (B0[:, index] for index in range(3))
for i, delta in enumerate((delta_s, delta_t, delta_r)):
    for j, coordinate in enumerate((S, T, R)):
        assert apply(delta, coordinate) == (1 if i == j else 0)
for left in (delta_s, delta_t, delta_r):
    for right in (delta_s, delta_t, delta_r):
        assert lie(left, right) == zero_vector

normal_a = (delta_s, sp.Integer(0))
normal_b = (-delta_t, S)
central_r = (zero_vector, R)
central_dr = (delta_r, sp.Integer(0))
central_dt = (delta_t, sp.Integer(0))
central_t = (-delta_s, T)

assert commutator(normal_a, normal_b) == one
for generator in (central_r, central_dr, central_dt, central_t):
    assert commutator(normal_a, generator) == zero
    assert commutator(normal_b, generator) == zero
assert commutator(central_dr, central_r) == one
assert commutator(central_dt, central_t) == one
for left in (central_r, central_dr):
    for right in (central_dt, central_t):
        assert commutator(left, right) == zero

# Adapted polynomial base coordinates.  Starting with (x,y,z), set
# q=y+x*z/3 and w=z+9*q^2.  The inverse is polynomial and R=2*x-3*x^2*q.
# Consequently k(x,y,z)=k(R,x,w) is purely transcendental over k(R).
q = sp.expand(y + x * z / 3)
w = sp.expand(z + 9 * q**2)
Y, Z = sp.symbols("Y Z")
q_inverse = sp.expand(Y + x * Z / 3)
z_inverse = sp.expand(Z - 9 * q_inverse**2)
y_inverse = sp.expand(q_inverse - x * z_inverse / 3)
assert sp.expand(q.subs({y: y_inverse, z: z_inverse}, simultaneous=True) - q_inverse) == 0
assert sp.expand(w.subs({y: y_inverse, z: z_inverse}, simultaneous=True) - Z) == 0
assert sp.expand(R - (2 * x - 3 * x**2 * q)) == 0

# A polynomial section of R proves k(R) intersect k[x,y,z]=k[R]: choose
# x=1, q=(2-r)/3 and w=0, then return through the polynomial inverse.
r = sp.symbols("r")
q_section = (2 - r) / 3
z_section = -9 * q_section**2
y_section = sp.expand(q_section - z_section / 3)
assert sp.expand(R.subs({x: 1, y: y_section, z: z_section}) - r) == 0

# Check the general normal form from the order-one centralizer theorem for
# representative symbolic polynomials in R.  The written proof shows that
# every order-one commutant has this form.
As = 1 + 2 * R + 3 * R**2
At = -2 + R**2
Ar = 3 - R
H = 5 + R + R**3
general_commutant = (
    sp.expand(As) * delta_s
    + sp.expand(At) * delta_t
    + sp.expand(Ar) * delta_r,
    sp.expand(-As * T + H),
)
assert commutator(normal_a, general_commutant) == zero
assert commutator(normal_b, general_commutant) == zero

print("PASS: the cotangent-graph constraints form an exact Weyl pair")
print("PASS: R, delta_R, delta_T, and T-delta_S form two commuting Weyl pairs")
print("PASS: the adapted base is k[R,x,w], with a polynomial section of R")
print("PASS: the common polynomial constants of delta_S and delta_T are k[R]")
print("PASS: the displayed k[R]-module is the complete order-one centralizer")
print("NEXT: search the centralizer at differential order two")
