#!/usr/bin/env python3
"""Exact Rees-cone ranks for maximally collided square/cube blocks.

For the degree-h collision polynomial S=z^h, write

    V=z^(2h)+X_0*z^(h-1)+...+X_(h-1).

After reversing z by w=1/z, the unique monic square root candidate U is the
degree-3h truncation of

    (1 + sum_j X_j*w^(h+1+j))^(3/2).

The coefficients beyond degree 3h in U^2-V^3 generate the transfer ideal.
This script Rees-homogenizes those equations in the transverse variables,
saturates by the Rees parameter, and checks that the special cone has
dimension 2^h.  Ferrand's factorization-algebra decomposition has the same
rank sum_i binomial(h,i)=2^h.

Optionally, the script compares the saturated cone with the current-power
ideal generated by [w^n](x_0+...+x_(h-1)w^(h-1))^k for n>=h+1-k.  This is
the concrete fusion/local-Weyl presentation suggested by the computations.
The raw method avoids Rees saturation, and the modular method supplies a
rigorous characteristic-zero upper bound by upper semicontinuity.  In
characteristic three, the primitive residual ideal also has an explicit
divided-Frobenius presentation; the optional comparison certifies that the
two ideals agree.
"""

from __future__ import annotations

import argparse
import math
import shutil
import subprocess

import sympy as sp


def singular_expression(expression: sp.Expr) -> str:
    return str(sp.expand(expression)).replace("**", "^")


def transfer_relations(degree: int) -> tuple[tuple[sp.Symbol, ...], list[sp.Expr]]:
    """Return the transverse variables and exact maximally-collided ideal."""

    w = sp.symbols("w")
    variables = sp.symbols(f"x0:{degree}")
    perturbation = 1 + sum(
        variables[index] * w ** (degree + 1 + index)
        for index in range(degree)
    )
    cube = sp.Poly(sp.expand(perturbation**3), w)

    square_root = [sp.Integer(0)] * (3 * degree + 1)
    square_root[0] = sp.Integer(1)
    for exponent in range(1, 3 * degree + 1):
        convolution = sum(
            square_root[index] * square_root[exponent - index]
            for index in range(1, exponent)
        )
        square_root[exponent] = sp.factor(
            (cube.coeff_monomial(w**exponent) - convolution) / 2
        )

    truncated = sum(
        square_root[exponent] * w**exponent
        for exponent in range(3 * degree + 1)
    )
    residual = sp.Poly(sp.expand(truncated**2 - perturbation**3), w)
    relations = [
        sp.factor(residual.coeff_monomial(w**exponent))
        for exponent in range(3 * degree + 1, 6 * degree + 1)
    ]
    return variables, relations


def rees_homogenize(
    expression: sp.Expr,
    variables: tuple[sp.Symbol, ...],
    rees_parameter: sp.Symbol,
) -> sp.Expr:
    """Homogenize for the adic order and clear rational denominators."""

    def transverse_degree(term: sp.Expr) -> int:
        powers = term.as_powers_dict()
        return sum(int(powers.get(variable, 0)) for variable in variables)

    terms = sp.Add.make_args(sp.expand(expression))
    order = min(transverse_degree(term) for term in terms)
    homogenized = sp.expand(
        sum(
            term
            * rees_parameter ** (transverse_degree(term) - order)
            for term in terms
        )
    )
    return sp.Poly(
        homogenized, *variables, rees_parameter, domain=sp.QQ
    ).clear_denoms()[1].as_expr()


def current_power_relations(
    degree: int, variables: tuple[sp.Symbol, ...]
) -> list[sp.Expr]:
    """Relations for the candidate sl2-current/fusion presentation."""

    relations: list[sp.Expr] = []
    coefficients: list[sp.Expr] = [sp.Integer(1)]
    for power in range(2, degree + 2):
        previous = (
            list(variables)
            if power == 2
            else coefficients
        )
        maximum_exponent = 2 * degree - power
        coefficients = [
            sp.expand(
                sum(
                    previous[exponent - index] * variable
                    for index, variable in enumerate(variables)
                    if 0 <= exponent - index < len(previous)
                )
            )
            for exponent in range(maximum_exponent + 1)
        ]
        threshold = degree + 1 - power
        # Coefficients above the next `degree`-term window follow from these
        # and the lower-power windows.  Keeping the border window avoids an
        # enormous redundant expansion in the optional comparison.
        relations.extend(
            coefficients[exponent]
            for exponent in range(
                max(0, threshold),
                maximum_exponent + 1,
            )
        )
    return [relation for relation in relations if relation != 0]


def characteristic_three_relations(
    degree: int, variables: tuple[sp.Symbol, ...]
) -> list[sp.Expr]:
    """The divided-Frobenius form of the primitive residual ideal mod 3.

    Write X^2=q+p with q supported in w-degrees at most h-2.  Primitive
    reduction of the square/cube residual has two boundary quadrics,
    all Frobenius cubes x_i^3, and the non-Frobenius coefficients of

        Delta_3(X) = (X(w)^3 - sum_i x_i^3 w^(3i))/3,

    corrected by the corresponding high coefficient of X^2.  The division
    is integral before reduction modulo 3.
    """

    w = sp.symbols("w")
    polynomial = sum(
        variable * w**index for index, variable in enumerate(variables)
    )
    square = sp.Poly(sp.expand(polynomial**2), w)
    cube = sp.Poly(sp.expand(polynomial**3), w)
    frobenius_cube = sum(
        variable**3 * w ** (3 * index)
        for index, variable in enumerate(variables)
    )
    divided_cube = sp.Poly(
        sp.expand((polynomial**3 - frobenius_cube) / 3), w
    )

    relations = [
        square.coeff_monomial(w ** (degree - 1)),
        square.coeff_monomial(w**degree),
    ]
    for exponent in range(3 * degree - 2):
        if exponent % 3 == 0:
            relations.append(variables[exponent // 3] ** 3)
            continue
        boundary_index = degree + 1 + exponent
        boundary = (
            square.coeff_monomial(w**boundary_index)
            if boundary_index <= 2 * degree - 2
            else sp.Integer(0)
        )
        relations.append(
            sp.expand(
                divided_cube.coeff_monomial(w**exponent) + boundary
            )
        )
    assert len(relations) == 3 * degree
    weights = {
        variable: degree + 1 + index
        for index, variable in enumerate(variables)
    }
    for relation in relations:
        term_weights = {
            sum(
                int(power) * weights[variable]
                for variable, power in term.as_powers_dict().items()
                if variable in weights
            )
            for term in sp.Add.make_args(sp.expand(relation))
        }
        assert len(term_weights) == 1, (degree, relation, term_weights)
    return relations


def primitive_integral_relations(
    relations: list[sp.Expr], variables: tuple[sp.Symbol, ...]
) -> list[sp.Expr]:
    """Clear denominators and remove the content of every relation."""

    integral_relations = []
    for relation in relations:
        cleared = sp.Poly(
            relation, *variables, domain=sp.QQ
        ).clear_denoms()[1]
        integral_relations.append(
            sp.Poly(cleared, *variables, domain=sp.ZZ)
            .primitive()[1]
            .as_expr()
        )
    return integral_relations


def verify_characteristic_three_model(
    degree: int, timeout: int
) -> None:
    """Compare the primitive transfer fiber with its divided-Frobenius form."""

    singular = shutil.which("Singular")
    assert singular is not None, "Singular is required for the certificate"
    variables, relations = transfer_relations(degree)
    primitive = primitive_integral_relations(relations, variables)
    divided_frobenius = characteristic_three_relations(degree, variables)
    primitive_generators = ",\n".join(
        singular_expression(relation) for relation in primitive
    )
    divided_generators = ",\n".join(
        singular_expression(relation) for relation in divided_frobenius
    )
    reversed_names = ",".join(str(variable) for variable in reversed(variables))
    program = f'''
ring R=3,({reversed_names}),dp;
ideal Primitive={primitive_generators};
ideal DividedFrobenius={divided_generators};
Primitive=slimgb(Primitive);
DividedFrobenius=slimgb(DividedFrobenius);
"PRIMITIVE_MOD_DIVIDED",size(reduce(Primitive,DividedFrobenius));
"DIVIDED_MOD_PRIMITIVE",size(reduce(DividedFrobenius,Primitive));
'''
    completed = subprocess.run(
        (singular, "-q"),
        input=program,
        text=True,
        capture_output=True,
        check=True,
        timeout=timeout,
    )
    values: dict[str, int] = {}
    lines = [line.strip() for line in completed.stdout.splitlines()]
    for position, line in enumerate(lines):
        for marker in (
            "PRIMITIVE_MOD_DIVIDED",
            "DIVIDED_MOD_PRIMITIVE",
        ):
            if line == marker:
                values[marker] = int(lines[position + 1])
            elif line.startswith(f"{marker} "):
                values[marker] = int(line.removeprefix(marker).strip())
    assert values == {
        "PRIMITIVE_MOD_DIVIDED": 0,
        "DIVIDED_MOD_PRIMITIVE": 0,
    }, (degree, values)


def divided_frobenius_dimension(
    degree: int, timeout: int, basis_engine: str
) -> int:
    """Compute the characteristic-3 length in the intrinsic tail weight."""

    singular = shutil.which("Singular")
    assert singular is not None, "Singular is required for the certificate"
    variables = sp.symbols(f"x0:{degree}")
    relations = characteristic_three_relations(degree, variables)
    generators = ",\n".join(
        singular_expression(relation) for relation in relations
    )
    reversed_names = ",".join(str(variable) for variable in reversed(variables))
    reversed_weights = ",".join(
        str(degree + 1 + index)
        for index in reversed(range(degree))
    )
    program = f'''
ring R=3,({reversed_names}),wp({reversed_weights});
ideal I={generators};
I={basis_engine}(I);
"DIVIDED_FROBENIUS_DIMENSION",vdim(I);
'''
    completed = subprocess.run(
        (singular, "-q"),
        input=program,
        text=True,
        capture_output=True,
        check=True,
        timeout=timeout,
    )
    lines = [line.strip() for line in completed.stdout.splitlines()]
    for position, line in enumerate(lines):
        if line == "DIVIDED_FROBENIUS_DIMENSION":
            return int(lines[position + 1])
        if line.startswith("DIVIDED_FROBENIUS_DIMENSION "):
            return int(
                line.removeprefix("DIVIDED_FROBENIUS_DIMENSION").strip()
            )
    raise RuntimeError(
        "Singular did not report the divided-Frobenius dimension:\n"
        f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
    )


def cone_invariants(
    degree: int, timeout: int, compare_current_power_ideal: bool
) -> tuple[int, tuple[int, ...]]:
    """Compute the colength and Hilbert vector of the saturated cone."""

    singular = shutil.which("Singular")
    assert singular is not None, "Singular is required for the Rees certificate"

    variables, relations = transfer_relations(degree)
    rees_parameter = sp.symbols("t")
    generators = ",\n".join(
        singular_expression(
            rees_homogenize(relation, variables, rees_parameter)
        )
        for relation in relations
    )
    comparison_program = ""
    if compare_current_power_ideal:
        target_generators = ",\n".join(
            singular_expression(relation)
            for relation in current_power_relations(degree, variables)
        )
        comparison_program = f'''
ideal Target={target_generators};
Target=std(Target);
"CURRENT_POWER_DIMENSION",vdim(Target);
"CONE_MOD_CURRENT_POWER",size(reduce(I,Target));
"CURRENT_POWER_MOD_CONE",size(reduce(Target,I));
'''
    reversed_names = ",".join(str(variable) for variable in reversed(variables))
    program = f'''
LIB "elim.lib";
ring R=0,({reversed_names},t),dp;
ideal J={generators};
ideal Saturated=sat(J,ideal(t));
ideal Cone=subst(Saturated,t,0);
ring Q=0,({reversed_names}),dp;
ideal I=imap(R,Cone);
I=std(I);
"CONE_DIMENSION",vdim(I);
ideal K=kbase(I);
intvec H={",".join("0" for _ in range(degree + 1))};
for (int i=1;i<=size(K);i++)
{{
  H[deg(K[i])+1]=H[deg(K[i])+1]+1;
}}
"HILBERT_VECTOR";
H;
{comparison_program}
'''
    completed = subprocess.run(
        (singular, "-q"),
        input=program,
        text=True,
        capture_output=True,
        check=True,
        timeout=timeout,
    )
    assert "?" not in completed.stderr, completed.stderr
    lines = [line.strip() for line in completed.stdout.splitlines()]
    dimension: int | None = None
    hilbert_vector: tuple[int, ...] | None = None
    comparison_values: dict[str, int] = {}
    for position, line in enumerate(lines):
        if line == "CONE_DIMENSION":
            dimension = int(lines[position + 1])
        elif line.startswith("CONE_DIMENSION "):
            dimension = int(line.removeprefix("CONE_DIMENSION").strip())
        elif line == "HILBERT_VECTOR":
            hilbert_vector = tuple(
                int(entry) for entry in lines[position + 1].split(",")
            )
        elif line in {
            "CURRENT_POWER_DIMENSION",
            "CONE_MOD_CURRENT_POWER",
            "CURRENT_POWER_MOD_CONE",
        }:
            comparison_values[line] = int(lines[position + 1])
        else:
            for comparison_marker in (
                "CURRENT_POWER_DIMENSION",
                "CONE_MOD_CURRENT_POWER",
                "CURRENT_POWER_MOD_CONE",
            ):
                if line.startswith(f"{comparison_marker} "):
                    comparison_values[comparison_marker] = int(
                        line.removeprefix(comparison_marker).strip()
                    )
    if dimension is None or hilbert_vector is None:
        raise RuntimeError(
            "Singular did not report the cone invariants:\n"
            f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
        )
    if compare_current_power_ideal:
        assert comparison_values == {
            "CURRENT_POWER_DIMENSION": 2**degree,
            "CONE_MOD_CURRENT_POWER": 0,
            "CURRENT_POWER_MOD_CONE": 0,
        }, (degree, comparison_values)
    return dimension, hilbert_vector


def raw_transfer_dimension(
    degree: int,
    timeout: int,
    characteristic: int = 0,
    basis_engine: str = "std",
) -> int:
    """Compute length before passing to the associated graded.

    For a finite-dimensional filtered algebra, this is also the total
    dimension of its associated graded.  This route avoids Rees saturation
    and reaches one degree farther in the current resource envelope.
    """

    singular = shutil.which("Singular")
    assert singular is not None, "Singular is required for the certificate"
    variables, relations = transfer_relations(degree)
    # Use the primitive integral model.  This makes the finite-field
    # certificate independent of irrelevant common factors introduced
    # while clearing the powers-of-two binomial denominators.
    integral_relations = primitive_integral_relations(relations, variables)
    generators = ",\n".join(
        singular_expression(relation) for relation in integral_relations
    )
    reversed_names = ",".join(str(variable) for variable in reversed(variables))
    program = f'''
ring R={characteristic},({reversed_names}),dp;
ideal I={generators};
I={basis_engine}(I);
"RAW_DIMENSION",vdim(I);
'''
    completed = subprocess.run(
        (singular, "-q"),
        input=program,
        text=True,
        capture_output=True,
        check=True,
        timeout=timeout,
    )
    lines = [line.strip() for line in completed.stdout.splitlines()]
    for position, line in enumerate(lines):
        if line == "RAW_DIMENSION":
            return int(lines[position + 1])
        if line.startswith("RAW_DIMENSION "):
            return int(line.removeprefix("RAW_DIMENSION").strip())
    raise RuntimeError(
        "Singular did not report the raw transfer dimension:\n"
        f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-degree", type=int, default=5)
    parser.add_argument("--max-degree", type=int, default=11)
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument(
        "--method",
        choices=("rees", "raw", "modular", "divided-three"),
        default="rees",
        help=(
            "use the saturated Rees cone, or only its equal total dimension "
            "computed from the raw filtered transfer algebra over Q or "
            "over a good finite field; divided-three uses the explicit "
            "characteristic-3 model and its intrinsic tail-weight order"
        ),
    )
    parser.add_argument(
        "--prime",
        type=int,
        default=32003,
        help="finite-field characteristic used by --method modular",
    )
    parser.add_argument(
        "--basis-engine",
        choices=("std", "slimgb"),
        default="std",
        help=(
            "Singular standard-basis engine for --method raw/modular; "
            "slimgb is substantially faster in the h=15 certificate"
        ),
    )
    parser.add_argument(
        "--compare-current-power-ideal",
        action="store_true",
        help=(
            "also prove equality with the coefficient ideal "
            "[w^n]X(w)^k, n>=h+1-k"
        ),
    )
    parser.add_argument(
        "--compare-characteristic-three-model",
        action="store_true",
        help=(
            "prove that the primitive characteristic-3 fiber equals its "
            "explicit divided-Frobenius presentation"
        ),
    )
    arguments = parser.parse_args()
    assert 1 <= arguments.min_degree <= arguments.max_degree
    assert not (
        arguments.method != "rees"
        and arguments.compare_current_power_ideal
    ), "current-power ideal comparison requires --method rees"

    for degree in range(arguments.min_degree, arguments.max_degree + 1):
        if arguments.compare_characteristic_three_model:
            verify_characteristic_three_model(degree, arguments.timeout)
            print(
                f"PASS: h={degree} primitive characteristic-3 fiber "
                "equals the divided-Frobenius presentation"
            )
        if arguments.method == "divided-three":
            dimension = divided_frobenius_dimension(
                degree, arguments.timeout, arguments.basis_engine
            )
            expected = 2**degree
            assert dimension == expected, (degree, dimension, expected)
            print(
                f"PASS: h={degree} divided-Frobenius characteristic-3 "
                f"fiber has length {dimension}=2^{degree}; "
                "upper semicontinuity gives the characteristic-zero "
                "upper bound"
            )
            continue
        if arguments.method in {"raw", "modular"}:
            characteristic = (
                0 if arguments.method == "raw" else arguments.prime
            )
            dimension = raw_transfer_dimension(
                degree,
                arguments.timeout,
                characteristic,
                arguments.basis_engine,
            )
            expected = 2**degree
            assert dimension == expected, (degree, dimension, expected)
            if arguments.method == "raw":
                print(
                    f"PASS: h={degree} raw collided transfer algebra has "
                    f"length {dimension}=2^{degree}; its associated graded "
                    "has the same total length"
                )
            else:
                print(
                    f"PASS: h={degree} characteristic-{characteristic} "
                    f"collided transfer fiber has length "
                    f"{dimension}=2^{degree}; upper semicontinuity gives "
                    "the characteristic-zero upper bound"
                )
            continue
        dimension, hilbert_vector = cone_invariants(
            degree,
            arguments.timeout,
            arguments.compare_current_power_ideal,
        )
        expected = 2**degree
        assert dimension == expected, (degree, dimension, expected)
        expected_hilbert = tuple(
            math.comb(degree, index) for index in range(degree + 1)
        )
        assert hilbert_vector == expected_hilbert, (
            degree,
            hilbert_vector,
            expected_hilbert,
        )
        print(
            f"PASS: h={degree} maximally collided cone has Hilbert vector "
            f"{hilbert_vector} and length {dimension}=2^{degree}"
        )


if __name__ == "__main__":
    main()
