#!/usr/bin/env python3
"""Exact degree-five attack on presentation-defined normalization selectors.

The canonical symmetric quintic has a mu_3 pencil symmetry which permutes all
three nonzero primitive roots while preserving the unmarked Hessian/Fitting
data.  The checker verifies that the symmetry cannot preserve the full
Zariski--Main package: among those roots, only W=1 has a regular source lift.
It also records the valuation obstruction to hiding the pole with one stable
identity variable.
"""

from __future__ import annotations

import sympy as sp


w, s, t, A, B, C = sp.symbols("w s t A B C")
alpha, beta = sp.symbols("alpha beta", nonzero=True)
zeta = sp.symbols("zeta")


def cyclotomic_reduce(expression: sp.Expr) -> sp.Expr:
    """Reduce a polynomial expression modulo zeta**2 + zeta + 1."""

    numerator, denominator = sp.cancel(expression).as_numer_denom()
    numerator_remainder = sp.rem(
        sp.Poly(sp.expand(numerator), zeta),
        sp.Poly(zeta**2 + zeta + 1, zeta),
    ).as_expr()
    denominator_remainder = sp.rem(
        sp.Poly(sp.expand(denominator), zeta),
        sp.Poly(zeta**2 + zeta + 1, zeta),
    ).as_expr()
    return sp.cancel(numerator_remainder / denominator_remainder)


# The smallest exact-double weighted seed whose marked-Hessian divisor has a
# nontrivial mark-preserving affine stabilizer.
H = sp.expand((w**2 - w**5) / 3)
H1 = sp.diff(H, w)
H2 = sp.diff(H, w, 2)
c = -H1.subs(w, 1)
kappa = sp.cancel(H2.subs(w, 1) / c)
a0 = sp.cancel(-(1 + kappa) / (2 + kappa))

assert H.subs(w, 0) == H1.subs(w, 0) == H.subs(w, 1) == 0
assert c == 1
assert kappa == -6
assert a0 == -sp.Rational(5, 4)
assert sp.factor(H / w**2 + (w - 1) * (w**2 + w + 1) / 3) == 0
assert sp.factor(H2 + 2 * (10 * w**3 - 1) / 3) == 0

# Direct coefficient enumeration of affine Hessian symmetries.  If
# alpha^2 H''(alpha*w+beta)=gamma H''(w), its w^2 coefficient forces beta=0;
# the constant and cubic coefficients then force gamma=alpha^2=alpha^5.
transformed_hessian = sp.Poly(
    sp.expand(alpha**2 * H2.subs(w, alpha * w + beta)), w
)
assert sp.factor(transformed_hessian.coeff_monomial(w**2)) == -20 * alpha**4 * beta
assert sp.factor(transformed_hessian.coeff_monomial(w**3)) == -sp.Rational(20, 3) * alpha**5
assert sp.factor(transformed_hessian.coeff_monomial(1).subs(beta, 0)) == sp.Rational(2, 3) * alpha**2
# Thus the exact affine stabilizer is mu_3, generated by w -> zeta*w.
assert cyclotomic_reduce(H.subs(w, zeta * w) - zeta**2 * H) == 0
assert cyclotomic_reduce(H2.subs(w, zeta * w) - H2) == 0

# The generator is a genuine self-equivalence of the two-parameter pencil,
# moving the base by (s,t)->(zeta*s,zeta^2*t).
E = H - s * w + t
pencil_transport = E.subs(
    {w: zeta * w, s: zeta * s, t: zeta**2 * t},
    simultaneous=True,
)
assert cyclotomic_reduce(pencil_transport - zeta**2 * E) == 0

# It fixes both reduced weighted target-boundary images.  With C fixed, the
# target scaling is (A,B,C)->(zeta^2*A,zeta*B,C).
assert cyclotomic_reduce((zeta * B) * C - zeta * (B * C)) == 0
assert cyclotomic_reduce((zeta**2 * A) * C**2 - zeta**2 * (A * C**2)) == 0

# It permutes the three candidate nonzero primitive roots transitively.
primitive = sp.factor(H / w**2)
for root in (1, zeta, zeta**2):
    assert cyclotomic_reduce(primitive.subs(w, root)) == 0
assert cyclotomic_reduce(zeta * 1 - zeta) == 0
assert cyclotomic_reduce(zeta * zeta - zeta**2) == 0
assert cyclotomic_reduce(zeta * zeta**2 - 1) == 0

# Boundary reconstruction separates the candidates.  On a simple root rho at
# C=0 one has gamma_0=-H'(rho)/c=rho and u_0=W/gamma=1.  Therefore the
# numerator of z is rho-1.  It vanishes only at the distinguished root one.
rho = sp.symbols("rho")
gamma0 = -H1.subs(w, rho) / c
gamma0_at_primitive_root = sp.rem(
    sp.Poly(sp.expand(gamma0 - rho), rho),
    sp.Poly(rho**3 - 1, rho),
).as_expr()
assert gamma0_at_primitive_root == 0
z_numerator_constant = sp.expand(rho - 1 - a0 * (rho / rho - 1))
assert z_numerator_constant == rho - 1
assert z_numerator_constant.subs(rho, 1) == 0
assert cyclotomic_reduce(z_numerator_constant.subs(rho, zeta)) == zeta - 1
assert cyclotomic_reduce(z_numerator_constant.subs(rho, zeta**2)) == -zeta - 2

# At rho=1 the defining choice of a0 also cancels the first-order numerator.
# Write W=1-B*C+O(C^2).  Then gamma=1-5*B*C+O(C^2) and
# u=W/gamma=1+4*B*C+O(C^2).
first_order_z_numerator = sp.expand(-5 * B - a0 * (4 * B))
assert first_order_z_numerator == 0

# At rho=zeta or zeta^2, x=C/gamma has valuation one and the nonzero constant
# above gives v(z)=-2.  A stable identity coordinate T has Gauss valuation
# zero.  Representative elementary mixes merely move, rather than remove,
# the negative valuation.
valuation = {"x": 1, "y": 0, "z": -2, "T": 0}
assert min(valuation["T"], valuation["z"]) == -2  # T -> T+z
assert min(valuation["z"], valuation["T"]) == -2  # z -> z+T
assert min(valuation["z"], 2 * valuation["y"]) == -2  # z -> z+y^2
assert min(valuation.values()) < 0

print("PASS selector attack: the symmetric quintic has exact pencil group mu_3")
print("PASS selector attack: the coarse symmetry permutes all three primitive-root marks")
print("PASS selector attack: zero, infinity, and the ordered target-boundary pair survive")
print("PASS selector attack: only root one meets the regular-reconstruction open")
print("PASS selector attack: one-variable stable mixing cannot remove the boundary pole")
