#!/usr/bin/env python3
"""Exact additive invariants on the normalized (2,4) factorization slice.

For a quadratic A and quartic B, impose the tangent normalization

    [AB]_(T^5)=a*d+c*p=1,  Res(A,B)=1.

The script verifies three natural gauge LNDs.  The commuting pair D10,D0 has
an exact common kernel generated by a,p,U,N,M,C,R,S.  The generic quotient is
the trinomial M^2+4*U*N^2=256*a^4; C,R,S are the successive regular boundary
fractions which select the correct component over a=0.

The checker verifies the polynomial identities and boundary coordinates.
The accompanying note supplies the slice and minimal-pole proof that the
displayed generators are the full common kernel.
"""

from __future__ import annotations

import sympy as sp


T = sp.Symbol("T")
a, c, z, p, d, y, x, w = sp.symbols("a c z p d y x w")
variables = (a, c, z, p, d, y, x, w)

A = a * T**2 + c * T + z
B = p * T**4 + d * T**3 + y * T**2 + x * T + w
m = a * d + c * p
resultant = sp.expand(sp.resultant(A, B, T))


def apply_derivation(
    polynomial: sp.Expr, images: tuple[sp.Expr, ...]
) -> sp.Expr:
    return sp.expand(
        sum(
            sp.diff(polynomial, variable) * image
            for variable, image in zip(variables, images, strict=True)
        )
    )


def reduce_by_m(polynomial: sp.Expr) -> sp.Expr:
    return sp.factor(sp.rem(sp.expand(polynomial), m - 1, d))


# The low-coefficient factor translation B -> B+t*A.
D0 = (
    sp.Integer(0),
    sp.Integer(0),
    sp.Integer(0),
    sp.Integer(0),
    sp.Integer(0),
    a,
    c,
    z,
)

# The tangent-preserving Euclidean shear
# B -> B+t*(a*T^2-2*c*T)*A.
D2 = (
    sp.Integer(0),
    sp.Integer(0),
    sp.Integer(0),
    a**2,
    -a * c,
    a * z - 2 * c**2,
    -2 * c * z,
    sp.Integer(0),
)

# Minus a times the upper binary-variable shear, corrected by
# B -> B+6*p*t*T*A.  The coefficient 6 is the product degree.
D10 = (
    sp.Integer(0),
    -2 * a**2,
    -a * c,
    sp.Integer(0),
    2 * a * p,
    -3 * a * d + 6 * c * p,
    -2 * a * y + 6 * p * z,
    -a * x,
)

for derivation in (D0, D2, D10):
    assert apply_derivation(m, derivation) == 0
    assert apply_derivation(resultant, derivation) == 0
    for variable in variables:
        iterate = variable
        for _ in range(1, 10):
            iterate = apply_derivation(iterate, derivation)
            if iterate == 0:
                break
        else:
            raise AssertionError(f"nilpotence bound failed on {variable}")

# D10 and D0 are the commuting primitive pair used below.  D2 commutes with
# D0 but has the controlled bracket [D10,D2]=-2*a*c*D0.
for index in range(len(variables)):
    bracket_10_0 = apply_derivation(D0[index], D10) - apply_derivation(
        D10[index], D0
    )
    bracket_2_0 = apply_derivation(D0[index], D2) - apply_derivation(
        D2[index], D0
    )
    bracket_10_2 = apply_derivation(D2[index], D10) - apply_derivation(
        D10[index], D2
    )
    assert bracket_10_0 == 0
    assert bracket_2_0 == 0
    assert sp.expand(bracket_10_2 + 2 * a * c * D0[index]) == 0

# The generic simultaneous quotient.
U = 4 * a * z - c**2
N = (
    -4 * a**3 * x
    + 4 * a**2 * c * y
    - 3 * a * c**2 * d
    - 12 * a * c * p * z
    + 4 * a * z
    + 5 * c**3 * p
    - c**2
)
M = -8 * (
    -2 * a**4 * w
    + a**3 * c * x
    + 2 * a**3 * y * z
    - a**2 * c**2 * y
    - 3 * a**2 * c * d * z
    - 2 * a**2 * p * z**2
    + a * c**3 * d
    + 4 * a * c**2 * p * z
    - c**4 * p
)

# Three boundary fractions, written as regular polynomial representatives.
C = -4 * (a**2 * x - a * c * y + 2 * c**2 * d + 3 * c * p * z - 5 * z)
R = 4 * p**2 * z + 2 * d - a * d**2
S = -8 * (
    -2 * a**3 * p**3 * w
    + a**2 * c * p**3 * x
    + 2 * a**2 * p**3 * y * z
    - a * c**2 * p**3 * y
    - 3 * a * c * d * p**3 * z
    - 2 * a * p**4 * z**2
    + 2 * c**3 * d * p**3
    + c**2 * d * p**2
    + 4 * c**2 * p**4 * z
    + c * d * p
    + d
)

for invariant in (a, p, U, N, M, C, R, S):
    assert apply_derivation(invariant, D0) == 0
    assert reduce_by_m(apply_derivation(invariant, D10)) == 0

assert sp.factor(a * C - (N + 4 * U)) == -5 * c**2 * (m - 1)
assert sp.factor(a * R - (p**2 * U + 1)) == (
    -a * d + c * p + 1
) * (m - 1)
geometric_sum = sum((c * p) ** exponent for exponent in range(4))
assert sp.factor(
    a * S - (p**3 * M - 8) + 8 * geometric_sum * (m - 1)
) == 0

norm_error = sp.factor(M**2 + 4 * U * N**2 - 256 * a**4 * resultant)
assert sp.factor(
    norm_error
    - 4
    * U**2
    * (m - 1)
    * (
        8 * a**3 * x
        - 8 * a**2 * c * y
        - 4 * a**2 * d * z
        + 7 * a * c**2 * d
        + 20 * a * c * p * z
        - 4 * a * z
        - 9 * c**3 * p
        + c**2
    )
) == 0

# Dividing the norm equation once after selecting p^3*M=8+a*S gives the
# relation Phi=0.  Its a=0 term is linear in S, so there is no continuing
# Hensel ladder after S.
Phi = (
    4 * C**2 * R * a**2 * p**4
    - 4 * C**2 * a * p**4
    - 32 * C * R**2 * a**2 * p**2
    + 64 * C * R * a * p**2
    - 32 * C * p**2
    + 64 * R**3 * a**2
    - 192 * R**2 * a
    + 192 * R
    + S**2 * a
    + 16 * S
    - 256 * a**3 * p**6
)
assert reduce_by_m(Phi - 256 * a**3 * p**6 * (resultant - 1)) == 0
assert sp.factor(
    Phi.subs(a, 0) - (16 * (S + 12 * R - 2 * C * p**2)).subs(a, 0)
) == 0

# Successive slices after a is inverted.  Projection along D10 sets c=0;
# Y,X,W are the resulting coefficient coordinates.
slice_10 = -c / (2 * a**2)
Y = (4 * a**2 * y - 6 * a * c * d + 3 * c**2 * p) / (4 * a**2)
X = (
    4 * a**3 * x
    - 4 * a**2 * c * y
    + 3 * a * c**2 * d
    + 12 * a * c * p * z
    - 5 * c**3 * p
) / (4 * a**3)
W = -(
    -8 * a**4 * w
    + 4 * a**3 * c * x
    - 2 * a**2 * c**2 * y
    + a * c**3 * d
    + 6 * a * c**2 * p * z
    - 2 * c**4 * p
) / (8 * a**4)
slice_0 = Y / a
L = sp.factor(W - U * Y / (4 * a**2))

assert apply_derivation(slice_10, D10) == 1
assert apply_derivation(slice_10, D0) == 0
assert sp.factor(apply_derivation(slice_0, D10)) == 0
assert sp.factor(apply_derivation(slice_0, D0)) == 1
for invariant in (a, p, U, N, M):
    assert apply_derivation(invariant, D10) == 0 or reduce_by_m(
        apply_derivation(invariant, D10)
    ) == 0
    assert apply_derivation(invariant, D0) == 0
assert sp.factor(N - (U - 4 * a**3 * X)) == 0
assert sp.factor(M - (16 * a**4 * L + U**2 * p)) == 0

# The primitive pair has rank two on the entire a=0 boundary: there cp=1,
# so D10(y)=6 and D0(x)=c are both units.  The displayed point also checks
# both defining equations.
boundary_point = {a: 0, c: 1, z: 0, p: 1, d: 0, y: 0, x: 0, w: 1}
assert m.subs(boundary_point) == 1
assert resultant.subs(boundary_point) == 1
boundary_rank = sp.Matrix.hstack(
    sp.Matrix([image.subs(boundary_point) for image in D10]),
    sp.Matrix([image.subs(boundary_point) for image in D0]),
).rank()
assert boundary_rank == 2

# Boundary coordinates for the minimal-pole proof.
boundary_substitution = {a: 0, p: 1 / c}
assert sp.factor(U.subs(boundary_substitution) + c**2) == 0
assert sp.factor(N.subs(boundary_substitution) - 4 * c**2) == 0
assert sp.factor(M.subs(boundary_substitution) - 8 * c**3) == 0
assert sp.factor(C.subs(boundary_substitution) - 8 * (z - c**2 * d)) == 0
assert sp.factor(R.subs(boundary_substitution) - (2 * d + 4 * z / c**2)) == 0
assert sp.factor(
    S.subs(boundary_substitution) - (2 * C * p**2 - 12 * R).subs(
        boundary_substitution
    )
) == 0

boundary_p = 1 / c
boundary_C = 8 * (z - c**2 * d)
boundary_R = 2 * d + 4 * z / c**2
boundary_jacobian = sp.Matrix(
    [
        [sp.diff(function, variable) for variable in (c, z, d)]
        for function in (boundary_p, boundary_C, boundary_R)
    ]
).det()
assert sp.factor(boundary_jacobian) == -48 / c**2

# Although D2 does not commute with D10, equation [D10,D2]=-2*a*c*D0
# shows that it preserves ker(D10) intersect ker(D0).  Its induced triangular
# LND on the exact common kernel is especially small.
for invariant in (a, U, N, M, C):
    assert reduce_by_m(apply_derivation(invariant, D2)) == 0
assert apply_derivation(p, D2) == a**2
assert reduce_by_m(apply_derivation(R, D2) - 2 * a * p * U) == 0
assert reduce_by_m(apply_derivation(S, D2) - 3 * a * p**2 * M) == 0
assert apply_derivation(p / a**2, D2) == 1

# The triple-kernel boundary is the cusp parametrization
# U=-c^2, M=8*c^3, with C an independent affine coordinate.
assert sp.factor(
    (M**2 + 64 * U**3).subs(boundary_substitution)
) == 0
assert sp.factor(
    sp.det(
        sp.Matrix(
            [
                [sp.diff(-c**2, c), sp.diff(-c**2, z)],
                [
                    sp.diff(8 * (z - c**2 * d), c),
                    sp.diff(8 * (z - c**2 * d), z),
                ],
            ]
        )
    )
) == -16 * c

print("PASS: D0,D2,D10 are global triangular LNDs on the normalized (2,4) slice")
print("PASS: D10 and D0 commute and retain rank two along a=0")
print("PASS: the generic common quotient is M^2+4*U*N^2=256*a^4")
print("PASS: C,R,S are regular common invariants selecting the a=0 component")
print("PASS: the S relation is boundary-linear, so the saturation ladder terminates")
print("PASS: ker(D10) intersect ker(D0)=k[a,p,U,N,M,C,R,S]")
print("PASS: the triple intersection is k[a,U,N,M,C], with a cusp boundary")
