#!/usr/bin/env python3
"""Exact global-jet continuation of the JC(2)--HC(4) boundary bridge.

The local paired initial-conormal cokernel vanishes.  This checker records
what survives after using the marked normalization E=A1.

1. A global affine parameter and a global frame of the conormal/different
   line identify equal-order endpoint jets up to one common scalar.  Their
   projective ratio is therefore intrinsic.
2. The quartic spectator packet has connector ratio -1.
3. Abstract cusp-node normalization packets with the same local conductor
   types realize the varying ratio -1/lambda^2.  Hence the conductor,
   marked cusp, affine-line structure, and line character do not force a
   universal ratio.
4. At lambda=-1 the packet is the explicit two-generated plane algebra
   k[T^2,T^3(T^2-1)] with equation y^2=x^3(x-1)^2.  It has the structured
   anti-diagonal ratio -1.
5. The vertical braid exponents of that plane carrier are 3 at the cusp and
   2 at the node.  The resulting braid and commutation relations force the
   two meridians to have equal transposition images, so no connected
   degree-four cover can use this carrier.
6. The canonical dualizing residue quotient at a node is annihilated by the
   conductor.  Multiplying its anti-diagonal logarithmic generator by the
   conormal residue produces regular differentials on both branches, so it
   cannot recover the two first jets.

This is an exact no-go theorem for two proposed transports.  The abstract
family is not asserted to be a degree-four finite cover or a Keller map.
Only its lambda=-1 member is proved here to be a two-generator plane
algebra.  Degree-four cover and meridian compatibility remain available for
a stronger obstruction.
"""

from __future__ import annotations

import sympy as sp


# ---------------------------------------------------------------------------
# 1. Projective jet ratio under the global affine/frame ambiguity
# ---------------------------------------------------------------------------

a, b, frame = sp.symbols("a b frame", nonzero=True)
c_plus, c_minus = sp.symbols("c_plus c_minus", nonzero=True)
contact_order = sp.symbols("m", integer=True, positive=True)

# For T'=a*T+b and e'=frame*e, the coefficient of
# rho=c*(T-p)^m*e becomes c*a^(-m)*frame^(-1).
transformed_plus = c_plus * a ** (-contact_order) / frame
transformed_minus = c_minus * a ** (-contact_order) / frame
assert sp.simplify(
    transformed_plus / transformed_minus - c_plus / c_minus
) == 0


# ---------------------------------------------------------------------------
# 2. Exact quartic spectator ratio
# ---------------------------------------------------------------------------

T = sp.symbols("T")
sqrt_three = sp.sqrt(3)
connector_plus = (1 + sqrt_three) / 4
connector_minus = (1 - sqrt_three) / 4
rho_quartic = -18 * T**2 * (2 * T - 1) ** 2 * (
    8 * T**2 - 4 * T - 1
)
quartic_plus_initial = sp.simplify(
    sp.diff(rho_quartic, T).subs(T, connector_plus)
)
quartic_minus_initial = sp.simplify(
    sp.diff(rho_quartic, T).subs(T, connector_minus)
)
assert quartic_plus_initial == -9 * sqrt_three / 2
assert quartic_minus_initial == 9 * sqrt_three / 2
assert sp.simplify(quartic_plus_initial / quartic_minus_initial) == -1


# ---------------------------------------------------------------------------
# 3. A varying family of abstract cusp-node normalization packets
# ---------------------------------------------------------------------------

lam = sp.symbols("lambda", nonzero=True)
rho_family = sp.expand(T**2 * (T - 1) * (T - lam))

# R_lambda consists of the polynomials f satisfying
# f'(0)=0 and f(1)=f(lambda).  It is a subring: the two conditions are
# preserved by sums and products.  Its conductor in k[T] is exactly the
# principal ideal generated by rho_family.  The four independent test
# polynomials below certify the necessary vanishing conditions for a
# conductor multiplier h; divisibility gives the converse.
h0, h1, hp, hm = sp.symbols("h0 h1 hp hm")
g_constant = sp.Integer(1)
g_linear = T
g_endpoint_plus = (T - lam) / (1 - lam)
g_endpoint_minus = (T - 1) / (lam - 1)
assert g_endpoint_plus.subs(T, 1) == 1
assert g_endpoint_plus.subs(T, lam) == 0
assert g_endpoint_minus.subs(T, 1) == 0
assert g_endpoint_minus.subs(T, lam) == 1

# Applying the cusp condition to h*1 and h*T gives h'(0)=h(0)=0.
# Applying the node condition to h*g_endpoint_plus and
# h*g_endpoint_minus gives h(1)=h(lambda)=0.  These four independent
# functionals force divisibility by T^2*(T-1)*(T-lambda).
conductor_constraint_matrix = sp.Matrix(
    [
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, -1],
    ]
)
assert conductor_constraint_matrix.rank() == 4

# The generator itself satisfies both defining conditions and hence belongs
# to R_lambda; every multiple by k[T] does as well.
assert sp.diff(rho_family, T).subs(T, 0) == 0
assert rho_family.subs(T, 1) == rho_family.subs(T, lam) == 0

family_plus_initial = sp.factor(sp.diff(rho_family, T).subs(T, 1))
family_minus_initial = sp.factor(sp.diff(rho_family, T).subs(T, lam))
family_ratio = sp.factor(family_plus_initial / family_minus_initial)
assert family_plus_initial == 1 - lam
assert family_minus_initial == lam**2 * (lam - 1)
assert family_ratio == -1 / lam**2
assert family_ratio.subs(lam, 2) != family_ratio.subs(lam, 3)

# The conductor quotient has constant dimension four upstairs.  Imposing
# the cusp derivative and node value-identification conditions leaves a
# two-dimensional downstairs quotient.  This is the local delta=1+1
# packet independently of lambda.
upstairs_mod_conductor_dimension = sp.degree(rho_family, T)
downstairs_condition_matrix = sp.Matrix(
    [
        [0, 1, 0, 0],
        [0, 1 - lam, 1 - lam**2, 1 - lam**3],
    ]
)
assert downstairs_condition_matrix.rank() == 2
downstairs_mod_conductor_dimension = (
    upstairs_mod_conductor_dimension - downstairs_condition_matrix.rank()
)
assert upstairs_mod_conductor_dimension == 4
assert downstairs_mod_conductor_dimension == 2


# ---------------------------------------------------------------------------
# 4. The symmetric member is an exact two-generated plane carrier
# ---------------------------------------------------------------------------

x, y = sp.symbols("x y")
plane_x = T**2
plane_y = T**3 * (T**2 - 1)
plane_relation = y**2 - x**3 * (x - 1) ** 2
assert sp.expand(
    plane_relation.subs({x: plane_x, y: plane_y})
) == 0

# The normalization parameter belongs to the fraction field:
# T=plane_y/(plane_x*(plane_x-1)).
assert sp.cancel(
    plane_y / (plane_x * (plane_x - 1)) - T
) == 0

symmetric_conductor = T**2 * (T**2 - 1)
assert sp.expand(symmetric_conductor - rho_family.subs(lam, -1)) == 0

# Every multiple of the conductor lies in k[plane_x,plane_y]:
# even multiples use conductor*x^j and odd multiples use plane_y*x^j.
# Modulo the conductor, the defining cusp/node conditions leave the basis
# (1,T^2)=(1,plane_x), so k[plane_x,plane_y] is the full R_{-1}.
symmetric_upstairs_basis = [1, T, T**2, T**3]
symmetric_condition_matrix = downstairs_condition_matrix.subs(lam, -1)
assert symmetric_condition_matrix.rank() == 2
assert symmetric_condition_matrix * sp.Matrix([1, 0, 0, 0]) == sp.zeros(2, 1)
assert symmetric_condition_matrix * sp.Matrix([0, 0, 1, 0]) == sp.zeros(2, 1)

# The affine plane curve has an ordinary cusp at (0,0), while (1,0) has
# tangent cone y^2-(x-1)^2 and normalized preimages T=+1,-1.
Xlocal = sp.symbols("Xlocal")
node_tangent_cone = sp.expand(
    plane_relation.subs(x, 1 + Xlocal)
)
assert sp.expand(
    node_tangent_cone
    - (y**2 - Xlocal**2 - 3 * Xlocal**3 - 3 * Xlocal**4 - Xlocal**5)
) == 0
cusp_derivative_determinant = sp.det(
    sp.Matrix(
        [
            [
                sp.diff(plane_x, T, 2).subs(T, 0),
                sp.diff(plane_y, T, 2).subs(T, 0),
            ],
            [
                sp.diff(plane_x, T, 3).subs(T, 0),
                sp.diff(plane_y, T, 3).subs(T, 0),
            ],
        ]
    )
)
assert cusp_derivative_determinant != 0
assert plane_x.subs(T, 1) == plane_x.subs(T, -1) == 1
assert plane_y.subs(T, 1) == plane_y.subs(T, -1) == 0
node_tangent_determinant = sp.det(
    sp.Matrix(
        [
            [
                sp.diff(plane_x, T).subs(T, 1),
                sp.diff(plane_y, T).subs(T, 1),
            ],
            [
                sp.diff(plane_x, T).subs(T, -1),
                sp.diff(plane_y, T).subs(T, -1),
            ],
        ]
    )
)
assert node_tangent_determinant != 0

symmetric_plus_initial = sp.diff(symmetric_conductor, T).subs(T, 1)
symmetric_minus_initial = sp.diff(symmetric_conductor, T).subs(T, -1)
assert (symmetric_plus_initial, symmetric_minus_initial) == (2, -2)
assert sp.Rational(symmetric_plus_initial, symmetric_minus_initial) == -1


# ---------------------------------------------------------------------------
# 5. Global meridian relation excludes the symmetric plane carrier
# ---------------------------------------------------------------------------

# For y^2=x^3*(x-1)^2, vertical projection to x has two moving punctures.
# Their difference has local orders 3/2 at x=0 and 2/2 at x=1, giving the
# positive B_2 braids sigma^3 (cusp) and sigma^2 (node).  Zariski--van
# Kampen imposes respectively aba=bab and ab=ba on the two fiber
# meridians.  Together these imply a=b.  The following exact S4 audit
# verifies the corresponding transposition statement and its failure of
# transitivity.
SheetPermutation = tuple[int, int, int, int]


def compose(
    left: SheetPermutation, right: SheetPermutation
) -> SheetPermutation:
    return tuple(left[right[index]] for index in range(4))


def transposition(first: int, second: int) -> SheetPermutation:
    values = list(range(4))
    values[first], values[second] = values[second], values[first]
    return tuple(values)


def orbit(
    generators: tuple[SheetPermutation, ...], start: int
) -> set[int]:
    reached = {start}
    frontier = [start]
    while frontier:
        sheet = frontier.pop()
        for generator in generators:
            image = generator[sheet]
            if image not in reached:
                reached.add(image)
                frontier.append(image)
    return reached


transpositions = [
    transposition(first, second)
    for first in range(4)
    for second in range(first + 1, 4)
]
meridian_pairs = []
for first in transpositions:
    for second in transpositions:
        commute = compose(first, second) == compose(second, first)
        braid = (
            compose(compose(first, second), first)
            == compose(compose(second, first), second)
        )
        if commute and braid:
            meridian_pairs.append((first, second))
            assert first == second
            assert max(
                len(orbit((first, second), sheet)) for sheet in range(4)
            ) == 2
assert len(meridian_pairs) == 6


# ---------------------------------------------------------------------------
# 6. The dualizing residue quotient is killed by the conductor
# ---------------------------------------------------------------------------

# At a node R=k[[x,y]]/(xy), a logarithmic dualizing generator on the
# normalization is eta=(dx/x,-dy/y), with residues (1,-1).  A conductor
# section rho=(x*A(x),y*B(y)) sends it to (A(x)dx,-B(y)dy), which is regular
# on both branches.  In the quotient omega_R/omega_N only logarithmic
# constant terms remain, so multiplication by either conductor generator
# is the zero map.
#
# Encode this quotient action in the basis eta.  The two conductor
# generators x and y both act by the zero 1x1 matrix.
x_action_on_dualizing_quotient = sp.zeros(1, 1)
y_action_on_dualizing_quotient = sp.zeros(1, 1)
assert x_action_on_dualizing_quotient.rank() == 0
assert y_action_on_dualizing_quotient.rank() == 0

# The canonical residue functional is anti-diagonal, but it sees only pole
# constants.  The conormal residue has zero pole constants after
# multiplication by eta.
residue_functional = sp.Matrix([[1, 1]])
eta_residues = sp.Matrix([1, -1])
regularized_residues = sp.Matrix([0, 0])
assert residue_functional * eta_residues == sp.zeros(1, 1)
assert residue_functional * regularized_residues == sp.zeros(1, 1)


print("PASS: the marked A1 normalization defines an intrinsic projective jet ratio")
print("PASS: the exact quartic spectator connector has jet ratio -1")
print("PASS: abstract cusp-node packets realize the varying ratio -1/lambda^2")
print("PASS: lambda=-1 is the plane carrier y^2=x^3*(x-1)^2 with ratio -1")
print("PASS: its cusp and node meridian relations force equal transpositions")
print("PASS: the structured plane carrier admits no connected quartic cover")
print("PASS: the node dualizing-residue quotient is annihilated by the conductor")
print("PASS: other carriers still require their actual degree-four meridian relation")
