#!/usr/bin/env python3
"""Exact local checks for the log-conductor degree-shift theorem.

The general normalization and local-cohomology statements are proved in the
companion note.  This script checks the two integrable node matrices, their
Fitting distinction, the finite normalization quotient, the two elementary
log-blowup factors, and the normalized F2 terminal bracket.
"""

from __future__ import annotations

from itertools import product

from sympy import Matrix, Rational, diff, simplify, symbols


def jacobian_matrix(first, second, variables) -> Matrix:
    return Matrix(
        [
            [diff(first, variable) for variable in variables],
            [diff(second, variable) for variable in variables],
        ]
    )


def finite_node_normalization_check(order: int = 5) -> None:
    """Check the node quotient on polynomials through the declared order."""

    # Coordinates are (1,u,...,u^order | 1,v,...,v^order) on the two
    # normalization branches.  The node ring is the subspace with equal
    # constant terms.
    dimension = 2 * (order + 1)
    columns = []

    shared_constant = [0] * dimension
    shared_constant[0] = 1
    shared_constant[order + 1] = 1
    columns.append(shared_constant)

    for exponent in range(1, order + 1):
        u_column = [0] * dimension
        u_column[exponent] = 1
        columns.append(u_column)

        v_column = [0] * dimension
        v_column[order + 1 + exponent] = 1
        columns.append(v_column)

    image = Matrix.hstack(*(Matrix(column) for column in columns))
    assert image.rank() == dimension - 1

    mismatch = Matrix([1] + [0] * (dimension - 1))
    assert image.row_join(mismatch).rank() == dimension

    # Multiplication by u or v kills the mismatch in the quotient: u(1,0)
    # is the image of u and v(1,0)=0.
    u_times_mismatch = Matrix([0, 1] + [0] * (dimension - 2))
    zero = Matrix.zeros(dimension, 1)
    assert image.row_join(u_times_mismatch).rank() == image.rank()
    assert image.row_join(zero).rank() == image.rank()


def main() -> None:
    u, v = symbols("u v")

    # Two genuine polynomial Jacobian matrices with the same determinant.
    glued_map = (Rational(1, 2) * u**2 * v, v)
    split_map = (Rational(1, 2) * u**2, Rational(1, 2) * v**2)
    glued = jacobian_matrix(*glued_map, (u, v))
    split = jacobian_matrix(*split_map, (u, v))

    assert glued == Matrix([[u * v, u**2 / 2], [0, 1]])
    assert split == Matrix([[u, 0], [0, v]])
    assert simplify(glued.det()) == u * v
    assert simplify(split.det()) == u * v
    assert simplify(glued.det() / (u * v)) == 1
    assert simplify(split.det() / (u * v)) == 1

    # A regular row operation reduces the first presentation to
    # diag(uv,1), whereas the second already presents R/(u) + R/(v).
    row_operation = Matrix([[1, -u**2 / 2], [0, 1]])
    assert row_operation.det() == 1
    assert row_operation * glued == Matrix([[u * v, 0], [0, 1]])

    # Fitt_1 is generated by the entries.  The glued matrix contains a unit;
    # the split matrix generates precisely the node maximal ideal (u,v).
    assert 1 in list(glued)
    split_entries = {simplify(entry) for entry in split if entry != 0}
    assert split_entries == {u, v}

    finite_node_normalization_check()

    # Blow up a smooth boundary point: (u,v)=(a,a*b).  Relative to
    # du/u ^ dv and da/a ^ db, the logarithmic Jacobian factor is a.
    a, b = symbols("a b")
    ordinary_blowup_jacobian = Matrix([[1, 0], [b, a]]).det()
    smooth_log_factor = simplify((ordinary_blowup_jacobian / a) / (1 / a))
    assert smooth_log_factor == a

    # Blow up a boundary node: relative to du/u ^ dv/v and
    # da/a ^ db/b the same chart is log crepant.
    node_log_factor = simplify(
        (ordinary_blowup_jacobian / (a * (a * b))) / (1 / (a * b))
    )
    assert node_log_factor == 1

    # The flagship F2 terminal type-I block has a nonzero divisorial bracket,
    # but after the full X^4 different is removed its normalized determinant
    # is exactly one.  It therefore supplies no scalar conductor mismatch.
    X, y = symbols("X y")
    s = X**17 * y**5
    terminal_p = X**4 * y * (1 + s)
    terminal_q = -X * (1 + 3 * s + Rational(9, 5) * s**2)
    terminal = jacobian_matrix(terminal_p, terminal_q, (X, y)).det()
    assert simplify(terminal) == X**4
    assert simplify(terminal / X**4) == 1

    # A small incidence regression: every labelled tree through six vertices
    # has full row-rank incidence, while adding one cycle creates one relation.
    for vertex_count in range(2, 7):
        for prufer in product(range(vertex_count), repeat=vertex_count - 2):
            degree = [1] * vertex_count
            for vertex in prufer:
                degree[vertex] += 1
            edges = []
            for vertex in prufer:
                leaf = next(i for i, value in enumerate(degree) if value == 1)
                edges.append((leaf, vertex))
                degree[leaf] -= 1
                degree[vertex] -= 1
            last = [i for i, value in enumerate(degree) if value == 1]
            edges.append((last[0], last[1]))

            incidence = Matrix(
                [
                    [
                        -1 if column == source else 1 if column == target else 0
                        for column in range(vertex_count)
                    ]
                    for source, target in edges
                ]
            )
            assert incidence.rank() == vertex_count - 1

    cycle = Matrix(
        [
            [-1, 1, 0],
            [0, -1, 1],
            [1, 0, -1],
        ]
    )
    assert cycle.rank() == 2

    print("PASS: log-conductor degree shift and determinant-insufficiency models")


if __name__ == "__main__":
    main()
