#!/usr/bin/env python3
"""Exact chart identities for the (2,3) affine modification and topology.

The topological conclusions use the integral Gysin sequence.  This script
checks all polynomial transition identities and the integer residue maps that
enter that sequence; it does not attempt to implement singular cohomology.
"""

from __future__ import annotations

import sympy as sp


T = sp.Symbol("T")
u, v, q, x, y = sp.symbols("u v q x y")

# The a0 != 0 chart: A is monic and the tangent coefficient is one.
A0 = T**2 + u * T + v
B0 = q * T**3 + (1 - u * q) * T**2 + sp.Symbol("b2") * T + sp.Symbol("b3")
quotient_constant = 1 - 2 * u * q
remainder_y = sp.expand(sp.Poly(B0, T).coeff_monomial(T) - q * v - quotient_constant * u)
remainder_x = sp.expand(sp.Poly(B0, T).coeff_monomial(1) - quotient_constant * v)
division_remainder = sp.rem(B0, A0, T)
assert sp.expand(division_remainder - (remainder_y * T + remainder_x)) == 0

Delta = sp.expand(remainder_x**2 - u * remainder_x * remainder_y + v * remainder_y**2)
assert sp.expand(sp.resultant(A0, B0, T) - Delta) == 0

# Rename the two remainder coefficients.  The auxiliary coordinate w exhibits
# the chart as the elementary modification y*v = x*u-w over Delta=x^2-y*w.
w = sp.Symbol("w")
assert sp.expand(
    ((x**2 - u * x * y + v * y**2) - (x**2 - y * w)).subs(
        w, u * x - v * y
    )
) == 0
assert sp.expand((y * v - x * u + w).subs(w, u * x - v * y)) == 0

# A single affine-modification presentation over A^2 x SL_2.
alpha, beta, gamma, delta = sp.symbols("alpha beta gamma delta")
f = alpha * beta * delta
fractions = (
    beta * delta**2 / f,  # Delta^{-1}
    alpha**2 * beta / f,  # Delta
    alpha**2 * (u * delta - gamma) / f,  # v
)
sl_substitution = {
    alpha: x,
    beta: y,
    gamma: w / (x**2 - y * w),
    delta: x / (x**2 - y * w),
}
assert sp.factor((alpha * delta - beta * gamma - 1).subs(sl_substitution)) == 0
assert sp.factor(fractions[0].subs(sl_substitution) - 1 / (x**2 - y * w)) == 0
assert sp.factor(fractions[1].subs(sl_substitution) - (x**2 - y * w)) == 0
assert sp.factor(
    fractions[2].subs(sl_substitution) - (x * u - w) / y
) == 0

# The a1 != 0 chart and its exact transition across the overlap.
r, V, Q, Y, X = sp.symbols("r V Q Y X")
A1 = r * T**2 + T + V
B1 = (1 - r * Q) * T**3 + Q * T**2 + Y * T + X
R1 = sp.expand(sp.resultant(A1, B1, T))
rho = sp.factor(R1.subs(r, 0))
assert rho == -X + V * Y - Q * V**2 + V**3

overlap = {
    u: 1 / r,
    v: V / r,
    q: r - r**2 * Q,
    sp.Symbol("b2"): r * Y,
    sp.Symbol("b3"): r * X,
}
A0_overlap = sp.expand(A0.subs(overlap))
B0_overlap = sp.expand(B0.subs(overlap))
R0_overlap = sp.factor(sp.resultant(A0_overlap, B0_overlap, T))
assert sp.factor(R1 - r * R0_overlap) == 0

beta_overlap = sp.factor(remainder_y.subs(overlap))
alpha_overlap = sp.factor(remainder_x.subs(overlap))
assert sp.factor(r * beta_overlap - (1 + r * (-2 * Q - V) + r**2 * (Y + Q * V))) == 0
assert sp.factor(r * alpha_overlap - (V - 2 * Q * r * V + X * r**2)) == 0
assert sp.factor((r * beta_overlap).subs(r, 0) - 1) == 0

# Integral residues.  On y != 0, H^1 is generated by dlog(y),dlog(Delta).
# Along y=0, Delta=x^2, hence the degree-two residue is multiplication by 2.
residue_h1 = sp.Matrix([[1, 0]])
residue_h2 = sp.Matrix([[2]])
assert residue_h1.rank() == 1
assert residue_h2.det() == 2
assert residue_h2.det() % 2 == 0

# At the missing divisor r=0, beta=r^{-1}(1+O(r)) and Delta=R1/r.
# Modulo two, res(dlog(beta) wedge dlog(Delta))=dlog(rho), so the
# Z/2 chart class has nonzero boundary.  This selects the nonsplit extension
# 0 -> Z -> H^3(X,Z) -> Z/2 -> 0, namely H^3(X,Z)=Z.
boundary_mod_2 = sp.Matrix([[1]])
assert int(boundary_mod_2.det()) % 2 == 1

print("PASS (2,3) Euclidean chart: resultant is the quadratic norm Delta")
print("PASS chart modification: k[X_a0] = k[A^2 x SL_2][I/f]")
print("PASS complementary chart: Delta=R1/r and beta=r^(-1)(1+O(r))")
print("PASS integral residues: 1, 2, and nonzero mod-2 boundary")
print("PASS Gysin input: H^*(X,Z)=Z in degrees 0 and 3 only")
