#!/usr/bin/env python3
"""Exact additive-action identities on the normalized (2,3) slice."""

from __future__ import annotations

import sympy as sp


T = sp.Symbol("T")
a, c, z, p, d, y, x = sp.symbols("a c z p d y x")
variables = (a, c, z, p, d, y, x)

A = a * T**2 + c * T + z
B = p * T**3 + d * T**2 + y * T + x
m = a * d + c * p
resultant = sp.expand(sp.resultant(A, B, T))


def apply_derivation(polynomial: sp.Expr, images: tuple[sp.Expr, ...]) -> sp.Expr:
    return sp.expand(
        sum(sp.diff(polynomial, variable) * image
            for variable, image in zip(variables, images))
    )


# The vertical Euclidean shear B -> B+t(aT-2c)A.
D22 = (
    sp.Integer(0),
    sp.Integer(0),
    sp.Integer(0),
    a**2,
    -a * c,
    a * z - 2 * c**2,
    -2 * c * z,
)

# A second homogeneous locally nilpotent derivation.  Unlike D22 it moves A.
D10 = (
    sp.Integer(0),
    -2 * a**2,
    -a * c,
    sp.Integer(0),
    2 * a * p,
    -2 * a * d + 5 * c * p,
    -a * y + 5 * p * z,
)

for derivation in (D22, D10):
    assert apply_derivation(m, derivation) == 0
    assert apply_derivation(resultant, derivation) == 0

    # Local nilpotence is checked on algebra generators, hence on the ring.
    for variable in variables:
        iterate = variable
        for _ in range(8):
            iterate = apply_derivation(iterate, derivation)
            if iterate == 0:
                break
        else:
            raise AssertionError(f"nilpotence bound failed on {variable}")

# The two actions commute.
for index, variable in enumerate(variables):
    bracket = (
        apply_derivation(D10[index], D22)
        - apply_derivation(D22[index], D10)
    )
    assert sp.expand(bracket) == 0, variable

# D10 has a global slice on X.  The displayed ambient error is a multiple of
# m-1, so the induced derivation on k[X] sends slice to one.
slice_coordinate = (
    14 * a * p * x
    - 14 * c * d**2
    - 7 * c * p * y
    - 35 * d * p * z
    + 9 * y
) / 10
slice_error = sp.factor(apply_derivation(slice_coordinate, D10) - 1)
assert sp.expand(
    slice_error - (28 * a * d - 35 * c * p + 10) * (m - 1) / 10
) == 0

# Four simultaneous invariants of the two visible Ga-actions.  On X their
# image lies in the trinomial threefold J^2+U*K^2=64*a^3.
U = 4 * a * z - c**2
V = 4 * a**2 * y - 4 * c + 7 * c**2 * p
W = 8 * a**3 * x - 4 * a**2 * c * y + 2 * c**2 - 8 * c**3 * p + 20 * a * c * p * z
K = sp.expand(V - p * U)
J = sp.expand(W - 2 * U)

for invariant in (a, U, K, J):
    assert apply_derivation(invariant, D22) == 0
    assert sp.rem(
        apply_derivation(invariant, D10),
        m - 1,
        d,
    ) == 0

trinomial_error = sp.factor(J**2 + U * K**2 - 64 * a**3 * resultant)
quotient = sp.factor(trinomial_error / (m - 1))
assert sp.expand(trinomial_error - (m - 1) * quotient) == 0

# D22 supplies a Derksen element whose leading slice term is a^2*s.  Thus the
# subalgebra generated by the two kernels becomes the whole coordinate ring
# after a is inverted, even though its behavior on a=0 remains undecided.
h = sp.factor(apply_derivation(slice_coordinate, D22))
assert apply_derivation(h, D22) == 0
assert sp.rem(apply_derivation(h, D10), m - 1, d) == 0
assert sp.rem(h - (7 * J - 12 * U) / 40, m - 1, d) == 0
derksen_element = sp.factor(a**2 * slice_coordinate - p * h)
assert apply_derivation(derksen_element, D22) == 0

# At a general convenient point the two fields are independent; on a=0 they
# can become proportional.  This is only a rank statement for these two
# actions, not a proof about all locally nilpotent derivations.
identity_point = {a: 1, c: 0, z: 0, p: 0, d: 1, y: 0, x: 1}
boundary_point = {a: 0, c: 1, z: 0, p: 1, d: 0, y: 0, x: -1}
for point in (identity_point, boundary_point):
    assert m.subs(point) == 1
    assert resultant.subs(point) == 1

identity_vectors = sp.Matrix.hstack(
    sp.Matrix([entry.subs(identity_point) for entry in D22]),
    sp.Matrix([entry.subs(identity_point) for entry in D10]),
)
boundary_vectors = sp.Matrix.hstack(
    sp.Matrix([entry.subs(boundary_point) for entry in D22]),
    sp.Matrix([entry.subs(boundary_point) for entry in D10]),
)
assert identity_vectors.rank() == 2
assert boundary_vectors.rank() == 1

# The trinomial quotient itself has an LND moving a.  In the generic product
# chart, its extension fixing p and s develops the displayed 1/a term on d.
qa, qU, qK, qJ, qp, qs, qd = sp.symbols("qa qU qK qJ qp qs qd")
quotient_variables = (qa, qU, qK, qJ)
quotient_lnd = (qK**2, 192 * qa**2, sp.Integer(0), sp.Integer(0))


def apply_quotient_derivation(polynomial: sp.Expr) -> sp.Expr:
    return sp.expand(
        sum(sp.diff(polynomial, variable) * image
            for variable, image in zip(quotient_variables, quotient_lnd))
    )


quotient_equation = qJ**2 + qU * qK**2 - 64 * qa**3
assert apply_quotient_derivation(quotient_equation) == 0
for variable in quotient_variables:
    iterate = variable
    for _ in range(5):
        iterate = apply_quotient_derivation(iterate)
        if iterate == 0:
            break
    else:
        raise AssertionError(f"quotient nilpotence bound failed on {variable}")

c_reconstruction = (7 * qJ * qp + 9 * qK - 12 * qU * qp) / 20 - 2 * qa**2 * qs
e_c = sp.factor(apply_quotient_derivation(c_reconstruction))
assert sp.expand(
    e_c + sp.Rational(576, 5) * qa**2 * qp + 4 * qa * qK**2 * qs
) == 0
e_d_from_m = sp.factor(-e_c * qp / qa - qd * qK**2 / qa)
assert sp.expand(
    e_d_from_m
    - sp.Rational(576, 5) * qa * qp**2
    - 4 * qK**2 * qp * qs
    + qd * qK**2 / qa
) == 0

print("PASS: D10 and D22 are commuting global locally nilpotent derivations")
print("PASS: D10 has a global slice, so X_(2,3) is an A1-cylinder")
print("PASS: a,U,K,J are common invariants with J^2+U*K^2=64*a^3 on X")
print("PASS: the visible Derksen subalgebra becomes the full ring after inverting a")
print("PASS: the two visible orbit directions drop from rank two to rank one on a=0")
print("PASS: an LND moving a on the trinomial quotient has a pole in its naive lift")
