"""Rational charts generated by short elementary toric/Cremona words."""
from dataclasses import dataclass
import sympy as sp

x, y, u, v = sp.symbols("x y u v")

@dataclass(frozen=True)
class Chart:
    name: str
    expressions: tuple[sp.Expr, sp.Expr]
    word: tuple[str, ...] = ()

    @property
    def jacobian(self):
        return sp.factor(sp.Matrix(self.expressions).jacobian((x, y)).det())

    def pullback(self, expression):
        return sp.cancel(expression.subs({u: self.expressions[0], v: self.expressions[1]}, simultaneous=True))

def cubic_chart():
    return Chart("t=y+1/x,r=2/x", (y+1/x, 2/x), ("translate_y_1/x", "invert_scale_x"))

def apply_word(word):
    a, b = x, y
    for operation in word:
        if operation == "mul":
            a, b = a, sp.cancel(a*b)
        elif operation == "div":
            a, b = a, sp.cancel(b/a)
        elif operation == "swap":
            a, b = b, a
        elif operation.startswith("translate:"):
            k = int(operation.split(":", 1)[1])
            a, b = a, sp.cancel(b + a**(-k))
        else:
            raise ValueError(operation)
    return Chart("/".join(word) or "identity", (a, b), tuple(word))

def enumerate_words(max_length=3, translations=(1, 2)):
    alphabet = ("mul", "div", "swap") + tuple(f"translate:{k}" for k in translations)
    charts = {("identity",): apply_word(())}
    frontier = [()]
    for _ in range(max_length):
        new = []
        for word in frontier:
            for op in alphabet:
                candidate = word + (op,)
                chart = apply_word(candidate)
                key = tuple(map(sp.srepr, chart.expressions))
                if key not in charts:
                    charts[key] = chart
                    new.append(candidate)
        frontier = new
    return list(charts.values())

