"""Basis-independent finite fingerprints for latent Mordell--Weil lattices.

The package deliberately separates three evidence layers:

``exact``
    integer-coordinate, elliptic group-law, reduction-code, and relation data;
``numerical``
    high-precision canonical heights and derived scores;
``search``
    bounded enumeration and matching results.

Nothing in this package promotes a bounded match to a generic-family theorem.
"""

from .elliptic import EllipticCurve, Point, point_complexity
from .integer import (
    canonical_unoriented,
    canonical_rational_unoriented,
    modular_rank,
    primitive_coordinates,
    rational_nullspace,
    rational_rank,
    row_basis_coordinates,
)
from .relations import (
    RelationComplex,
    build_relation_complex,
    lift_relation_vertex_bijection,
    lift_relation_vertex_injection,
)
from .finite import FiniteQuotientBlock, discriminant, finite_quotient_block
from .local import ComponentBlock, multiplicative_component_block
from .codes import (
    CandidateFiniteSignature,
    ComponentCodeSignature,
    PrimeCodeSignature,
    candidate_finite_signature,
    candidate_finite_signature_from_record,
    finite_joint_class_key,
    finite_rarity_scores,
    finite_rarity_weights,
    finite_signature_distance,
)
from .height import (
    CloudHeightSignature,
    HermiteSignature,
    PrimitiveHermiteSignature,
    IntrinsicShellSignature,
    IntrinsicShellDistance,
    RelationMetricSignature,
    ThetaSignature,
    cloud_height_profile_distance,
    cloud_height_signature,
    cloud_height_signature_from_record,
    hermite_signature,
    hermite_signature_distance,
    primitive_hermite_signatures,
    intrinsic_shell_signature,
    intrinsic_shell_profile_distance,
    relation_metric_profile_distance,
    relation_metric_signature,
    restricted_height_gram,
    theta_profile_distance,
    theta_signature,
)
from .fingerprints import (
    CandidateRelationFingerprint,
    JointCandidateScore,
    candidate_relation_fingerprint,
    joint_nearest_candidate_scores,
    robust_standardize_fingerprint_families,
)
from .consensus import (
    GraphWalkConsensusCandidate,
    GraphWalkConsensusLedger,
    IntersectionConsensusCandidate,
    IntersectionConsensusLedger,
    exact_graph_walk_consensus,
    exact_intersection_consensus,
    rescore_graph_walk_consensus,
)
from .matching import (
    MetricRelationEmbedding,
    MetricRelationSearchLedger,
    PartialRelationReplay,
    StarComponentCandidate,
    StarComponentSearchLedger,
    bounded_metric_relation_search,
    bounded_metric_star_component_search,
    exact_partial_relation_replay,
    partial_replay_finite_signature,
)
from .pari import (
    ExactEmbedding,
    ShortVectorRecord,
    enumerate_short_vectors,
    exact_rational_ranks,
    height_gram,
    primitive_column_closure,
    row_embedding_is_primitive,
    row_embedding_saturation_indices,
    row_embedding_smith_invariant_factors,
    recover_exact_embedding,
)
from .subspace import (
    SubspaceCandidate,
    GrowthProposal,
    RecombinedSearchLedger,
    RepeatedIntersectionLedger,
    RepeatedIntersectionProposal,
    RepeatedIntersectionScore,
    MultiBoundIntersectionScore,
    aggregate_repeated_intersection_ledgers,
    beam_subspace_scan,
    cross_bound_intersection_proposals,
    exact_span_mask,
    exact_row_space_intersection,
    extend_core_proposals,
    independent_row_basis,
    independent_relation_growth_proposals,
    modular_row_space_key,
    modular_right_kernel_basis,
    primitive_span_basis,
    repeated_cross_bound_intersection_ledger,
    recombined_core_extension_search,
    relation_seeded_subspace_scan,
)

__all__ = [
    "EllipticCurve",
    "ExactEmbedding",
    "FiniteQuotientBlock",
    "GrowthProposal",
    "GraphWalkConsensusCandidate",
    "GraphWalkConsensusLedger",
    "RecombinedSearchLedger",
    "RepeatedIntersectionLedger",
    "RepeatedIntersectionProposal",
    "RepeatedIntersectionScore",
    "MultiBoundIntersectionScore",
    "MetricRelationEmbedding",
    "MetricRelationSearchLedger",
    "PartialRelationReplay",
    "StarComponentCandidate",
    "StarComponentSearchLedger",
    "ComponentBlock",
    "CandidateFiniteSignature",
    "CandidateRelationFingerprint",
    "ComponentCodeSignature",
    "CloudHeightSignature",
    "HermiteSignature",
    "PrimitiveHermiteSignature",
    "IntrinsicShellSignature",
    "IntrinsicShellDistance",
    "IntersectionConsensusCandidate",
    "IntersectionConsensusLedger",
    "JointCandidateScore",
    "RelationMetricSignature",
    "Point",
    "PrimeCodeSignature",
    "RelationComplex",
    "ShortVectorRecord",
    "SubspaceCandidate",
    "ThetaSignature",
    "beam_subspace_scan",
    "aggregate_repeated_intersection_ledgers",
    "build_relation_complex",
    "bounded_metric_relation_search",
    "bounded_metric_star_component_search",
    "exact_partial_relation_replay",
    "exact_graph_walk_consensus",
    "exact_intersection_consensus",
    "partial_replay_finite_signature",
    "lift_relation_vertex_bijection",
    "lift_relation_vertex_injection",
    "candidate_finite_signature",
    "candidate_relation_fingerprint",
    "candidate_finite_signature_from_record",
    "cloud_height_profile_distance",
    "cloud_height_signature",
    "cloud_height_signature_from_record",
    "cross_bound_intersection_proposals",
    "hermite_signature",
    "hermite_signature_distance",
    "primitive_hermite_signatures",
    "intrinsic_shell_signature",
    "intrinsic_shell_profile_distance",
    "joint_nearest_candidate_scores",
    "relation_metric_profile_distance",
    "relation_metric_signature",
    "canonical_unoriented",
    "canonical_rational_unoriented",
    "enumerate_short_vectors",
    "exact_rational_ranks",
    "finite_quotient_block",
    "finite_joint_class_key",
    "finite_rarity_scores",
    "finite_rarity_weights",
    "finite_signature_distance",
    "exact_span_mask",
    "exact_row_space_intersection",
    "extend_core_proposals",
    "height_gram",
    "independent_row_basis",
    "independent_relation_growth_proposals",
    "modular_row_space_key",
    "modular_rank",
    "modular_right_kernel_basis",
    "multiplicative_component_block",
    "point_complexity",
    "primitive_column_closure",
    "row_embedding_is_primitive",
    "row_embedding_saturation_indices",
    "row_embedding_smith_invariant_factors",
    "primitive_span_basis",
    "repeated_cross_bound_intersection_ledger",
    "rescore_graph_walk_consensus",
    "primitive_coordinates",
    "rational_nullspace",
    "recombined_core_extension_search",
    "relation_seeded_subspace_scan",
    "rational_rank",
    "row_basis_coordinates",
    "robust_standardize_fingerprint_families",
    "recover_exact_embedding",
    "restricted_height_gram",
    "theta_profile_distance",
    "theta_signature",
    "discriminant",
]
