/-
Copyright (c) 2026 Roy van Rijn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Roy van Rijn
-/
import Mathlib.Algebra.Group.Irreducible.Lemmas
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.GroupTheory.GroupAction.Primitive

/-!
# The Galois-theoretic kernel of primitive-monodromy atomicity

This module formalizes the presentation-independent core of
`verified/PRIMITIVE_MONODROMY_ATOMICITY.md`.

Let `M/K` be a finite Galois extension and let `L` be the intermediate field
representing the source function field inside a Galois closure.  If the
fixing subgroup of `L` is the stabilizer of a point in a primitive transitive
Galois action, then `L` is an atom in the lattice of intermediate fields.
Consequently every intermediate field below `L` is either `K` or `L`.

The final theorem packages the remaining application to composition in an
abstract monoid.  A caller supplies:

* the intermediate field produced by a factorization;
* the proof that it lies below the source field; and
* the two endpoint lemmas saying that a degree-one factor is a unit.

For polynomial Keller maps, those inputs are respectively the pullback
function-field tower and the birational Keller lemma.  Their multivariable
algebraic-geometric formalization, as well as invariance under constant-field
extension and stabilization, remains outside this module.
-/

noncomputable section

namespace FiniteEtaleKeller

universe uK uM uX uA

variable {K : Type uK} {M : Type uM}
variable [Field K] [Field M] [Algebra K M]
variable [FiniteDimensional K M] [IsGalois K M]

/-- A maximal fixing subgroup corresponds, under the order-reversing Galois
correspondence, to an atomic intermediate field. -/
theorem intermediateField_isAtom_of_fixingSubgroup_isCoatom
    (L : IntermediateField K M)
    (hL : IsCoatom L.fixingSubgroup) :
    IsAtom L := by
  let e :
      IntermediateField K M ≃o
        (Subgroup (M ≃ₐ[K] M))ᵒᵈ :=
    IsGalois.intermediateFieldEquivSubgroup
  rw [← e.isAtom_iff L]
  change IsAtom (OrderDual.toDual L.fixingSubgroup)
  exact hL

/-- If the fixing subgroup of `L` is maximal, there is no proper
intermediate field between the base field and `L`. -/
theorem intermediateField_eq_bot_or_eq_of_fixingSubgroup_isCoatom
    (L E : IntermediateField K M)
    (hL : IsCoatom L.fixingSubgroup)
    (hEL : E ≤ L) :
    E = ⊥ ∨ E = L :=
  (intermediateField_isAtom_of_fixingSubgroup_isCoatom L hL).le_iff.mp hEL

/-- Primitive monodromy makes the source field atomic in the lattice of
intermediate fields of a finite Galois closure.

The hypothesis `hstab` is the precise bridge identifying the subgroup that
fixes the source function field with the stabilizer of the distinguished
generic sheet. -/
theorem intermediateField_eq_bot_or_eq_of_primitive_monodromy
    {X : Type uX}
    [MulAction (M ≃ₐ[K] M) X]
    [Nontrivial X]
    [MulAction.IsPreprimitive (M ≃ₐ[K] M) X]
    (L E : IntermediateField K M)
    (x : X)
    (hstab :
      L.fixingSubgroup =
        MulAction.stabilizer (M ≃ₐ[K] M) x)
    (hEL : E ≤ L) :
    E = ⊥ ∨ E = L := by
  apply intermediateField_eq_bot_or_eq_of_fixingSubgroup_isCoatom L E
  · rw [hstab]
    exact
      MulAction.IsPreprimitive.isCoatom_stabilizer_of_isPreprimitive
        (M ≃ₐ[K] M) x
  · exact hEL

/-- Abstract monodromy-to-atomicity compiler.

`middle g h` is the intermediate field attached to a factorization
`f = g * h`.  In the Keller-map application it is the field generated by the
coordinates of the inner factor.  The endpoint hypotheses encode:

* `middle g h = ⊥`: the outer factor has geometric degree one;
* `middle g h = L`: the inner factor has geometric degree one.

Once degree-one factors are known to be units, primitive monodromy proves
that `f` is irreducible in the noncommutative monoid sense. -/
theorem irreducible_of_primitive_monodromy
    {X : Type uX} {A : Type uA}
    [MulAction (M ≃ₐ[K] M) X]
    [Nontrivial X]
    [MulAction.IsPreprimitive (M ≃ₐ[K] M) X]
    [Monoid A]
    (f : A)
    (hf : ¬ IsUnit f)
    (L : IntermediateField K M)
    (x : X)
    (hstab :
      L.fixingSubgroup =
        MulAction.stabilizer (M ≃ₐ[K] M) x)
    (middle : A → A → IntermediateField K M)
    (middle_le :
      ∀ {g h : A}, f = g * h → middle g h ≤ L)
    (unit_outer_of_middle_eq_bot :
      ∀ {g h : A}, f = g * h → middle g h = ⊥ → IsUnit g)
    (unit_inner_of_middle_eq_source :
      ∀ {g h : A}, f = g * h → middle g h = L → IsUnit h) :
    Irreducible f := by
  refine ⟨hf, ?_⟩
  intro g h hfactor
  rcases intermediateField_eq_bot_or_eq_of_primitive_monodromy
      L (middle g h) x hstab (middle_le hfactor) with hbot | hsource
  · exact Or.inl (unit_outer_of_middle_eq_bot hfactor hbot)
  · exact Or.inr (unit_inner_of_middle_eq_source hfactor hsource)

/-- Irreducibility is preserved by multiplication by units on both sides.
For the Keller monoid this is the formal monoid core of polynomial
left--right invariance. -/
theorem irreducible_isUnit_mul_mul
    {A : Type uA} [Monoid A]
    {f u v : A}
    (hf : Irreducible f)
    (hu : IsUnit u)
    (hv : IsUnit v) :
    Irreducible (u * f * v) := by
  exact (irreducible_mul_isUnit hv).2
    ((irreducible_isUnit_mul hu).2 hf)

#print axioms intermediateField_isAtom_of_fixingSubgroup_isCoatom
#print axioms intermediateField_eq_bot_or_eq_of_primitive_monodromy
#print axioms irreducible_of_primitive_monodromy
#print axioms irreducible_isUnit_mul_mul

end FiniteEtaleKeller
