name = "gmc2-lower-face"
version = "0.1.0"
keywords = ["math", "gaussian-moments"]
defaultTargets = ["GMC2"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.1"

[[lean_lib]]
name = "GMC2"
